### ISSUE TITLE
add Powerline symbols

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/cascadia-code#10]
|codepoint|glyph|codepoint|glyph|
|-|-|-|-|
|`E0A0`|![image](https://user-images.githubusercontent.com/14316954/63142523-f9e84e80-bf9e-11e9-838f-e3ae9ebdfe2e.png)<br>_branch_|`E0A1`|![image](https://user-images.githubusercontent.com/14316954/63142529-02408980-bf9f-11e9-8dd5-58365099be9d.png)|
|`E0A2`|![image](https://user-images.githubusercontent.com/14316954/63142537-09679780-bf9f-11e9-820d-c30aea428d14.png)|
|`E0B0`|![image](https://user-images.githubusercontent.com/14316954/63142612-50558d00-bf9f-11e9-90de-7fe0530c0089.png)<br>_left divider (hard)_|`E0B1`|![image](https://user-images.githubusercontent.com/14316954/63142620-58153180-bf9f-11e9-8d1b-5849849a049d.png)<br>_left divider (soft)_|
|`E0B2`|![image](https://user-images.githubusercontent.com/14316954/63142626-5f3c3f80-bf9f-11e9-95ba-9900ae8e7aae.png)<br>_right divider (hard)_|`E0B3`|![image](https://user-images.githubusercontent.com/14316954/63142634-67947a80-bf9f-11e9-9452-7022cc85633e.png)<br>_right divider (soft)_|

**Comment by isaac2004** [comment]
Can I piggy back nerd fonts?

**Comment by khuongduybui** [comment]
It will be AMAZINGLY AWESOME for this font to come with Nerd Fonts out of the box!!!

**Comment by cerebrate** [comment]
On the off-chance that I'm the first person to have tried it with the release, I can confirm that

`fontforge -script font-patcher -w -c ~/Downloads/Cascadia.ttf`

...works just the way you'd expect it to. For those of us who can't give up our Powerline prompts even for the moment. :)

**Comment by khuongduybui** [comment]
On the off chance that you are the only one who successfully did that, can you please publish the patched font somewhere?

**Comment by cerebrate** [comment]
...let me check what the license permits/requires.

**Comment by DHowett-MSFT** [comment]
Like Fira, you’ll have to change the name. Everything else is SIL OFL, but the name is trademarked. :smile:

**Comment by khuongduybui** [comment]
`Cascadian Code`?

**Comment by khuongduybui** [comment]
Or Cascadia Code Plus Plus?

**Comment by cerebrate** [comment]
Well, that's simple enough. [Delugia Code Nerd Font Complete is here](https://1drv.ms/u/s!AqrcZdowvFOLqYIpZgfXk-OJL_rDCg?e=Ypukvn).

Please bear in mind that I know within delta of nothing about font editing, so if this doesn't work for you, I can only recommend that you fire up [font-patcher](https://github.com/ryanoasis/nerd-fonts#font-patcher) yourself and see how it goes.

(It works great on WSL 2, by the way. 😊)

**Comment by DerAlbertCom** [comment]
If the whole nerd fonts does not make it into this, please thing about the powerline extra symbols  https://github.com/ryanoasis/powerline-extra-symbols

![image](https://user-images.githubusercontent.com/136992/65251214-37d51700-daf7-11e9-8383-0d138b1ed371.png)

**Comment by i3d** [comment]
This font looks good. I am eagerly wanted to see it support powerline syms.

**Comment by RobCannon** [comment]
I think a great solution would be to produce 2 or 3 font variations:

CascadiaCode - The basic font
CascadiaCode PL - Add just the PowerLine glyphs
CascadiaCode NF - Add the full set of NerdFont glyphs

That way, anyone concerned about the size can get just what they need.

**Comment by rivy** [comment]
@khuongduybui , I suggest `Cascodia PF` and `Cascodia NF`.
😄

**Comment by mdtauk** [comment]
If the extra Powerline glyphs are added, I'd like to see them made a little cleaner in style.

- The Fire could be made simpler

- The "Watercolor" style blocks
![image](https://user-images.githubusercontent.com/7389110/65819317-df96c700-e212-11e9-8f6d-48c86368d43a.png)

- And the frozen icicle style design

**Comment by adam7** [comment]
I figured you could automate downloading and patching the font using GitHub Actions so I had a go and now I have this repository [https://github.com/adam7/delugia-code/](https://github.com/adam7/delugia-code/). @cerebrate I stole your name, let me know if you want me to change it, @RobCannon based on your suggestion I generated a Powerline and a Complete version.

**Comment by cerebrate** [comment]
@adam7 Nicely done, and you're welcome to the name!

**Comment by ryanoasis** [comment]
@mdtauk Good suggestions/ideas. Those that I made are a bit kludgy :blush: I really do like the blocks in the window title as well.. very clean

**Comment by devlife** [comment]
> I figured you could automate downloading and patching the font using GitHub Actions so I had a go and now I have this repository https://github.com/adam7/delugia-code/ which does just that.
> 
> @cerebrate I stole your name, let me know if you want me to change it, @RobCannon based on your suggestion I generated a Powerline and a Complete version.
> 
> You can grab the patched fonts from the [Releases page](https://github.com/adam7/delugia-code/releases).
> 
> ~The fonts can be downloaded as Artifacts from the Actions page https://github.com/adam7/delugia-code/actions?workflow=Generate+Fonts~

I tried for so long to figure out how to use font patcher via fontForge on windows and just couldn't do it. Thank you so much for this @adam7 . Worked like a dream!

**Comment by aaronbell** [comment]
All done! :D

**Comment by ExE-Boss** [comment]
Is&nbsp;this&nbsp;using the&nbsp;default **PowerLine**&nbsp;symbols, or&nbsp;a&nbsp;custom‑ish&nbsp;design?

**Comment by aaronbell** [comment]
@Exe-Boss They're pretty much the default ones. Some have been scaled to fit into Cascadia's metrics, but this first round was focused on supporting the glyphs rather than making them "Cascadian". Feel free to file an issue if they look too out of place!

**Comment by ScottHutchinson** [comment]
> All done! :D

What was done? I don't see any PR/merge linked. Where do we get the Cascadia font patched with nerd glyphs?

I'm interested because when I run `fontforge -script font-patcher -q --complete /mnt/c/Users/scott/Downloads/CascadiaCode-2009
.22/ttf/CascadiaCode.ttf` on Ubuntu 20.04.1 LTS (WSL) I get `fontforge: can't open file 'font-patcher': [Errno 2] No such file or directory` and I can't find how to fix that. Thanks!

**Comment by aaronbell** [comment]
@ScottHutchinson see here:
https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code

We released a separate version called “Cascadia Code PL” that include those symbols. And can be downloaded from the Github release.

**Comment by ScottHutchinson** [comment]
Also my PowerShell prompt looks like this, which is not as nice as I have on another computer. I'm not sure how to fix it.

![image](https://user-images.githubusercontent.com/16599128/104133894-3d352100-533b-11eb-82c0-c4438bf59d36.png)

**Comment by ScottHutchinson** [comment]
@aaronbell Thanks I did download that, but thought maybe it did not include all the glyphs, since my prompt doesn't look quite right (see above).

I have `"fontFace": "Cascadia Code PL"`

**Comment by aaronbell** [comment]
It looks like you’re getting the right glyphs. How do you expect it to look?

**Comment by ScottHutchinson** [comment]
Never mind. I guess it's good enough. It looked like this on my old computer that I configured about a year ago. Now if I could just get it to look like that on Ubuntu.
![image](https://user-images.githubusercontent.com/16599128/104135763-d74e9680-5346-11eb-8ee6-1077654f4ad9.png)
