### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by zangxx66** [microsoft/cascadia-code#101]
It dont support Chinese so the system has replaced it with SimSun.But SimSun is not suitable for coding.

**Comment by ExE-Boss** [comment]
Duplicate of #55

**Comment by Rean1030** [comment]
> It dont support Chinese so the system has replaced it with SimSun.But SimSun is not suitable for coding.

很多IDE可以设置多个字体的，你把需要的首选中文字体写在里面，它就会优先显示了。
