### ISSUE TITLE
Bug Report 's' followed by '=' doesn't have enough kerning in italics

### ISSUE THREAD

**Issue by praveenpuglia** [microsoft/cascadia-code#103]
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: VSCode 1.38.1
OS platform and version: MacOS Catalina 10.15
Screen resolution (i.e. 220dpi): 220

Any other software?
```

# Steps to reproduce

- Go to VSCode
- Use a theme that supports italics. 
- Type `s=`
- Check the kerning between those two.

# Expected behavior

Expecting a little bit of breathing room between 's' and '='.

# Actual behavior

No breathing room at all.
![image](https://user-images.githubusercontent.com/313363/65405784-f5fbe780-ddfa-11e9-9dbc-432dc285652e.png)

**Comment by madig** [comment]
There is no italic so you're looking at something synthesized.

**Comment by praveenpuglia** [comment]
Makes sense. So, shall I close the issue?

**Comment by DHowett-MSFT** [comment]
Sure. :smile:

**Comment by ExE-Boss** [comment]
Duplicate of #63

**Comment by fitojb** [comment]
Also, by the way, by definition, monospaced fonts have **no** kerning. If it had, it wouldn’t be monospaced anymore :P
