### ISSUE TITLE
Does this font support the UTF-8 subset for IBM437 symbols?

### ISSUE THREAD

**Issue by eabase** [microsoft/cascadia-code#104]
It's not clear from the README what glyphs and character sets this font supports. 
There are a lot of very useful symbols in UTF-8 and IBM437 that *should* be included, but not mentioned anywhere. Symbols for boxes, bullet points a check marks etc.

So what does it have?
* https://www.ascii-codes.com/
* https://en.wikipedia.org/wiki/Box-drawing_character

**Comment by joshg253** [comment]
Doesn't look like it, in Character Map:
![image](https://user-images.githubusercontent.com/297115/65435807-f1710800-ddd5-11e9-9b46-47d39d804ac8.png)

**Comment by ExE-Boss** [comment]
See #11, #70 and many others.

**Comment by eabase** [comment]
Buuuuh!! 

:-1:

**Comment by mdtauk** [comment]
I think there should be a pinned post detailing what languages and codepage ranges **will be** supported, when the font reaches a more finished state.

So we can reduce the amount of duplicated issues, and any languages not planned for, can be argued for, and +1'd to show support.

**Comment by bitcrazed** [comment]
@cinnamon-msft is working on the roadmap for when more glyphs will be added to the font and will publish in a week or so.
