### ISSUE TITLE
Visual Studio 2019 - Arrow operator ligature not working

### ISSUE THREAD

**Issue by alexhajdu** [microsoft/cascadia-code#107]
# Environment

```none
Cascadia Code version number:
Application (with version) used to display text: Visual Studio 2019 Professional 16.2.5
OS platform and version: Win 10 x64
Screen resolution (i.e. 220dpi): 1920x1080

```

# Steps to reproduce
Try to access members through a pointer.

# Expected behavior
> Screenshot from Terminal
![image](https://user-images.githubusercontent.com/1824796/65422048-a8d14300-de05-11e9-981d-8e0827437f7a.png)

# Actual behavior
> Screenshot from VS Studio 2019 Prof.
![image](https://user-images.githubusercontent.com/1824796/65422030-9b1bbd80-de05-11e9-8498-99a6ea98ede1.png)

**Comment by fireyoshiqc** [comment]
> This is a vscode issue (actually upstream : [xtermjs/xterm.js#958](https://github.com/xtermjs/xterm.js/issues/958) )

It's not. This is in "standard" Visual Studio 2019, not VSCode.
@alexhajdu it's also happening on my side.
![image](https://user-images.githubusercontent.com/16504440/65449203-770dab80-de08-11e9-8949-4908c4b9c543.png)

**Comment by encladeus** [comment]
The same issue for the arrow ligature not properly displaying in VS2019 (and VS2017) using Fira Code was reported earlier this year. Perhaps this is a Visual Studio issue. Reference the following bug report, which is now closed (not fixed).

https://developercommunity.visualstudio.com/idea/591741/font-ligatures-not-working.html

**Comment by alexhajdu** [comment]
Seems like Visual Studio has some issues with rendering some fonts in general. Look at how nice the font looks in the new Terminal in comparison with VS. IMHO there must be some not so easy replaceable layer not allowing the developers to use some new approach for displaying the fonts. For example, it's a shame we can't just change the line spacing in VS, etc...I hope this will be fixed sooner or later.

**Comment by imdragonet** [comment]
![image](https://user-images.githubusercontent.com/951734/65475395-002ced00-deb2-11e9-95d4-6e2f77fa3d3d.png)
just enable font ligatures in your vs code settings.

**Comment by fireyoshiqc** [comment]
> ![image](https://user-images.githubusercontent.com/951734/65475395-002ced00-deb2-11e9-95d4-6e2f77fa3d3d.png)
> just enable font ligatures in your vs code settings.

Again, this issues is about "standard" Visual Studio, not VSCode.

**Comment by encladeus** [comment]
Now that the Visual Studio issue with ligatures is reopened and as mentioned in the issue report:

> If folks have other feedback or wish to upvote this, it will certainly help.

https://developercommunity.visualstudio.com/idea/591741/font-ligatures-not-working.html

**Comment by bitcrazed** [comment]
Closing this issue as it appears to be a VS issue.

**Comment by iCodeIT** [comment]
For me it was fixed by simply installing the font again (and restarting the applications)

**Comment by iCodeIT** [comment]
Actually it didn't work. After rebooting ligature was gone again.
I downloaded newest Cascadia version and I am on newest V2019 version (not preview). Similarly I am on newest VS Code version.

**Comment by MythreyaK** [comment]
This seems to be an issue with all WPF applications, and given VS is based on WPF, no wonder it doesn't work there. Even the new Terminal has an issue with rendering hyphen-based ligatures.

**Comment by DHowett-MSFT** [comment]
> even the new Terminal has an issue with

Uh? We haven’t heard anything of the sort- would you mind filing a bug over on our repository about this?

**Comment by MythreyaK** [comment]
Done, [issue here](https://github.com/microsoft/terminal/issues/3834#issue-532895208). 
Hope that works!

> This seems to be an issue with all WPF applications,

Also, is the rest of my comment above accurate? I just checked with some WPF apps (and a quickly hacked together custom app) and this issue seems to me present. Don't think it's related to the new Terminal, since it uses a custom rendering engine.

**Comment by bitcrazed** [comment]
This is a known issue with WPF - the VS team are aware and are planning on looking into this issue in a future release. If you're interested in more info, please contact [Dante Gagne](https://twitter.com/DanteGagne) via Twitter.

**Comment by aaronbell** [comment]
If this is being tracked elsewhere, do we need to track it here?

**Comment by MythreyaK** [comment]
Thanks for the info!

**Comment by aaronbell** [comment]
Great! Closing :)

**Comment by khelpix** [comment]
The Arrow does not workl.
