### ISSUE TITLE
Add box-drawing and block element glyphs

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/cascadia-code#11]
The entire range of [box drawing](https://en.wikipedia.org/wiki/Box_Drawing_(Unicode_block)) (`U+2500 - U+257F`) and [block element](https://en.wikipedia.org/wiki/Block_Elements) (`U+2580 - U+259F`) characters is not covered by the font.

**Comment by grantcarthew** [comment]
I just used my Node.js package [console-probe](https://www.npmjs.com/package/console-probe) and the tree structure is a mess. This is required to support many console tools.

Prior to Cascadia Code:

![console-probe](https://raw.githubusercontent.com/grantcarthew/node-console-probe/master/images/aussieslang-json.png)

With Cascadia Code:

![Capture](https://user-images.githubusercontent.com/572141/65729474-bf2b1780-e101-11e9-8923-3b8bd877b92a.PNG)

I am starting to like this font though. Great work.

**Comment by ExE-Boss** [comment]
Same thing occurs with [`pnpm list ‑‑depth <number>`](https://pnpm.js.org/en/cli/list) and [`pnpm why <pkg>`](https://pnpm.js.org/en/cli/why).

**Comment by mdtauk** [comment]
Here are Box Drawing glyphs which can be added to the font - I have exported just those glyphs as a PS OpenType, so it should be trivial to add them in @aaronbell @cinnamon-msft @bitcrazed 

- Vertical Strokes are **180** units wide
- Horizontal Strokes are **176** units wide.
- There are **-20** / **+20** offshoots to avoid gaps between those glyphs which are designed to connect

**Comment by DHowett-MSFT** [comment]
@mdtauk U+2526 looks a little upset:

![image](https://user-images.githubusercontent.com/14316954/65822962-f7198400-e201-11e9-92a8-ffab385f9b01.png)

**Comment by mdtauk** [comment]
@DHowett-MSFT @aaronbell   Thanks for the catch - it happened during export to OTF.  I corrected the curves so the overlap of the glyph shapes exports correctly.
![image](https://user-images.githubusercontent.com/7389110/65823036-9a8c8800-e246-11e9-97d9-07dab83be7ca.png)

[CascadiaCode - Box Drawing.zip](https://github.com/microsoft/cascadia-code/files/3666072/CascadiaCode.-.Box.Drawing.zip)

**Comment by aaronbell** [comment]
@mdtauk Thanks for your help! These look pretty easy to integrate :). 

A couple of things:
1) It looks like the vertical overlaps aren't quite working. I think part of the challenge is that interpretation of vertical metrics can vary from app to app, so it is better to base the height off of the winAscender and winDescender values.

2) I'm noting that there's a number of other box drawing characters that appear to be missing from the set (mostly the block set). 

In all this, though, I happened to remember that Adobe kindly [released a script](https://github.com/adobe-type-tools/box-drawing) to generate all of these box drawing characters (including blocks). Handy!

**Comment by mdtauk** [comment]
@aaronbell  I was testing in the preview pane within FontLab, but any adjustments that need to be made will be good.

I just got done doing the Block Elements glyphs

![image](https://user-images.githubusercontent.com/7389110/65824137-7c7d5280-e25b-11e9-89ed-ebb7f0060b4f.png)


[CascadiaCode - Block Elements.zip](https://github.com/microsoft/cascadia-code/files/3666179/CascadiaCode.-.Block.Elements.zip)

**Comment by aaronbell** [comment]
Thanks @mdtauk! 

Yeah, I tested it in Sublime Text and a couple other places. No problem, I can sort it out!
