### ISSUE TITLE
No ligature version

### ISSUE THREAD

**Issue by chiniara** [microsoft/cascadia-code#110]
# No ligature version

The font is really nice, but some ides don't allow us to disable ligatures and some of us also don't like ligatures but really liked this font, so... 
Can we have a no ligature version?

**Comment by DHowett-MSFT** [comment]
Please search for existing requests before filing a new one. Thanks!

**Comment by chiniara** [comment]
Sorry but i couldnt find a feature request that looked like mine, thats why i posted it.

**Comment by mdtauk** [comment]
Ligatures are a feature that is turned off within the applications using the font, and so there is no need to create multiple versions of the fonts

**Comment by chiniara** [comment]
iirc visual studio doenst have this option, i searched about this some months ago
