### ISSUE TITLE
Idea: Get rid of VTT, and use Glyphs’ TT hiniting

### ISSUE THREAD

**Issue by be5invis** [microsoft/cascadia-code#111]
Synchronizing hitns between Glyphs and VTT is not a sustainable way to maintain this font.
Could we use Glyphs' TT hinting instead?

Some features that Glyphs _may_ lacking:

 - `ResYDist`-like links;
 - Stem hierarchy, i.e., CVT entry of X is considered relative to CVT entry Y (typical case: overshoots).

cc. @schriftgestalt

**Comment by schriftgestalt** [comment]
Both features are supported. 
- The stems in Glyphs are "Res" by default. 
- Zones can be "aligned" in the zone dialog.

**Comment by aaronbell** [comment]
We are planning an overhaul of the workflow that will convert the source to a UFO as that will allow this project to be more platform agnostic. As such, using Glyphs' inbuilt hinting is not a viable option for this project.

**Comment by madig** [comment]
VTT continues to be an impediment though. Wish there was a capable open-source hint compiler, doesn't even have to be VTT...

**Comment by aaronbell** [comment]
Yeah. I know the situation will be resolved in time—it is just a pain for now!

**Comment by madig** [comment]
Do you know something no one else knows? 😯
