### ISSUE TITLE
Monospace font for Chinese, Japanese, and Korean (CJK) users

### ISSUE THREAD

**Issue by heartacker** [microsoft/cascadia-code#112]
亲爱的微软,
可以开发一个中英文都等宽的字体吗?
万分感激,
中文和因为都等宽的,而不是中文2 英文1的字体.
'''
中文字体5 
chinese89
'''

**Comment by Rean1030** [comment]
这个话题已经有了啊：CJK compatibility #55

**Comment by bitcrazed** [comment]
Translation:

> Dear Microsoft,
> Can I develop a font that is equal to the same width in both Chinese and English?
> Thank you so much.
> Chinese and because they are equally wide, rather than Chinese2 English 1 font.
> '''
> Chinese Font5
> Chinese89 '''

Could you clarify: Do you mean can YOU create a font, or can Microsoft create a monospace font?

**Comment by heartacker** [comment]
> Translation:
> 
> > Dear Microsoft,
> > Can I develop a font that is equal to the same width in both Chinese and English?
> > Thank you so much.
> > Chinese and because they are equally wide, rather than Chinese2 English 1 font.
> > '''
> > Chinese Font5
> > Chinese89 '''
> 
> Could you clarify: Do you mean can YOU create a font, or can Microsoft create a monospace font?

sorry,I can't, I wish M$ can :D

**Comment by bitcrazed** [comment]
I understand :)

We are very aware that there needs to be an overhauled monospace font for Chinese, Japanese, and Korean users, in particular, and are exploring options. 

No news to share at this time, but know that we are aware and exploring options.

**Comment by hdd1013** [comment]
+1 Without the CJK glyphs that align well with Latin characters, I can't expect this font being widely used in East Asian countries.

**Comment by bitcrazed** [comment]
@hdd1013 We hear you loud and clear. Alas, this isn't an easy problem to solve, but we are actively exploring options here when we can.

Thanks for sharing your thoughts on this important consideration.

**Comment by NDelt** [comment]
+1 I hope to use CJK monospace font designed by Microsoft.

**Comment by xinkunZ** [comment]
"宋体" is really shit in windows terminal!!!

**Comment by mdtauk** [comment]
Many Japanese and Chinese fonts include monospaced Latin character sets using the same spacing as the full width characters.

I am not sure the character width used currently for the latin glyphs, would not be wide enough to support the detail needed for the various syllabaries used by those East Asian languages.

But if the fonts included the full and half width versions, the latin and other characters could align nicely.

https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by bitcrazed** [comment]
@xinkunZ Terminal v0.10 seems to render those glyphs pretty close to Edge & Chrome:

![image](https://user-images.githubusercontent.com/961950/77339744-7d161380-6ce9-11ea-9441-2494c41407c7.png)

**Comment by xinkunZ** [comment]
@bitcrazed  yeap, It seems like windows terminal render CJK by Microsoft yahei font.

**Comment by aaronbell** [comment]
For the sake of streamlining the bug list, I'm duping this against #55 as both request the addition of CJK coverage.
