### ISSUE TITLE
Bug Report - Higher Second Asterisk than the Others (ONLY when there's three asterisks)

### ISSUE THREAD

**Issue by tommymaynard** [microsoft/cascadia-code#116]
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: Windows PowerShell 5.1/PowerShell 6.2.3/PowerShell 7.0.0-Preview4 in Windows Terminal 0.5.2661.0
OS platform and version: Windows 10 Version 1903 (OS Build 18362.356)
Screen resolution (i.e. 220dpi): 1920 x 1080 (unknown DPI)
```

# Steps to reproduce

```powershell
1..5 | ForEach-Object {'*' * $_}
*
**
*** # This line renders correctly on GitHub, but it does not in the above applications (see below linked image).
****
*****
```

# Expected behavior

It's expect that three asterisks should render like any other number of asterisks. This only happens with Cascadia Code.

# Actual behavior
```powershell
*** # The second asterisk is higher than the others, but only when there's three astericks. Can anyone else reproduce this!?
```
[Imgur Image](https://i.imgur.com/0WXKFrS.png)

**Comment by DHowett-MSFT** [comment]
This ligature was added on purpose.

**Comment by tommymaynard** [comment]
Thank you for the information, @DHowett-MSFT. Is there anywhere in which you can point me, so I may read more about ligatures, and this one especially? I have a function that replaces plain text passwords, fed into a PowerShell functions (idiotically), with the same number of asterisks. This ensures that passwords aren't written to log files, or the screen. It's just that now, that this seriously awesome font, currently used in every console I can, looks broken. Thank you for your time!

**Comment by DHowett-MSFT** [comment]
Unfortunately, I don't have a very good resource for that question! Fortunately, though, the ligature shuts itself off when you put more than three asterisks in a row. I know that it looks somewhat strange at first :smile:
