### ISSUE TITLE
Support for `≡`?

### ISSUE THREAD

**Issue by saschanaz** [microsoft/cascadia-code#117]
# Environment

```none
Cascadia Code version number: 1906.16
Application (with version) used to display text: Windows Terminal Preview
OS platform and version: Windows 10 Insider Preview 18990
Screen resolution (i.e. 220dpi): 96DPI

Any other software? N/A
```

# Steps to reproduce

1. Set font as Cascadia Code in Windows Terminal
2. Copy-paste `≡` multiple time in `pwsh`, `cmd` or even `ubuntu`. (The character is used in [posh-git](https://github.com/dahlbyk/posh-git))
3. Try moving cursor between `≡`s

# Expected behavior

It should be half-width character as in Consolas.

# Actual behavior

It's rendered as full-width character and confuses Windows Terminal. (Related with https://github.com/microsoft/terminal/issues/42 ?)

**Comment by ExE-Boss** [comment]
See also: https://github.com/microsoft/terminal/issues/2066
