### ISSUE TITLE
Tilde ~ malformed (11pt)

### ISSUE THREAD

**Issue by alexhajdu** [microsoft/cascadia-code#125]
# Environment

```none
Cascadia Code version number: 
Application (with version) used to display text: Visual Studio VS 2019 Prof. 16.3.1
OS platform and version: Win10 x64
Screen resolution (i.e. 220dpi): 2560x1440

Any other software?
```

# Steps to reproduce
![image](https://user-images.githubusercontent.com/1824796/65752231-a411d500-e10c-11e9-8c1e-97342df0940e.png)
virtual ~Foo();

# Expected behavior
Note: Expected behavior was achieved by changing the font from 11pt to 12pt.

![image](https://user-images.githubusercontent.com/1824796/65752300-cdcafc00-e10c-11e9-845b-5c3609d05977.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/1824796/65752271-c0ae0d00-e10c-11e9-8ef7-6a3af2fdd3c3.png)

**Comment by aaronbell** [comment]
Out of interest, where did the 'Expected behavior' screenshot come from?

**Comment by alexhajdu** [comment]
> Out of interest, where did the 'Expected behavior' screenshot come from?

From my IDE, why? :)

**Comment by aaronbell** [comment]
I mean, what application. You've stated that the Actual Behavior is not working correctly, but I was confused that the "Expected behavior" looks like it came from the same application. What is different between the two?

**Comment by alexhajdu** [comment]
Yeah, it's Visual Studio 2019 Prof 16.3.1 as noted in the description. 
Expected behavior has changed the size from 11pt to 12pt to demonstrate the desired result.

**Comment by aaronbell** [comment]
Ah. Different point size. Thanks.
