### ISSUE TITLE
Lambda symbol isn't present

### ISSUE THREAD

**Issue by kmboyito** [microsoft/cascadia-code#126]
Lambda symbol isn't present

![image](https://user-images.githubusercontent.com/13785361/65777044-dd484600-e108-11e9-9f90-cc52a884d81e.png)

**Comment by Dob6458** [comment]
Maybe because it's the first version of Cascadia Code.

**Comment by Dob6458** [comment]
If this logicial can support the multiple fonts, use: `Cascadia Code, Consolas`.

**Comment by bitcrazed** [comment]
We hear you. @cinnamon_msft is working on the plan for when and how we add more glyphs to Cascadia-Code. She'll publish a roadmap in the next week or so.

**Comment by aaronbell** [comment]
Thanks! This will be resolved with the addition of Greek language support. For now, duplicating against #33.
