### ISSUE TITLE
Feature Request: Support full Latin Core glyph set

### ISSUE THREAD

**Issue by cshei** [microsoft/cascadia-code#127]
# Description of the new feature/enhancement (with images if possible)

Google Fonts requires fonts to cover the [Latin Core](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam) glyph set before they will consider adding a font.  Since Cascadia Code doesn't cover this, https://github.com/google/fonts/issues/2179 is currently on hold.  Since there are many requests for new glyphs, could this be used as a milestone to target?  I'd really like to see this font get added to Google Fonts, since Google's internal web IDE only pulls fonts from there, and you can't manually install fonts on ChromeOS.  Thanks!

**Comment by bitcrazed** [comment]
We agree! :) @cinnamon-msft is working through some planning stuff for when and how we're going to add more glyphs and will post a roadmap in the next week or so.
