### ISSUE TITLE
Feature Request: Provide more weights

### ISSUE THREAD

**Issue by cata0309** [microsoft/cascadia-code#128]
# Description of the new feature/enhancement
Many IDE's do not have the settings as a configurable file( like some text editors: example Atom has stylesheet.less, Visual Studio Code has settings.json ) where you can choose the weight of the font.
I am thinking that more weights would be awesome to have. I really like the Iosevka structure:
It has  weights 8 weights but it would be more than enough to have 4 Light, Regular, Medium and Bold:
Thin
Thin italic
Thin oblique

Extralight
Extralight italic
Extralight oblique

Light
Light italic
Light oblique

Regular
Italic
Oblique

Medium
Medium italic
Medium oblique

Semibold
Semibold italic
Semibold oblique

Bold
Bold italic
Bold oblique

Extrabold
Extrabold italic
Extrabold oblique

**Comment by mdtauk** [comment]
I am not sure if the font needs both an Italic and an Oblique.  They both serve the same purpose, except an Italic will alter the letter shapes to better suit the slant - whereas an Oblique is mostly the same letters, but slanted.

**Comment by cata0309** [comment]
4 are must have Italic, Regular, Medium and Bold any additional weight would be just a bonus

**Comment by mdtauk** [comment]
I made an issue #90 asking for it to be a Variable font, which would allow for using a slider or numeric value like **450** to set the weight of the font.

It would also allow setting the width of the characters, which would allow narrow, normal to wide characters.

**Comment by cata0309** [comment]
I know this is a great feature but this would be helpful just for the text editors/IDE's that allow writing stylesheet for the editor. This would work if they make use of the fact that "it will be a variable" font and generate or make a way to generate the font weights.

**Comment by mdtauk** [comment]
> I know this is a great feature but this would be helpful just for the text editors/IDE's that allow writing stylesheet for the editor. This would work if they make use of the fact that "it will be a variable" font and generate or make a way to generate the font weights.

Most Variable fonts tend to export some fixed instance weights, as well as include the "breakpoints" for those weights within the font, for compatibility with older software.

It makes the creating of the font much easier, as it is a single set of outlines to maintain.

**Comment by cata0309** [comment]
@mdtauk very clear explanation, thank you !

**Comment by dodalovic** [comment]
Hi, guys, I'm not an expert at all in this area, but what I see is that this nice font renders too bold, using Intellij IDEA on MacOS. Is there anything that could be done about it, or ..?

Thanks for the really nice font!

**Comment by GregoryHorvath** [comment]
+1 I'd love to have a light version of this font, because even with 100% dpi scaling everything is so chunky in VSCode it feels like the letters leak into eachother. (on W10)
In cmd it feels better though I don't know why.

**Comment by musm** [comment]
Can we get a compressed version?

**Comment by musm** [comment]
My preference is Concolas (and Roboto Mono), too bad Consolas  has horribly glyph support and very few math glyphs .

**Comment by Braytiner** [comment]
I'd love to have a light version of this font. I'm using FiraCode Light weight, size 15. I tryed Cascadia but it's so chunky and bold on VS 2019 (Windows 10).

![FiraCode Light](https://user-images.githubusercontent.com/11064602/66318738-404c9080-e8f2-11e9-88f0-a60176e513a3.png)
![Cascadia Code](https://user-images.githubusercontent.com/11064602/66318739-404c9080-e8f2-11e9-9826-3efe8611e115.png)

**Comment by txhai** [comment]
Still wait for Light built version, it's bold in Intellij

**Comment by mdtauk** [comment]
I would describe the current default weight as more of a Semi/Demi Bold, than a true Bold.  Certainly chunky compared to most Regular/Normal or Medium weights.

**Comment by tuananh** [comment]
this is probably the most anticipated feature

**Comment by TaylorRayHoward** [comment]
For those that want a thinner font on JetBrains IDEs (IntelliJ, Webstorm, etc), try going to Appearance & Behavior > Appearance > Antialiasing and changing it to Greyscale.  This could be considered a temp fix till this issue is resolved.

**Comment by michaelkthai** [comment]
> For those that want a thinner font on JetBrains IDEs (IntelliJ, Webstorm, etc), try going to Appearance & Behavior > Appearance > Antialiasing and changing it to Greyscale. This could be considered a temp fix till this issue is resolved.

Thanks for the tip. Made it much less of an eyesore for me. FYI, a similar result can be achieved in VSCode by setting 'Font Aliasing' to 'antialiased' in settings.

**Comment by DHowett-MSFT** [comment]
"eyesore" is a terrifically unkind thing to say about somebody else's project. :smile:

**Comment by michaelkthai** [comment]
@DHowett-MSFT You're right. I love the FF itself - I moreso meant the bolder typeface alongside the rest of my specific editor setup made it an eyesore.. It's certainly not the designer's problem that I didn't figure out what settings to use with it sooner :grimacing:

**Comment by emailsters** [comment]
good font.but it seems everything is bold in termimal, regular font weight is really need.

**Comment by GregoryHorvath** [comment]
It will come ~March, check: https://github.com/microsoft/cascadia-code/wiki/Roadmap

**Comment by lhughey** [comment]
The font is nice, but looks bold in Visual Studio. A light weight would be very visually pleasing for pages with lots of markup.

**Comment by patrickfatrick** [comment]
Worth making sure you have antialiasing turned on in your IDE especially if you're using a hi-dpi monitor like any recent macbook. In sublime you set the following in your preferences:

```json
        "font_options":
	[
		"gray_antialias"
	],
```

**Comment by tuananh** [comment]
> It will come ~March, check: https://github.com/microsoft/cascadia-code/wiki/Roadmap

March can't come soon enough

**Comment by SidShetye** [comment]
### Need a `Light` weight variant that's crisp.

Cascadia Code PL definitely need to go on a diet. 

#### Roboto Mono Light for Powerline
![image](https://user-images.githubusercontent.com/2595088/77101114-01a81f80-69d4-11ea-9021-ebf7f2d956c7.png)

#### Cascadia Code PL

![image](https://user-images.githubusercontent.com/2595088/77101242-3916cc00-69d4-11ea-813a-1425a141bec9.png)

#### Consolas

![image](https://user-images.githubusercontent.com/2595088/77101452-8c891a00-69d4-11ea-8380-fffd994a52f1.png)

**Comment by electronic-dk** [comment]
FYI, this seems to have been resolved with the latest release. I see that the bold font now renders fine in Intellij Idea:
![image](https://user-images.githubusercontent.com/2945527/81823610-271d5980-953d-11ea-8fc5-43a40c232f1f.png)

**Comment by mdtauk** [comment]
I think it is still using a faux bold, but with new hinting.

**Comment by idan** [comment]
Hey maintainers! Are you able to share any updates about progress towards this?

No pressure at all, just excited for the lighter weights as my (very subjective) eye struggles with legibility of the regular weight.

Thank you!
