### ISSUE TITLE
Feature Request: More Braille Characters?

### ISSUE THREAD

**Issue by babbott1000** [microsoft/cascadia-code#130]
# Description of the new feature/enhancement

I have in recent years been frustrated with the fact that I cannot use braille characters in the default windows terminals, but I am really excited to see that this font supports braille.  I immediately went to the [blessed-contrib repository](https://github.com/yaronn/blessed-contrib), a NodeJS module that uses braille characters for displaying dashboard information, and ran the demo file, it did mostly work.
![blessedContribDashboard](https://user-images.githubusercontent.com/20113527/65821527-570d2c00-e1fc-11e9-86a3-6a8626972e4a.jpg)

It seems there are a few glitches which I suspect is because not all braille characters are supported.

If these defects could be fixed that would be tremendously helpful.

If you would like to run the demo for yourself, you can check out the [blessed-contrib repository](https://github.com/yaronn/blessed-contrib) and look at the instructions to run the demo, it's pretty straight forward.

**Comment by aaronbell** [comment]
Actually, the font does not at current support any Braille characters and, at least in your screenshot, it looks like you're using a different font. We can certainly add them to the list of symbols to support though!

**Comment by babbott1000** [comment]
That's odd.  I have no idea what font I'm using them, but that would be great if they could be added! 😃

**Comment by gnuvince** [comment]
> That's odd. I have no idea what font I'm using then, but that would be great if they could be added! 😃

You're using Consolas.
