### ISSUE TITLE
Missing Glyph: U+00A0 NON-BREAKING SPACE

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/cascadia-code#132]
# Environment

```none
Cascadia Code version number: 1909.30 [TEST]
```

**Comment by madig** [comment]
I suppose one can add a cmap entry poiting to `space`, even if this turns a `nbspace` into a `space` if the font ends up in a PDF with the text stripped and just the glyph names remaining.

**Comment by aaronbell** [comment]
I'm not usually a fan of double-encoding glyphs, but these would be the exact same. 🤷‍♂️

**Comment by madig** [comment]
What problems have you found with double-encoding?

**Comment by aaronbell** [comment]
Admittedly this is some years ago, but the tools that I was using would behave weird with double encoded characters—sometimes breaking them silently, or not reading them properly, so they were things I had to constantly pay careful attention to. I have heard that things are better now, though.

**Comment by mdtauk** [comment]
AFAIK you can't really do these "duplicated" spacing characters with components, like with accented characters etc

**Comment by madig** [comment]
Tools as in font design software or other applications? If the latter, I'd be in favor of double encoding on purpose to stress test the Windows text handling stack :grin: 

 > AFAIK you can't really do these "duplicated" spacing characters with components, like with accented characters etc

Yes, but you can do it everywhere where you'd have exact copies of glyphs otherwise, i.e. these four different hyphens defined in Unicode that are usually the same glyphs. Source Sans Pro does it for example, IIRC.

**Comment by mdtauk** [comment]
> Tools as in font design software or other applications? If the latter, I'd be in favor of double encoding on purpose to stress test the Windows text handling stack 😁
> 
> > AFAIK you can't really do these "duplicated" spacing characters with components, like with accented characters etc
> 
> Yes, but you can do it everywhere where you'd have exact copies of glyphs otherwise, i.e. these four different hyphens defined in Unicode that are usually the same glyphs. Source Sans Pro does it for example, IIRC.

Yes, visible identical glyphs can be inserted as components, which alter the sidebearings, but non-visible spacings wont. (At least not in FontLab) :)
