### ISSUE TITLE
Not equal ligature for vb language

### ISSUE THREAD

**Issue by pproost** [microsoft/cascadia-code#136]
Hello, love the font.

I have the following issue. We have a mixed codebase (legacy) vb.net and new c#. In vb the not equal sign isn't replaced with the ligature. 

With the new font it would be nice if the vb not equal sign <> would also be replaced by the not equal ligature. Now this looks rather ugly in vb files

![image](https://user-images.githubusercontent.com/32439778/66124828-b8ab0d00-e5e5-11e9-9e1a-eb4c4b2e8dee.png)

**Comment by PhMajerus** [comment]
Agreed, this is also important for WSH VBScript files, remember people have huge set of these scripts still in use, and it could even help Office VBA users as well.

**Comment by PhMajerus** [comment]
It actually does have a ligature for the <> sign, it turns it into the air-tight diamond instead of leaving a gap between the two symbols.

**Comment by aarondglover** [comment]
I agree. Would be great to have VB code use the Not Equal ligature in lieu of the air tight diamond. 

Is there a work around in Visual studio or VS Code which can control the font ligatures? ie: Override the ligatures for particular character combinations?

**Comment by DHowett-MSFT** [comment]
@aaronbell can correct me if I'm wrong, but one of the guiding principles of the ligature design was that each ligature would look at least reasonably close to the characters that compose it. I think that having `<>` turn into what is effectively `=/=` works counter to that intent; perhaps there's some understanding to be found that "not equal" simply looks different in those languages? It's already a different symbol, and perhaps we should embrace that difference.

**Comment by aaronbell** [comment]
Generally yes. The ligatures are intended to be a representation of the component characters. However, I can understand that it could be useful to have a different ligature in cases where requested. We added a [stylistic set for Lua that swapped ~= with the not equals ligature](https://github.com/microsoft/cascadia-code/issues/98). If this is something that users in general would like, I can add it into the same stylistic set.

**Comment by PhMajerus** [comment]
I think completely changing the look of a symbol shouldn't be the job of ligatures, instead that should be a code editor extension if people really want that.

**Comment by mizuno-gsinet** [comment]
I think making `!=` look like `≠` should not be the job of ligatures too :)

**Comment by DHowett** [comment]
@mizuno-gsinet you always have the option of not using the ligatured version if you disagree with the ligatures that have been chosen.

**Comment by aaronbell** [comment]
Hi! I'm going back through old bugs. In reconsidering this, I'm going to leave it as it is. :)
