### ISSUE TITLE
1910.04: LIGA table is back

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/cascadia-code#140]
`>>>>`
![image](https://user-images.githubusercontent.com/14316954/65849771-cb30f800-e300-11e9-8355-ed433225666d.png)

`****`
![image](https://user-images.githubusercontent.com/14316954/65849772-cec47f00-e300-11e9-818d-9acbf579e63e.png)

`====`
![image](https://user-images.githubusercontent.com/14316954/65849790-e13eb880-e300-11e9-80c5-4824e83469c9.png)

_Originally posted by @DHowett-MSFT in https://github.com/microsoft/cascadia-code/pull/131#issuecomment-536396990_

This bug came back with the prerelease drop of 1910.04.

**Comment by DHowett-MSFT** [comment]
This is probably the cause for #139, honestly.

**Comment by aaronbell** [comment]
Probably. I'm not entirely sure how it ended up back in there since neither the Glyphs source nor the VTT source I checked in has it. And yet. :/ 

I'll prep a fixed one.

**Comment by DHowett-MSFT** [comment]
(fyi: the file we got also has new PANOSE data and a glyph00730, which has no outline data :smile:)

**Comment by aaronbell** [comment]
Not present in the final release! :D
