### ISSUE TITLE
Missing Glyph U+25A0 (Black Square) and some other high-ASCII characters from CP437

### ISSUE THREAD

**Issue by PhMajerus** [microsoft/cascadia-code#142]
# Environment

```none
Cascadia Code version number: 1910.040
Application (with version) used to display text: Windows Terminal & ConHost
```

The font is missing the U+25A0 (Black Square) glyph. In Windows Terminal it gets replaced by a full-width version from some other font, while in ConHost it shows as the missing empty rectangle.
This character is important as it is part of the base MDA/CGA / Codepage 437 characters set, and is often used along the full block and half blocks as a centered half block, and therefore should be included as part of the new box drawing glyphs.

Also, providing all 256 characters from CP437 would highly improve compatibility with original PC console/terminal outputs, so the other characters missing in the screenshot below would be a great addition.

Consolas:
![MDA charset Consolas](https://user-images.githubusercontent.com/25664275/66254901-41a87c80-e77d-11e9-9096-007015b6eac2.png)

Cascadia Code:
![MDA charset Cascadia Code](https://user-images.githubusercontent.com/25664275/66254905-4a00b780-e77d-11e9-8294-b4b3be84f4f5.png)

**Comment by PhMajerus** [comment]
Even better if you can add the few specific ones needed to cover all original MS-DOS codepages, here's the example for Latin I (Western Europe, Latin America and Canada), aka CP850 (remember the extra Euro symbol for CP858).

Consolas:
![CP850 Consolas](https://user-images.githubusercontent.com/25664275/66255055-7cabaf80-e77f-11e9-9bf3-681c768e8934.png)
Cascadia Code:
![CP850 Cascadia Code](https://user-images.githubusercontent.com/25664275/66255056-7fa6a000-e77f-11e9-8417-a974dfdf6cbb.png)

**Comment by aaronbell** [comment]
Still missing a few symbols not previously identified: U+263A, U+263B, U+266B and U+263C

**Comment by aaronbell** [comment]
Closing as there's a separate issue now.
