### ISSUE TITLE
Accented characters show up as blocks in Windows CMD/Notepad++ but work in VSCode/Sublime

### ISSUE THREAD

**Issue by GregoryHorvath** [microsoft/cascadia-code#143]
# Environment

```none
Cascadia Code version number: 1910.04
Application used to display text: latest Windows Command Prompt, Notepad++, VSCode, Sublime Text 3 to date
OS platform and version: Windows
Screen resolution (i.e. 220dpi): 1920x1080, 100% scaling
```

# Actual behavior

Accented characters show up as empty blocks, like: éáöüóí. Strange thing is they work perfectly in modern text editors like VSCode or Sublime.

**Comment by aaronbell** [comment]
I have not been able to repro this, either in the Windows Command Prompt nor Notepad++. In both cases the font has rendered the accented characters correctly. 

Maybe try uninstalling, redownload, and try again? 

Also, note, that if you've installed the Windows Terminal, there can be situations where the [installed version in the package overrides the new version](https://github.com/microsoft/terminal/issues/2979), so that might also be contributing.

**Comment by GregoryHorvath** [comment]
> I have not been able to repro this, either in the Windows Command Prompt nor Notepad++. In both cases the font has rendered the accented characters correctly.
> 
> Maybe try uninstalling, redownload, and try again?
> 
> Also, note, that if you've installed the Windows Terminal, there can be situations where the [installed version in the package overrides the new version](https://github.com/microsoft/terminal/issues/2979), so that might also be contributing.

Hmm, I (thought I) installed the latest version today, but after checking it in my Windows/Fonts folder it says it is the previous version still and I can't even delete it.
Closing this because the issue lies at me then.

**Comment by aaronbell** [comment]
Yes, it sounds like you're encountering the same problem that I did in the link above. This is actually a problem with Windows Terminal.

**Comment by DHowett-MSFT** [comment]
As far as we could tell, this only breaks font lookup from within Windows Terminal (since the packaged font gets elevated to the first spot in font lookup inside the package.)

**Comment by aaronbell** [comment]
Oh? I found it overrode all requests for Cascadia Code throughout the system. So even in VSCode, I'd get the package version rather than the new one.

**Comment by GregoryHorvath** [comment]
I really don't know what happened but I had 3 instances of the font installed and had to purge them from the registry because otherwise delete just didn't do anything on them. (and Windows' Font manager/folder showed only 1)
