### ISSUE TITLE
Emacs render font as `bitmap` but not vector

### ISSUE THREAD

**Issue by jilen** [microsoft/cascadia-code#146]
# Environment

```none
Cascadia Code version number: 1910.04
Application (with version) used to display text: Emacs
OS platform and version: Archlinux(latest,2019.10.08)
Screen resolution (i.e. 220dpi):  Xft.dpi:	96
```

# Actual behavior

![Screenshot from 2019-10-08 10-13-41](https://user-images.githubusercontent.com/546573/66362276-ad285f00-e9b4-11e9-9290-fddfa691d2d4.png)

# Note
The first release looks just fine.
![Screenshot from 2019-10-08 10-18-19](https://user-images.githubusercontent.com/546573/66362342-fbd5f900-e9b4-11e9-907a-455ebee8ab1a.png)

**Comment by aaronbell** [comment]
I am not able to repro this bug on emacs (on Windows).

<img width="800" alt="emacs" src="https://user-images.githubusercontent.com/8460297/66448857-dcb48700-ea07-11e9-9ff6-fc9ff0e11ffd.PNG">

If one font is working and the other isn't, I'd suggest uninstalling (make sure all instances are removed), and reinstall from the GitHub release. Or otherwise check your settings in emacs to ensure that smoothing / antialiasing is turned on.

**Comment by peterwu** [comment]
I have the same issue on my Emacs on Arch Linux. The font works fine in Emacs on Windows 10. Antialiasing and hinting are turned on on Linux and the problem persists as if these settings had no effect at all. If I replace Cascadia Code with another font, say, Iosevka, Emacs displays Iosevka correctly. The only difference is the font in this exercise. btw, It worked fine with the first release of Cascadia Code but the the recent release.

**Comment by aaronbell** [comment]
Hmm. Thanks for the update. I'll see if I can find some differences between the different versions and Iosevka, but it might end up requiring digging into how ArchLinux decides to turn on antialiasing / hinting.

**Comment by peterwu** [comment]
OK. I figured out why. 

I had the 2 env vars defined for hidpi.

`export GDK_SCALE=2
export GDK_DPI_SCALE=0.5`

Once I commented them out, the font started to look correct. Hope this helps.

**Comment by aaronbell** [comment]
Thanks Peter! I hoped it was something on the ArchLinux side :). Scaling letterforms can definitely have an impact on rendering. 

Closing for now.

**Comment by jilen** [comment]
@peterwu  I've no such env settings. But the antialias not working. Do you have any idea?

**Comment by peterwu** [comment]
Assuming you installed the font by using the ttf-cascadia-code in the AUR, I have a workaround that works for me. If you copy the Cascadia.ttf file to your ~/.local/share/fonts and uninstall the AUR package, log out and back in, Emacs will render the font correctly. The 2 env vars mentioned in my post don't appear to matter. It seems when the font is installed at the global location, for some reason, Emacs can't render it correctly. It works for me and hopefully it will work for you.

**Comment by jilen** [comment]
@peterwu That works! Really wired.

**Comment by aaronbell** [comment]
Brilliant! Thanks @peterwu.
