### ISSUE TITLE
Suggestion: Better readable Symbols for Greater or Equal and Less or Equal

### ISSUE THREAD

**Issue by teebeast** [microsoft/cascadia-code#147]
The following image shows that the less or equal operator is smaller than the inequality operator and in comparison difficult to recognize.

![image](https://user-images.githubusercontent.com/20777572/66372241-d2fa3780-e9a5-11e9-9407-4811d7e741c7.png)

Please make both symbols more readable. Here my suggestion for an alternative design.

![image](https://user-images.githubusercontent.com/20777572/66373153-38e7be80-e9a8-11e9-9c28-d36e9f867136.png)

**Comment by alexleduc76** [comment]
Strongly prefer the the "lesser than" in the screenshot. Perhaps it's proportions are wrong and it looks pixelated in the screenshot compared to the other characters, but it's a much more stylish ligature.

**Comment by lmcarreiro** [comment]
The `gte` and `lte` version of the operators when used with underline, like in a text that is a link, can be confused with `gt` and `lt`. Need to consider that, maybe it is best to not use a horizontal line below the `<` and `>` to avoid this situation.

**Comment by Entroper** [comment]
Just be sure the horizontal line is above the underline.

**Comment by aaronbell** [comment]
Thanks for the comments! I'm planning a modification of these forms. For now, I'm closing this as a dup of #144.
