### ISSUE TITLE
Box art alignment with reversed video text

### ISSUE THREAD

**Issue by blanalex** [microsoft/cascadia-code#149]
# Environment

```none
Cascadia Code version number: 1910.04
Application (with version) used to display text: Windows Terminal Preview 0.5.2681.0
OS platform and version: Windows 10 v1903
Screen resolution (i.e. 220dpi): 100% (96 dpi)

Any other software? no
```

# Steps to reproduce

With cmd.exe, my prompt is set as follows: 
$e[94m$T$+ $M$_░▒▓$e[7m$P$e[27m▓▒░>$e[39m

# Expected behavior

The reversed video part should align with the block characters, as in the following example with conhost, using the Hack font:
![image](https://user-images.githubusercontent.com/28639664/66418677-9a238800-e9d0-11e9-9c5c-3187231ec11d.png)

# Actual behavior

The block characters appears lower than the reversed video text.
![image](https://user-images.githubusercontent.com/28639664/66419049-58471180-e9d1-11e9-891b-9c366a25778b.png)

Although I think part of the issue might be with Windows Terminal itself, because if i try the same thing with the Hack font with Windows Terminal, the reversed video is wider than the block drawing characters, but at least it is centered instead of being offset.

![image](https://user-images.githubusercontent.com/28639664/66418992-42395100-e9d1-11e9-9c3a-47e3129922bb.png)

**Comment by DHowett-MSFT** [comment]
Yes, this is a terminal issue. microsoft/terminal#455. :smile:
