### ISSUE TITLE
v1910.04 incorect rendering

### ISSUE THREAD

**Issue by MirceaTheOldMan** [microsoft/cascadia-code#154]
I just installed latest version of Cascadia v1910.04. It replaced the initial version and when I reopened my code editor it looks "encoded" as in the image bellow:
![Capture](https://user-images.githubusercontent.com/13944535/66630209-70ef3b80-ec0c-11e9-992a-ab8a4ada8425.JPG)

Going back to the previous version, everything works ok.

**Comment by MirceaTheOldMan** [comment]
I use Windows 10, Android Studio as IDE

**Comment by aaronbell** [comment]
Hello! This issue is due to multiple versions of the font being installed. Please follow the steps in [this post](https://github.com/microsoft/cascadia-code/issues/150#issuecomment-539873102).

**Comment by aaronbell** [comment]
Closing.

**Comment by MirceaTheOldMan** [comment]
Thank you @aaronbell I just want to confirm that your solution worked. I had that font installed with two different names and Windows Font settings UI can't handle such a complex task.
