### ISSUE TITLE
Bold mode in visual studio 2019 breaks alignments when scale is 100%

### ISSUE THREAD

**Issue by bdrum** [microsoft/cascadia-code#156]
Hello!
First of all thanks for the nice font!

I've seen such thing:
In case of settings of editor that you also can see on the screenshot everything is fine with alignment
![](https://sun9-59.userapi.com/c858224/v858224957/a78fc/fvK9wyuVzJs.jpg)

But, please, look what happens if I will check bold mode:
![](https://sun9-39.userapi.com/c858224/v858224957/a7910/OaoVWUGbVzg.jpg)

I've noticed in case of increasing a scale in visual studio alignment has become fine, but not in case of 100%.

Cheers

-----
Visual Studio 2019 16.3.4
Windows 10 1903

**Comment by aaronbell** [comment]
The font does not contain a bold weight, so when you select "bold", you're actually getting a mechanically bolded version which does not preserve font metrics. Adding a bold is on our task list :).
