### ISSUE TITLE
Kitty Terminal no Bold Font

### ISSUE THREAD

**Issue by arkhan** [microsoft/cascadia-code#157]
Configure Cascadia Code on the Kitty terminal but when displaying bold text it is not shown as you can see in the image, on the left Cascadia Code and on the right Fira Code

![img-2019-10-15-083638](https://user-images.githubusercontent.com/3141865/66973847-c25d5780-f05e-11e9-89ab-ff4347f11b52.png)

Thanks for the help

**Comment by aaronbell** [comment]
At current, the font does not include Bold weight—it is on our roadmap! We're currently tracking this issue in feature request #128. 

Thanks!
