### ISSUE TITLE
@ looks like ©

### ISSUE THREAD

**Issue by DoubleDeez** [microsoft/cascadia-code#159]
# Description of the new feature/enhancement (with images if possible)
The @ symbol could easily be confused with the copyright symbol with the current design. Especially at smaller sizes, it looks a bit like a 'c' in an ellipse.
![WindowsTerminal_9q9QPocUn1](https://user-images.githubusercontent.com/1893819/67165968-fb881700-f33f-11e9-99f8-e9baeb461407.png)

While the copyright symbol is obviously a copyright symbol, the @ symbol is not obviously an @ symbol.

# Proposed technical implementation details (optional)
Separating the tail of the 'a' from the outline should eliminate any potential confusion, such as:
![image](https://user-images.githubusercontent.com/1893819/67165988-38540e00-f340-11e9-9442-b6998813eb44.png)

**Comment by aaronbell** [comment]
Thanks for the feedback! The core problem is that both the @ and copyright symbol have been designed to have maximum internal space. I think that in context they're fairly straightforward to tell apart, but I'll leave this open so that if other people have issues with this then we can look to address it.

**Comment by mdtauk** [comment]
The copyright and registered symbols could be filled circles with a C or R reversed out.

The At symbol, could also terminate it's curved tail to the left side, rather than the bottom

**Comment by aaronbell** [comment]
Hmm. I'll have to do some experiments. Thanks!

**Comment by mdtauk** [comment]
> Hmm. I'll have to do some experiments. Thanks!

![image](https://user-images.githubusercontent.com/7389110/68717181-f49aa000-059d-11ea-808c-8c85193b2191.png)

**Comment by Qqwy** [comment]
What about connecting the 'a' slightly with the circle at the top, and let the tail stop slightly sooner?

![Screenshot_2019-11-20_16-29-42](https://user-images.githubusercontent.com/5345745/69252421-42716280-0bb3-11ea-814a-dba025335d58.png)
