### ISSUE TITLE
Alignment when using "bold" text decoration with numbers

### ISSUE THREAD

**Issue by TipaRiordan** [microsoft/cascadia-code#162]
# Environment

Cascadia Code version number: 1910.04
Application (with version) used to display text: Notepad++ 7.6.2
OS platform and version: Windows 10 Pro, 10.0.18362.175
Screen resolution (i.e. 220dpi): 1600x1200 (can't find a dpi setting ... "100%" in Windows settings)

Any other software?
-none-

# Steps to reproduce

- In settings, set Notepad++ to use Cascadia Code everywhere (Global Styles, all Styles).
- In style for VB/VBA, remove all "bold" settings except for "NUMBERS"
- load a data file with some long columns of mixed numers (some negative) into np++, i.e. 
>> https://datacenter.iers.org/data/latestVersion/186_EOP_C01_2000.1846_NOW_V2013_01186.txt
- save as xxx.vb (to format in np++ as VB)

# Expected behavior

Columns of numbers should be neatly aligned

# Actual behavior

Columns are not proper aligned, possibly due to "-" (0x2D) having a different width than space (0x20) when bold.
![Cascadia Code Problem with width](https://user-images.githubusercontent.com/46349551/67362919-851c2c80-f56c-11e9-8408-a16102fc5420.png)

**Comment by aaronbell** [comment]
Thanks for the feedback! Unfortunately the font does not at current have a bold version, so when the software tries to embolden the glyphs, it does not do it in a tabular way. This is covered in other issues, such as #163 and #43. Closing as duplicate.
