### ISSUE TITLE
<==> Symbol unsupported (Dafny)

### ISSUE THREAD

**Issue by alexsurelee** [microsoft/cascadia-code#164]
The use of a `<==>` symbol as found in Dafny (one of Microsoft's languages) shows up as a separate `<=` symbol next to an `=` and a `>`. Screenshot included.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/11603625/67535347-ad538900-f72e-11e9-98ea-cd73dfd35f8f.png">

**Comment by aaronbell** [comment]
Hm. I haven't been able to repro this on my end. Can you provide a bit more info about which version of the font and where you're encountering this? 

Thanks!

**Comment by alexsurelee** [comment]
I'm admittedly using a patched fork of the font, but just tried with latest release and the same issue.

Have just noticed that this doesn't occur in the terminal, so may be an issue with VSCode instead? Ticket may be closable, sorry!

**Comment by aaronbell** [comment]
No worries! Another question—do you have an older install of the Windows Terminal on your system? 

Something that we've noticed is that the previous version of Cascadia Code included with an earlier version of the Windows Terminal application tends to override everything else on the system. And occasionally malfunctioning coding ligatures was a 'feature' of that earlier version of Cascadia Code. 

If you are running an earlier version of Windows Terminal, I'd suggest uninstalling it, and reinstalling the latest version. Also, you may want to uninstall the Cascadia Code font as the two can 'compete' with problematic results. See #150 for a more involved process for making sure there aren't any duplicate fonts installed.

**Comment by alexsurelee** [comment]
Nah actually on Mac with iTerm.

The `<==>` symbol works as intended in iTerm, but shows up as screenshotted in VS Code, so think that must be where the issue lies.

**Comment by mdtauk** [comment]
> Nah actually on Mac with iTerm.
> 
> The `<==>` symbol works as intended in iTerm, but shows up as screenshotted in VS Code, so think that must be where the issue lies.
>
Are any of the other ligatures working in VS Code.  If not perhaps you haven't got them turned on - I think there is an option for that.

**Comment by alexsurelee** [comment]
> Are any of the other ligatures working in VS Code. If not perhaps you haven't got them turned on - I think there is an option for that.

Yup - if you check out the screenshot it appears to be bumping the first two characters together into a ligature, but ignoring the fact that it's immediately succeeded by other characters that should be attributed to it as well.

**Comment by aaronbell** [comment]
<img width="141" alt="Screen Shot 2019-10-24 at 11 10 49 PM" src="https://user-images.githubusercontent.com/8460297/67547506-1f3abc80-f6b4-11e9-8548-6dad4ec68af0.png">

So in my copy of VS Code on the Mac, I'm able to see the ligature render correctly. Which makes me wonder what's going on with your particular case. I wonder if there's something weird going on with fallback or a different style being applied. Can you copy / paste the text string into a code block so I can take a look?

**Comment by alexsurelee** [comment]
Ahhh okay, appears to only happen working in a `.dfy` file, which has let me narrow it down to this extension being the cause: https://github.com/DafnyVSCode/Dafny-VSCode

Surprised it has any influence on ligatures, how strange.

**Comment by aaronbell** [comment]
That is strange! Please file an issue against them :).
Meanwhile I'm going to close this as it isn't related to Cascadia's functionality.

**Comment by DHowett-MSFT** [comment]
For what it’s worth, it’s probably the split colorization that is breaking the ligature! How would you color what is effectively one character two colors? :smile:

**Comment by alexsurelee** [comment]
> For what it’s worth, it’s probably the split colorization that is breaking the ligature! How would you color what is effectively one character two colors? 😄

Yeah I'm not sure, the intention isn't for it to be multiple colours, it's just the incorrect parsing of it that seems to be doing it. `<=` transforms to a single coloured ligature correctly, so definitely just something strange playing up.

**Comment by mdtauk** [comment]
> > For what it’s worth, it’s probably the split colorization that is breaking the ligature! How would you color what is effectively one character two colors? 😄
> 
> Yeah I'm not sure, the intention isn't for it to be multiple colours, it's just the incorrect parsing of it that seems to be doing it. `<=` transforms to a single coloured ligature correctly, so definitely just something strange playing up.
>
Does the same thing happen with other fonts which use the same ligature behaviour?

**Comment by alexsurelee** [comment]
> Does the same thing happen with other fonts which use the same ligature behaviour?

Just tried with Fira Code, appears to do the exact same thing.

**Comment by mdtauk** [comment]
> > Does the same thing happen with other fonts which use the same ligature behaviour?
> 
> Just tried with Fira Code, appears to do the exact same thing.
>
Thanks, guess that narrows it down to the plugin
