### ISSUE TITLE
Bug Report Custom symbols fail to display on column 100

### ISSUE THREAD

**Issue by killbunny** [microsoft/cascadia-code#166]
# Environment

```none
Cascadia Code version number: Version 1910.040
Application (with version) used to display text: Visual Studio 2013
OS platform and version: Windows 7 SP1 build version 7601
Screen resolution (i.e. 220dpi):  1366x768 

```

# Steps to reproduce

On Column 100, if the text row contains an alphabeth letter the custom symbols ( e.g. ![image](https://user-images.githubusercontent.com/21988191/67585678-ae2bf100-f715-11e9-8b98-361bb221adeb.png )) fails to display
![image](https://user-images.githubusercontent.com/21988191/67585554-660cce80-f715-11e9-9e33-d71749349f97.png)

# Expected behavior

The custom symbols should display as usual

# Actual behavior

The symbol for not equals is not displaying in the column number 100 
It also happens for all custom symbols
![image](https://user-images.githubusercontent.com/21988191/67585879-0c58d400-f716-11e9-8fa2-2deaf832e4ca.png)

**Comment by DHowett-MSFT** [comment]
This just seems like a VS 2013 issue? I didn't even know VS 2013 supported ligatures...

**Comment by killbunny** [comment]
I replicate it in VS 2019 but only when i put quotes after the ==
![image](https://user-images.githubusercontent.com/21988191/67588172-13361580-f71b-11e9-9e82-728743feb2dc.png)

**Comment by ExE-Boss** [comment]
That&nbsp;seems more&nbsp;like a&nbsp;**Visual&nbsp;Studio**&nbsp;issue, than&nbsp;a&nbsp;**Cascadia&nbsp;Code**&nbsp;issue.

**Comment by aaronbell** [comment]
Agreed, this sounds like a VS issue. Closing :).
