### ISSUE TITLE
Gap between slash(//) marks becomes wider when CJK words are used

### ISSUE THREAD

**Issue by NDelt** [microsoft/cascadia-code#167]
# Environment

```none
Cascadia Code version number: 1910.04
Application (with version) used to display text: Visual Studio 2019
OS platform and version: Windows 10 1903, 18362.418
Screen resolution (i.e. 220dpi): 1920x1080 with 15.6", 141.21dpi
```

# Steps to reproduce

1. Write double slash(`//`).
2. Write some CJK words.

# Actual behavior

![comment](https://user-images.githubusercontent.com/46282492/67744760-b6fa2b00-fa65-11e9-8e30-00017bff6501.PNG)

The gap between slashes becomes wider when the sentence is not started with ASCII words.
I have used many other fonts that not supporting CJK glyphs, but there was no issue like this.

**Comment by DHowett-MSFT** [comment]
Something about the font fallback seems to turn off ligatures.

**Comment by NDelt** [comment]
I agree. Is it possible to turn off ligatures completely on VS2019?

**Comment by aaronbell** [comment]
AFAIK there is no way to disable ligatures in VS2019, but I'm planning to put together a version of Cascadia Code with ligatures disabled, which will help work around whatever bug this is.

**Comment by aaronbell** [comment]
@NDelt not sure if you saw that Cascadia Mono (the font without ligatures) was released. Does that version help solve your problem?

**Comment by NDelt** [comment]
@aaronbell Yeah, the issue has resolved after changing the font to Cascadia Mono.

But anyway, Visual Studio needs enable/disable option for font ligature.
Following screenshot is JetBrains Mono, and it contains ligature so same issue occurs in VS.

![vs2019](https://user-images.githubusercontent.com/46282492/72495715-db96bf80-386a-11ea-9342-67b38f097882.PNG)

**Comment by aaronbell** [comment]
Great! Well, I mean great that the mono version works better for you. , not that the bug is present in other fonts. This definitely sounds like something the visual studio team should look into (if they aren’t already).

As this is not a font bug with Cascadia Code, closing!
