### ISSUE TITLE
Include the √ character (charcode 0x221A)

### ISSUE THREAD

**Issue by emptyother** [microsoft/cascadia-code#176]
# Description of the new feature/enhancement (with images if possible)

Noticed when I ran the command `yo doctor` that their checkboxes were missing. This is the `√` character (charcode 0x221A). Consider including?

**Comment by mdtauk** [comment]
Full math symbol support would be nice to have

**Comment by emptyother** [comment]
[I learned](https://github.com/adam7/delugia-code/issues/20#issuecomment-550501264) that Windows Terminal will pick up that character from another font if it is missing, it is just Conhost that doesn't do that. So this feature isn't really needed unless you want to support conhost-based terminals, i guess.
