### ISSUE TITLE
Check mark symbol

### ISSUE THREAD

**Issue by JVimes** [microsoft/cascadia-code#177]
# Description of the new feature/enhancement

The check mark symbol `✓` (U+2713) would be useful to have.

There are variations to consider (probably not all are necessary)
* ✓ check mark (U+2713)
* ✔ heavy check mark (U+2714)
* 🗸 light check mark (U+1F5F8)
* ⍻ not check mark (U+237B)
* ☑ ballot box with check (U+2611)
* ✅ white heavy check mark (U+2705)

**Comment by aaronbell** [comment]
Thanks! I'm planning to include the check mark (u+2713) in the next release of the font. The other items will probably come as the font continues to expand. Closing for now!

**Comment by aaronbell** [comment]
Derp, I should leave this open until the new version is live. Sorry!

**Comment by JVimes** [comment]
Awesome thanks! 😊
