### ISSUE TITLE
Make Cascadia Code available in the Microsoft Store

### ISSUE THREAD

**Issue by Erableto** [microsoft/cascadia-code#178]
# Description of the new feature/enhancement

Many fonts, like [Arial Nova](https://www.microsoft.com/store/productId/9NS5CT1MZ7M8), are available in the Microsoft Store. I think it would be nice to see Cascadia Code there too.
It would also allow you to easily update the font directly from the Store.

**Comment by IllusionMH** [comment]
Looks similar to #39

**Comment by Erableto** [comment]
> Looks similar to #39

Yep. Thanks ^^.

**Comment by aaronbell** [comment]
Closing as duplicate. Thanks!
