### ISSUE TITLE
Feature Request: support "Geometric Shapes"

### ISSUE THREAD

**Issue by rivy** [microsoft/cascadia-code#179]
As a complement to the ["box drawing"](https://unicode-table.com/en/blocks/box-drawing) and ["block elements"](https://unicode-table.com/en/blocks/block-elements) characters, the ["geometric shapes"](https://unicode-table.com/en/blocks/geometric-shapes)(`U+25A0-25FF`) block would be a useful addition.

[`tig`](https://github.com/jonas/tig), specifically, uses characters from that block to display `git` log graphs.

**Comment by mdtauk** [comment]
@aaronbell @cinnamon-msft  Hopefully these Geometric Shapes should be good to go.

I used 150pt as the stroke thickness, to match the 1/8 block element thickness.

![image](https://user-images.githubusercontent.com/7389110/68547360-92dd0900-03d8-11ea-9471-58b23969180e.png)


[CascadiaCode - Geometric Shapes.zip](https://github.com/microsoft/cascadia-code/files/3828698/CascadiaCode.-.Geometric.Shapes.zip)

**Comment by aaronbell** [comment]
Looks great! Thanks :)

I'll add it into the source for the next drop.

**Comment by mdtauk** [comment]
Some of the contours have errors looking at the latest released 1911.20 version of the font.

![image](https://user-images.githubusercontent.com/7389110/69373446-b71fcc00-0c9b-11ea-9be2-d18a1d922e4f.png)

and with the circle quarters
![image](https://user-images.githubusercontent.com/7389110/69373501-d4549a80-0c9b-11ea-98d0-b2a28fe6f83f.png)

These do not appear in the TTF file I generated
![image](https://user-images.githubusercontent.com/7389110/69373622-24336180-0c9c-11ea-9096-dddfbae1dfea.png)
![image](https://user-images.githubusercontent.com/7389110/69373704-5349d300-0c9c-11ea-9bb9-32a0adf48aec.png)

**Comment by DHowett-MSFT** [comment]
@mdtauk can you file a separate issue for this?

**Comment by mdtauk** [comment]
> @mdtauk can you file a separate issue for this?

@DHowett-MSFT #192
