### ISSUE TITLE
Feature Request - Letter w and m not quite readable

### ISSUE THREAD

**Issue by wp-kitten** [microsoft/cascadia-code#180]
# Description of the new feature/enhancement (with images if possible)

The letters: W w M m are not very readable, unless the font size is very big.

![soma  D__www_soma  -  _extensiiprofesionale ro_wp-content_plugins_woocommerce_src_Packages php - PhpStorm 2019-11-11 18 04 34](https://user-images.githubusercontent.com/9017321/68601804-c76ec480-04ad-11ea-8247-6e4f314e0012.png)

# Proposed technical implementation details (optional)

Please improve the readability of those letters when using small font sizes, ex: 12, 13, 14px)

**Comment by aaronbell** [comment]
Thanks for the report. This issue is due to the lack of a bold weight. As such, the application is bolding the font in software which produces poor results. There are plans to build out the weight ranges for this font. Sorry for the trouble until the updated version is available!

**Comment by aaronbell** [comment]
This is covered by #43. Closing as duplicate.

**Comment by wp-kitten** [comment]
Thank you for the information, much appreciated!
