### ISSUE TITLE
Tab character is displayed with 'A' in BBEdit

### ISSUE THREAD

**Issue by nostodnayr** [microsoft/cascadia-code#183]
# Environment

```none
Cascadia Code version number: 1910.04 (and with November Update #181 builds)
Application (with version) used to display text: BBEdit 13.0.3
OS platform and version: macOS 10.15.1
Screen resolution (i.e. 220dpi): n/a
```

# Steps to reproduce

1. Download and install BBEdit 13.0.2 from https://www.barebones.com/support/bbedit/updates.html
2. Create a new text document in BBEdit
3. Enter a `tab` character (0x0009)

# Expected behavior

The tab character should appear as ‘clear’. For reference, using Consolas:

<img width="662" alt="consolas-tab-example" src="https://user-images.githubusercontent.com/2190735/68986055-e333eb00-085e-11ea-8c80-b77a177e7c11.png">

# Actual behavior

Using Cascadia Code (including the new November update #181 and the Mono variants) this is displayed thusly:

<img width="647" alt="cascadia-tab-example" src="https://user-images.githubusercontent.com/2190735/68986058-e929cc00-085e-11ea-8cb0-daff5475c0a1.png">

Note that the Mono variants display an accented A (Á) in the tab character.

**Comment by aaronbell** [comment]
Interesting. That character is not contained in the font, so it is probably going to a fallback character, or something else is going on. I'll add it in.

**Comment by nostodnayr** [comment]
Thanks for adding the character, I expect that will take care of the issue.

Fallbacks were changed in macOS 10.15, it seems. For monospace fonts, the OS appears to fall back to Menlo, though something is clearly going wrong along the way.

On 10.14, the 1909.16 release didn't suffer from this issue, but 1910.04 did. On 10.15, even the initial release does. Definitely a mystery.

**Comment by nostodnayr** [comment]
@aaronbell, I tried this with the builds in your fork today and it may be improved, but not fully corrected. I now see the accented Á in place of a tab with all the fonts.

<img width="349" alt="Screenshot 2019-11-19 at 20 49 17" src="https://user-images.githubusercontent.com/2190735/69144188-1354e580-0b0e-11ea-86c0-1fcc03626c88.png">

Apologies if I'm jumping the gun here, but I thought it better to bang on it now.

**Comment by aaronbell** [comment]
<img width="429" alt="Screen Shot 2019-11-19 at 9 18 42 AM" src="https://user-images.githubusercontent.com/8460297/69169863-ebce3080-0aad-11ea-87ee-52f58e458f56.png">

Unfortunately, I don't have an install of 10.15 available to test on, but in my build on 10.14, I am seeing the 'tab' invisible character (delta) appear correctly with the latest version of the font (the one that you looked at from my branch this morning). 

I wonder if there's an issue with font conflicts going on—this can happen if the font stored in the font cache on your system is different than the one that is actually installed. I'd suggest (a) removing all traces of the font from your system, (b) clearing your font cache, (c) reinstalling the font. This is an issue that I've run into a lot in the past, which is why I use a font manager application rather than installing fonts directly.

**Comment by nostodnayr** [comment]
Note that when I’m trying, I’m _not_ using show invisibles. 

The font cache idea is definitely worth investigating. I’ll blow it all out when I get a chance later today and keep my fingers crossed. Thanks, Aaron.

**Comment by aaronbell** [comment]
Oh, that's super confusing. Might be a BBEdit / Mac OSX thing?

You might also double check the character encoding (UTF-8) since sometimes accented characters show up in those scenarios too.

**Comment by nostodnayr** [comment]
I first filed it as a BBEdit bug, but was told it pretty much had to be a font bug. My understanding, though, is that BBEdit uses some different/unusual, yet entirely legal, methods for displaying text. 

The encoding shouldn’t have been an issue, but I’ll consider it in my testing and investigation. Fingers crossed it’s just the cache. 😅

**Comment by nostodnayr** [comment]
Font caches all cleared out, rebooted, tried with different users and the issue remains, unfortunately. Changing the encoding didn't affect anything, either. 😕

**Comment by nostodnayr** [comment]
And, not that I expected any different, but I tested with the release version and the tabs still make the fonts unusable. I don't intend to pursue this any further.

**Comment by aaronbell** [comment]
Thanks @nostodnayr. I'm sorry that we weren't able to sort out what's going on! I'll leave this bug open in case and try to figure it out in the future.

**Comment by aaronbell** [comment]
@nostodnayr if you could do me a favor, could you copy the string that includes the unexpected letter and drop it in here. I’d like to double check which Unicode slot is showing up. Meanwhile I’m taking it up with BBEdit :)

**Comment by nostodnayr** [comment]
This is the character: [	]

BBEdit's Character Inspector reports:
<img width="322" alt="Screenshot 2019-11-25 at 15 49 55" src="https://user-images.githubusercontent.com/2190735/69518633-678f1800-0f9b-11ea-8a2d-85c301debecb.png">

Here's a zipped text file that contains the character, just in case that's helpful at all.
[cascadia-tab.text.zip](https://github.com/microsoft/cascadia-code/files/3885181/cascadia-tab.text.zip)

With luck, it'll just be a BBEdit issue, presuming the font is fine. I suspect it might be the OS, and I don't imagine it would be considered a high-priority.

Thanks for continuing to work on it.

**Comment by aaronbell** [comment]
@nostodnayr just wanted to let you know we figured out the cause of the bug that you observed. Apparently BBEdit is running on top of an antiquated Apple API which, for whatever reason, requires the presence of certain glyphs in the font. By adding the requisite glyph slots, it is now working correctly! :)

The next release of the font will contain the new glyph. Please look forward to it!

**Comment by nostodnayr** [comment]
@aaronbell that's fantastic. I just built the fonts and they're working great. Thanks for being tenacious in tracking this down and fixing it.
