### ISSUE TITLE
Use a 'pointing in' glyph for *true* single and double quotation marks

### ISSUE THREAD

**Issue by nostodnayr** [microsoft/cascadia-code#184]
Open quotation marks, single and double, feel as though they’re pointing the wrong direction.

The characters have a bit more weight at the bottom but ‘point outward’, making it appear backwards.

<img width="221" alt="Cascadia Code" src="https://user-images.githubusercontent.com/2190735/68986422-a4a02f80-0862-11ea-8167-8859eb4943ad.png">

Contrast this with Courier and Courier New, both of which use a similar glyph style:

Courier has a weighted bottom, pointing ‘in’:
<img width="173" alt="Courier" src="https://user-images.githubusercontent.com/2190735/68986427-abc73d80-0862-11ea-9881-ea77dbc1b6c0.png">

Courier New has a weighted top, pointing ‘in’:
<img width="249" alt="Courier New" src="https://user-images.githubusercontent.com/2190735/68986431-baadf000-0862-11ea-9322-5f2d80b6e488.png">

***

Cascadia should use a ‘pointing inward’ glyph for its quotation marks.

I find the ‘weighted top’ style to be easier to read when using this style of glyph. For example, compare to SF Mono, whose quotes are very difficult to discern at anything but large sizes because it uses a ‘weighted bottom’ style:

<img width="193" alt="SF Mono" src="https://user-images.githubusercontent.com/2190735/68986536-ac140880-0863-11ea-8ca4-835563bf078b.png">

**Comment by mdtauk** [comment]
I think Courier New has the most pleasing idea, even if it doesn't adhear to the 66 and 99 of traditional quotation marks

**Comment by aaronbell** [comment]
Hmm. Interesting. I'll do some experimentation. My preference tends toward the 'weighted bottom' approach as I think it is more typographically attractive than the weighted top, but maybe there's something we can do to make them more recognizable.

**Comment by nostodnayr** [comment]
Like with the other issue, I tried the builds in your fork, @aaronbell, and the quotes are much better. It's still a little hard to tell if _single_ quotes are curled the right direction. There's enough accumulated weight in doubles that it's quite easy.

Regardless, they now _look right_, which will make this writer's life a little easier. Thanks very much!

**Comment by aaronbell** [comment]
Glad they're working better!
