### ISSUE TITLE
Suggestion: Enable GitHub wiki for community-built documentation

### ISSUE THREAD

**Issue by dmxt** [microsoft/cascadia-code#185]
### The issue
After skimming the issue page, I noticed many issues created revolving documentation issues after attempting to take on ligature documentation due to the open issue https://github.com/microsoft/cascadia-code/issues/37 by initiating a wiki page dedicated to ligature keywords. 

In progress, I couldn't find a Github wiki nor a way to create one, so it gives me the impression that this feature may be intentionally disabled, or it may be disabled for community editing for this repository.

### Suggestion
If we have the wiki, we may witness:
* README.md is no longer crammed like it is now
* We also may witness an increase in contributions due to no development knowledge requirement in documentation/wiki editing, just like me as a candidate. 

Check out [FiraCode Github wiki](https://github.com/tonsky/FiraCode/wiki) as an excellent example of how our wiki could be if enabled.

---

The intended purpose for this issue is to feel out the opinion from the community or contributors themselves. If we're affirmative on creating a wiki, by then, it's a potential possibility that we'll have one. So, therefore, the question:

**To everybody: Do you agree or disagree that it's a good idea to enable community-based wiki?**

Please reply with your thoughts on this suggestion if you can! Everybody's responses are appreciated and factored into consideration.

**Comment by aaronbell** [comment]
You got it! I've updated the README and moved most of the content to a new Wiki. I've also added some content around the current coding ligature info and other things. Look forward to your help 👍
