### ISSUE TITLE
Odd Padding in VSCode Terminal (Xterm)

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/cascadia-code#186]
# Environment

```none
Cascadia Code version number: 1910.04
Application (with version) used to display text: vscode-insiders and vscode
OS platform and version: Windows 10 GA and Insiders
Screen resolution (i.e. 220dpi): Multiple monitors, multiple DPIs tested

Any other software?
```

# Steps to reproduce
1. Set "terminal.integrated.fontFamily": "Cascadia Code"
2. Open terminal
3. Use some characters that have a background color
4. There will be background padding at the bottom.

# Expected behavior
No additional padding below the lines

# Actual behavior
![image](https://user-images.githubusercontent.com/15258962/69079242-6fc0e380-09ee-11ea-88bb-f3ba28a7e566.png)
Note the padding at the bottom. No other font tested does this.

**Comment by aaronbell** [comment]
Hi Justin, can you try the latest version and specifically the PL (Powerline) version you see if this is resolved? 

I suspect part of the problem was that you were getting a fallback character for the circle from a different font that doesn’t align with Cascadia.

**Comment by JustinGrote** [comment]
Same issue (Note the additional padding at bottom), maybe this is a vscode thing however, as it looks proper in Windows Terminal I noticed. Something to open with the vscode team?

![image](https://user-images.githubusercontent.com/15258962/69920288-dad0d800-143a-11ea-86e9-680144ca3824.png)

**Comment by JustinGrote** [comment]
Also trying it with a different powerline-patched font (Inconsolata NF) doesn't show the padding
![image](https://user-images.githubusercontent.com/15258962/69920303-3307da00-143b-11ea-80d3-4da9b4cdea25.png)
