### ISSUE TITLE
build.py: update the main UFOs public.glyphOrder when adding glyphs from auxilliary UFOs

### ISSUE THREAD

**Issue by madig** [microsoft/cascadia-code#191]
# Description of the new feature/enhancement

Expanding on https://github.com/microsoft/cascadia-code/pull/189#discussion_r348786297: The UFO specification does not define the order of glyphs that are outside the `public.glyphOrder` key. ufo2ft, the compiler used in the build script, will sort those glyphs alphabetically, but you may want to explicitly define the order of all glyphs to prevent surprises down the road.

# Proposed technical implementation details (optional)

Add after https://github.com/microsoft/cascadia-code/blob/0fc275c0d3736640cbaa2351eb1ad5b60b924f98/build.py#L30-L32

```Python
instance.lib["public.glyphOrder"].extend(ufo.lib["public.glyphOrder"])
```

to append the order of the auxiliary UFO as is to the current one.

**Comment by aaronbell** [comment]
I haven't been super concerned about the setting a glyph order of the Nerd Font additions as those glyphs are not hinted. But should things change, then definitely would make sense to preserve glyph order.

**Comment by aaronbell** [comment]
Hi! I'm going through old bugs. This is not an issue that I'm concerned about, so I'm going to go ahead and close it for now :).
