### ISSUE TITLE
Bug Report: Some Geometric Shape characters have incorrect contour directions

### ISSUE THREAD

**Issue by mdtauk** [microsoft/cascadia-code#192]
# Environment

```none
Cascadia Code version number: 1911.20
Application (with version) used to display text: UWP Character Viewer
OS platform and version: Windows 10 1909
Screen resolution (i.e. 220dpi): 100% dpi

Any other software?
```

# Details

Some of the contours have errors looking at the latest released 1911.20 version of the font.

![image](https://user-images.githubusercontent.com/7389110/69373446-b71fcc00-0c9b-11ea-9be2-d18a1d922e4f.png)

and with the circle quarters
![image](https://user-images.githubusercontent.com/7389110/69373501-d4549a80-0c9b-11ea-98d0-b2a28fe6f83f.png)

These do not appear in the TTF file I generated, which were used to add the glyphs
![image](https://user-images.githubusercontent.com/7389110/69373622-24336180-0c9c-11ea-9096-dddfbae1dfea.png)
![image](https://user-images.githubusercontent.com/7389110/69373704-5349d300-0c9c-11ea-9bb9-32a0adf48aec.png)

**Comment by DHowett-MSFT** [comment]
Interesting. It looks like the stroke directions got a little out of whack with these glyphs... I wonder why.

**Comment by mdtauk** [comment]
> Interesting. It looks like the path directions got a little out of whack with these glyphs... I wonder why.

I submitted a TTF where the contours were collapsed.  But perhaps they were redrawn, and the path directions were not made correctly.

**Comment by DHowett-MSFT** [comment]
It also looks like there's a hinting program in the source for those glyphs which is getting ignored. Curious.

@aaronbell any idea?

**Comment by mdtauk** [comment]
> It also looks like there's a hinting program in the source for those glyphs which is getting ignored. Curious.
> 
> @aaronbell any idea?

I imported the glyphs file, added the new Glyphs in FontLab 6, removed the other glyphs so only those codepages were there, and exported to TTF

**Comment by aaronbell** [comment]
Yeah, when I integrated @mdtauk's ttf in, I was correcting the cubic / quadratic conversion and thought it easier to split the outer circle from the inner section (as round to straight lines get particularly messy), but it appears that Glyphs decided that the contour directions should be flipped and I didn't notice. I'll have a quick fix for it here in a min.

**Comment by mdtauk** [comment]
> Yeah, when I integrated @mdtauk's ttf in, I was correcting the cubic / quadratic conversion and thought it easier to split the outer circle from the inner section (as round to straight lines get particularly messy), but it appears that Glyphs decided that the contour directions should be flipped and I didn't notice. I'll have a quick fix for it here in a min.

Thanks @aaronbell, it was only when I explored the released version, that I noticed it.  Sorry to be a bummer for the version release.

**Comment by mdtauk** [comment]
@aaronbell  If I submit any more glyphs in the future, I will be sure to submit as OpenType OTF, so the curves retain their bezier nodes.
