### ISSUE TITLE
Cascadia Code PL renders poorly in VSCode

### ISSUE THREAD

**Issue by bterlson** [microsoft/cascadia-code#193]
# Environment

```none
Cascadia Code PL 1911.20
Application (with version) used to display text: VSCode 1.40.1
OS platform and version: Windows 10
Screen resolution (i.e. 220dpi): various tried (see below)
```

# Steps to reproduce

On a monitor with 100% scaling (aka no scaling, I think?), Cascadia Code PL renders poorly. A monitor with scaling enabled renders the font nicely. 

![image](https://user-images.githubusercontent.com/11236/69375455-3e018400-0c5d-11ea-98d9-07c24161b3f0.png)

# Expected behavior

It should render like the non-PL variant of Cascadia Code.

![image](https://user-images.githubusercontent.com/11236/69375516-5d001600-0c5d-11ea-87c5-a8127f77c323.png)

**Comment by DHowett-MSFT** [comment]
What font size is that?

**Comment by bterlson** [comment]
14px

**Comment by DHowett-MSFT** [comment]
Curiously, this is what I get at "14px" on a 100% display. It's hinted for 12pt, which is approximately correct.


![image](https://user-images.githubusercontent.com/14316954/69376988-355e7d00-0c60-11ea-91eb-89b55a65b786.png)

**Comment by bterlson** [comment]
I've found angle brackets are the easiest place to spot the issue. FWIW I see the same issue at 12px, but it's not as noticeable thanks to my poor eyesight 😀

To me the strangest thing is that this happens with only with the PL variant. I noticed this yesterday when I built everything myself from source, too.

**Comment by aaronbell** [comment]
The image you showed above looks like it is gridfitted, but unhinted.

@DHowett-MSFT Can you confirm that your script properly processed the PL font through VTT? 

@bterlson Did you do the last manual step of processing the font through VTT when you built it yourself? I know that they're looking to set up an automated system, but I don't think it is in place yet.

**Comment by DHowett-MSFT** [comment]
Yep: looking at the PL font in VTT before and after vttshell yields this:

### before

![image](https://user-images.githubusercontent.com/14316954/69379513-773df200-0c65-11ea-9778-a8b8e483dbcf.png)


### after

VTT offered to import the hinting programs from the binary data, so it looks like it decompiled what it had earlier compiled, and all the VTT comments are gone. :smile:

![image](https://user-images.githubusercontent.com/14316954/69379522-7a38e280-0c65-11ea-9159-62cc6d69781a.png)

**Comment by bterlson** [comment]
@aaronbell I did no manual process, just ran the python script and installed the resulting files.

**Comment by Basaingeal** [comment]
I'm also seeing this. Alphanumeric letters look overall crisper in Cascadia Code PL, than in Cascadia Code. I like the look better, but the angled glyphs look worse.

### Cascadia Code
![image](https://user-images.githubusercontent.com/36519219/69381455-6a77c900-0c7a-11ea-8f58-d13badf1a7ff.png)

### Cascadia Code PL
![image](https://user-images.githubusercontent.com/36519219/69381477-7499c780-0c7a-11ea-9a8b-0b2076e4112d.png)

**Comment by aaronbell** [comment]
Hmmm. So something I am noticing is that the GASP table data I had attempted to insert into the font apparently is not being preserved. While all the glyphs are correctly hinted, the lack of a GASP table may be resulting in the rendering engine 'guessing' about how to treat the fonts. It may be that in the case of PL, it is guessing they are unhinted (rather than hinted) and thus is rendering them differently.

**Comment by DHowett-MSFT** [comment]
@bterlson if you’re just using the build script output, your font is totally unhinted.

**Comment by bterlson** [comment]
@DHowett-MSFT I am seeing the issue with the downloaded version as well. I suppose it's possible vscode is still using the custom one I built? I downloaded the PL variant from releases, set vscode's font name to `Cascadia Code PL` and restarted it also just to be sure.

**Comment by aaronbell** [comment]
@bterlson For some reason even the 'official' version is not rendering correctly. I've submitted a PR to add a GASP table to all versions, which should make rendering more consistent.
