### ISSUE TITLE
Documentation Issue - Chocolatey Install Instructions

### ISSUE THREAD

**Issue by zunderscore** [microsoft/cascadia-code#198]
Since app/environment-specific installation instructions have moved out of the README and into the wiki, can we add the following Chocolatey install instructions to the wiki?

## Installation Via Chocolatey (unofficial)

[Chocolatey](https://chocolatey.org) users can download and install the latest release of Cascadia Code or any of its variants via the following packages:

```powershell
choco install cascadiacode
choco install cascadiamono
choco install cascadiacodepl
choco install cascadiamonopl
```

You can also upgrade to the latest version by running:

```powershell
choco upgrade cascadiacode
choco upgrade cascadiamono
choco upgrade cascadiacodepl
choco upgrade cascadiamonopl
```

If you have any issues installing/upgrading a package please go to that package's page (e.g. [Cascadia Code](https://chocolatey.org/packages/cascadiacode)) and follow the [Chocolatey triage process](https://chocolatey.org/docs/package-triage-process).

**Comment by aaronbell** [comment]
You got it! Thanks :)
https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code
