### ISSUE TITLE
Return original Glyphs project file

### ISSUE THREAD

**Issue by den32ds** [microsoft/cascadia-code#203]

**Comment by DHowett-MSFT** [comment]
Why? We explicitly moved away from Glyphs. Please qualify your ask.

**Comment by aaronbell** [comment]
We have converted the source file to UFO. If you'd like to convert it to a Glyphs source, please use [glyphslib](https://github.com/googlefonts/glyphsLib).

**Comment by den32ds** [comment]
IMHO UFO does not support all features as original project file from font editor.

**Comment by den32ds** [comment]
If this is not Robofont*

**Comment by aaronbell** [comment]
This topic was discussed in #78.

Essentially, yes, there are features that Glyphs, or Fontlab offer that are not available in UFO—for example smart components. However, this project does not use any of those features, and is not planning to use any of those features. As such, there is no reason, at this time, to use a Glyphs source, and greater benefit to use a UFO source.

**Comment by den32ds** [comment]
I do not agree with this, but it is not for me to decide

**Comment by aaronbell** [comment]
As I said, if you want to work with it in a Glyphs source, you can easily convert the UFO to a Glyphs file using glyphslib. From there, make any modifications that you'd like. Or explain to me what features we've lost.
