### ISSUE TITLE
What's the different between Cascadia.ttf and CascadiaMono.ttf?

### ISSUE THREAD

**Issue by ytingone** [microsoft/cascadia-code#204]
The "original" Cascadia.ttf looks mono, so I am wondering what's the different between them.
![image](https://user-images.githubusercontent.com/7035143/69477527-3dfeb100-0e22-11ea-84ab-a06efe7ba28c.png)

**Comment by DHowett-MSFT** [comment]
![Uploading image.png…]()

**Comment by DHowett-MSFT** [comment]
er, sorry.

that failed terribly :smile:

![image](https://user-images.githubusercontent.com/14316954/69477557-62b04580-0d9c-11ea-87c5-6e57a0d1da46.png)


I've also copied that to the latest release note.

**Comment by ytingone** [comment]
Thank you very much!

**Comment by smlombardi** [comment]
Can this be added to the ReadMe file?  I had to Google it.
