### ISSUE TITLE
Add Unicode character 'NO-BREAK SPACE' (U+00A0)

### ISSUE THREAD

**Issue by aurel26** [microsoft/cascadia-code#207]
It seems that the font does not include the character 'NO-BREAK SPACE' (U+00A0).
This character is used especially by the current console for file sizes.
Since this character is not present, the substitution character is used.

![charmap](https://user-images.githubusercontent.com/12686104/69485913-c478ba00-0e45-11ea-850d-cadc0d044c16.png)

**Comment by DHowett-MSFT** [comment]
What led you to believe that that is a non-breaking space? On my locale, it is a comma (`,`). Can you copy/paste the directory listing to the clipboard to reveal what the character actually is?

I ask only because the font _actually does_ have a non-breaking space in it.

![image](https://user-images.githubusercontent.com/14316954/69485958-11836e80-0dfb-11ea-92aa-996cd6836c07.png)

**Comment by DHowett-MSFT** [comment]
commas: 

![image](https://user-images.githubusercontent.com/14316954/69485961-2a8c1f80-0dfb-11ea-9f36-1934a6abdbf4.png)

**Comment by aurel26** [comment]
Probably because your system is in English and configured to use a comma for "Digit grouping symbol".

In French, the "Digit grouping" use a space, preferably not breakable. This is the default configuration of Windows.

You have to use the legacy control panel (control.exe) to see this configuration.

![control](https://user-images.githubusercontent.com/12686104/69491255-e8aeb800-0e92-11ea-8392-e06c302acbaa.png)

**Comment by DHowett-MSFT** [comment]
Still, it’s not character A0. Can you help figure out what it really is?
Thanks!

**Comment by PhMajerus** [comment]
I tested with the standard fr-FR locale, and the default separator is U+00A0 and showing properly with all flavors of Cascadia in the standard conhost.

**Comment by aurel26** [comment]
I got it!
My previous font update did not work correctly and I used a version older to pull request #141.
Indeed, the updated font (1911.210) does contain the character (U+00A0). Everything is fine now.
Sorry for the inconvenience and thank you for your work.
