### ISSUE TITLE
release: include all fonts in ZIP when publishing a release

### ISSUE THREAD

**Issue by bnb** [microsoft/cascadia-code#208]
# Description of the new feature/enhancement (with images if possible)
In GitHub releases, ship an additional ZIP file that includes all fonts. This will enable 1 download rather than multiple.

# Proposed technical implementation details (optional)
ZIP the (currently) 4 fonts up before publishing the release and include that file in the release.

**Comment by janhenke** [comment]
I second that. For the first 2 releases the archive did include these, making the packaging for my distribution (Gentoo) really easy. For the current release, it no longer works like that, holding back the update until I can build all fonts locally.

**Comment by aaronbell** [comment]
Looks like Dustin has gotten back to releasing them as a zip :)
