### ISSUE TITLE
Add more change math signs

### ISSUE THREAD

**Issue by Tomirad** [microsoft/cascadia-code#209]
My idea is render more math signs, example:

`+` & `-` to  `±`

^n to ⁿ
^2 to ²

Mathematical formulas are more readable, maybe other people will have more ideas.

**Comment by aaronbell** [comment]
This is an interesting idea. I think there's two main issues with it, though.

1) In the current ligature implementation, replacing two characters with one maintains the width of the two characters. So `+` and `-` would result in a two-width version of `±`. Similarly, `^` and `n` would be a double-width version of `ⁿ`. It ensures that line lengths are maintained despite the ligation. So this suggestion would break that. 

2) I suspect that certain merged forms might have other meanings in certain coding languages and am hesitant to make over-use of the ligated forms in case that it breaks stuff. This kind of feature might make a lot of sense in a math-centric variant of the font.

**Comment by Tomirad** [comment]
So I think you can use this idea in the future.

**Comment by PhMajerus** [comment]
^ is the bitwise XOR in JavaScript, as in 7^2=5, showing that as 7²=5 would be highly confusing.
(details: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Bitwise_XOR )

**Comment by VladimirMarkelov** [comment]
as for:

> ^n to ⁿ
> ^2 to ²

I can suggest implementing "superscript and subscript" section. Example from DejaVu Sans:

⁰ⁱ⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ⁿ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎ₐₑₒₓₔₕₖₗₘₙₚₛₜ

**Comment by aaronbell** [comment]
@VladimirMarkelov Cascadia Code already included a full numeral subscript / superscript feature.

Per @PhMajerus‘ comment, I don’t think this kind of ligature should be implemented in the font at this time.

**Comment by VladimirMarkelov** [comment]
I agree with you - no need to add ligatures in this case since here the font has to draw one-space character instead of two-space one. 

Which font version includes full sub-/superscript features? I checked "Cascadia Code" installed with Windows Terminal (font version 1911.210) and it says - 18 out 24 characters:

⁰⁴⁵⁶⁷⁸⁹ⁿ₀₁₂₃₄₅₆₇₈₉

That was why I added my comment (because, e.g, I did not see "2" as a superscript to imitate "^2").

**Comment by aaronbell** [comment]
Yeah, it is kind of irritating how the set is split up in the unicode range, but they're all there :).
