### ISSUE TITLE
hinting on all the ligatures is either wrong or missing

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/cascadia-code#21]
12pt 96dpi

![image](https://user-images.githubusercontent.com/14316954/65067675-e7658a00-d93b-11e9-8a78-a3afc6f85560.png)

**Comment by aaronbell** [comment]
Jagginess is due to Visual Studio's text rendering mode that does not support y-direction antialiasing. No fix necessary to the font :).
