### ISSUE TITLE
Include missing glyphs used by oh-my-posh

### ISSUE THREAD

**Issue by pmartin-brierley** [microsoft/cascadia-code#210]
Please include some of the following glyphs that are used by oh-my-posh themes.  These can be added to the powerline variants:

VirtualEnvSymbol  \ue606
PromptIndicator ❯ \u276f
FailedCommandSymbol ⨯ \u2a2f
BranchUntrackedSymbol ≢ \u2262
BranchIdenticalStatusToSymbol  ≣ \u2263
Bitbucket  \uf171
GitLab  \uf296
Github  \uf09b

**Comment by hanubeki** [comment]
Could be #194

**Comment by aaronbell** [comment]
I am able to add some of the characters that you mention, but cannot add the u+exxx or u+fxxx characters at this time as they're part of the greater Nerd Fonts set. Once that all has been sorted out, this will get resolved :)

**Comment by pmartin-brierley** [comment]
> 
> 
> I am able to add some of the characters that you mention, but cannot add the u+exxx or u+fxxx characters at this time as they're part of the greater Nerd Fonts set. Once that all has been sorted out, this will get resolved :)

Got it, thanks!

**Comment by sba923** [comment]
Also missing:

ElevatedSymbol \u26a1 HIGH VOLTAGE SYMBOL

**Comment by sba923** [comment]
Now that I know there are fonts out there with these glyphs ;-) I would've liked to try "Hack Nerd Font" with PowerShell, but it seems it lacks the `isFixedPitch` bit and thus cannot be used... Any alternative (feel free to reject this as "off-topic")?

**Comment by LuanVSO** [comment]
the character \u276F ("❯") which is the bold version of \u276D ("❭") which the font does have.

conhost with cascadia set as font:
![](https://user-images.githubusercontent.com/43626415/73868178-c3d9a800-4826-11ea-8010-9697b74b6765.png)
(i am using zsh here because that command doesn't work in bash)
