### ISSUE TITLE
Asterisks (***) are not rendered properly.

### ISSUE THREAD

**Issue by rajanand** [microsoft/cascadia-code#211]
When 3 asterisks (***) are typed, the second one is not rendering properly. 
![image](https://user-images.githubusercontent.com/1008581/70035497-efe36d80-15d8-11ea-9933-8561b46dff1c.png)

# Environment

```none
Cascadia Code version number:
Application (with version) used to display text: SQL Server Management Studio v18.2
OS platform and version: Windows 10
Screen resolution (i.e. 220dpi): 

Any other software?
```

# Steps to reproduce

Type ***

# Expected behavior

# Actual behavior

**Comment by hanubeki** [comment]
It's a liguature, a feature of this font.

**Comment by mdtauk** [comment]
So maybe the question should be, how many contiguous Asterisks could be turned into ligatures? 4, 5, 6, more?

**Comment by DHowett-MSFT** [comment]
We're following Fira Code's lead here, and they've chosen three.
