### ISSUE TITLE
Powerline GitHub glyph is incorrect

### ISSUE THREAD

**Issue by AndreaPasqualini** [microsoft/cascadia-code#215]
# Environment

```none
Cascadia Code version number: 1911.21
Application (with version) used to display text: GNOME Terminal
OS platform and version: Ubuntu 19.10
Screen resolution (i.e. 220dpi): 96 dpi, text scaled to 1.25 through Gnome Settings -> Universal Access -> Large Text (on)

Any other software?
```

# Steps to reproduce

- Add [trueline.sh](https://github.com/petobens/trueline) to ~/.bashrc
- Navigate the terminal to a GitHub repository

# Expected behavior

- The GitHub glyph would show up in the trueline prompt

# Actual behavior

- Another glyph shows up

# Extra info

- The GitLab glyph instead shows up as expected

![image](https://user-images.githubusercontent.com/24243677/70810776-a955f600-1dc4-11ea-913e-467d79287fd4.png)

**Comment by DHowett-MSFT** [comment]
Powerline contains neither a GitHub nor a GitLab glyph, so neither does Cascadia Code PL...

**Comment by apsql** [comment]
But then I have another question. Why am I seeing the GitLab glyph? Am I getting everything wrong? I clean-installed Ubuntu 19.10 right this morning, so I did not mess around too much with fonts and/or the terminal. In particular, I have no Nerd Font installed.

Anyway, I'm sorry I did not look closer into powerline glyphs and thank you for your reply. Feel free to close the issue. I guess I'll look forward to future developments of #194!

**Comment by tuananh** [comment]
just guessing: a fallback font maybe?

**Comment by aaronbell** [comment]
Hello! I'm going through old bugs. It appears that this issue is not specifically related to Cascadia Code as none of these glyphs is present in the font, so there must be some sort of fallback happening external to the font. As such, I am closing this. If there is reason to re-open, please feel free.
