### ISSUE TITLE
Visual Regression between releases

### ISSUE THREAD

**Issue by craigjennings11** [microsoft/cascadia-code#217]
# Environment

```none
Cascadia Code version number: 1911.21
Application (with version) used to display text: VS Code
OS platform and version: Windows 10 Pro Version 10.0.18362 Build 18362
Screen resolution (i.e. 220dpi): 1920x1080

Any other software?
```

# Steps to reproduce

1. Set VS Code to use `Cascadia Code` at font size `13`
1. Install version 1909.16
1. Take note of ligature rendering
1. Uninstall font
1. Install version 1910.04
1. Take note of ligature rendering
1. Uninstall font
1. Install version 1911.21
1. Take note of ligature rendering

# Expected behavior

Consistent ligature rendering

# Actual behavior

1909.16 Rendering (looks good)
![image](https://user-images.githubusercontent.com/1683368/70921855-b18f7a80-1fea-11ea-8d89-a1c66dc01bf6.png)

1910.04 Rendering (notice misalignment of `===` ligature)
![image](https://user-images.githubusercontent.com/1683368/70921894-c2d88700-1fea-11ea-8250-4e315f13cfe6.png)

1911.21 Rendering (notice blurred `=` character and `=>` ligature rendering)
![image](https://user-images.githubusercontent.com/1683368/70921916-cf5cdf80-1fea-11ea-969c-d6f3c3d6c308.png)

**Comment by aaronbell** [comment]
Thanks for bringing this up. Due to various reasons, the hinting has needed to be redone between versions and it may be that these particular glyphs were hinted differently (either intentionally or unintentionally).

When I have a chance I’ll do a compare of the different hinting versions and determine if a change is necessary.

**Comment by aaronbell** [comment]
Hi there, with the conversion to a variable font, the hinting had to be redone (again 😢 ). Hopefully the new rendering is more workable for you!
