### ISSUE TITLE
Feature Request: A install mechanism for Linux distors. "apt inistall cascadia-code"

### ISSUE THREAD

**Issue by PranavBhattarai** [microsoft/cascadia-code#220]
Like how I installed Firecode, I wish could install **CascadeCode** using `apt install cascadi-code` to install/update. 

It would be really awesome.

![Ubuntu 19.10](https://user-images.githubusercontent.com/32763112/71197593-0fa5b180-22ba-11ea-81d6-b5c8b331bb43.png)

`Distro: Ubuntu 19.10`

**Comment by mfocko** [comment]
Don't mean to be offensive, but what holds you back from creating a package and maintaining it?
[There are distributions that have Cascadia](https://repology.org/project/fonts:cascadia-code/versions)

**Comment by PranavBhattarai** [comment]
@mfocko I wish I could.

**Comment by alexmyczko** [comment]
meanwhile it's packaged:
https://packages.debian.org/source/sid/fonts-cascadia-code
https://launchpad.net/ubuntu/+source/fonts-cascadia-code

**Comment by PranavBhattarai** [comment]
@alexmyczko 
A noob question:

Does this it will come in APT repository? Because it comes there, almost all debain based distros (like Ubuntu) will be able to install it easily.

**Comment by mfocko** [comment]
> Does this mean it will come in APT repository? Because it comes there, almost all Debian based distros (like Ubuntu) will be able to install it easily.

in `focal` it will be in `universe`...
regarding debian... looks liek it's in `unstable` repo

**Comment by fitojb** [comment]
I think this issue can be closed. As a general rule, it isn’t upstream vendor’s business to produce packaging for every distro under the sun, so please avoid sending this kind of bug reports to software authors.

**Comment by DHowett-MSFT** [comment]
@fitojb you're totally right. Thanks. :smile:
