### ISSUE TITLE
Feature Request: 'NON‑BREAKING HYPHEN' (U+2011)

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/cascadia-code#222]
## Description of the new feature/enhancement

I use the non‑breaking hyphen in my commit messages when I intend to enforce where line‑breaks may not occur.

This makes my commit messages show boxes in place of non‑breaking hyphens.

**Comment by schuelermine** [comment]
@aakatz3 Does your PR fix this issue? Shouldn't it be closed?
