### ISSUE TITLE
Documentation Issue: build.py doesn't need to pass sources directory anymore.

### ISSUE THREAD

**Issue by xatier** [microsoft/cascadia-code#224]
The build instruction in this [wiki](https://github.com/microsoft/cascadia-code/wiki/Modifying-Cascadia-Code) is not accurate.

I found that the `build.py` sets the `sources` directory [on its own](https://github.com/microsoft/cascadia-code/blob/master/build.py#L11)

Please consider the following changes in the build instruction wiki. Thank you!

```
python3 build.py sources
```

```
python3 build.py
```

**Comment by xatier** [comment]
Hey @DHowett-MSFT, sorry for bugging you again. Would you please kindly take a glance on this issue for wiki update?

**Comment by DHowett-MSFT** [comment]
Changed. Thanks for waiting. :smile:

**Comment by xatier** [comment]
Thank you!
