### ISSUE TITLE
Using Cascade-code fonts in Ubuntu 19.10 can make GNOME fonts app unresponsive and can even crash entire OS.

### ISSUE THREAD

**Issue by PranavBhattarai** [microsoft/cascadia-code#227]
It's been more than a week I am using Cascadia-code fonts on Ubuntu 19.10. As much as I love it the way it looks, it can turn out as disastrous.

This (crash) has happened to me 3 times. I can't take it anymore. I am gonna use Fire Code from now on.
I hope this gets fixed in future.

Note: This doesn't happen all the time.

For a real new event:
_I was using Pycharm (with Cascade code), also using Firefox(with Cascade code) and watching S2E10 of Mr. Robot. Suddenly, I decide to launch app named, "All fonts" (a GUI app to maintain fonts in GNOME). The entire OS froze. I had to leave the GUI session and type "shutdown" after trying all things to close the app._

Even after a fresh reboot of OS, trying to launch "All fonts" apps doesn't respond. It's dead. No response at all. I can't even uninstall it.

![Screenshot from 2019-12-30 17-14-22](https://user-images.githubusercontent.com/32763112/71580818-6ddc5b00-2b2a-11ea-8ab8-6918902eeb81.png)
 As u can see in the screenshot, the fonts app is not showing any fonts. But I can go to the "About section" to get the screenshot. A whole bunch of fonts went **AWOL**.

ciao, Cascadia-code. Learned a lesson.

Edit: OR, is there something fishy on GNOME's "All fonts" app?

**Comment by mfocko** [comment]
Probably related to these?
https://gitlab.gnome.org/GNOME/gnome-font-viewer/issues/8
https://gitlab.gnome.org/GNOME/gnome-font-viewer/issues/2

**Comment by aaronbell** [comment]
This sounds more like an issue with that specific application than with Cascadia Code (which runs without issue everywhere else). That said, it is always worth a look. 

Unfortunately I do not have a Ubuntu environment to test on, so please provide any logs or other data as to why the application is crashing (especially about why the font might be causing it). Without that there isn’t much I can do.

Cheers.

**Comment by alexmyczko** [comment]
I do have an Ubuntu 20.04 (unreleased) installation, and `gnome-font-viewer` works flawlessly, I have the fonts-cascadia-code package installed.

**Comment by PranavBhattarai** [comment]
@alexmyczko Then closed this issue.

I will try this font when its apt repo.
