### ISSUE TITLE
Instructions for installing Cascadia Code in VS Code are out-of-date

### ISSUE THREAD

**Issue by barik** [microsoft/cascadia-code#228]
Since at least VS Code `1.41.1`, the method for installing Cascadia Code has changed.

In Step (1), it is now `File > Preferences > Settings`. After typing `Font Face` the UI is also different than what is presented in the [existing documentation](https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code):

![image](https://user-images.githubusercontent.com/441243/71772941-2d555680-2f09-11ea-90da-980b664e34f8.png)

**Comment by aaronbell** [comment]
Thanks for the feedback. I've updated the Wiki. Thanks!
