### ISSUE TITLE
Bug Report: Ubuntu: Cascadia Code PL Regular does not work on VSCode stable

### ISSUE THREAD

**Issue by gsbhasin123** [microsoft/cascadia-code#229]
# Environment

```none
Cascadia Code version number: 1911.21
Application (with version) used to display text:
OS platform and version:
Screen resolution (i.e. 90dpi): 


```

# Steps to reproduce

Open VSCode's latest stable version on Ubuntu Budgie 19.10 and set the font to Cascadia Code PL Regular
# Expected behavior
Font changes to Cascadia Code PL Regular

# Actual behavior

It turns to times new roman or similar.
![image](https://user-images.githubusercontent.com/48339289/72125307-f6be7800-331c-11ea-981d-0e3ab5d6c676.png)

![image](https://user-images.githubusercontent.com/48339289/72125316-076eee00-331d-11ea-9689-bcc8e94ffb4c.png)

it works in other apps and it's fork Delugia Nerd Font works...

**Comment by aaronbell** [comment]
Can you try, "Cascadia Code PL" without the "Regular"?

**Comment by gsbhasin123** [comment]
Fixed w; that
