### ISSUE TITLE
Feature Request  Can you please make 4 normal?

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [microsoft/cascadia-code#231]
Hi there, 
Obviously great job with these fonts, visible, better looking..great in any way. There is however one minor issue I'm experiencing with it. The character 4 is the only "open" character and it's highly distracting. Can you please make it normal like all the other characters?
Thanks!

**Comment by DHowett-MSFT** [comment]
This is a duplicate of #66.

**Comment by Vulgaris-Viridis** [comment]
Well that was quick :) Sorry, haven't seen it. Thank you.
