### ISSUE TITLE
Bold and Italic plz

### ISSUE THREAD

**Issue by bao007fei** [microsoft/cascadia-code#233]
# Description of the new feature/enhancement (with images if possible)
Really love this font than any others. Bold and Italic plz.

# Proposed technical implementation details (optional)

**Comment by VladimirMarkelov** [comment]
Duplicated #63 and #128 

Please consider adding 👍 to both/one of themto make them more important instead creating duplicated issues

**Comment by DHowett-MSFT** [comment]
Indeed. Thanks!
