### ISSUE TITLE
Improvement Idea: Dropping '<<' and '>>' ligatures

### ISSUE THREAD

**Issue by InDieTasten** [microsoft/cascadia-code#234]
# Description of the new feature/enhancement (with images if possible)

I'd like to propose dropping the << and >> ligatures. I am going to explain the reasoning for my request in the following.
When coding in C#, oftentimes you run into generic type parameters.
![image](https://user-images.githubusercontent.com/7047377/72908580-fa4af980-3d35-11ea-819e-170ffed7c7eb.png)

In this case, the >> is meant to just represent two closing-angle-brackets, and IS NOT any particular operator, like a bit-shift, or redirecting stream values.
The ligature spacing will become distracting IMHO, because the opening and closing brackets don't match in terms of their perceived occupancy of space, or in short: It looks like a closing angle bracket is missing at first glance.

I find that the ligature also isn't even very noticeable in other scenarios, and not having it wouldn't decrease the beauty of the font IMHO.

# Proposed technical implementation details (optional)

Drop the << and >> ligatures.

An alternative solution would be to nudge the spacing a bit more towards non-ligatures, but since all the ligature does is move the brackets close together, moving them apart would probably just look like no ligature anyways.

---

# Disclaimer

I am fully aware, that this can be highly subjective, and maybe I just need to get used to the ligature. I've never really used ligature fonts before. I really like all the other ligatures though, and this was the first time for me going "huh, I don't know if I want that after all". I keep using it for now though.

<3

**Comment by jwortmann** [comment]
Whether ligatures are applied to << and >> depends on whether your editor recognizes the adjacent angle brackets as a single or two separate tokens. Here is an example in Sublime Text, where the use of ligatures for >> depends on context: 
![screenshot](https://user-images.githubusercontent.com/6579999/72954285-21d2ae00-3d98-11ea-9a45-221d671def4e.png)

Just that your editor doesn't use ligatures correctly in your example shouldn't be an argument to completely drop them in the font.

**Comment by InDieTasten** [comment]
Ooooh, I didn't know that.

**Comment by InDieTasten** [comment]
Since there doesn't seem to be any movement forming for this request, I'm assuming everyone else is fine with it or having an editor preventing ligatures across tokens like sublime.

I've also gotten more familiar with the font the last couple days, so I will close this on my own. I'm still not strictly against the idea of dropping the ligature, if anybody wants to reopen this.
