### ISSUE TITLE
Documentation Issue: Wiki Scoop Install

### ISSUE THREAD

**Issue by sbatten** [microsoft/cascadia-code#235]
I notice in the wiki that `choco` is referenced as an unofficial method of installation. Some people use `scoop` like myself and it could also be included. Here are the commands if you'd like.

Note that even though the bucket is the `nerd-fonts` bucket, it is pulling directly from the releases page of this repository as seen [here](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/Cascadia-Code.json).

# Add the bucket
```
scoop bucket add nerd-fonts
```

# Install the fonts
```
scoop install Cascadia-Code
scoop install Cascadia-Mono
scoop install Cascadia-PL
scoop install Cascadia-MonoPL
```

# Update the fonts
```
scoop update Cascadia-Code
scoop update Cascadia-Mono
scoop update Cascadia-PL
scoop update Cascadia-MonoPL
```

**Comment by aaronbell** [comment]
Added to the [Wiki](https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code)!
Thanks for your contribution :)

**Comment by sbatten** [comment]
Thanks @aaronbell, it looks like the first install and update `Cascadia-Code` got left off in the actual docs

**Comment by aaronbell** [comment]
Derp. Thanks. Fixed!
