### ISSUE TITLE
Provide WOFF for Cascadia Code

### ISSUE THREAD

**Issue by str8edgedave** [microsoft/cascadia-code#236]
Would it be possible to get a webfont (WOFF) for Cascadia Code?

Many technical bloggers use monospaced fonts when including code samples or examples of commands in articles. A webfont would make it easier to include in a blog or webpage.

Also, with the rise of online code editors like Eclipse Che, or online writing tools like StackEdit, being able to use Cascadia Code would be awesome!

**Comment by str8edgedave** [comment]
A couple of people on Twitter suggested a WOFF2 file as well.

**Comment by IamRifki** [comment]
I made a quick and dirty webfont conversion using https://transfonter.org/. You can find it [here](https://github.com/IamRifki/IamRifki.github.io/tree/master/font/cascadia). Although, I still prefer if we get an actual webfont and not just some conversion using an online tool.

**Comment by str8edgedave** [comment]
I did the same using a different online converter (https://www.fontsquirrel.com/tools/webfont-generator). I would like an official one, too.
