### ISSUE TITLE
Cascadia font doesn't render correctly in VS code terminal

### ISSUE THREAD

**Issue by Mackolicious** [microsoft/cascadia-code#244]
# Environment

```none
Cascadia Code version number: 1911.21
Application (with version) used to display text: VS Code 1.42.1
OS platform and version: Windows 10 18363.657
Screen resolution (i.e. 220dpi): 1920 x 1080

```

# Steps to reproduce

Follow the steps to configure powerline for Git and Cascadia code here: https://www.hanselman.com/blog/HowToMakeAPrettyPromptInWindowsTerminalWithPowerlineNerdFontsCascadiaCodeWSLAndOhmyposh.aspx

# Expected behavior

VS code terminal should display glyphs correctly 

# Actual behavior

VS code displays glyphs as shown in this image:
![image](https://user-images.githubusercontent.com/25466120/76199129-330c3880-61e7-11ea-87b4-d81a67d1cd94.png)

**Comment by aaronbell** [comment]
Hi! Can you confirm that you've installed / are using the "Cascadia Code PL" font? The standard version of Cascadia Code does not include Powerline symbols, so that could be your problem.

**Comment by TerensTare** [comment]
Hey there, @aaronbell,
I am having a similar issue with Cascadia Code PL as my default font for the WSL Ubuntu bash. I have set up zsh and powerlevel10k. I am getting symbols that overdraw on each other, like this:

![](https://user-images.githubusercontent.com/37905314/76745706-9f9eae80-6776-11ea-91e6-a1832045b55d.png)

Notice the star and the number 1. It seems that the start occupies two spaces, rather than one.

**Comment by aaronbell** [comment]
@TerensTare in your case the star glyph does not exist in Cascadia Code, so it is being pulled from another font that does not have the same glyph widths as Cascadia Code. As a result, you are seeing the overlap. If the star is a glyph you’d like to see added (along with any others), please open a new bug report with the glyph info! :)

**Comment by TerensTare** [comment]
That seems logic to me. Didn't think in that manner. Thank you @aaronbell. Happy coding!

**Comment by aaronbell** [comment]
I'm assuming that the issue was related to not using the PL variant and am closing the issue for now. Cheers!

**Comment by scollovati** [comment]
> 
> 
> Hi! Can you confirm that you've installed / are using the "Cascadia Code PL" font? The standard version of Cascadia Code does not include Powerline symbols, so that could be your problem.

hi @aaronbell I've the same issue in vscode. In the terminal settings I have "fontFace":  "Cascadia Code PL" and the font is installed system-wide.

**Comment by aaronbell** [comment]
@scollovati, Hm interesting! If you haven't seen it, we have a set of install instructions here: https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code which may help. Here's how my vscode is set:

<img width="565" alt="Screen Shot 2020-12-30 at 11 40 58 AM" src="https://user-images.githubusercontent.com/8460297/103377325-f79f6b00-4a93-11eb-9ad6-97610e278ce7.png">

(note, this is for the editor, but I left the terminal one blank and it defaults to this one).

**Comment by LU-House** [comment]
> @scollovati, Hm interesting! If you haven't seen it, we have a set of install instructions here: https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code which may help. Here's how my vscode is set:
> 
> <img alt="Screen Shot 2020-12-30 at 11 40 58 AM" width="565" src="https://user-images.githubusercontent.com/8460297/103377325-f79f6b00-4a93-11eb-9ad6-97610e278ce7.png">
> 
> (note, this is for the editor, but I left the terminal one blank and it defaults to this one).

**Hello aaronbell**, 
Thank you for showing your vscode settings. It helps me to fix my problem. Thanks!
