### ISSUE TITLE
Ligature rendering issues

### ISSUE THREAD

**Issue by drhaas** [microsoft/cascadia-code#245]
# Environment

```none
Cascadia Code version number: 1911.210
Application (with version) used to display text: Windows Terminal 0.10.651.0
OS platform and version: Win 10
Screen resolution (i.e. 220dpi): 110dpi (2560x1440 on 27")

Any other software?
```

# Steps to reproduce

For me on size 6, 12 and 24 the ligatures fail to render properly (see attached image). Type // or *** on your terminal using the Cascadia Code font and change the font size until the ligatures stop rendering correctly

# Expected behavior

Ligatures will render as expected.

![image](https://user-images.githubusercontent.com/1771672/76243197-2ee71780-61f5-11ea-847e-d552bac7f076.png)

# Actual behavior

Ligatures are not rendering at all or just rendering a tiny dot.

![image](https://user-images.githubusercontent.com/1771672/76241955-11b14980-61f3-11ea-8256-0e9fc7a5502f.png)

**Comment by DHowett-MSFT** [comment]
This is actually microsoft/terminal#4806
