### ISSUE TITLE
Feature request: C++ Spaceship operator (<=>) support

### ISSUE THREAD

**Issue by ryder052** [microsoft/cascadia-code#247]
Please recognize the spaceship operator, currently it's seen as "<=" + ">" which doesn't look good.

**Comment by hez2010** [comment]
![image](https://user-images.githubusercontent.com/14960345/79252258-e685de00-7eb3-11ea-9df1-b5a31a436f7f.png)

<=> is already recognized.

**Comment by DHowett-MSFT** [comment]
![image](https://user-images.githubusercontent.com/14316954/79255250-d1209d80-7e3a-11ea-8a7b-dd4bdd7262fd.png)

yup

Visual Studio has trouble with ligatures involving the `<` and `>` characters. Nothing we can do about that. Sorry.
