### ISSUE TITLE
Any plans for a lighter weight? (Or am I using it wrong?)

### ISSUE THREAD

**Issue by winzig** [microsoft/cascadia-code#25]
Tried switching to CC in VS Code on macOS, from my previous font of SFMono-Regular, by installing the .ttf into Font Book, and putting `'Cascadia Code'` at the beginning of the Font Family box in VS Code. 

To my eyes, the font is a bit heavier than what I'd prefer. It seems as though only one weight was installed, "Regular," is that right? If so, any plans to provide lighter weights to choose from?

**Comment by thisguychris** [comment]
That was my first thought as well, been using Meslo font for a while now. I hope you guys make a thinner version of this, otherwise, it's perfect 👌🏻

**Comment by bterlson** [comment]
It's a bit too bold for me as well. Previously used FiraCode's light/300 weight (with the NF patch, of course 😁).

**Comment by vuongggggg** [comment]
yes, I got the same problem 😢, otherwise the font works very well on Windows Terminal. I really love this font. 😍

**Comment by michael-wilson** [comment]
+1 on weight, i use Source Sans at 100 and 300 in various, this is great but a tad too thick for VSC (for me)

**Comment by ExE-Boss** [comment]
I’m used to the thickness of **Consolas** and [**Input Mono**](https://input.fontbureau.com/). (see also: #41)

**Comment by musm** [comment]
Same. Consolas and Roboto Mono has a great thickness, this new font looks like it's basically bold.

**Comment by vittau** [comment]
Agreed, I wish there was a light weight. Italic would also be nice for themes that support it (usually meant for Operator Mono style fonts).

**Comment by will-stone** [comment]
It doesn't have to be _much_ lighter though. After using it for a day, I no longer have the same feeling as when I first installed it; it does feel quit comfortable now on a retina screen at 14px (24px line height) in VSCode.

**Comment by Marco87Developer** [comment]
I too would like a lighter version! In the same way of Consolas default font un Visual Studio Code.

**Comment by predopredo** [comment]
+1 for the lighter weight!
LOVED this font!

**Comment by Esteban-Rocha** [comment]
+1 I'm finding this font to be quite comfortable, I'm liking it a lot! But It's too bold, tires me petty quickly so I have to go back to `Ligconsolata` or `Fira`.

I think this issue should be one of the top priorities for `Cascadia`

**Comment by predopredo** [comment]
> +1 I'm finding this font to be quite comfortable, I'm liking it a lot! But It's too bold, it tires me petty quickly so I have to go back to `Ligconsolata` or `Fira`.
> 
> I think this issue should be one of the top priorities for `Cascadia`

100% agreed

**Comment by codebymiles** [comment]
Adding more support for a lighter weight variant.

**Comment by GregoryHorvath** [comment]
+1 Somehow it's okay in cmd (thought my éá,etc characters are not working) but in VSCode every character is so chunky.

**Comment by vuongggggg** [comment]
I got the same problem, then I change **Editor: Font Weight** to **400** and it seems better (similar with my terminal).

**Comment by GregoryHorvath** [comment]
> I got the same problem, then I change **Editor: Font Weight** to **400** and it seems better (similar with my terminal).

400 is the default font weight in nearly everything so it shouldn't look any different.

**Comment by pedropablo** [comment]
+1 

It looks chunky on VS2019, and with function names and other stuff with bold it becomes quite hard to read.

![cascadia](https://user-images.githubusercontent.com/5614764/67114106-c2657080-f1a0-11e9-9781-1bbb62066d54.png)

**Comment by winzig** [comment]
Did a little digging and noticed a branch by @cinnamon-msft that adds a roadmap to the bottom of the README file, which indicates they are targeting March 2020 to resolve this. 

https://github.com/microsoft/cascadia-code/blob/cinnamon/add-roadmap/README.md#roadmap

<img width="869" alt="Screen Shot 2019-10-18 at 10 20 02 AM" src="https://user-images.githubusercontent.com/127062/67114520-ef118c00-f190-11e9-9870-799f53d48fdb.png">

**Comment by roqvist** [comment]
Does anyone have any updates about this repo? It seems that work has halted, no new changes for months. The only reference is the old roadmap which suggests new features in March 2020 which is pretty much over now. It would be good with some official info and probably an updated roadmap.

**Comment by zr9** [comment]
You can basically use a custom patch via fontforge, just change a value until you satisfied, not the best but working one.

 `import fontforge

name = 'Cascadia Scaled'

font = fontforge.open('./build/CascadiaCodeTest.ttf')
font.fontname=name
font.familyname=name
font.fullname=name
font.copyright=""
font.selection.all()
font.changeWeight(-50.0)
font.generate('./build/CascadiaCodeScaled.ttf')`

**Comment by aaronbell** [comment]
Hello! Sorry for the radio silence. I've been on paternity leave for several months. 😄 

I understand that the Microsoft team will be updating the roadmap here soon, but just wanted to let you know that work is picking back up and the heavy weight of Cascadia Code is top of the list to resolve.

**Comment by kameshkotwani** [comment]
Any updates on the light version of this beautiful font? Any release date yet?

**Comment by musm** [comment]
> Any updates on the light version of this beautiful font? Any release date yet?

Seriously ? Did you read literally the direct post above yours.

**Comment by cinnamon-msft** [comment]
I will update the roadmap soon, but it looks like the font weights will arrive in the June - August 2020 timeframe. 😊

**Comment by kameshkotwani** [comment]
@cinnamon-msft Thank you :)

**Comment by estebandee** [comment]
Just installed this alongside the new Terminal. Waiting for lighter weights since it's pretty chunky right now. Good work on the font!

**Comment by nfantone** [comment]
Still an issue for me entering 2022. Font looks way too bold on my eyes. Even on lower `"editor.fontWeight"` values.

![image](https://user-images.githubusercontent.com/476069/144417212-ccda2936-d948-4b9e-a87d-1526a00b325f.png)

>  it looks like the font weights will arrive in the June - August 2020 timeframe.

@cinnamon-msft Is this still relevant?

**Comment by aaronbell** [comment]
What you’re seeing in VS Code is a [known issue](https://github.com/microsoft/vscode/issues/128097).

For you, I would suggest using the static versions of Cascadia wherein you can directly select the SemiLight weight.

**Comment by nfantone** [comment]
Thanks for the clarification!

**Comment by huksley** [comment]
In VS Code, try putting `"workbench.fontAliasing": "antialiased"` in settings.json, it will make font thinner.
