### ISSUE TITLE
Documentation Issue: Coding ligature coverage page has errors

### ISSUE THREAD

**Issue by schuelermine** [microsoft/cascadia-code#256]
It doesn't include `|||>` and writes `~@` as `~at`

**Comment by DHowett-MSFT** [comment]
I mean, to be fair, `|||>` is two ligatures (`||` and `|>`)
![image](https://user-images.githubusercontent.com/14316954/80632610-5c3d8e00-8a0c-11ea-91cf-01596f006b22.png)

**Comment by schuelermine** [comment]
> 
> 
> I mean, to be fair, `|||>` is two ligatures (`||` and `|>`)
> ![image](https://user-images.githubusercontent.com/14316954/80632610-5c3d8e00-8a0c-11ea-91cf-01596f006b22.png)

It's not. See this:
![TJup9pyKxg](https://user-images.githubusercontent.com/48802534/80632900-2faf6380-8a58-11ea-9422-7ab221e0e9d0.gif)

**Comment by DHowett-MSFT** [comment]
Fair enough.

**Comment by aaronbell** [comment]
fixed

**Comment by schuelermine** [comment]
Why are `<|||` and `|||>` supported, actually? Is there some language that uses them?

**Comment by aaronbell** [comment]
You can use them to pass three parameters in a pipe operator in F#.

**Comment by schuelermine** [comment]
Ok, thanks.
