### ISSUE TITLE
Support the glyphs needed for oh-my-posh

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/cascadia-code#26]
[oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh) is a popular and nice prompt for PowerShell, but it requires a font that supports glyphs that don't seem to be present in Cascadia Code right now. Would be great if those could be added.

**Comment by bterlson** [comment]
I believe this is a duplicate of #10.

**Comment by davidanthoff** [comment]
Yes, that is a duplicate.
