### ISSUE TITLE
Add support for U+23CE

### ISSUE THREAD

**Issue by schuelermine** [microsoft/cascadia-code#262]
# Description of the new feature

Add support for ⏎ (U+23CE "RETURN SYMBOL")

Currently it looks like this: 
![cascadia-return-symbol-missing](https://user-images.githubusercontent.com/48802534/81620796-ffb77700-93ec-11ea-9ed4-be50076268e7.png)

## Why?

`fish` uses ⏎ to indicate line breaks added to preserve prompt structure

**Comment by ExE-Boss** [comment]
**See also:** <https://github.com/microsoft/cascadia-code/issues/264>
