### ISSUE TITLE
Feature Request: Code points for control/hidden chars (e.g. U+21B2, U+2771, U+2770, U+2423)

### ISSUE THREAD

**Issue by abravalheri** [microsoft/cascadia-code#264]
Hi guys, thank you very much for Cascadia, it is really good.

The usage of codepoints (e.g. U+21B2, U+2771, U+2770, U+2423) to represent hidden/control chars is [common pratice in text editors](https://www.reddit.com/r/vim/comments/4hoa6e/what_do_you_use_for_your_listchars/)  to provide extra information about the text and disambiguation. Particularly, I have the following in my vimrc:
```vim
set listchars=tab:▶\ ,trail:•,extends:❱,precedes:❰,nbsp:␣,eol:↲
```
This is how it is rendered right now (FVim front end that uses [Avalonia](http://avaloniaui.net) and F#):
![image](https://user-images.githubusercontent.com/320755/81671776-3fa84980-9441-11ea-86fc-e23c0b3ad972.png)
This is more or less how it could be
![image](https://user-images.githubusercontent.com/320755/81671719-30290080-9441-11ea-8589-bfc4efa6d8dd.png)

I was wondering if we could have something like these codepoints.

**Comment by LuanVSO** [comment]
u2771 is also used as the default prompt char for some shell themes like [powerlevel10k](https://github.com/romkatv/powerlevel10k) and [pure](https://github.com/sindresorhus/pure)
