### ISSUE TITLE
Please upload the prebuilt binaries for 2004.30 release

### ISSUE THREAD

**Issue by ismail** [microsoft/cascadia-code#265]
Currently, https://github.com/microsoft/cascadia-code/releases/tag/v2004.30 contains only the source code which is very cool but it'd be awesome if you can upload a binary archive containing the TTF/OTF binaries at least.

Thanks!

**Comment by DHowett-MSFT** [comment]
Huh?

![2C6EFD75-4F85-4754-981A-EFB3C7F477E9](https://user-images.githubusercontent.com/14316954/81770922-81171400-9496-11ea-8b20-0a4b1caf0b95.jpeg)

That’s definitely got the assets in it.

**Comment by ismail** [comment]
I was downloading v2004.30.tar.gz instead of the zip, so thanks for pointing that out!
