### ISSUE TITLE
Feature Request: Grave and Acute tones marks accessibility improvement 

### ISSUE THREAD

**Issue by AlexYash** [microsoft/cascadia-code#268]
# Description of the new feature/enhancement (with images if possible)

First, thank you very much for fixing that issue with incorrect combining diacritic marks placement. Everything works correctly now, but I noticed that combining Grave (#0340) and Acute (#0341) tones' marks are hardly distinguished from a dot over a standard small "i" when font size is not large (<=12). It would be great to modify these marks by increasing their slopes and making upper parts of these symbols a bit thicker like in this picture.
![accent diactrics](https://user-images.githubusercontent.com/45464862/81928449-f0534c00-95ed-11ea-924a-d17a47e67a47.png)
There are two variants - upper one using Cascadia Code (10pt) and the lower one using Calibri (11pt), image is scaled to make it easier to notice the difference.

# Proposed technical implementation details (optional)

Increase the slope of these tone marks and make them thicker in the upper parts (see an example with accented small "i" in the end of the first row - the first small "i" with Grave is a current glyph, the second glyph is a proposed option.)

**Comment by aaronbell** [comment]
Thanks for the feedback. My fear with increasing the slope angle is that it will make them blurrier and lighter at smaller sizes, but I'll definitely see if there's some way I can give them a little more presence.

**Comment by AlexYash** [comment]
> ...it will make them blurrier and lighter at smaller sizes.
Actually the main issue is at small sizes and since my vision is far from 20/20 that's the area where I can reliably say if it works or not. Calibri is even thinner than Cascadia but I can confidently distinguish normal "i" and accented "i". I don't really see those elements as they are both blurred for me at 10-12pt sizes but I can recognize them because accent marks are lighter than the dot on top of "i" and have noticeable slope. While in Cascadia those accent marks are more vertical now and as bold as the dot, so when they are blurred a bit, they looks the same.
