### ISSUE TITLE
2004.30 fonts no longer appear properly in Windows console windows

### ISSUE THREAD

**Issue by DewVinci** [microsoft/cascadia-code#270]
# Environment

```none
Cascadia Code version number: 2004.30
Application (with version) used to display text: Windows Console (conhost.exe)
OS platform and version: Win10 19041
Screen resolution (i.e. 220dpi): 140ppi
```

# Steps to reproduce

1. Open a conhost and set font to 14pt Cascadia Mono PL. Notice appearance.
2. Upgrade from 1911.21 to 2004.30
3. Open a conhost with the same settings as before. Notice appearance.

The characters in the 14 pt found are now much smaller than they used to be, and much smaller than similar fixed-width fonts at 14 pt (e.g. Consolas, Lucida Console, Bitstream Vera Sans Mono).

# Expected behavior

Font in conhost.exe appear roughly the same as they used to. 14 point font is sized similarly to other fixed-width fonts.

Here is what 1911.21 looks like:
![1911 21](https://user-images.githubusercontent.com/322691/81980506-9baad380-95e3-11ea-9328-ef7bdd9e2135.jpg)

# Actual behavior

Characters have shrunk substantially and padding has increased.

Here is what 2004.30 looks like:
![2004 30](https://user-images.githubusercontent.com/322691/81980597-c301a080-95e3-11ea-9363-5edf8af632f0.png)

**Comment by aaronbell** [comment]
Hi. This is related to bug #266. The font metrics were modified in the recent release of Cascadia Code to enable more consistent rendering across environments, and to ensure proper display of Vietnamese text. I have just submitted a PR that will help resolve this to an extent (#271) and you should see a modest increase in glyph size as a result.

Unfortunately, text will be smaller in applications like PowerShell which use older typesetting APIs. May I suggest trying the new Windows Terminal? It has better typesetting capabilities than PowerShell and you will be able to see text at the size you expect it to.

**Comment by aaronbell** [comment]
If you've installed Cascadia Code via the github release, please try out the [latest version](https://github.com/microsoft/cascadia-code/releases/tag/v2005.15), which should be improved for PowerShell environments. If you get the font via Windows Terminal, the next release will include the updated font.

**Comment by DewVinci** [comment]
Certainly improved, but still 10% narrower than 1911.21 and similar 14pt fonts. Thanks for the update.

![2005 15_14pt](https://user-images.githubusercontent.com/322691/82099514-645c2580-96bc-11ea-82c8-1e1cfdee9935.jpg)
