### ISSUE TITLE
Incorporate new ligatures in Fira Code v2, v3, v4 and v5

### ISSUE THREAD

**Issue by wopian** [microsoft/cascadia-code#276]
Fira Code v3 was released last month and v4 this week. v2 & v3 includes a large number of new coding ligatures (from the looks of things the ligatures from Fira Code seem to be before v2).

Releases show the added ligatures and what they look like:
https://github.com/tonsky/FiraCode/releases/tag/4
https://github.com/tonsky/FiraCode/releases/tag/3
https://github.com/tonsky/FiraCode/releases/tag/2

v4 features infinite arrow combinations instead of tens of individual ligatures:

![](https://github.com/tonsky/FiraCode/raw/master/extras/arrows.png)

**Comment by aaronbell** [comment]
Thanks! We'll definitely look into these.

**Comment by wopian** [comment]
v5 has been released with a few more ligatures

https://github.com/tonsky/FiraCode/releases/tag/5

**Comment by subnut** [comment]
@aaronbell Any ETA? Anybody working on this yet?

**Comment by aaronbell** [comment]
Hi. No, we haven't started on this yet. Sorry! We're figuring out next steps for the font :).

**Comment by wopian** [comment]
Thank you :tada:
