### ISSUE TITLE
Cascadia Mono 16px height - frame drawing lines not connecting

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/cascadia-code#278]
# Environment

```none
Cascadia Code version number: 2005.15
Application (with version) used to display text: Native terminal
OS platform and version: Windows 7, Windows 10 1909
Screen resolution (i.e. 220dpi): DPI is a pixel density, NOT resolution.
20'' 1680×1050 LCD panel

Any other software?
```

# Steps to reproduce

Install font, register as candidate for terminal fonts, choose it in console properties at 16px height.

# Expected behavior

![image](https://user-images.githubusercontent.com/6532485/82487056-7daf0880-9ae6-11ea-8e0f-db5efa50fc93.png)

# Actual behavior

Veritcal lines are not connecting.
![image](https://user-images.githubusercontent.com/6532485/82487029-71c34680-9ae6-11ea-85ee-46a62e96dcc9.png)

**Comment by DHowett** [comment]
> Screen resolution (i.e. 220dpi): DPI is a pixel density, NOT resolution.

Correcting this without answering the question you obviously realized we were asking is needless pedantry. Fortunately, since you're apparently on Windows 7, I know that you're not using display scaling because it was so bad back then.

**Comment by AnrDaemon** [comment]
I answered it. 
> 20'' 1680×1050 LCD panel

**Comment by mdtauk** [comment]
> I answered it.
> 
> > 20'' 1680×1050 LCD panel
> 
> Though, DPI scaling for native terminal ain't any better in Win10.

This is part of what Windows Terminal is trying to fix, by moving from the ageing GDI rendering methods to the new DirectWrite and WinUI frameworks, which know how to handle DPI scaling

**Comment by aaronbell** [comment]
hum. I thought this had been resolved in one of the recent updates. I'll take another look at them.

**Comment by AnrDaemon** [comment]
And just to answer the "Windows 7" remark... in Windows 10 it is, actually, even worse.

16px
![image](https://user-images.githubusercontent.com/6532485/82491137-eac59c80-9aec-11ea-934d-7409a19c90e6.png)

18px
![image](https://user-images.githubusercontent.com/6532485/82491179-fca73f80-9aec-11ea-875f-25c1696293c7.png)

20px
![image](https://user-images.githubusercontent.com/6532485/82491220-092b9800-9aed-11ea-88ab-58468dbe607b.png)

I have a feeling that Win7 rendering 18px/20px fine by pure accident (i.e. rounding error). 24px is not connecting on Win7 as well.

> This is part of what Windows Terminal is trying to fix

Terminal is useless without fonts. And there's no single TrueType font that is even close to VGA terminal font. Though Cascadia is trying hard to be one, it still bears all issues of other would-be-terminal fonts. One common issue I described in #279 .

**Comment by AnrDaemon** [comment]
Looks ok now on Win7. Thanks!
