### ISSUE TITLE
Cascadia Mono: Not enough spacing on the right side

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/cascadia-code#279]
Cascadia Mono is not really usable as terminal font. The main issue is that there's not enough spacing on the right side of the glyph, which is extremely apparent in native console and cause letters look "glued" to the decoration elements to the right of them.

# Environment

```none
Cascadia Code version number: 2005.15
Application (with version) used to display text: Native terminal
OS platform and version: Win 7, Win 10 1909
Screen resolution: 1680×1050 no scaling
```

# Steps to reproduce

Install Cascadia Mono PL as a terminal font and choose 18px size for a window.
18px is chosen as it exaggerates the issue. It remains true for other font sizes.

# Expected behavior

Well, I expect it to look better. Way better.

# Actual behavior

(Click for full size)
![image](https://user-images.githubusercontent.com/6532485/82492333-b2bf5900-9aee-11ea-82ce-da9ca999480b.png)

# Historically-technical sidestep

VGA 80x25 text mode is 720×400 pixels with (unsurprisingly) 9x16 character glyph size. However, VGA raster font glyph is 8×16 pixels in size. The ninth vertical line is created by duplicating the eighth vertical of the font glyph by the terminal.

This little known fact leads to even less known consequence: no letter glyph span beyond 7'th vertical. Failing that, the added 9'th vertical will make letter or number look like ~shit~ it grew a belly. Or worse, glue to the next glyph, which may not be a letter at all.

For the same reason, letters best not to glue to the left side either.

When you are designing GUI font to be used in GUI terminal, you have to keep this problem in mind as well. However, with GUI font you are not constrained by artificial 9'th vertical, thus the choice of tricks available to you is that much wider.

My `Hellfont Cyr` raster font is a replica of an old 8×16 VGA font realigned for better visual perception in GUI. The letters are mostly 7px wide, more or less exactly centered on the 9px glyph. Note the space on the right side. It's merely a single pixel, but how much it improves the font perception? Same can be seen on the left side, where letters are close to the edge of the terminal (in this case, but it could be some full-width decoration glyph just as well).

![image](https://user-images.githubusercontent.com/6532485/82497182-83ace580-9af6-11ea-8cf5-227eea015fc5.png)

Yes, it is a 9x16 font, I've had no time to redesign it to 9x18 or so. It would have looked a tad better probably, but I got used to its original look.

**Comment by aaronbell** [comment]
Cascadia Code is not designed for your specific use case, I'm afraid.
I do not intend to make the characters narrower than they already are.

**Comment by AnrDaemon** [comment]
Actually, they need to be made wider, not narrower.

**Comment by AnrDaemon** [comment]
Or may be not wider, but character glyphs needs to be realigned.
