### ISSUE TITLE
Bug Report -> in VS 2015

### ISSUE THREAD

**Issue by HolyChen** [microsoft/cascadia-code#28]
In this font, ->should be replaced with a right arrow. But in visual studio 2015, it's not.
![image](https://user-images.githubusercontent.com/8280605/65202825-43a3e780-dabd-11e9-92e8-85a4f40b0b00.png)

**Comment by marklam** [comment]
Probably this bug: https://github.com/dotnet/wpf/issues/109

**Comment by Fell** [comment]
It's the same in VS2017 and VS2019, I guess now it's time to fix that, Microsoft.

**Comment by cinnamon-msft** [comment]
This is a rendering issue with Visual Studio. I recommend following the bug @marklam mentioned.
