### ISSUE TITLE
Rendering for Unicode Caret

### ISSUE THREAD

**Issue by aviks** [microsoft/cascadia-code#282]
# Environment

```none
wt 0.11.1333
OS platform and version: Windows 10 1903
```

# Steps to reproduce

Paste this string onto a wsl bash prompt, or a Julia REPL (win/linux) inside terminal: `α̂=1`

The four characters in this string are
```
U+03B1 : GREEK SMALL LETTER ALPHA
U+0302 : COMBINING CIRCUMFLEX ACCENT {hat}
U+003D : EQUALS SIGN
U+0031 : DIGIT ONE
```

# Expected behavior

With Fira Code, size 12

![image](https://user-images.githubusercontent.com/378918/82731478-2c2d9600-9cff-11ea-8b6f-ca9a4bf5b9dd.png)

# Actual behavior

With Cascadia Mono, 12

![image](https://user-images.githubusercontent.com/378918/82731506-554e2680-9cff-11ea-8a5f-8743299d2bd0.png)

With Cascadia, 12
![image](https://user-images.githubusercontent.com/378918/82731519-6eef6e00-9cff-11ea-959c-1dbe1bb16ebe.png)

_Note_: If testing on powershell prompt, the display is incorrect even with Fira Code, but look at the rendering of the PS error message, where the display is correct with Fira, but incorrect with Cascadia

**Comment by aviks** [comment]
I should also mention, that while FiraCode displays the caret in with its horizontal positon correctly, the rendering for full height characters seems problematic. Not sure if that issue is with the font or the renderer. 

![image](https://user-images.githubusercontent.com/378918/82732960-854df780-9d08-11ea-80c2-98df4ffef525.png)

With Cascadia, the incorrect horizontal postion makes the vertical position irrelevant

![image](https://user-images.githubusercontent.com/378918/82732997-ad3d5b00-9d08-11ea-8170-83ae6a0a75df.png)

**Comment by aaronbell** [comment]
Thanks! Cascadia Code is currently set up to support monotonic Greek, but I agree that this should be totally workable. It should be a fairly straightforward fix.

And with Fira Code, I anticipate that the issue is two fold. One is that the font metrics appear set close to the letter form heights. That’s handy in that it makes letters larger. However, many rasterizers clip letterforms at those font metric boundaries, so the diacritic mark is being sliced off. So if the rasterizer didn’t do the clipping or if the font metrics were increased, it’d look fine.

**Comment by aaronbell** [comment]
Out of interest, what applications are you using the combining mark with Greek? Do you want to use the combining mark with all Greek characters, or just specific ones?

**Comment by aviks** [comment]
I'm using this in the Julia REPL on the terminal, or in Julia code in a VSCode editor.  

Julia allows using unicode characters as variable names, and since both the greeks as well has the _hat_ operator are very common in mathematical notation, it is useful to write _hatted_ greeks as variables. As to which, since they are just variable names, they are limited by the imagination of the author/developer, so ... all.. I guess? 

HTH

**Comment by AlexYash** [comment]
> Julia allows using unicode characters as variable names, and since both the greeks as well has the _hat_ operator are very common in mathematical notation, it is useful to write _hatted_ greeks as variables. As to which, since they are just variable names, they are limited by the imagination of the author/developer, so ... all.. I guess?

@aviks , beware. You're opening Pandora's box - https://en.wikibooks.org/wiki/LaTeX/Special_Characters#Math_mode :)
