### ISSUE TITLE
Use better `==` symbol

### ISSUE THREAD

**Issue by aminya** [microsoft/cascadia-code#284]
It is hard to distinguish between these two:
```
1==2
1=2
```

![image](https://user-images.githubusercontent.com/16418197/83316864-23046380-a1ee-11ea-82e8-d41c2c60e7ef.png)

Borg-sans-mono has a better symbol for this:
https://github.com/marnen/borg-sans-mono
![image](https://user-images.githubusercontent.com/16418197/83317230-bd65a680-a1f0-11ea-81ef-88965eb34a6d.png)

**Comment by aaronbell** [comment]
Hm. To be honest, I think that they're sufficiently differentiated simply by their lengths, and adding a break in the middle kind of defeats the purpose of even having a ligature. I do appreciate your frustration though, and am interested to hear if others share it. For the time being I'll leave this open to see if others chime in, but do not have any intent to change it currently. 

Thanks!

**Comment by aminya** [comment]
When you look at this in a big code base, in which necessarily these are not written near each other it is very hard to determine between the two. The purpose of a font should be to enhance the experience of the user, but now the user goes into a guessing game!

I want to say that this does not question the ligature usage at all. We can choose a single ligature that has a custom space in between the two `=`, which is not possible normally.

Jetbrains Mono also has something similar for `_`. Something that is always hard using normal fonts
![image](https://user-images.githubusercontent.com/16418197/83464190-b4b1e200-a435-11ea-9c44-2654d170b1ae.png)

**Comment by aggserp4** [comment]
I agree with this. I often have trouble telling a single equals sign from a double one, especially if there isn't a point of reference.
> adding a break in the middle kind of defeats the purpose of even having a ligature.

I disagree. The point of ligatures is to make code easier & quicker to read. If we have to double check equals signs to make sure that there's two of them and not one, that's not very productive and it goes against the point of having them! They also have the function of making text look prettier, but that should only be a secondary function.

**Comment by aminya** [comment]
Thanks for fixing this!

**Comment by weitzhandler** [comment]
I actually like the old one better.

**Comment by Sherlock-Holo** [comment]
the old is better

actually if someone enabled ligatures, he won't want to see there is a space between two =, otherwise, why enable the ligatures?

if someone doesn't like there's any space between two =, why doesn't he disable ligatures?

**Comment by aminya** [comment]
`==` is just one ligature among 100s that Cascadia provides. 

You can patch this symbol if you hate this extra space.
https://github.com/gaplo917/Ligatured-Hack

**Comment by Sherlock-Holo** [comment]
for people who want no space between two `=`, after updating to the latest version, the `==` becomes unaccepted

**Comment by weitzhandler** [comment]
I'm also gonna share my sentiment here. When someone enables ligatures they want a wide assignment sign. Hence `==` should be displayed as a single wide character.
