### ISSUE TITLE
Cascadia Mono shouldn't use contextual alternate for x

### ISSUE THREAD

**Issue by Kwpolska** [microsoft/cascadia-code#285]
I was working with a third-party service that provided me with a URL of this form:

    https://example.com/1234x5678.png   (1 2 3 4 x 5 6 7 8)

I saw this URL in Windows Terminal, which defaults to Cascadia Mono. The way this URL displayed was this:

    https://example.com/1234×5678.png

This made me think the third-party service is using × (U+00D7 MULTIPLICATION SIGN) instead of the usual letter x (U+0078 LATIN SMALL LETTER X). This confusion is not something I want from a terminal. In my opinion, the contextual alternate should only be in Cascadia Code.

Here’s a sample (in Word, with ligatures and contextual alternates enabled):

![image](https://user-images.githubusercontent.com/327323/83335503-8e613a80-a2ad-11ea-8f60-6498354381ec.png)

And in Windows Terminal:

![image](https://user-images.githubusercontent.com/327323/83335531-c8cad780-a2ad-11ea-867c-11dbd2111a40.png)

**Comment by DHowett** [comment]
Good catch. Thanks!

**Comment by aaronbell** [comment]
Fair enough :). I don't think, though, that this is a "Code" vs "Mono" thing, though, as the same situation could happen in either case. I'll disable the code entirely for now until we figure out a better way to implement it.

**Comment by Kwpolska** [comment]
Yeah, perhaps getting rid of this feature would be better for both fonts. (Then again, I don’t ever use ligature fonts for programming, precisely because I don’t like being tricked by my fonts, so I can’t answer for Code.)
