### ISSUE TITLE
/> tag doesn't look balanced

### ISSUE THREAD

**Issue by ratishphilip** [microsoft/cascadia-code#29]
As of now the */>* tag looks like this

![image](https://user-images.githubusercontent.com/7021835/65202632-60013f00-da3f-11e9-9929-e0d5dc6368ff.png)

Same issue with Fira Code Retina font.

It looks unbalanced. Can you please fix this?

**Comment by mgasparel** [comment]
Same goes for closing tags, ie: </

This is even worse in italics

**Comment by ratishphilip** [comment]
I missed that. 😊 Thanks @mgasparel.
