### ISSUE TITLE
Add ligature for /\ and \/

### ISSUE THREAD

**Issue by xmha97** [microsoft/cascadia-code#290]
Hello,
Please add ligature for `/\` and `\/`
Like "Fira Code" font

**Comment by mratsim** [comment]
It's very useful for formal verification languages like TLA.

**Comment by xmha97** [comment]
> 
> 
> It's very useful for formal verification languages like TLA.

Now "Fira Code" font supports this ligature.

**Comment by johannesrave** [comment]
👍🏻 :)
