### ISSUE TITLE
PL Glyphs are missing after reboot (Windows Bug?)

### ISSUE THREAD

**Issue by clericc** [microsoft/cascadia-code#293]
# Environment

```none
Cascadia Code version number: 2005.15
Application (with version) used to display text: Windows Terminal 1.0.1402.0, Powershell Core 7.0.2
OS platform and version: Windows 10 build 19043.329
Screen resolution (i.e. 220dpi): WQHD 100% scale

Any other software?
```

# Steps to reproduce

- Install TTF fonts, especially Code PL
- works fine in mentioned Terminals
- reboot PC
- reopen Terminals

- see Glyphs gone
![image](https://user-images.githubusercontent.com/851823/84592997-d2c20e00-ae49-11ea-9fce-fb568a219299.png)

- install TTF Code PL again
![image](https://user-images.githubusercontent.com/851823/84593009-e53c4780-ae49-11ea-869e-146c3fd362bf.png)

- reopen Terminal
- Glyhps are back (top: Before reinstall; bottom: After reinstall)
![image](https://user-images.githubusercontent.com/851823/84593019-f5542700-ae49-11ea-98b9-cc2bda28931d.png)

# Expected behavior
Glyphs stay

# Actual behavior
Glyphs do not survive reboot

**Comment by tritium21** [comment]
What did you see?!  How did you resolve this?

**Comment by jwefers** [comment]
What i did was instead of drag drop them into fonts folder or the windows 10 settings panel, i right-click and "Install for all users", admin permissions required.

No idea about why it happened as user.

Also, when opening this bug, i thought TTF better than OTF, then learning about preferring OTF
