### ISSUE TITLE
Add support for 0x279C "➜" character

### ISSUE THREAD

**Issue by jethas-bennettjones** [microsoft/cascadia-code#296]
# Environment

```none
Cascadia Code version number: 2005.15
Application (with version) used to display text: Standard Windows Terminal (Windows version 18363.900)
OS platform and version: Windows 10 18363.900
Screen resolution (i.e. 220dpi): 🤷🏽‍♂️

Any other software?
posh-git
oh-my-posh
```

# Steps to reproduce
Install PowerShell 7
Install posh-git and oh-my-posh as modules (Using Install-Module with CurrentUser scope)
Install Meslo LG M Regular Nerd Font Complete and Complete Mono from here: https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0
Set the Font in Properties to Cascadia Mono PL
Set the Oh My Posh theme to Zash (Set-Theme Zash)
Note that the arrow character is shown as a block (i.e. a missing) character.
Switch the Font in Properties to the Meslo font previously installed.
Note that the arrow character is rendered correctly.

# Expected behaviour
Cascadia Code should include the arrow character used by this font.

# Actual behaviour
The arrow character is shown as a block character instead.
![image](https://user-images.githubusercontent.com/62298251/85140227-35c4f380-b202-11ea-84ef-5b6660083785.png)

**Comment by lnfel** [comment]
mine only shows "->"

**Comment by jethas-bennettjones** [comment]
As of today, it looks like this has been resolved.
