### ISSUE TITLE
PL Font must be reinstalled after restart on Windows 10 version 2004

### ISSUE THREAD

**Issue by Jonathing** [microsoft/cascadia-code#297]
# Environment

```none
Cascadia Code version number: 2005.15
Application (with version) used to display text:
- Windows Terminal 1.0.1401.0
- Visual Studio Code 1.46.0
OS platform and version: Windows 10 Pro Version 2004 (OS Build 19041.329)
Screen resolution (i.e. 220dpi): 1080p with 125% dpi scaling

Any other software?
- I am running an HP Pavilion Gaming Laptop 15t if that helps
```

# Steps to reproduce

1. Make sure your PC is running Windows 10 version 2004 (May 2020 Update)
2. Install Cascadia Code PL
3. Restart your PC
4. Launch Windows Terminal and/or Visual Studio Code (Terminal) with their font selected as Cascadia Code PL

# Expected behavior

The font should behave as normal with no missing characters.

# Actual behavior

The font is missing important powerline characters. This can only be worked around by reinstalling the font.  
In VS Code's Terminal, the font just won't load at all and load something else instead.

## Windows Terminal Before Font Reinstall
![https://i.imgur.com/Izv8r7H.png](https://i.imgur.com/Izv8r7H.png)

## Windows Terminal After Font Reinstall
![https://i.imgur.com/qI5VKCa.png](https://i.imgur.com/qI5VKCa.png)

## VS Code Terminal Before Font Reinstall
![https://i.imgur.com/CbIlMid.png](https://i.imgur.com/CbIlMid.png)

## VS Code Terminal After Font Reinstall
![https://i.imgur.com/pmD9tzm.png](https://i.imgur.com/pmD9tzm.png)

**Comment by DHowett** [comment]
Can you try to “install for all users” instead?

**Comment by Jonathing** [comment]
@DHowett what do you mean by that? The font or the programs I use?

**Comment by DHowett** [comment]
Sorry, the font. That option should be available if you right-click it in File Explorer.

**Comment by Jonathing** [comment]
Ok, I will try now and post my results.

**Comment by Jonathing** [comment]
Ok, I just tried it and it does work. Thanks for your response!

**Comment by aaronbell** [comment]
Sounds like this has been sorted out :). Closing!
