### ISSUE TITLE
Feature Request: More programming ligatures

### ISSUE THREAD

**Issue by weitzhandler** [microsoft/cascadia-code#299]
# Please implement additional common ligatures

Please add character combinations (ligatures) for common C++ / C# / Dart / Python programming or console combinations, such as:

- `->` (e.g. `md->width`)
- `=>` (e.g. `IsEmpty(s) => s == string.Empty`)
- `--` (e.g. `git push --force`)
- `?.`, `!.`, `??` (e.g. `this.Context?.Name`)
- `//` (e.g. `x // y` - Python floor division)

**Comment by DHowett** [comment]
Cascadia Code already supports _every single one of these_ except maybe `!.`

![image](https://user-images.githubusercontent.com/189190/85647200-c4969d80-b652-11ea-97f2-69db41c8fc3c.png)

**Comment by DHowett** [comment]
(It may be non-obvious in the `--` and `//` cases, but the glyphs move closer together when they're next to eachother.)

**Comment by weitzhandler** [comment]
I must have set up my environment the wrong way.
Thank you!

**Comment by weitzhandler** [comment]
Yup. I set it up as "Cascadia", "Cascadia Code" does the job!

**Comment by DHowett** [comment]
I'm glad to hear that! :smile:
