### ISSUE TITLE
The letter "k" is too curvy

### ISSUE THREAD

**Issue by ratishphilip** [microsoft/cascadia-code#31]
In my opinion, it's better to use straight lines for the lowercase letter "k"

![image](https://user-images.githubusercontent.com/7021835/65203603-50362a80-da40-11e9-90d1-b852a34be1f3.png)

**Comment by mdtauk** [comment]
I disagree, this typeface needs it's character preserved.

Feel free to create a stylistic alternative however if opinions are mixed

**Comment by cerebrate** [comment]
I, too, prefer the curvy one.

**Comment by polarathene** [comment]
If you look at other characters, there seems to be quite a few that mix in a curve or feel a bit truncated(like "c"), while other characters are quite compressed/squished feeling. 

I think it's all part of the typeface style(not one that I'm particularly fond of), so making the glyph lose the curve would detract from what this typeface is going for style wise?

**Comment by cinnamon-msft** [comment]
We find the "k" to be very characteristic of the font and we would like to keep it. You're welcome to fork the repo and create your own version though!
