### ISSUE TITLE
Patching with Nerd Fonts patcher produces segmentation fault

### ISSUE THREAD

**Issue by BladeMF** [microsoft/cascadia-code#313]
I appologise in advance - I was not sure where to post this, but it looks to me that I will get more attention to it here than in Nerd Fonts. 

When I try to patch the latest version of the font I get segmentation fault (see screenshot). When I patched the 2005 version it was patched successfuly so I figured you might guess why is this happening. The reason I patch it is because I want to use it with Powerlevel 10 and oh-my-zsh.

If this is indeed not a bug, please change the type.

# Environment

```none
Cascadia Code version number: 2007.01
Application (with version) used to display text: n/a
OS platform and version: Ubuntu 18.04.1 LTS on WSL2, Microsoft Windows 2004 OS Build 19041.329
Screen resolution (i.e. 220dpi): 1920x1080, 100% scaling
```

# Steps to reproduce

execute `./font-patcher CascadiaCode.ttf` on WSL Ubuntu

# Expected behavior

Sucessful patch.

# Actual behavior

![image](https://user-images.githubusercontent.com/12109622/86222548-137e8e80-bb8f-11ea-8e84-74c43b8bca00.png)

**Comment by aaronbell** [comment]
The new version of Cascadia Code is built as a variable font—which is to say that it has the full weight range contained within the single font file. 

From your screenshot, Font Forge does not understand at least some aspects of Variable font technology (for example, the HVAR and STAT table), so it would not surprise me if it encountered other things it didn't understand and errored out. 

Unfortunately, this is something that the Nerd Font patcher or Font Forge is going to need to sort out.
