### ISSUE TITLE
In Visual Studio 2019, I see 2 items for Cascadia Code font (regular)

### ISSUE THREAD

**Issue by pasqualedante** [microsoft/cascadia-code#314]
# Windows 10 Home Edition

Cascadia Code version number:2007.001
Application (with version) used to display text: Visual Studio 2019
OS platform and version: Windows 10 Home Edition 2004 build 19041.329
Screen resolution (i.e. 220dpi):  1920x1080

# Steps to reproduce

Open Visual Studio setting to change font to Cascadia Code: I see 2 Cascadia Code items and cannot distinguish the last intalled;
# Expected behavior

Open Visual Studio setting to change font to Cascadia Code: I see only one Cascadia Code item (the last installed)

# Actual behavior

Maybe this issue is related to Windows Terminal (preview) that I have installed? Maybe the Terminal is packed with a Cascadia Code\Cascadia Mono font that I cannot overwrite in Windows\Fonts folder?

Thanks for all your great work.

<img width="595" alt="screenshot" src="https://user-images.githubusercontent.com/813690/86224110-c0a1d880-bb88-11ea-9a79-dd4016031380.png">

**Comment by aaronbell** [comment]
Yeah, this is due to Windows Terminal shipping their own version of the font. Once they catch up, you can switch over. Sorry for the trouble! In the meanwhile, you could use the PL version of the font.

**Comment by DHowett** [comment]
However, I see this even on a system with just one version of Terminal installed... and, suspiciously, Bold is missing from the named list of faces with weights.

**Comment by DHowett** [comment]
(I suspect that what’s happening is that Regular and Bold are showing up as “Cascadia Code”)

**Comment by aaronbell** [comment]
Yeah, Bold is style linked with Regular, so it isn't showing up.

**Comment by pasqualedante** [comment]
> Yeah, this is due to Windows Terminal shipping their own version of the font. Once they catch up, you can switch over. Sorry for the trouble! In the meanwhile, you could use the PL version of the font.

Ok thanks!
