### ISSUE TITLE
Using the new light version of the font does not correct render powerline glyphs in Windows Terminal

### ISSUE THREAD

**Issue by alaatm** [microsoft/cascadia-code#315]
# Environment

```none
Cascadia Code version number: 2007.001
Application (with version) used to display text: Windows Terminal
OS platform and version: Windows 10 x64
Screen resolution (i.e. 220dpi): 2560x1440 @ 100%

Any other software?
```

# Steps to reproduce

In Windows Terminal settings, change the font to **Cascadia Code PL Light**.

# Expected behavior

Powerline glyphs should render correctly.

# Actual behavior

![image](https://user-images.githubusercontent.com/2095803/86241976-9104c780-bbac-11ea-8907-5cfe2770ab25.png)

**Comment by aaronbell** [comment]
The font being displayed is not Cascadia Code PL Light. In fact, it is not Cascadia Code at all. That is likely your problem. :)
