### ISSUE TITLE
Undefined name: Where is step_remove_ligatures() defined?

### ISSUE THREAD

**Issue by cclauss** [microsoft/cascadia-code#317]
# Environment

```none
Cascadia Code version number: GitHub master branch
Application (with version) used to display text:
OS platform and version:
Screen resolution (i.e. 220dpi): 

Any other software?
```

# Steps to reproduce

https://github.com/microsoft/cascadia-code/search?q=step_remove_ligatures

[flake8](http://flake8.pycqa.org) testing of https://github.com/microsoft/cascadia-code on Python 3.8.3

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./build.py:258:25: F821 undefined name 'step_remove_ligatures'
                        step_remove_ligatures,
                        ^
./build.py:303:17: F821 undefined name 'step_remove_ligatures'
                step_remove_ligatures,
                ^
2     F821 undefined name 'step_remove_ligatures'
2
```
https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this issue does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* F82 tests are _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python a __NameError__ is raised which will halt/crash the script on the user.

# Expected behavior

# Actual behavior

**Comment by aaronbell** [comment]
That area of the build script is from an older portion of the code which is currently inactive as we are not building a full Nerd Fonts version of the font (which is why Python doesn't throw any errors). I'll update it to align with the PL build process.
