### ISSUE TITLE
I hope to have a larger spacing like source-code-pro

### ISSUE THREAD

**Issue by DestinyHunter** [microsoft/cascadia-code#32]

**Comment by aaronbell** [comment]
Hi. I'm not sure what you really mean by "larger spacing". Do you refer to the width of characters? The amount of whitespace between characters? Or something else?

**Comment by DestinyHunter** [comment]
![image](https://user-images.githubusercontent.com/20897838/68646353-e3c63c00-0555-11ea-8a91-3c7eeaf86200.png)
It seems a bit crowded

**Comment by aaronbell** [comment]
I think what you're observing is that the font is slightly narrower and heavier than Source Code Pro. At current, there are plans to provide a lighter weight in the near future which will reduce the perception of cramping. However, there is no current plan for a wider variant. 

As such, I dupe this against #25 (the need for a lighter weight). Thanks!
