### ISSUE TITLE
font build fails on GNU/Linux: mismatch between filenames in build.py and the actual filenames in sources/features

### ISSUE THREAD

**Issue by ajalexei** [microsoft/cascadia-code#323]
# Environment

Cascadia Code version number: 2007.01
Application (with version) used to display text: rxvt-unicode, version - 9.22
OS platform and version: Debian GNU/Linux, bullseye/sid
Screen resolution (i.e. 220dpi): 96dpi

# Steps to reproduce

Enter the Cascadia Code source directory, and try to compile the TTF fonts with "python3 build.py" on a GNU/Linux system
(very likely any system with case sensitive filesystem)

# Expected behavior

Normally the execution of "python3 build.py" should generate four files - CascadiaCode.ttf, CascadiaCodePL.ttf, CascadiaMono.ttf, CascadiaMonoPL.ttf - under the "build" directory

# Actual behavior

the compilation process started with "python3 build.py" causes the following error message:

  File "build.py", line 263, in <module>
    step_set_feature_file(INPUT_DIR / "features" / "features_mono_pl.fea"),
  File "build.py", line 41, in step_set_feature_file
    fea = n.read_text()
  File "/usr/lib/python3.8/pathlib.py", line 1232, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'sources/features/features_mono_pl.fea'

and an identical error is present for "features_code_pl.fea", up to the  substitution "mono" --> "code", and a different line number in the "build.py" file

This is caused by the build.py using "sources/features/features_mono_pl.fea" and "sources/features/features_code_pl.fea", while the actual filenames are "sources/features/features_mono_PL.fea" and "sources/features/features_mono_PL.fea" respectively.

Renaming: 
  sources/features/features_mono_PL.fea --> sources/features/features_mono_pl.fea
  sources/features/features_code_PL.fea --> sources/features/features_code_pl.fea
fixes the issue on my version of GNU/Linux

**Comment by aaronbell** [comment]
Thanks! Yeah, Linux seems to have an issue with this. We'll update it.

**Comment by DHowett** [comment]
Hint, from the build log.

`ModuleNotFoundError: No module named 'vttLib'`

It looks like somebody hasn't set the appropriate python packages as `Build-Dependencies`. You should consult the maintainer (which are are not).

**Comment by alexmyczko** [comment]
@ajalexei where did you get statmake from? (pip3 install statmake?)

**Comment by ajalexei** [comment]
> @ajalexei where did you get statmake from? (pip3 install statmake?)

yes, "pip3 install statmake".
I kept pip3-ing untill the build succeeded.

I think a better/intended way is to use the instructions from the (cascadia source folder)/requirements.txt to install/check which packages are required.
