### ISSUE TITLE
Documentation Issue - Installation instructions inside README.md

### ISSUE THREAD

**Issue by p2well** [microsoft/cascadia-code#328]
Installation instructions inside README.md should be updated.

Instead of installing the font using "Install" button you need to install the font by choosing the right mouse click option "Install for all users". Otherwise after restart of your Windows 10 system the font will not load correctly. See https://github.com/microsoft/cascadia-code/issues/297 for more details.

**Comment by aaronbell** [comment]
Thanks! I've updated the readme file.
