### ISSUE TITLE
Release 2007.15?

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/cascadia-code#331]
[Windows Terminal v1.1.2021.0](https://github.com/microsoft/terminal/releases/tag/v1.1.2021.0) has been released today. The release notes state:

> This version of Windows Terminal ships with Cascadia Code v2007.15 ([#6958](https://github.com/microsoft/terminal/pull/6958))

But I cannot find the corresponding release of Cascadia Code.

Did you forget to release this version? 😃 I would like to install the Powerline versions of the font since they are not shipped with Windows Terminal for some reason.

**Comment by DHowett** [comment]
We're investigating a couple issues with the versions of the font that _don't_ ship in Terminal :smile: which has given us pause on releasing them broadly.

**Comment by Alovchin91** [comment]
Okay, good to know that it's still in the pipeline 😃

**Comment by aaronbell** [comment]
Yup! We're working on it. Closing this for now.
