### ISSUE TITLE
Ligatures dissapear when selecting non regular variant

### ISSUE THREAD

**Issue by musm** [microsoft/cascadia-code#332]
# Environment

```none
Cascadia Code version number: 2007.15 
Application (with version) used to display text: VS Code and also Windows Terminal
OS platform and version: Windows 10 is the best
Screen resolution (i.e. 220dpi):  normal 

Any other software? no thanks
```

# Steps to reproduce

Set 

```
            "fontFace": "Cascadia Code Semilight",  

```

Similarly for other applications, e.g. VS Code.

# Expected behavior and  Actual behavior

Ligatures no longer apply, i.e.
```
-> doesn't show up as  the fused variant
 
```

**Comment by DHowett** [comment]
Because both of those applications are expecting a font _family_ name, you need to vary the font weight by setting `font-weight` (VSCode) or `fontWeight` (Windows Terminal)

I'm going to guess that in WT, you're actually seeing Consolas. :smile:

**Comment by musm** [comment]
homer simpson moment
