### ISSUE TITLE
Leading incorrect at small font sizes?

### ISSUE THREAD

**Issue by musm** [microsoft/cascadia-code#334]
# Description of the new feature/enhancement (with images if possible)

Cascadia code at very small font sizes (e.g. 8) is quite compressed in the leading   when you compare it to Consolas or Roboto Mono, and more importantly the leading looks too small.

![1](https://user-images.githubusercontent.com/4319522/88873466-b1936200-d1ea-11ea-81aa-062eeb7571c8.gif)

**Comment by aaronbell** [comment]
Thanks for the feedback. Font leading is by design and was not intended to align with Roboto Mono or Consolas. 

I'd suggest adding your support to [this thread](https://github.com/microsoft/terminal/issues/3498) which requests the ability to customize the line spacing in Windows Terminal.
