### ISSUE TITLE
x-height too short at small font sizes making it unusable 

### ISSUE THREAD

**Issue by musm** [microsoft/cascadia-code#335]
# Description of the new feature/enhancement (with images if possible)

The x-height compared to say Roboto Mono at small font sizes (size 8) is extremely small making it unusable at these small font sizes compared to say Roboto Mono or consolas. 

![2](https://user-images.githubusercontent.com/4319522/88873882-b6a4e100-d1eb-11ea-92a2-c110718bdbff.gif)

**Comment by aaronbell** [comment]
If you look closely, you'll note that actually all of Cascadia Code's glyphs are slightly smaller than Roboto Mono at the same size. Personally I find that this gives Cascadia Code a horizontality that makes the longer lines of text easier to read.

To obtain a similar x-height sizing, I'd suggest increasing the point size of Cascadia Code slightly.

**Comment by musm** [comment]
Yes I noticed that, unfortunately Windows Terminal doesn't allow fractional font sizes so jump from size 8 to size 9 is very massive

**Comment by aaronbell** [comment]
Ah, sorry about that! I suggest filing a bug on [their Github](https://github.com/microsoft/terminal) to request it. :)

**Comment by aaronbell** [comment]
Strike that. I found your bug! Haha.
