### ISSUE TITLE
Bug Report  cascadia-code cause the wpf-app hang in win 10 -10.0.14393

### ISSUE THREAD

**Issue by heartacker** [microsoft/cascadia-code#339]
FYI:

https://github.com/dotnet/wpf/issues/3309#issuecomment-670092316

**Comment by aaronbell** [comment]
Question. Are you observing the same issue with all versions of the font (like both PL and normal) and have you tried the static OTF files versus the variable TTF versions?

**Comment by aaronbell** [comment]
As there hasn't been any update on this issue, and it is not clear that the font is at issue, I am closing this for now. Feel free to re-open if there is new information.

**Comment by aaronbell** [comment]
As there hasn't been any update on this issue, and it is not clear that the font is at issue, I am closing this for now. Feel free to re-open if there is new information.

**Comment by DHowett** [comment]
Since this is windows version 14393, I believe this bug is the same as #319! It's also a WPF app on that version of Windows.

**Comment by aaronbell** [comment]
Thanks @DHowett. Any update on that bug? ;)

**Comment by aaronbell** [comment]
Thanks @DHowett. Any update on that bug? ;)
