### ISSUE TITLE
Feature Request: font is very feeble on Visual Studio - windows

### ISSUE THREAD

**Issue by amithegde** [microsoft/cascadia-code#34]
# Description of the new feature/enhancement (with images if possible)

I just changed my font to Cascadia Code on VS 2017 and it looks very feeble compared to Consalas which I have been using forever.
![image](https://user-images.githubusercontent.com/816051/65211075-5df4ab80-da52-11e9-8476-6e306cf5c757.png)

I would prefer it to be stronger than it exists now👍

**Comment by DHowett-MSFT** [comment]
Uh, that’s courier new.

**Comment by amithegde** [comment]
@DHowett-MSFT its not! I added courier new as well for comparing both. BTW what was the reason to close?

**Comment by DHowett-MSFT** [comment]
No, look, your screenshot is literally a screenshot of Courier New. It means that Visual Studio can’t find the font. Restart your computer.

**Comment by amithegde** [comment]
Let me try restarting.

**Comment by amithegde** [comment]
Restarting has actually fixed it. Thanks!

**Comment by ChrisTorng** [comment]
Restart Visual Studio works. Confirmed in Visual Studio 2017/2019.
