### ISSUE TITLE
SemiLight can't be activated in vscode.

### ISSUE THREAD

**Issue by bao007fei** [microsoft/cascadia-code#340]
# Environment

```none
Cascadia Code version number: 2007.01
Application (with version) used to display text: Visual Studio Code
OS platform and version: Windows 10 Pro 2004
Screen resolution (i.e. 220dpi): Dell U2414H, 23.8 in, 1920 x 1080 pixels, 92ppi

Any other software?
Windows Terminal
```

# Steps to reproduce

SemiLight can't be activated in vscode. 

# Expected behavior

A **lighter** regular font face like Consolas or Fira code.

# Actual behavior

IMHO Regular one is too bold and Light one is too light. Especially in Dark mode, feels too heavy.

**Comment by aaronbell** [comment]
Thanks for the bug report. This is a [known issue](https://github.com/microsoft/vscode/issues/101467) with VS Code that will hopefully be resolved soon. If you could go throw support behind that bug, it'll get addressed sooner :)

**Comment by IllusionMH** [comment]
Just in case: [numeric values are now supported for `editor.fontWeight`](https://code.visualstudio.com/updates/v1_49#_numeric-fontweight-values) in 1.49 so 350 is now valid value.
Support for integrated terminal didn't make it to 1.49 but already available in 1.50-insiders build and will be in next stable.

**Comment by LucasKuhn** [comment]
Sorry to comment on a closed issue, but I'm still not able to use semi-light on VSCode 
VSCode version 1.58.0 | Cascadia Code 2106
Setting to 350 sets the weight the same as 500
<img width="438" alt="image" src="https://user-images.githubusercontent.com/26127185/126994180-f3d9f74c-0e07-4ce4-b829-503f108eaa9e.png">

**Comment by aaronbell** [comment]
See: https://github.com/microsoft/vscode/issues/128097

appears to be an issue with Chromium’s rendering of `font-weight`. I’ve been discussing solutions with @IllusionMH.

**Comment by linktoahref** [comment]
Nothing related to the issue.
@LucasKuhn What theme are you using ? Looks nice.

**Comment by andreynering** [comment]
While this is not fixed, I found a good enough workaround here: https://github.com/microsoft/cascadia-code/issues/25#issuecomment-1024890739

**Comment by LucasKuhn** [comment]
> Nothing related to the issue. @LucasKuhn What theme are you using ? Looks nice.

Atom One Dark
