### ISSUE TITLE
Font Ligatures From Mono and Mono PL Do not work with Terminal.app or iTerm2

### ISSUE THREAD

**Issue by jamespack** [microsoft/cascadia-code#341]
# Environment

```none
Cascadia Code version number: 2007
Application (with version) used to display text: Terminal.app(2.10) & iTerm2(3.3.12)
OS platform and version: MacOS 10.15.6
Screen resolution (i.e. 220dpi): 227 ppi Retina display

Any other software?
```

# Steps to reproduce

Install Cascadia Code Fonts
Set the default fonts of Terminal.app or iTerm2 to Cascadia Code Mono or Cascadia Code Mono PL. (Some of the ligatures are broken in the non mono fonts in iTerm2). Enabled font ligatures in iTerm2 for ligatures support

# Expected behavior
I expect the font ligatures to work

# Actual behavior
Font ligatures do not work.

Is this a bug or intended behavior of the Monospaced fonts?

**Comment by DHowett** [comment]
The “Mono” variant of the font does not have ligatures. The “Code” variant is the only variant that has ligatures.

**Comment by DHowett** [comment]
Just to clear up any confusion: _both of them are monospaced!_ 😄

**Comment by jamespack** [comment]
I knew they were both mono. Wasn’t sure if that was intended behavior though. Thanks!

**Comment by jamespack** [comment]
Oh wait.. you are saying even Cascadia Code is monospaced?

**Comment by DHowett** [comment]
So, they're both officially monospaced fonts -- every glyph has the same width. Cascadia Code _is_ monospaced, but it has ligatures that retain the monospaced character of the font.

For a little bit of fun implementation details:

Each glyph in the font has the same width, including the ligatures. Every time you enter a set of glyphs that get ligatured, they get replaced with other glyphs.

For example, take the `===` ligature. Normally, three equals signs next to eachother would look like this. I've highlighted the bounding box in red to show the widths.

![image](https://user-images.githubusercontent.com/189190/90342376-ac8d2b80-dfbc-11ea-82fc-d03e0036610c.png)

In Cascadia Code (and Fira Code!), the first two equals signs actually get replaced with _space characters_ (or something very similar). The _final_ equals sign gets replaced with one that extends way to the left outside of its box.

So, it looks like this. The first two "equals" characters (replaced with spaces) are on top, and the final one is on the bottom.

![image](https://user-images.githubusercontent.com/189190/90342421-21606580-dfbd-11ea-8fc7-c4775bc5a57b.png)

When you put them all together, you get this:

three cells, "one" symbol :)

![image](https://user-images.githubusercontent.com/189190/90342456-5371c780-dfbd-11ea-89c7-2e21c736fc62.png)

**Comment by jamespack** [comment]
I see.. thanks for the clarification. I use this in every tool I can from professional to personal.
