### ISSUE TITLE
Masculine/feminine ordinal indicators (0xBA and 0xAA) should be underlined

### ISSUE THREAD

**Issue by afmenez** [microsoft/cascadia-code#342]
The masculine and feminine Ordinal Indicators (0xBA and 0xAA) should be underlined, like in the "Consolas" font.  If they are not underlined, the masculine indicator looks identical to the Degree Sign (0xB0).

**Comment by aaronbell** [comment]
Thanks for the feedback! There's been some discussion back and forth in the type community regarding the treatment of ordinals in fonts, as Brazilian Portuguese prefers use of an underline, whereas other languages (including Portugual Portuguese) see it as optional, or prefer not to have them. 

My understanding is that the underline essentially acts as an abbreviation of a mandatory dot for abbreviations and that in contemporary Spanish / Portuguese, that dot is often represented instead as a preceding period like so: `M.ª` and `n.º` (and if the underline is present, then the period should be removed). Given this seemingly optional nature, some fonts include the underline by default (such as Consolas, Input Mono, and Fira Code), whereas others do not (Source Code Pro, Dank Mono, and JetBrains Mono). 

I appreciate the concern that there can be confusion between the ordinals and the degree symbol and can look to resolve that, but my question to you is—given that the abbreviation can be marked using a period, how crucial is the addition of the underline? 

Normally I'd suggest that an underlined version be provided via OpenType, but most code editing environments do not offer support sufficiently to make it feel like a solution to me.

**Comment by CodeCrazy-ywt** [comment]
Maybe you can take stylistic sets into consideration.

**Comment by afmenez** [comment]
I am migrating from Consolas to Cascadia.  I have code that used to show correctly in Cascadia, and shows correctly on display and printer when the code runs.  It is not viable to review all the code I already have just to make it show nice with the new font on the editor but break when running.

**Comment by aaronbell** [comment]
Glad you found a solution that works for you. As there is no specific issue in the Cascadia, I’m closing this.
