### ISSUE TITLE
Symbol rendered in font previewer, but not in Windows Terminal

### ISSUE THREAD

**Issue by burhan** [microsoft/cascadia-code#344]
# Environment

Windows Terminal (Preview) build, and Cascadia Font PL in light weight.

I thought the `PL` version includes the programming ligatures, but when I enabled it in Windows Terminal, I am not getting the repository symbol, but when I view the font in Windows Font previewer, I'm getting the correct symbol, but then the down arrow symbol is not working.

Not sure if this is an issue with Windows Terminal or with the font, but adding it here as its rendering oddly in the previewer. I am also not sure if the font being used in Windows Terminal is the bundled version or the one installed on the machine.

```none
Cascadia Code version number: 1911.210
Application (with version) used to display text: Windows Terminal Preview (1.2.2234.0)
OS platform and version: Windows Professional 19042.450
Screen resolution (i.e. 220dpi): N/A
```

Here is the relevant configuration for Windows Terminal; I have not modified it except to add the font in `defaults`.

```none
    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "fontface": "Cascadia Code PL",
            "colorScheme": "Tango Dark",
            "fontWeight": "light"
        },
```

# Steps to reproduce

1. Download latest preview build from Windows Store
2. Open Windows Terminal Preview
3. Edit settings (see snippet above)

# Expected behavior

I thought it would work like Delugia Nerd Font to be honest.

# Actual behavior

![image](https://user-images.githubusercontent.com/603112/90483249-1f251500-e13d-11ea-9c7e-22da191d09b1.png)

**Comment by aaronbell** [comment]
Strange. The 1911 version of Cascadia Code PL contains both of those characters. Can you double check that you’ve called for `Cascadia Code PL` everywhere and are not getting a fallback font?

Also, 1911 doesn’t have the lighter weights available. I’d suggest uninstalling it and installing that latest version from the GitHub releases page.

**Comment by DHowett** [comment]
Yeah, this should be working:
![image](https://user-images.githubusercontent.com/189190/90542995-d586fb00-e139-11ea-8268-a934f4f17c65.png)

I wonder if there's a _separate_ codepoint some Nerd Font variants use for the branch name?

**Comment by aaronbell** [comment]
I see that symbol at the same codepoint in both Delugia and Cascadia Code PL

**Comment by aaronbell** [comment]
Looking at the above again, I think that the "fontweight" declaration of "light" is the problem. As version 1911 is not a variable font, it does not contain the light weight of the font. As such, by requesting the "light", the font itself is not being found, and is falling back to the "Cascadia Code" version that ships in WT which contains no PL characters (but *does* have a light weight). 

As I mentioned before, you will need to uninstall version 1911 and install 2007 instead.

**Comment by burhan** [comment]
Downloaded the updated font and font previewer worked, but Windows Terminal (Preview) wasn't. Opened settings and then Visual Studio Code highlighted `fontface`. Turns out, the property is `fontFace` 🤦‍♂️  (but it didn't highlight this before). Now everything is working.
