### ISSUE TITLE
Feature Request: Parallel build system

### ISSUE THREAD

**Issue by madig** [microsoft/cascadia-code#349]
# Description of the new enhancement

Building the fonts for experimentation is currently painfully slow.

# Proposed technical implementation details

1. Use multiprocessing in the build script. Probably doable, I did something for statics generation over at https://gitlab.gnome.org/GNOME/cantarell-fonts/-/blob/master/scripts/make-static-fonts.py
2. Use a proper build system capable of parallel execution. I know of https://pydoit.org/, but find it a bit cumbersome to work with.

I suppose Make would fit the bill but is there a truly cross-platform one one can use without a tedious setup step for at least one major platform? ... Ninja?

**Comment by aaronbell** [comment]
I’m definitely not experienced enough at the moment to have a solution for this, but I am interested in what experimentation you’re doing :)

**Comment by madig** [comment]
None, I just remembered that I was annoyed by the tediousness of doing everything serially when I did the small build script clean up.

**Comment by madig** [comment]
@aaronbell @DHowett if you still care (I do), I made https://github.com/madig/test-generate-instances to compare several ways of dealing with the parallel instance generation problem. The scripts do not compile anything, just write out generated instances. Spoiler: on my Linux machine, using shared memory wins.

**Comment by madig** [comment]
Second insight: I tried using the  shared memory approach of fully loading the Designspace with UFOs up front and then pickling it into shared memory for both VF and statics compilation functions to unpickle it from there. I got me an about 1 second improvement on a `-S -W` run and no discernible improvement on a just-VFs run on my Linux machine... I suppose careful profiling and maybe subdividing the stages further might help, but I think the low hanging fruit may be picked. Unless I'm doing something wrong. Maybe Python is the wrong language for this kind of work and _someone_ needs to finally rewrite the relevant libraries in Rust.

**Comment by aaronbell** [comment]
Thanks for the further investigation! Really interesting. I definitely agree it sounds like we’ve taken Python as far as it can go here and that the only way to get more significant gains would be to rewrite everything in a faster language. Python works really well for quick tasks but man it can drag at larger ones.

**Comment by madig** [comment]
Hm, well there might be one low hanging fruit left. Currently the nerdfonts
UFO is loaded multiple times (per instance!)
