### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by Quppa** [microsoft/cascadia-code#35]
An officially-maintained [Chocolatey package](https://chocolatey.org/) for the font would be great to have (à la https://chocolatey.org/packages/FiraCode-ttf).

**Comment by cerebrate** [comment]
In the interim, unofficial package is here:

https://chocolatey.org/packages/cascadiacode

(Not mine.)

**Comment by zunderscore** [comment]
> In the interim, unofficial package is here:
> 
> https://chocolatey.org/packages/cascadiacode
> 
> (Not mine.)

That's mine. 😊 I'd be more than happy to put the source up somewhere or continue maintaining it myself if y'all would like.

**Comment by digitalcoyote** [comment]
@zunderscore 
You could also add the maintainer(s) of this repository as to the chocolatey package's maintainer list. This would give them access to push new versions and lend credibility to your package.

**Comment by aaronbell** [comment]
Hello! We're not planning at the moment to maintain a chocolatey package, so I'm glad that @zunderscore has stepped up to do one for us. As such, I'm going to close this and point to his package via the wiki. Cheers!
