### ISSUE TITLE
[Linux/FreeType + VariableTTF-specific] Some glyphs (e.g. a '4', or the bottom-right stem of lowercase 'u') look weird at certain sizes, due to mis-handling overlapping paths of variable font. Needs FreeType 2.10.3 and font flag OVERLAP_{SIMPLE, COMPOUND}

### ISSUE THREAD

**Issue by ronjouch** [microsoft/cascadia-code#350]
# Environment

```none
Cascadia Code version number: 2008.25
Application used to display text: VS Code 1.48.2, Firefox 80.0, Kitty 0.18.3, everywhere
OS platform and version: Ubuntu 20.04.1
Screen resolution (i.e. 220dpi): I don't know
```

# Steps to reproduce

Display a `u` at size 14.7

# Expected behavior

`u` is good-looking

# Actual behavior

`u` looks weird: the bottom right stem has sort of a glitch, where it overlaps to the inside part of the curve:

![screenshot_cascadia-code-weird-u_2020-08-27-10:37:25](https://user-images.githubusercontent.com/522085/91456517-5f794700-e851-11ea-95b1-aae9ef690d75.png)

**Comment by ronjouch** [comment]
Here's another slightly bigger size looking funky:

![screenshot_other-size_2020-08-27-10:40:59](https://user-images.githubusercontent.com/522085/91456992-e3cbca00-e851-11ea-8504-3b83c1eab1d7.png)

**Comment by aaronbell** [comment]
Hi. What is interesting is that you can see on the 4 that it appears that the diagonal stroke is extending past the horizontal one. I'm guessing that you've installed the variable font version (since what you're observing happens where different strokes overlap). Did you install the OTF or TTF version?

However, I am not able to repro the issue that you're observing on Windows or Mac, which makes me suspect that it has something to do with how ubuntu is interpreting the font.

**Comment by ronjouch** [comment]
@aaronbell 

> What is interesting is that you can see on the 4 that it appears that the diagonal stroke is extending past the horizontal one.

Indeed 👍.

> I'm guessing that you've installed the variable font version (since what you're observing happens where different strokes overlap).

What do you mean by "the variable font version"?

> Did you install the OTF or TTF version?

I had installed the TTF version. And, lo and behold, the OTF version doesn't exhibit the issue! Here's a screenshot of the OTF version at the same size as the initial screenshot (14.7), the problem is gone:

![screenshot_otf_2020-08-27-12:40:51](https://user-images.githubusercontent.com/522085/91470567-df5bdd00-e862-11ea-8fba-2a12c3392346.png)

> However, I am not able to repro the issue that you're observing on Windows or Mac, which makes me suspect that it has something to do with how ubuntu is interpreting the font.

Not just Ubuntu, though, I see the same thing on my Arch Linux machine. So, maybe a bug in a common rendering library? Which one is responsible for this exactly? FreeType? Harfbuzz?

**Comment by aaronbell** [comment]
In the 2008.25 package, there are static OTFs (each weight is a separate .otf) and TTFs, both variable (all styles are contained within one .ttf file) and static (each weight is a separate .ttf). 

When you installed the TTF version, did you install `CascadiaCode.ttf` or `CascadiaCode-Regular.ttf`?

**Comment by ronjouch** [comment]
> In the 2008.25 package, there are static OTFs (each weight is a separate .otf) and TTFs, both variable (all styles are contained within one .ttf file) and static (each weight is a separate .ttf).
> 
> When you installed the TTF version, did you install `CascadiaCode.ttf` or `CascadiaCode-Regular.ttf`?

@aaronbell my initial report was with the variable TTF (all styles in one .ttf). After a `rm -rf ~/.local/share/fonts/Saja* && fc-cache -fv` followed by an install of static `Cascadia_Code_Regular.ttf` + `Cascadia_Code_Bold.ttf`, things look good:

![screenshot_ttf-static_2020-08-27-13:04:43](https://user-images.githubusercontent.com/522085/91472764-edf7c380-e865-11ea-80e4-439fe0d42414.png)

→ Yes, the problem is specific to the variable TTF (all styles are contained within one .ttf file).

What could explain this?

**Comment by aaronbell** [comment]
It is probably an issue with FreeType's method of dealing with variable fonts, or fonts that have overlapping paths within one glyph (normally these overlaps are removed, but for variable fonts it is useful to preserve them). 

Which version of FreeType are you running? According to [the FreeType page](https://sourceforge.net/projects/freetype/files/freetype2/2.9/) you should be running 2.9 at minimum for proper Variable font support.

**Comment by ronjouch** [comment]
> Which version of FreeType are you running? According to [the FreeType page](https://sourceforge.net/projects/freetype/files/freetype2/2.9/) you should be running 2.9 at minimum for proper Variable font support.

@aaronbell I'm running the [libfreetype6 2.10.1 package](https://packages.ubuntu.com/focal/libfreetype6) shipping as part of Ubuntu 20.04. Do you suggest I report this bug to FreeType?

**Comment by aaronbell** [comment]
From what I can tell, that package doesn't look like it has the most up-to-date version of FreeType. Can you try upgrading to the latest? If the latest still shows the issue, then yeah, it should be reported.

**Comment by ronjouch** [comment]
> From what I can tell, that package doesn't look like it has the most up-to-date version of FreeType. Can you try upgrading to the latest? If the latest still shows the issue, then yeah, it should be reported.

@aaronbell no and yes. No because in a non-rolling-release Linux (like Ubuntu), you never upgrade such a core package out of major versions, that's a recipe for a broken system. That being said, yes because my home machine runs Arch (which is a rolling release currently shipping the latest [freetype 2.10.2](https://www.archlinux.org/packages/extra/x86_64/freetype2/)) and exhibits the problem. Will file a bug upstream and closing this one. Thanks for all the guidance.

**Comment by ronjouch** [comment]
@aaronbell FYI, as I'm preparing the FreeType bug report:

- (Broken multi-font bundle) `ftview -d 1024x768x24 30 CascadiaCode-2008.25/ttf/CascadiaCode.ttf`
![screenshot_cascadia-1-bad-ttfBundle_2020-08-27-19:07:37](https://user-images.githubusercontent.com/522085/91503976-dfc39a80-e899-11ea-8bf8-770b6bfdb0a7.png)
- (Good single font) `ftview -d 1024x768x24 30 CascadiaCode-2008.25/ttf/static/CascadiaCode-Regular.ttf`:
![screenshot_cascadia-2-ok-singleRegular_2020-08-27-19:06:58](https://user-images.githubusercontent.com/522085/91503981-e2be8b00-e899-11ea-9f48-4da7c7bf79ab.png)
- A looping GIF animating between both:
![cascadia-code-animation](https://user-images.githubusercontent.com/522085/91504004-ef42e380-e899-11ea-9358-5d78c1d926b6.gif)

**Comment by ronjouch** [comment]
Filed [FreeType bug #59026: Multi-weight TTF of font "Cascadia Code" renders artifacts on some glyphs](https://savannah.nongnu.org/bugs/?59026)

**Comment by aaronbell** [comment]
Thank you!

**Comment by apodtele** [comment]
FreeType will handle overlapping contours in the next release but it will require OVELAP_SIMPLE or OVERLAP_COMPOUND set. We understand that those flags are optional in variation fonts but oversampling quadruples the rendering time. Buyer beware.

**Comment by ronjouch** [comment]
> FreeType will handle overlapping contours in the next release but it will require `OVELAP_SIMPLE` or `OVERLAP_COMPOUND` set. We understand that those flags are optional in variation fonts but oversampling quadruples the rendering time. Buyer beware.

Thanks @apodtele . @aaronbell, Alexei also posted a few more details on [the FreeType bug](https://savannah.nongnu.org/bugs/index.php?59026) that should be of interest to you. Quoting them here:

> You correctly identified the issue: overlapping contours can produce pixels with inflated coverage because FreeType normally integrates the coverage. To mitigate the artefacts, oversampling is necessary (increase resolution 4x4 and average the results). 
> 
> We implemented this recently but it quadruples the rendering time. Only glyphs with explicit OVERLAP_SIMPLE or OVERLAP_COMPOUND would be subject to oversampling.
> 
> Those flags are required in static fonts with overlaps. CascadiaCode just removes the overlaps in the static fonts, which is even better alternative. The flags are optional in variation fonts however but not all variation fonts have overlaps. We stopped short of enabling oversampling for all variation fonts. 

@aaronbell, can you build me a pre-release version of CascadiaCode with one of the `OVERLAP_` flags set? I'll test it with the latest git version of FreeType.

Side note: over at the FreeType bug [I'm also asking](https://savannah.nongnu.org/bugs/index.php?59026#comment2) what's the path forward for distribution packagers.

**Comment by aaronbell** [comment]
Thanks for the investigation and info on this. It appears that the python library that we're using to build the Variable font doesn't automatically implement the OVERLAP_SIMPLE or OVERLAP_COMPOUND flag where it should be. AFAIK, this isn't a problem in the Mac / Windows rasterizers, but seems that it is in FreeType. I'll investigate further.

**Comment by aaronbell** [comment]
@ronjouch Can you test the attached font? 
[CascadiaCodeTEST.ttf.zip](https://github.com/microsoft/cascadia-code/files/5143124/CascadiaCodeTEST.ttf.zip)

**Comment by ronjouch** [comment]
> Can you test the attached font? [CascadiaCodeTEST.ttf.zip](https://github.com/microsoft/cascadia-code/files/5143124/CascadiaCodeTEST.ttf.zip)
> 
> (BTW, this font does not contain hinting, which may cause other unexpected changes, but I wanted to see if my fix actually resolved the overlap issue)

@aaronbell (cc @apodtele) problem fixed if using that font and FreeType 2.10.2+p53+g6730854c3 (but not FreeType 2.10.2 stable). For completeness, what flag/changes did you use to produce this build?

Proof: screenshots of `ftview -d 1024x768x24 30 CascadiaCodeTEST.ttf`,

1. With FreeType 2.10.2 stable: broken, with artifacts:
![screenshot_cascadiacodeTEST-freetype2102stable_2020-08-28-12:31:34](https://user-images.githubusercontent.com/522085/91591563-1ac1de80-e92b-11ea-916e-6c53829a6dab.png)
2. With FreeType 2.10.2+p53+g6730854c3: fixed, no artifacts:
![screenshot_cascadiacodeTEST-freetype2102+p53+g6730854c3_2020-08-28-12:32:37](https://user-images.githubusercontent.com/522085/91591579-1e556580-e92b-11ea-9fc4-284c9aec4aaf.png)
3. A GIF animating between both:
![screenshot_cascadiacodeTEST-animation](https://user-images.githubusercontent.com/522085/91591587-231a1980-e92b-11ea-925f-912c6249a380.gif)

**Comment by apodtele** [comment]
I think that the root of the problem is in the rasterizer implementation
- Microsoft rasterizer is based on 4x4 oversampling for anti-aliasing which is likely slower but handles overlaps naturally. Microsoft even omitted these flags in [the earlier versions of specification](https://docs.microsoft.com/en-us/typography/opentype/otspec170/glyf).
- Apple rasterizer is probably based on integration, which is likely faster but does not handle overlaps well. Hence they care about the OVERLAP_SIMPLE or OVERLAP_COMPOUND flags but probably give in and do oversampling on top of integration for **all variable fonts**. This is just a guess and they might have a fast algorithm to detect overlaps.
- FreeType is certainly based on integration. We would like to be explicit about oversampling by setting the flags because it quadruples the rendering time. We did not investigate if detecting overlaps is plausible.

Thus this is an active area...

**Comment by aaronbell** [comment]
Thank you for your help! For this test version of the font I adapted @chrissimpkin's code [from here](https://github.com/TypeNetwork/Vollkorn-Typeface/issues/8#issuecomment-655791672) to the build process. This forces the OVERLAP_SIMPLE or OVERLAP_COMPOUND flags to be applied to all glyphs if simple or compound, respectively. 

Perhaps a bit of a brute force approach, but it solves the problem.

**Comment by aaronbell** [comment]
@apodtele My understanding aligns with yours—for variable fonts, MacOS acts as if the OVERLAP_SIMPLE and OVERLAP_COMPOUND flags are present, even if not actually set in font.

Seems that FreeType is the only rasterizer that actually cares if the flags are present in a variable font.

**Comment by apodtele** [comment]
Ideally, only glyphs with overlaps should have these flags set. I wonder what @madig is doing.

Would you like to bring this up on [freetype-devel](https://lists.nongnu.org/mailman/listinfo/freetype-devel)? I honestly have no idea how prevalent the overlaps in variable fonts. I would like to see overlap-free variable fonts if it is practical.

**Comment by aaronbell** [comment]
If this [is any indication](https://www.mail-archive.com/freetype-devel@nongnu.org/msg12168.html) he's putting it everywhere 😆 . 

Overlaps are actually extremely common in variable font development. For example, at extreme heavy weights, glyphs often have greater amount of overlap than they do at the extreme light end. If overlaps were removed in such a situation, it would be impossible to preserve master compatibility. So preserving outline overlaps is a necessity. 

From what I have found, it sounds like this issue has already been raised several times on the FreeType mailing list, so I wouldn't be adding anything more to the discussion 😄.

**Comment by madig** [comment]
> Seems that FreeType is the only rasterizer that actually cares if the flags are present in a variable font.

macOS < 10.16 cares, too.

> I honestly have no idea how prevalent the overlaps in variable fonts. I would like to see overlap-free variable fonts if it is practical.

The usual (most common) open-source pipeline to make VFs is based on ufo2ft, which currently doesn't do anything, so there are unlikely to be many VFs with those flags set...

**Comment by apodtele** [comment]
If you agree with setting the flags explicitly, we are on the same page and the specs will catch up eventually by recommending these flags. Implying the overlaps in all variable fonts seems to be an overkill unless I miss something. That is what needs to be discussed in a larger community.

**Comment by madig** [comment]
> If you agree with setting the flags explicitly

Sure, even if this is to work around an InDesign bug.

> That is what needs to be discussed in a larger community.

Use this community: https://github.com/googlefonts/ufo2ft/issues/402, it's the only one I care about ☺

**Comment by ronjouch** [comment]
On the distro packaging side, I filed [Arch FS#67746 - [ttf-cascadia-code] Some glyphs show artifacts due lack of overlap support in FreeType 2.10.2](https://bugs.archlinux.org/task/67746), where I suggest they switch to packaging the static fonts (with the caveat of increased disk space) until the font is patched with OVERLAY flags and a stable FreeType release supports them.
