### ISSUE TITLE
HEX number ligature not working anymore in 2008.25 release

### ISSUE THREAD

**Issue by dodmi** [microsoft/cascadia-code#353]
# Environment

```none
Cascadia Code version number: 2008.25
Application (with version) used to display text: Notepad++ 7.8.9 (x86)
OS platform and version: Windows 10 2004 (x64)
Screen resolution (i.e. 220dpi):  ??

Any other software? no
```

# Steps to reproduce
- Ensure ligature support is enabled (Preferences -> MISC. -> Use DirectWrite)
- Ensure Cascadia Code is selected as display font
- Enter a hex formatted digit as 0x123

# Expected behavior

The "x ligature" is appearing like in version 2007.01
![image](https://user-images.githubusercontent.com/4572946/91642761-411c7280-ea2e-11ea-9e4e-1d3d4466e34d.png)

# Actual behavior

The "x ligature" is gone (I read in the changes, that you've removed it in Cascadia Code Mono, but now it's missing in Cascadia Code, too)

![image](https://user-images.githubusercontent.com/4572946/91642793-8476e100-ea2e-11ea-8e87-1d92a08a1536.png)

**Comment by DHowett** [comment]
It was intentionally removed in all variants of the font. I will make sure the release notes are clear on this. /cc @aaronbell for DSAT about the `x`

**Comment by aaronbell** [comment]
Yes. The hex version of the `x` was causing more problems than not.
