### ISSUE TITLE
Ligatures not displayed in Notepad++ with some font styles

### ISSUE THREAD

**Issue by dodmi** [microsoft/cascadia-code#354]
# Environment

```none
Cascadia Code version number: 2008.25 and 2007.01
Application (with version) used to display text: Notepad++ 7.8.9 (x86)
OS platform and version: Windows 10 2004 (x64) ??
Screen resolution (i.e. 220dpi): ??

Any other software? no
```

# Steps to reproduce
- Ensure ligature support is enabled (Preferences -> MISC. -> DirectWrite)
- Enter some text, which should contain ligatures

# Expected behavior

Ligatures are shown in all Cascadia Code variants

# Actual behavior

Ligatures are only shown in some variants:
Version 2008.25 combined ttf, only "Cascadia Code" is working:
![image](https://user-images.githubusercontent.com/4572946/91642918-77a6bd00-ea2f-11ea-9e6b-3485a87d23e8.png)
![image](https://user-images.githubusercontent.com/4572946/91642927-81302500-ea2f-11ea-8995-8d38959d4bc7.png)
![image](https://user-images.githubusercontent.com/4572946/91642933-8b522380-ea2f-11ea-9e4e-f377f6f26cee.png)
![image](https://user-images.githubusercontent.com/4572946/91642940-94db8b80-ea2f-11ea-8159-bb9294085f35.png)
![image](https://user-images.githubusercontent.com/4572946/91642953-a886f200-ea2f-11ea-8f41-2e91d69151d2.png)

2008.25 static ttf, only "Cascadia Code" and "Cascadia Code SemiLight" is working:
![image](https://user-images.githubusercontent.com/4572946/91643003-f00d7e00-ea2f-11ea-9946-6a671a273c58.png)
![image](https://user-images.githubusercontent.com/4572946/91643011-fbf94000-ea2f-11ea-8da3-5985a8771932.png)
![image](https://user-images.githubusercontent.com/4572946/91643015-0287b780-ea30-11ea-988f-7af154b79b60.png)
![image](https://user-images.githubusercontent.com/4572946/91643026-0c111f80-ea30-11ea-8459-103314dd9e7b.png)
![image](https://user-images.githubusercontent.com/4572946/91643040-2519d080-ea30-11ea-8d73-c38a44a24a2d.png)

**Comment by DHowett** [comment]
If you look closely you can tell that it isn’t even _using_ the Cascadia font family in half your screenshots. This looks like an issue in Notepad++’s rendering engine.
