### ISSUE TITLE
-<< looks off with font-weight set to 300

### ISSUE THREAD

**Issue by rbusquet** [microsoft/cascadia-code#355]
# Environment

```none
Cascadia Code version number:  2008.25
Application (with version) used to display text: PyCharm 2020.2.1, Chrome 85.0.4183.83 
OS platform and version: macOS catalina
Screen resolution (i.e. 220dpi): 192dpi (I think)

Any other software? No
```

# Steps to reproduce

In chrome, change CSS of an element to use: -<<

```css
{
    font-family: 'Cascadia Code';
    font-weight: 300,
}
```

# Expected behavior

Expected the same for >>- but reversed
![image](https://user-images.githubusercontent.com/7198302/91773007-ef055980-ebb3-11ea-9998-56d6c75dc12d.png)

And this is how it looks like with normal fontweight:
![image](https://user-images.githubusercontent.com/7198302/91773109-1e1bcb00-ebb4-11ea-9395-bd9c3bd57835.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/7198302/91772835-a188ec80-ebb3-11ea-8d5f-ec3b6f9f07d5.png)

PyCharm using this font weight by default and I can't find a setting to change it

**Comment by aaronbell** [comment]
Thanks! Will fix that :)
