### ISSUE TITLE
Consider a font variant without any Glyphs/Ligatures for character combinations

### ISSUE THREAD

**Issue by ZStoner** [microsoft/cascadia-code#356]
# Feature Request:
Consider creating a font variant that doesn't have any special Ligature displays for certain character combinations.

# Problem/Issues:
As much as I love Cascadia Code (and I have had it as my browser's Monospace font for quite some time now :), one of the problems is actually understanding what some of the Ligature combos are... especially for ones that are 3+ chars across.

Take the 3-char combo of: `!==`
The ligatured version makes it look visually similar to: `=≠=`

While of course the visual representation quickly fits the mental picture of "not equal" or "inequality", it's visually unclear that the actual underlying chars are `!==`.  Because this is the "_triple not equals_", it looks even stranger to see an extra-long set of equals, and then a slash.

For coding purposes, I still like Cascadia Code, but I would love it even more if there was a different variant of Cascadia Code that didn't have any of the character-combo ligatures.  I would add that to my browser's Monospaced font in a heartbeat (_and for Notepad++ for general text_).
And I would continue using regular Cascadia Code in VS and VS Code.
 

# Proposed technical implementation details (optional)
Consider providing a variant of Cascadia Code without any ligatures.
Perhaps named as "Cascadia Code _Clean_", as a font name suffix of "Light" typically indicates a thinner type stroke.

**Comment by DHowett** [comment]
We already have this; it’s called “Cascadia Mono” and it is provided with every Cascadia distribution.

**Comment by aaronbell** [comment]
Try Cascadia Mono! All the fun of Cascadia Code without those pesky ligatures: 
https://github.com/microsoft/cascadia-code/releases/tag/v2008.25

**Comment by DHowett** [comment]
(Also, thanks for saying you love it! I end up using it everywhere i can 😄)
