### ISSUE TITLE
Documentation Issue: Briefly explain static/non-static versions

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/cascadia-code#358]
`README.md`:
> For optimal rendering quality, we recommend using the TTF version on Windows

This is a great hint for people unaware of the differences between TTF, OTF, WOFF2, and TFFOTFWFFTFTFFF (just kidding). However, I'm still not sure whether to install static or non-static (or both). Please clarify in the README.

**Comment by aaronbell** [comment]
I will update it. But generally we recommend installing the non-static ‘CascadiaCode.ttf’ font (or the various PL / Mono versions). It is a variable font with all the weight options and should work in most circumstances. However, should it _not work_ for whatever reason, static versions are also supplied as backup. For folks who prefer ‘otf’ format font files, those are provided as well. ‘WOFF2’ are used for the web.

**Comment by aaronbell** [comment]
Updated :)

**Comment by bersbersbers** [comment]
Great, thank you!
