### ISSUE TITLE
Missing character from IBM Graphics set.

### ISSUE THREAD

**Issue by DLasher106** [microsoft/cascadia-code#359]
Cascadia Code has the IBM Graphics characters found in positions x01–x1F of DOS codepages 437, 850, etc. But there is also a graphics character at x7F, Unicode U+2302 HOUSE, that is missing from Cascadia Code. I think that character is necessary for a terminal font.

![Untitled](https://user-images.githubusercontent.com/18547206/93556158-16934a80-f946-11ea-9265-281a66182eda.png)

**Comment by DarioViva42** [comment]
I also stumbled on this. Would be nice if they would add it.

**Comment by PhMajerus** [comment]
Oh, right, can't believe I forgot that one in #205!
@aaronbell, can you squeeze that one in? It's a last one of those characters that are only accessible to apps tinkering directly with the text video memory on legacy graphics cards, and needed for proper console compatibility.

**Comment by aaronbell** [comment]
<img width="302" alt="Screen Shot 2020-12-03 at 11 39 30 AM" src="https://user-images.githubusercontent.com/8460297/101079378-407b0700-355c-11eb-9ec2-ee3258373ca2.png">

?

**Comment by PhMajerus** [comment]
@aaronbell Yeah, that one ☺
Doesn't show with 2009.022, did you have it ready for next release or was it already in 2009.022 and something prevents it from rendering in conhost?

**Comment by aaronbell** [comment]
It is in my local repository for future release! :D

**Comment by PhMajerus** [comment]
@aaronbell Great, thanks!
And thanks @DLasher106 for spotting it.
