### ISSUE TITLE
Strange Stroke Overshot on certain font weights.

### ISSUE THREAD

**Issue by flowchartsman** [microsoft/cascadia-code#362]
# Environment

```none
Cascadia Code version number: 2009.14
Application (with version) used to display text: Fontbook
OS platform and version:

- Air: macOS Catalina 10.15.6 (19G2021)
- Pro Touchbar: macOS Mojave 10.14.6

Screen resolution:

- Air: 
  - Display Type: LCD
  - Resolution: 1440 x 900 (Widescreen eXtended Graphics Array Plus)
- Pro Touchbar:
  - Display Type: Built-In Retina LCD
  - Resolution: 2880 x 1800 Retina
```

# Steps to reproduce

Horizontal strokes and a couple of joins seem to overshoot and look strange for certain glyphs and weights when I preview the font in fontbook before installation. This appears on both my old Macbook Air _and_ my newer Macbook Pro. (images attached)

<img width="312" alt="Cascadia Code PL 2020-09-19 12-19-34" src="https://user-images.githubusercontent.com/926884/93671794-fb265d80-fa73-11ea-811e-2aac4cebeedb.png">

![image](https://user-images.githubusercontent.com/926884/93671849-6d973d80-fa74-11ea-872c-9f1440a2cabc.png)

# Expected behavior

No Bulges

# Actual behavior

Bulges

**Comment by aaronbell** [comment]
Thanks for the feedback! Out of interest, what does the font do in TextEdit *after* you’ve installed it?

**Comment by aaronbell** [comment]
So as far as I can tell, this is an issue with MacOS interpretation of variable fonts.  I'd suggest using the static instances (either OTF or TTF) to achieve better rendering. 

Thanks!

**Comment by aaronbell** [comment]
Sorry, I should clarify—macOS doesn't have an issue with variable fonts per se, but Cascadia Code happens to have outlines with coincident edges, thus causing the problem. This is unfortunately something that they should fix. As such, I have filed a bug report through their feedback tool.

**Comment by apodtele** [comment]
This confirms that macOS rasterizer is based on cumulative coverage, similar to FreeType.

**Comment by madig** [comment]
You may want to reopen this because https://github.com/microsoft/cascadia-code/pull/365#issuecomment-696395164 :D

**Comment by aaronbell** [comment]
Unfortunately the bug is still present even in the version with the correct flag set. So still Apple's problem :D
<img width="169" alt="Screenshot_9_21_20__3_19_PM" src="https://user-images.githubusercontent.com/8460297/93827313-df5ebb00-fc1d-11ea-9701-f9f8599ec9dd.png">

**Comment by chrissimpkins** [comment]
@aaronbell Do you know if this was addressed by Apple? If so, when?

**Comment by aaronbell** [comment]
@chrissimpkins Not to my knowledge. But I haven't seen the latest OS.

**Comment by pixelglow** [comment]
Check out the macOS 27 beta 😉 ...
