### ISSUE TITLE
Documentation Issue - no list of ligatures

### ISSUE THREAD

**Issue by tabatkins** [microsoft/cascadia-code#37]
I think I've looked at every file in the repo, and I don't see any documentation of what ligatures exist. I'd like to know what all I'm able to use. ^_^

**Comment by Qqwy** [comment]
For everyone who is eager, here is a short picture that shows most of the ligatures. I created it by looking in KFontViewer at the 'all characters' setting, and then trying to reproduce them.

Of course, a proper, nicely formatted list (especially one that also documents how you type the ligature) would be much app
![cascadia_code_characters_flattened](https://user-images.githubusercontent.com/5345745/65252534-681db500-daf9-11e9-972d-c45d16547dfe.png)
reciated :slightly_smiling_face: !

**Comment by SteveGilham** [comment]
The relevant key combinations are generally discoverable : most of them look like the characters just run together without spacing, and others just show naturally when you write some code e.g. ≡ is shown when you type === and ≢ for !== 

Not shown above,  are obvious ligatures when you type them out; -- may also be a ligature. There 's a <| ligature looking like ◁ to match the |> as ▷ for the F# coders ; and presumably <|| is a ligature too, though it's harder to tell (in the same way that [| and |], {| and |} are not immediately obvious as being rendered as ligatures), but the not-obviously-used-in-code =| doesn't have a ligature to go with |=

F# active pattern banana clips (| |) don't seem to have ligatures

**Comment by GregTheHun** [comment]
Wish there was an official list of ligatures too +1

**Comment by Sv443** [comment]
If this is gonna be added, might I propose that the corresponding language is added to the list / table as well? I'm seeing tons of char combos I've never seen before and I'd find it pretty interesting to know what their purpose is.

**Comment by aaronbell** [comment]
Hello! An official list of ligatures supported has been added to [the wiki](https://github.com/microsoft/cascadia-code/wiki/Coding-ligature-coverage).

**Comment by celynwalters** [comment]
Thanks!
I looked at @Qqwy's post and noticed `www` was missing.
I haven't checked completely for any others though.
