### ISSUE TITLE
"Dash-dotted line" (.-) disctracts in journal abbreviations

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/cascadia-code#372]
# Environment

```none
Cascadia Code version number:
Application (with version) used to display text: VS Code
OS platform and version: Windows 10
Screen resolution (i.e. 220dpi): I don't know (don't think that's relevant)
```

# Steps to reproduce

```J. Neuro.-Oncol.``` 

# Expected behavior

```J. Neuro.-Oncol.```  (with three identical dots)

# Actual behavior

![image](https://user-images.githubusercontent.com/12128514/94437814-90c19b80-019e-11eb-970f-9347db994323.png)

I find the second, raised dot very distracting, especially as I was trying to figure out whether that was a space (I turned whitespace markers off for the screenshot).

**Comment by aaronbell** [comment]
For your purposes, I suggest using “Cascadia Mono” which has the ligatures disabled. Unfortunately there is no way for the font to know that you’re trying to write a journal abbreviation or coding!

**Comment by bersbersbers** [comment]
> Unfortunately there is no way for the font to know that you’re trying to write a journal abbreviation or coding!

Certainly true ;) although this does come up in some form of coding - this is actually from a BibTeX file. My point was that maybe, `.-` comes up more often in real code than it is used for drawing lines (is that what this ligatures is actually used for?). Anyway, I get your point and will try Mono next, thank you!

**Comment by aaronbell** [comment]
Actually, the `.-` was added specifically for coding, not for drawing lines. :x
The main issue is that journal abbreviations and coding overlap in their structure!

Anyway, I think the Mono version will work better for you.
