### ISSUE TITLE
【Issue Report】Difficult to identify quotation marks 【U+201C】【U+201D】【U+2018】【U+2019】

### ISSUE THREAD

**Issue by byyxx128** [microsoft/cascadia-code#375]
Up to 2009.22, this issue still exists.

It is difficult to distinguish between 【U+201C】`“` and【U+201D】`”`, 【U+2018】`‘` and【U+2019】`’`.

In some cases, I must recognize and use them correctly, so it is currently a little inconvenient so far.

Actually, many fonts have this problem, but I hope cascadia can improve.

**Comment by nostodnayr** [comment]
@aaronbell the first update to the shape of curled quotes (#184) really helped with recognisability and these new glyphs are *even better*. Excellent work! 💜 I love them.

**Comment by aaronbell** [comment]
@nostodnayr glad you like them! I got really annoyed with their design and decided to toss them out the window and try again. 😄
