### ISSUE TITLE
GDEF glyph classes are incomplete

### ISSUE THREAD

**Issue by moyogo** [microsoft/cascadia-code#379]
# Environment

```none
Cascadia Code version number: 2009.22
Application (with version) used to display text: any that supports the mark feature
OS platform and version: any
Screen resolution (i.e. 220dpi):  any

Any other software?
```

# Steps to reproduce

Test the string "Ɔ̂ɔ̂ɪ̂ᴀ̂". None of the marks are placed on these base letters (and others) even though they have the correct anchors in the sources.
Test the string "m̥m̱m̲
". Theses combining marks will not be placed correctly even though the have the correct anchors in the sources.

# Expected behavior

The anchors in the sources should end up in the mark feature.

# Actual behavior

The anchors in the sources are not processed by ufo2ft when it generates the mark feature because the GDEF definition is incomplete.

![base](https://user-images.githubusercontent.com/1923747/95571900-122bf000-0a21-11eb-8927-e4d04678dd20.png)
![marks](https://user-images.githubusercontent.com/1923747/95571990-34257280-0a21-11eb-8f90-e2321a22318e.png)

**Comment by moyogo** [comment]
Can the GDEF definition be removed from the sources/features/ files? This would let ufo2ft generate the GDEF at build time.

**Comment by aaronbell** [comment]
Ah interesting. Seems Glyphs hadn't included them all :/. Yeah, removing the GDEF is fine with me.
