### ISSUE TITLE
'W' and 'w' glyphs appear to be set too low

### ISSUE THREAD

**Issue by astearns** [microsoft/cascadia-code#38]
# Environment

Cascadia Code version number: version used in Sept 19 2019 blog post
Application (with version) used to display text: Mac Firefox 69 and Chrome 76
OS platform and version: MacOSX 10.13.6
Screen resolution (i.e. 220dpi): 220dpi

# Steps to reproduce

1. Load the blog post https://devblogs.microsoft.com/commandline/cascadia-code/
2. Look closely at the first subhead (“Wait, what’s Cascadia Code?”)
3. Note how the baseline of the ‘W’ and ‘w’ characters fit with the rest of the line

# Expected behavior

The baseline of the Ws should match the surrounding characters (particularly the ‘i’ and ‘h’)

# Actual behavior

The baseline of the Ws appears to be a pixel too low.

![image](https://user-images.githubusercontent.com/1380751/65213972-25e97900-dae3-11e9-80d3-5c3a2a1c5ca1.png)

**Comment by astearns** [comment]
Hmm - the screenshot may need to be blown up to show the gap

<img width="167" alt="image" src="https://user-images.githubusercontent.com/1380751/65214062-6cd76e80-dae3-11e9-8cf9-fc6c6148f88b.png">

<img width="279" alt="image" src="https://user-images.githubusercontent.com/1380751/65214065-6fd25f00-dae3-11e9-83fc-cc3c4940afab.png">

**Comment by gaoxiaoning** [comment]
looks good,cool
