### ISSUE TITLE
ᶿ thetamod U+1DBF should be taller

### ISSUE THREAD

**Issue by moyogo** [microsoft/cascadia-code#381]
Regarding #357. The current thetamod ᶿ U+1DBF looks like obarredmod ᶱ U+1DB1.
Note: Glyphs.app GlyphData.xml calls ᶱ U+1DB1 barredomod instead of obarredmod, even though it calls ɵ U+0275 obarred.

The thetamod ᶿ U+1DBF should be vertically taller than obarredmod ᶱ U+1DB1.

If obarredmod ends up in the font, maybe consider adding its uppercase and lowercase equivalents: Obarred U+019F and obarred ɵ U+0275. Note: Again Glyphs app names them inconsistently: U+019F Ocenteredtilde, U+0275 obarred, U+1DB1 barredomod because their Unicode character names are not consistent either.
If added:
- Obarred U+019F can be a composite of Obarred-cy Ө U+04E8 (which is very slightly different from Theta Θ U+0398, a less than 5-units shift with the bar, maybe both Obarred and Obarred-cy should be composites of Theta)
- obarred ɵ U+0275 can be a composite of obarred-cy ө U+04E9.
- obarredmod ᶱ U+1DB1 is the current thetamod ᶿ U+1DBF.

# Environment

```none
Cascadia Code version number: 2009.22
Application (with version) used to display text: any
OS platform and version: any
Screen resolution (i.e. 220dpi): any

Any other software?
```

# Steps to reproduce
Use thetamod ᶿ for example in the test string "wʷθᶿ" or in the Comox/Sliammon "[gagat̓ᶿakʷup](https://www.firstvoices.com/explore/FV/sections/Data/Salish/Northern%20Salishan/Sliammon/learn/words/f9e32b18-8225-42b9-ba44-d0356109d009)".

# Expected behavior

The thetamod ᶿ should be taller than x-height modifier letters instead of the same vertical size.
# Actual behavior

The thetamod looks like an obarredmod ᶱ U+1DB1, a superscript obarred ɵ, instead of a superscript theta θ.

![Cascadia-thetamod](https://user-images.githubusercontent.com/1923747/95654740-f5afb680-0af9-11eb-8e70-97f7c6a3e1d0.png)
![gagat̓ᶿakʷup](https://user-images.githubusercontent.com/1923747/95654910-4ffd4700-0afb-11eb-930b-32c817e5b80b.png)

**Comment by aaronbell** [comment]
Thanks for the issue report. I had liked having the shorter thetamod to reduce its visual impact on long text runs of text, but I can understand how it could, as a result, be misinterpreted in other scenarios. Probably best to modify. 

Also, thanks for the info on obarred (and related). I don't think we have an explicit reason to include them now, but may do so in the future.
