### ISSUE TITLE
Fit nhookleft in advance width

### ISSUE THREAD

**Issue by moyogo** [microsoft/cascadia-code#382]
The current design of nhookleft U+0272 ɲ extends left of the left-side-bearing. This means it may clash with some glyphs on the left.

# Description of the new feature/enhancement (with images if possible)

Change the design of nhookleft to fit within the 1200-unit advance width, either reducing width of the whole glyph or reducing the width of the n-part.

Here’s 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/1923747/95757617-47de0c80-0c9f-11eb-83c1-1b361d4e3be1.png">
<img width="441" alt="image" src="https://user-images.githubusercontent.com/1923747/95757639-4f051a80-0c9f-11eb-9246-3fe72e8f8c37.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/1923747/95757676-5af0dc80-0c9f-11eb-81ec-e97f82ad0c11.png">

**Comment by aaronbell** [comment]
Can you provide a text sample that includes clashing?

**Comment by moyogo** [comment]
> Can you provide a text sample that includes clashing?

Good question. It doesn’t seem to clash with anything with the current scope of the font.

Some rare pairs may be very close, like /eng/nhookleft in Kimré words like heŋɲê or meŋɲê.
![meŋɲê](https://user-images.githubusercontent.com/1923747/95781451-bb931000-0cc5-11eb-9b0c-35a3399c695c.png)

More importantly, the left of the hook will be chopped off when it is the first character of a line in some contexts:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/1923747/95780933-bf726280-0cc4-11eb-8806-c98bbfbeb6b6.png">
