### ISSUE TITLE
Right and left arrow ligature doesn't show up on Visual Studio.

### ISSUE THREAD

**Issue by EV32114** [microsoft/cascadia-code#387]
#Environment

```none
Cascadia Code version number: 2009.22
Application (with version) used to display text: visual studio
OS platform and version: windows 10
Screen resolution (i.e. 220dpi): 1366 x 768 laptop
```

# Steps to reproduce

trying to type an arrow -> in visual studio with cascadia code. it works on other platforms such as vs code but not on vs. other ligatures in vs work.

# Actual behavior
![image](https://user-images.githubusercontent.com/63321707/97808970-b432a700-1c72-11eb-8d5d-f5baa426122d.png)

**Comment by DHowett** [comment]
This is a well-known issue in Visual Studio.

**Comment by EV32114** [comment]
> This is a well-known issue in Visual Studio.

Is there anything I can do about it?
