### ISSUE TITLE
Ligature for equality operator is not applied

### ISSUE THREAD

**Issue by mu88** [microsoft/cascadia-code#390]
# Environment

```none
Cascadia Code version number: 2009.021
Application (with version) used to display text: Visual Studio Enterprise 2019 v16.7.7 & Visual Studio Code v1.51.0
OS platform and version: Windows 10, v2004
Screen resolution (i.e. 220dpi): 1920x1080
```

# Steps to reproduce

Open any code file (`*.cs`, `*.bat*`, `*.js`) within Visual Studio or Visual Studio Code.

# Expected behavior

The equality operator `==` is rendered using the ligature where both equal signs are bound together.

# Actual behavior

The equality operator `==` is rendered as two independent equal signs. The ligature does not get applied.
![image](https://user-images.githubusercontent.com/4560672/98535242-10ef1c80-2286-11eb-800b-bcc1dad4235d.png)

Other ligatures like the arrow for a lambda statement are displayed as expected. However, greather than (>=) looks a bit ugly in Visual Studio.
![image](https://user-images.githubusercontent.com/4560672/98535203-ff0d7980-2285-11eb-860f-e33b9e2922cb.png)

**Comment by aaronbell** [comment]
Thanks for the feedback! 

So here's the thing, [formerly we had a merged version](https://github.com/microsoft/cascadia-code/issues/284) of `==`, but there were a number of concerns around recognition at a glance—I too also have had an issue with this. So I chose to split it, even in the ligature, to help with that. 

As for the `>=` glyph, it appears that you are not using font smoothing. Maybe try [Text Sharp](https://marketplace.visualstudio.com/items?itemName=SergeyVlasov.TextSharp) to adjust?

**Comment by mu88** [comment]
Okay, thank you for your response! At the moment, I'll stay with Fira Code, it seems more mature. But interesting project, I'll keep an eye on it.
