### ISSUE TITLE
Bug Report (Lua inequality ~= rendered counter-intuitive)

### ISSUE THREAD

**Issue by tsafin** [microsoft/cascadia-code#394]
# Environment

```none
Cascadia Code version number: 2009.021
Application (with version) used to display text: Windows Terminal 1.5.3242.0
OS platform and version: Windows 10 10.0.19041.630
Screen resolution (i.e. 220dpi): 

Any other software?
```

# Steps to reproduce

This is follow-up to the FiraCode report https://github.com/tonsky/FiraCode/issues/1171 which appeared to be already addressed in their modern releases. Some time ago they have ligature ~= which rendered confusingly as approximately equal. There is no language out there, where this ligature is correct, and there is language where it's shown counter-intuitively - Lua uses ~= as not equal.

# Expected behavior

For consistency reasons I'd prefer you to delete this ligature from Cascadia Code similar as they have deleted it from Fira Code.
https://github.com/tonsky/FiraCode/issues/381

# Actual behavior

![image](https://user-images.githubusercontent.com/4956130/102929103-0477f980-44ab-11eb-932a-2137a04fb4b0.png)

**Comment by DHowett** [comment]
You may be better served by using “Cascadia Mono”, which does not have ligatures, instead of playing _whack-a-mole_ with individual ligatures you find disagreeable 😄

**Comment by aaronbell** [comment]
Hm. You know it does strike me that the `~=` ligature is really only used in Lua and Matlab. 

Given the concerns both on FiraCode and here, perhaps it would be worth redesigning the ligature to look a bit more like the standard form.

**Comment by tsafin** [comment]
> 
> 
> You may be better served by using “Cascadia Mono”, which does not have ligatures, instead of playing _whack-a-mole_ with individual ligatures you find disagreeable 😄

Good point :) And I'll probably take this route. 

But point is still valid IMHO, it's very confusing to have here some incompatible set of ligatures in Fira Code and Cascadia Code...

**Comment by aaronbell** [comment]
@tsafin  they don’t ask our opinion ligature additions or deletions to Fira Code so it is natural that we may end up with inconsistent sets 😄
