### ISSUE TITLE
Different behaviors between powershell Core native app and windows terminal

### ISSUE THREAD

**Issue by trickyrat** [microsoft/cascadia-code#398]
# Environment

```none
Cascadia Code version number: 2009.022
Application (with version) used to display text: Powershell Core 7.1 and Windows Terminal
OS platform and version: Windows 10 1909 Simplify-Chinese Version
Screen resolution (i.e. 220dpi): 1080p

Any other software?

oh-my-posh
posh-git
```

# Steps to reproduce

Follow the  #296 steps. But there are two results.

# Expected behavior
Both apps should show the arrow.

# Actual behavior
Only Windows Terminal app shows the arrow
![figure1](https://user-images.githubusercontent.com/19605145/104158188-cd509480-5427-11eb-93f6-14a8e4d12390.png)

**Comment by DHowett** [comment]
This font does not have that arrow glyph. 

Windows Terminal supports font fallback, where glyphs from a different font will be substituted in if one is missing. 

The vintage Windows Console does not support font fallback.
