### ISSUE TITLE
Some ligatures aren't working in Windows Terminal

### ISSUE THREAD

**Issue by hansswolfs** [microsoft/cascadia-code#40]
I have installed Cascadia from Github here and in Visual Studio Code the ligatures seem to be working as expected.

In Windows Terminal though, some of them aren't working.
More in particular I have tested these: -> <- >= =>

![image](https://user-images.githubusercontent.com/7773447/65220861-fd9a5400-dabb-11e9-857a-ce9816839b8e.png)

**Comment by hanubeki** [comment]
I think it's because characters are rendered separately as they have different colors.
Try their ligatures in cmd which doesn't syntax highlight.

**Comment by stebet** [comment]
Like @hanubeki mentioned above, they actuallly do work, in a standard command prompt. It seems to be just PowerShell they do not work with.

![image](https://user-images.githubusercontent.com/661658/65227821-db530700-dab8-11e9-9a32-e5c0dba71d40.png)

**Comment by hansswolfs** [comment]
Checked and indeed you both are right 👍

Also don't think it's that big of a thing in PowerShell as well.

Thanks both for chiming in and clearing this out!
