### ISSUE TITLE
Better differentiate ° degree from º ordmasculine

### ISSUE THREAD

**Issue by moyogo** [microsoft/cascadia-code#400]
# Description of the new feature/enhancement
The ° degree and º ordmasculine glyphs are very similar and hard to distinguish at most sizes.

Here are C°Cºªoa  in weight=200,400,700, that's /C/degree/C/ordmasculine/ordfeminine/o/a:
![Cascadia-Code-700-C°Cºªoa-16](https://user-images.githubusercontent.com/1923747/104555743-4e7d7680-5636-11eb-9320-697bb0579384.png)
![Cascadia-Code-400-C°Cºªoa-16](https://user-images.githubusercontent.com/1923747/104555829-6b19ae80-5636-11eb-92e2-9764983df574.png)
![Cascadia-Code-200-C°Cºªoa-16](https://user-images.githubusercontent.com/1923747/104555747-4faea380-5636-11eb-91e5-aa2516ce892d.png)

# Proposed technical implementation details (optional)
Some possible changes to /degree:
- make is smaller
- make it have a thinner stroke especially in normal and bolder weights.
- make it sit at a different height from ordmasculine
Possible change to /ordmasculine:
- make it less round (although this one is hard with the proportions of other superscripts).

**Comment by schuelermine** [comment]
Are there any languages that distinguish/use both?

**Comment by VladimirMarkelov** [comment]
I see sometimes ordmasculine is underlined: https://en.wikipedia.org/wiki/Ordinal_indicator

**Comment by aaronbell** [comment]
There was another issue posted (#342) that discusses the Brazilian example. However, I'm not convinced adding the underline is necessary / good (see the discussion on the thread). 

In any case, I can experiment with options. Actually one that might be simplest is to just make the degree bigger. :)
