### ISSUE TITLE
Bug Report: Activate a python virtualenv in Windows Terminal has a broken icon/font in the prompt

### ISSUE THREAD

**Issue by ghorsey** [microsoft/cascadia-code#401]
# Environment

```none
Cascadia Code version number: 2009.22
Application (with version) used to display text: Windows Terminal 1.5.10271.0
OS platform and version: Windows 10 OS Build: 19042.746
Screen resolution (i.e. 220dpi): 2560 x 1440

Any other software?
```

# Steps to reproduce

1. On windows, inside Windows Terminal, download and setup python and configure a `virtualenv`
2. In the working directory activate the python virtualenv e.g. `.\.env\Scripts\activate` 

# Expected behavior

1. There to not be any broken icons in the prompt.

# Actual behavior

1. There is a square icon in the prompt next to the activate environment.
![image](https://user-images.githubusercontent.com/448706/106366530-548b7c80-62f1-11eb-9efd-b774eb7373db.png)

# Notes
I don't know if this is the correct repo for this defect or not.  Hopefully, I got it right.

**Comment by aaronbell** [comment]
Thanks for the feedback! The glyph that you're looking for is part of the full NerdFonts character set, which Cascadia Code does not support at current, and is covered by bug #194. As such, I am going to close this as a dupe against that issue.
