### ISSUE TITLE
Stylistic set for letter r

### ISSUE THREAD

**Issue by enriqueMartinezInter** [microsoft/cascadia-code#403]
I wish there would be the option to change the letter r from this
![image](https://user-images.githubusercontent.com/12499680/107166577-0246fd00-697c-11eb-8d5d-4549c9077322.png)

to something like this, where the end of the upper part of the character is pointing upwards
![image](https://user-images.githubusercontent.com/12499680/107166542-ee9b9680-697b-11eb-9336-73b08dc31f37.png)

It would make this letter look much more in tune with all the other sans-serif characters and make code much more readable and not distracting because of the shape of the upper part of r

**Comment by aaronbell** [comment]
Thanks for the feedback! 

I think it would help to explain a bit of the design process behind Cascadia Code. Cascadia is actually neither a serif, nor a sans-serif design. The primary technical goal of Cascadia is to ensure it renders clearly, and recognizably at small sizes on low resolutions screens. That meant optimizing less for internal consistency and rather designing almost on a character-by-character basis. 

As an example of this, I purposefully lowered the crossbar of the /f as (a) it helps open the whitespace within the letterform, and (b) makes it more recognizable as an /f, even though the design is quite unexpected. 

For the /r, amplifying the hook similarly served both purposes. (a) It helps absorb whitespace on the right side of the letterform so the right side doesn't feel so empty (Recursive gets away with it more by being an overall narrower design). (b) the hook of the /r has been scientifically shown to be the defining feature that helps with letter recognition for the /r. So by emphasizing the form, I aimed to make the letter more recongizable. 

OK! So there's been other requests for a more 'sans-serif' variant of this font (#83), and I'm definitely open to creating a stylistic set that has this sort of modification, but have to say that it isn't a top priority versus adding new features / capabilities. Anyway, I'm going to close this as a dupe against #83, but don't worry, I'm not forgetting you. :)
