### ISSUE TITLE
Powerline glyphs support

### ISSUE THREAD

**Issue by afucher** [microsoft/cascadia-code#405]
I didn't found any place that says all the glyphs supported by cascadia-code, is there any?

**Comment by kenmcd** [comment]
There is a `cascadia-code-characters.png` in the images folder, but I do not know if it is up-to-date.
[https://github.com/microsoft/cascadia-code/blob/main/images/cascadia-code-characters.png](https://github.com/microsoft/cascadia-code/blob/main/images/cascadia-code-characters.png)

**Comment by DHowett** [comment]
Cascadia Code/Mono PL support all of the symbols from [Powerline with Extra Symbols](https://github.com/ryanoasis/powerline-extra-symbols).
