### ISSUE TITLE
Misaligned arrows when creating infinite arrow using equals sign

### ISSUE THREAD

**Issue by dziban303** [microsoft/cascadia-code#406]
# Environment

```none
Cascadia Code version number: 2102.03
Application (with version) used to display text: Windows Terminal Preview 1.6.10412.0
OS platform and version: Win10 x64 20H2 19042.804
Screen resolution (i.e. 220dpi): 1920x1080, not sure about dpi

Any other software? Happens in Notepad++ v7.9. Also tested Cascadia Code PL 2102.03 with same results.
```

# Steps to reproduce

Add arrows with double angle brackets << or >> while drawing infinite arrows using equals signs ==
The segment with the arrows will appear vertically misaligned vis-à-vis the arrow shaft if the arrows are in the middle of the line body. 

E.g., the double arrows in this will appear to be a pixel or two below the rest of the arrow body:
<====<<====>>====|

# Expected behavior

Presumably the arrow will line up correctly with the rest of the line body.

# Actual behavior

The details of the misalignment (direction and pixel offset) vary depending on the font size. It's almost invisible at 14 point font, but particularly bad at 13. It seems to be perfect at a font size of 22. All other sizes I tested show it.

The effect does not seem to be present when using single angle bracket arrows < and >, and it doesn't seem to appear when using single or double angle brackets on a line made of minus symbols ----

Screenshot showing the behavior (Terminal Preview, Cascadia Code PL, font size 13):
![image](https://user-images.githubusercontent.com/7931765/107707869-2f4f2480-6c88-11eb-90c8-41608d390ff7.png)
It looks like the double arrow portions are a few pixels below the rest of the line.

Another screenshot, zoomed in (as above, but font size 16):
![image](https://user-images.githubusercontent.com/7931765/107706893-a388c880-6c86-11eb-8a05-393cd28cfb5f.png)
In this example, they're both above and below, but in different amounts depending on which direction the arrows are facing.

**Comment by aaronbell** [comment]
Thanks! I’ll take a look at the hunting of those glyphs.

**Comment by yg8ijvjvjv** [comment]
The only way to fix this is to use manual hinting, including horizontal and vertical instructions and the disable of anti-aliasing at single pixel stem sizes.
