### ISSUE TITLE
Doc: Add list of available stylistic sets

### ISSUE THREAD

**Issue by bew** [microsoft/cascadia-code#407]
Hello,

FiraCode has a little table of the available stylistic sets here:
https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets

For CascadiaCode, I see there is a huge file [sources/features/features_code.fea](https://github.com/microsoft/cascadia-code/blob/main/sources/features/features_code.fea) that lists a few feature sets, but I really have no idea nor the tools to udnerstand this file or preview what each does.

I would like to have a table showing what each stylistic set does.

Thank you :pray:

**Comment by aaronbell** [comment]
Sure, we can add something like that. Honestly, we haven't really implemented much of any stylistic set functionality so far. And I'm not sure who even uses them!

ss02: swaps `~=` with `!=`
ss19: swaps dotted zero with slash zero
ss20: swaps standard form of control characters with graphical ones. 

At some point we need to come up with a plan about these, but I, honestly, haven't seen much value in creating stylistic alternates so far. Haha.

**Comment by Zooce** [comment]
Wow I learned something with this today. I was looking for a way to get a slash zero instead of a dotted one, didn't realize I could change `"editor.fontLigatures": true` to `"editor.fontLigatures": "'ss19'"`. This is super useful! Thank you both!

**Comment by systo** [comment]
Adding a +1 to this.  'zero' also appears to be a shorthand for ss19.  Would be nice to know what all the options are similar to the aforementioned Fira Code table.

**Comment by aaronbell** [comment]
Just realized this is done now on the main README :)
