### ISSUE TITLE
Wrong design for U+2262

### ISSUE THREAD

**Issue by DLasher106** [microsoft/cascadia-code#408]
Version 2102.03

The Mathematical Operator U+2262 NOT IDENTICAL TO has four horizontal lines, similar to U+2263 STRICTLY EQUIVALENT TO. It should have three horizontal lines, similar to U+2261 IDENTICAL TO.

**Comment by aaronbell** [comment]
Huh. Interesting. I think I looked at another font as a reference for that glyph, but you're right, it should be just 3 lines. Will fix it! Thanks.
