### ISSUE TITLE
[2102.03 regression] Some ligatures appear weird (A. shrunk, B. truncated) in some Linux apps

### ISSUE THREAD

**Issue by ronjouch** [microsoft/cascadia-code#409]
# Environment

- Cascadia Code version number: 2102.03 (TTF)
  - This is a regression, problem didn't happen with 2009.22 (TTF).
  - Or maybe this isn't exactly a regression, but a newly-used font feature that is badly handled by apps. In this case, help welcome to narrow down on what I should tell to the app authors.
- Applications:
  - [Kitty](https://sw.kovidgoyal.net/kitty/) 0.19.3 (run with default config, except `font_family Cascadia Code`)
  - [Sublime Text](https://www.sublimetext.com/) v3210
- OS: Ubuntu Linux 20.10, fully up-to-date
- Xorg / GNOME Shell
- Screen resolution: 2560x1440
- Available for more debug info, please ask

# Steps to reproduce

1. Type text with ligatures
2. Look at rendered text

# Expected behavior

In some apps, some ligatures are rendered correctly:

1. No left/right truncating of the ligatures
2. Same font size as the no-ligatures text around

# Actual behavior

With test string `echo 'https://google.com' && echo 'a !== b' && echo '--version' && echo 'foo && bar'` (which has ligatures in `//`, `&&`, `!==`, `--`)

1. In Sublime Text, it looks like **some** ligatures takes too much horizontal space, resulting into truncating the right side of `!==` and`//` (but strangely, the other ligatures `&&` and `--` appear correct):
  ![screenshot_sublime_2021-02-12-12:53:51](https://user-images.githubusercontent.com/522085/107804168-92e15c80-6d31-11eb-8f7d-d2d9f825af27.png)
2. In Kitty, **all ligatures** seem to render at a smaller font size (half, maybe?), borking all ligatures [ `//`, `&&`, `!==`, `--` ]:
  ![screenshot_kitty_2021-02-12-12:52:55](https://user-images.githubusercontent.com/522085/107804177-95dc4d00-6d31-11eb-9488-84fd5811f999.png)
3. In other apps, ligatures are rendered perfectly. Here's a screenshot of a bit of this issue in Firefox and Chrome, forcing `Cascadia Code` usage through a CSS override:
    - Firefox 87.0a1 (2021-02-12):
      ![screenshot_firefox_2021-02-12-13:08:15](https://user-images.githubusercontent.com/522085/107805491-6e867f80-6d33-11eb-8d2b-3e6efdaad4d1.png)
    - Chrome 89.0.4389.9:
      ![screenshot_chrome_2021-02-12-13:13:00](https://user-images.githubusercontent.com/522085/107805989-29af1880-6d34-11eb-8f0d-957de88d0041.png)

**Comment by DHowett** [comment]
@aaronbell hmm.. the new calt code plus somebody trying to force the glyph to fit in its monospaced box?

**Comment by aaronbell** [comment]
Well isn't that interesting. 

I am not able to repro the issue in Sublime Text on Mac nor Windows. Can you try updating your install of Sublime Text and see if the bug is still present? I have Version 3.2.2 on both systems.

As for Kitty, I believe that this is a bug that Kitty needs to address. From what I can tell, it is misinterpreting the intent of the ligature, forcing it into a single character monowidth rather than allowing it to overflow. 

Looking at the Kitty Github, I see this bug: https://github.com/cyd01/KiTTY/issues/247 which indicates that there are known problems with ligature rendering. Can you add the sample images / feedback over there?

**Comment by ronjouch** [comment]
> I am not able to repro the issue in Sublime Text on Mac nor Windows. Can you try updating your install of Sublime Text and see if the bug is still present? I have Version 3.2.2 on both systems.

@aaronbell I'm running the latest Sublime Text dev build available in APT repos: build 3210.

> As for Kitty, I believe that this is a bug that Kitty needs to address. From what I can tell, it is misinterpreting the intent of the ligature, forcing it into a single character monowidth rather than allowing it to overflow.
> 
> Looking at the Kitty Github, I see this bug: [cyd01/KiTTY#247](https://github.com/cyd01/KiTTY/issues/247) which indicates that there are known problems with ligature rendering. Can you add the sample images / feedback over there?

@aaronbell This is the wrong Kitty 😄 (fun week with kitties, eh?).

- You linked to https://github.com/cyd01/KiTTY , *"a free telnet/ssh client for Windows "* ...
- ... but I'm using https://github.com/kovidgoyal/kitty , *"Cross-platform, fast, feature-rich, GPU based terminal "*.

Regardless, if you maintain it feels like an app bug rather than a font bug, can you help me precise what I should write to the Kitty author? (Potential mishandled font features? A clue of what changed between 2009.22 and 2102.03, etc). Thanks.

**Comment by aaronbell** [comment]
@ronjouch

With Sublime text, that sounds like a modification was made to Sublime Text between my version and the latest dev version that they introduced, and should resolve. 

🤦 Too many kitties about. But anywayyyyy. This is a known issue related to glyphs with negative right sidebearings: https://github.com/kovidgoyal/kitty/issues/2599 And unfortunately, it appears that the developer is not interested to fix it. So you'll have to take it up with them. 

Previously, the ligatures in Cascadia were "backwards looking", which is to say that in a three glyph run, such as `>>>`, the final `>` would contain the ligature with a negative left side bearing, and normal right side bearing. However, I changed it to be "forwards looking" which means that the first `>` contains the ligature as that allows me to be more efficient with my code and simplifies things quite a bit. But it appears that KiTTY can't deal with that. I don't really understand the dev's rationale.

**Comment by ronjouch** [comment]
> This is a known issue related to glyphs with negative right sidebearings: [kovidgoyal/kitty#2599](https://github.com/kovidgoyal/kitty/issues/2599) And unfortunately, it appears that the developer is not interested to fix it. So you'll have to take it up with them.
> 
> Previously, the ligatures in Cascadia were "backwards looking", which is to say that in a three glyph run, such as `>>>`, the final `>` would contain the ligature with a negative left side bearing, and normal right side bearing. However, I changed it to be "forwards looking" which means that the first `>` contains the ligature as that allows me to be more efficient with my code and simplifies things quite a bit. But it appears that KiTTY can't deal with that. I don't really understand the dev's rationale.

@aaronbell great, thanks for taking the time to explain what's going on, I'll talk to Kovid. With that, closing, will re-open / chime in as needed. Thanks for your work on the font!

**Comment by aaronbell** [comment]
@ronjouch BTW, on that Sublime issue, it appears that they've decided to change it so that a glyph can overlap the following glyph, but not two. Not sure why they'd implement that sort of change, but must have been a reason.

**Comment by aaronbell** [comment]
I found a bug listing here: https://forum.sublimetext.com/t/ligature-glyphs-cut-off-horizontally/53275/3

Seems that this has been reported already. They can also use Cascadia to test against.

**Comment by ronjouch** [comment]
@aaronbell over at https://github.com/kovidgoyal/kitty/issues/2599#issuecomment-778561725 , Kitty's author writes:

> This is a monospaced font. To render a ligature composed of three characters, the result needs to be three cells wide, not more. If kitty is rendering the result smaller it will be because the ligature does not fit in three cells. kitty does not care what direction ligatures are declared in.

Does that make sense?

**Comment by aaronbell** [comment]
@ronjouch no

**Comment by aaronbell** [comment]
Based on our conversation it appears this is an issue on Kitty’s side. Closing :)

**Comment by ronjouch** [comment]
> Based on our conversation it appears this is an issue on Kitty’s side. Closing :)

Filed Kitty bug https://github.com/kovidgoyal/kitty/issues/3313 . Thanks for all the help!

**Comment by aaronbell** [comment]
@ronjouch btw, in reading [other threads](https://github.com/MonoLisaFont/feedback/issues/36), it sounds like the ST4 beta has resolved this issue: https://aur.archlinux.org/packages/sublime-text-4-dev/

Don’t know if you can use it (as it requires a special license) but thought I’d mention.

**Comment by ronjouch** [comment]
> @ronjouch btw, in reading [other threads](https://github.com/MonoLisaFont/feedback/issues/36), it sounds like the ST4 beta has resolved this issue: https://aur.archlinux.org/packages/sublime-text-4-dev/
> 
> Don’t know if you can use it (as it requires a special license) but thought I’d mention.

@aaronbell thx, good to know. No, I cannot use it, I only have a regular ST3 license. Will try it when it's publicly available.

**Comment by ronjouch** [comment]
Kitty bug fixed in https://github.com/kovidgoyal/kitty/commit/912c46fc57362d3bd2a2f82b4b0a2ef939d6e1ec .
