### ISSUE TITLE
Small gaps are visible in new arrow ligatures in the Konsole terminal emulator

### ISSUE THREAD

**Issue by schuelermine** [microsoft/cascadia-code#414]
# Environment

```none
Cascadia Code version number: 2102.003
Application (with version) used to display text: konsole 20.08.2
Font size: 11pt
Font variant: Cascadia Code Roman
OS: Pop!_OS 20.10
with Linux 5.8.0-7642-generic and GNOME 3.38.3
Screen resolution (i.e. 220dpi): 1920px×1080px
apparently 344mm×194mm (96x96dpi) according to xrandr and xdpyinfo
UI Scaling: 100%
Hinting setting: Slight (changed & reset recently)
Antialiasing: Standard (changed & reset recently)
Further settings: Large fonts accessibility option is enabled
```

# Steps to reproduce

Get the terminal to render a combining arrow ligature

# Expected behavior

Dashes / equal signs join exactly

# Actual behavior

Small gaps

# Screenshot

![Screenshot from 2021-02-14 22-21-41](https://user-images.githubusercontent.com/48802534/107889652-70f3ff80-6f14-11eb-927b-506c736d5f34.png)

**Comment by aaronbell** [comment]
Do you see small gaps between box drawing characters?

for example `───────────┐`

**Comment by schuelermine** [comment]
> Do you see small gaps between box drawing characters?
> 
> for example `───────────┐`

No

![Screenshot from 2021-02-15 12-17-25](https://user-images.githubusercontent.com/48802534/107939985-d33a1800-6f87-11eb-9d64-a7fbb9e79c14.png)

**Comment by aaronbell** [comment]
Great! I’ll look into increasing the overlaps for the arrows.
