### ISSUE TITLE
Bug: Top bar of Serbian Cyrillic capital Dje Ђ in bold is too thin

### ISSUE THREAD

**Issue by NoxUltima** [microsoft/cascadia-code#418]
# Environment

```none
Cascadia Code version number: 2102.03
Application (with version) used to display text: any
OS platform and version: any
Screen resolution (i.e. 220dpi): any
```

# ~~Steps to reproduce~~

~~Put Ђ Ћ together in bold weight, now compare the two side by side. Notice the different widths of the top bars.~~

# Expected behavior 

Just a little bug/inconsistency i have to point out: In the bold weight, the top-bar of the Cyrillic Dje Ђ is thinner than that of Tshe Ћ. 

![20210220_140421.jpg](https://user-images.githubusercontent.com/16898444/108585666-8d64c180-7384-11eb-8207-1d46078a72de.jpg)

# Actual behavior

It renders like this in bold weight, and I'm sure this is because of interpolation, as the top bars in both letters are the same width in Regular and lighter weights.

![20210220_140408.jpg](https://user-images.githubusercontent.com/16898444/108585665-8b026780-7384-11eb-8f7d-57f64ab96f6d.jpg)

**Comment by aaronbell** [comment]
huh! Thanks. I'll fix that.

**Comment by bedriczwaleta** [comment]
In a future update, which will also add that things in #420, #421 and #422.

**Comment by DHowett** [comment]
Please keep comment threads on-topic. Thanks!

**Comment by yg8ijvjvjv** [comment]
This might have been caused by the emboldening used, because some emboldening parameters of autobold operations cause glitching like this.
