### ISSUE TITLE
Bug Report: <!-- (html comment start) ligature cuts off most of its < part

### ISSUE THREAD

**Issue by tabatkins** [microsoft/cascadia-code#42]
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: Sublime Text 3.2.1 Build 3207
OS platform and version: Linux (...whatever version you get by default in ChromeOS linux containers)
Screen resolution (i.e. 220dpi): Don't know, but this isn't hinting related so I don't think it matters.
```

# Steps to reproduce
Type `<!--` into a text document.

# Expected behavior
Cool html-comment-start ligature appears.

# Actual behavior
Ligature appears, but almost all of the `<` part is clipped. See screenshot:

![Screenshot 2019-09-19 at 4 32 03 PM](https://user-images.githubusercontent.com/682840/65223296-d9f6fe00-dafb-11e9-9e93-1fac1fed2b18.png)

This happens regardless of where in the line the `<!--` appears.

**Comment by bterlson** [comment]
@tabatkins FWIW it seems to work fine in vscode or Chrome on Windows:

![image](https://user-images.githubusercontent.com/11236/65262562-75b64900-dabf-11e9-821c-d59a24ebe1cd.png)

![image](https://user-images.githubusercontent.com/11236/65262738-d9407680-dabf-11e9-971d-802e5f4f2306.png)

**Comment by cinnamon-msft** [comment]
This appears to be a rendering issue with Sublime. I installed Sublime Text 3.2.1 Build 3207 on Windows and cannot repro this.
