### ISSUE TITLE
Fully support Subset1

### ISSUE THREAD

**Issue by aaronbell** [microsoft/cascadia-code#421]
Font is missing some characters for full coverage of [Subset1](https://unicodesubsets.miraheze.org/wiki/Subset1). Specifically `ḂḃḊḋḞḟṀṁṖṗṠṡṪṫ`

Split out of (#419)

**Comment by yg8ijvjvjv** [comment]
F001, F002, FFFD as well. So a total of 17 characters missing

**Comment by aaronbell** [comment]
In thinking through this issue, I do not see a purpose in supporting Traditional Irish typography, nor F001 / F002 (which are PUA). If there is a specific need for these in the future, I'm happy to reconsider. Closing for now
