### ISSUE TITLE
Tickmarks on new arrow ligatures at font size 24 in gedit

### ISSUE THREAD

**Issue by schuelermine** [microsoft/cascadia-code#423]
# Environment

```none
Cascadia Code version number: 2102.003
Application (with version) used to display text: gedit 3.38.0
Font size: 24
Font variant: Cascadia Code Roman
OS: Pop!_OS 20.10
with Linux 5.8.0-7642-generic and GNOME 3.38.3
Screen resolution (i.e. 220dpi): 1920px×1080px
apparently 344mm×194mm (96x96dpi) according to xrandr and xdpyinfo
UI Scaling: 100%
Hinting setting: Slight (changed & reset recently)
Antialiasing: Standard (changed & reset recently)
Further settings: Large fonts accessibility option is enabled
```

# Steps to reproduce

Type some combining arrow ligatures

# Expected behavior

Uniform arrow bodies

# Actual behavior

Small tickmarks

# Screenshot

![Screenshot from 2021-02-22 04-55-51](https://user-images.githubusercontent.com/48802534/108659631-11c15c80-74cb-11eb-86de-00d2367b1d9d.png)

**Comment by schuelermine** [comment]
This also occurs with the very short `/=` ligature (possibly others)

**Comment by aaronbell** [comment]
Unfortunately this is due to the rendering engine in your OS / application and not something that I can do anything about in the font. It is due to the overlapping glyphs 'doubling'. 

Sorry!

**Comment by schuelermine** [comment]
Ok

**Comment by schuelermine** [comment]
Ok
