### ISSUE TITLE
>=< ligature

### ISSUE THREAD

**Issue by schuelermine** [microsoft/cascadia-code#424]
# Description of the new feature/enhancement (with images if possible)

`>=<` should be a ligature similar to `>==<`, but with a short arrow body

**Comment by schuelermine** [comment]
Image of `>==<`
![Image of >==<](https://user-images.githubusercontent.com/48802534/108661542-57caf000-74cc-11eb-81f9-f942573905a9.png)

**Comment by aaronbell** [comment]
Per https://github.com/tonsky/FiraCode/issues/548, there are certain circumstances with MathML/XML where this ligature would cause confusion. 

`<mo>=</mo>​​​​​`

As such, a ligature like this would become problematic as it confuses content with structural elements. Sorry!
