### ISSUE TITLE
Misaligned box drawing characters

### ISSUE THREAD

**Issue by yg8ijvjvjv** [microsoft/cascadia-code#425]
The bounds of the box drawing characters should be aligned with the horizontal and vertical boundaries (left: 0, right: 1200, top: 2226, bottom: -480).

Currently, it is extremely misaligned:
* The top of U+2588 is 1980. It does not go all the way to the font top, leading to gaps when it is stacked vertically, though the left, right and bottom are correct.
* U+2580 and U+2584 do not match, and this issue is repeated for the quarter blocks. The half point should be the midpoint of font top and font bottom (873).
* U+2320 and U+2321 should match the box drawing lines, it is misaligned instead.
* U+253C and similar have an extremely glitchy bounding box: The top is 2309, the bottom is -891, the left is -106, the right is 1306. This exceeds vertical boundaries by a significant amount. In usable renderers, vertical boundaries are clipped. It should go to the horizontal and vertical boundaries mentioned in the beginning.
* The arrows are worth mentioning as well. In some environments, the arrows are box drawing, so having arrows be box drawing makes it possible to simulate such environments. It might seem similar to https://github.com/microsoft/cascadia-code/issues/302 however the box drawing arrows do not rely on ligatures to work and makes it possible vertically as well.

Demonstration:

```

┌─┬─┐ ╔═╦═╗ ╓─╥─╖ ╒═╤═╕ ○○○○◙◙◙◙••••◘◘◘◘
│ │ │ ║ ║ ║ ║ ║ ║ │ │ │ ○○○○◙◙◙◙••••◘◘◘◘
├─┼─┤ ╠═╬═╣ ╟─╫─╢ ╞═╪═╡ ○○○○◙◙◙◙••••◘◘◘◘
│ │ │ ║ ║ ║ ║ ║ ║ │ │ │ ○ ○ ◙ ◙ • • ◘ ◘ 
└─┴─┘ ╚═╩═╝ ╙─╨─╜ ╘═╧═╛  ○ ○ ◙ ◙ • • ◘ ◘ 

 ▀▄█                     ▘▝▀▖▌▞▛▗▚▐▜▄▙▟█
                                    
▀▀█▀▀               █   ▀▛▘       ▌ 
  █    ▄▄▄   ▄▄▄▄  ▀█▀   ▌ ▗▄ ▗▄▖▝▛ 
  █   █▄▄▄█ ▀▄▄▄    █    ▌ ▙▄▌▚▄  ▌ 
  █   ▀▄▄▄▄ ▄▄▄▄▀   ▀▄▀  ▌ ▚▄▖▄▄▘ ▚▘
                                    

⌠1              ░░▒▒▓▓██    ↑      ⇑   
│ x² dx = 1÷3   ░░▒▒▓▓██  ←─┼─→  ⇐═╬═⇒ 
⌡0              ░░▒▒▓▓██    ↓      ⇓   
```

![](https://i.imgur.com/ybUTgF5.png)

**Comment by bedriczwaleta** [comment]
Yeah, that looks tofu. Along with the next issue it is in process of being blacklisted I guess.

**Comment by yg8ijvjvjv** [comment]
The differences between Moshita Mono and Cascadia Mono:

![](https://i.imgur.com/d0Dq1zR.png)

Note: Moshita Mono is monospaced and never exceeds vertical boundaries, but it sometimes exceeds horizontal boundaries. Exceeding horizontal boundaries is allowed, but exceeding vertical boundaries will clip in usable renderers. Blacklisted fonts aren't funny.

**Comment by aaronbell** [comment]
I am happy to look into any issues with the box drawing characters. However, when you’re engaging in discourse on this repository, please follow our [code of conduct](https://opensource.microsoft.com/codeofconduct/). Thanks.

**Comment by yg8ijvjvjv** [comment]
You are [banned from Type Design](https://typedesign.miraheze.org/wiki/Banned_from_Type_Design).

**Comment by DHowett** [comment]
Please leave, and take your childish burn book with you.
