### ISSUE TITLE
The font is not monospaced

### ISSUE THREAD

**Issue by yg8ijvjvjv** [microsoft/cascadia-code#426]
The about section is misinformation, because some of the glyphs are zerowidth, such as combining characters.

Monospaced font: All glyphs have the width n  
Duospaced font: All glyphs have the width n or 2n  
Trispaced font: All glyphs have the width 0, n, or 2n  
Proportional font: The font is not monospaced, duospaced, or trispaced

**Comment by aaronbell** [comment]
There have been extensive discussions regarding if combining marks should be zero width in a monospace font. I believe that they should.

**Comment by bedriczwaleta** [comment]
I do not believe it. Fix the separate issues that I mentioned a few time ago.
Also it must be same width, or it will be legally declared proportional else.
