### ISSUE TITLE
Bug Report: parenthesis width changes when bold

### ISSUE THREAD

**Issue by bugadani** [microsoft/cascadia-code#43]
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: pyCharm
OS platform and version: windows 10, 18362.356
Screen resolution (i.e. 220dpi): multiple screens, 4k on 27" and FullHD 15"

Any other software? Issue not present in Notepad++ (but that editor does not display combined glyphs (e.g. !=) correctly so it may be irrelevant.
```

See attached images, anything right of ( gets pushed a few pixels when ( is highlighted. Same is true for [ and {

![image](https://user-images.githubusercontent.com/977627/65227186-81f2d400-dac8-11e9-8d48-b4958a5a45ee.png)
![image](https://user-images.githubusercontent.com/977627/65227203-8919e200-dac8-11e9-89e3-c8d8d6b42a77.png)

**Comment by ahardin13** [comment]
This also seems to apply to some letters.  It looks like "e" and "a" are pushing an extra pixel or 2 here as well.
![image](https://user-images.githubusercontent.com/12464376/65242435-fcfdbf80-dab3-11e9-9524-62f327c8c896.png)

**Comment by aaronbell** [comment]
At current the font does not have a paired bold, so you're seeing a mechanically generated 'fake bold' created by the software.
