### ISSUE TITLE
Invalid chars are there in prompt!

### ISSUE THREAD

**Issue by SMRHG** [microsoft/cascadia-code#430]
Hi guys
I need help;
Unfortunately, invalid chars are there in prompt!
Font face property is set to "Cascadia Code PL" in windows terminal JSON settings file but still ...
Thanks 🌻
![Capture](https://user-images.githubusercontent.com/59525413/109428027-56d51980-7a0a-11eb-9d48-83cd1bdbe410.PNG)

**Comment by aaronbell** [comment]
This is due to a lack of full nerd font coverage, covered by #194. Thanks!
