### ISSUE TITLE
Add Support for Command Prompt

### ISSUE THREAD

**Issue by l3afblow3r** [microsoft/cascadia-code#431]
Cascadia fonts do not appear in Command Prompt fonts list.
![image](https://user-images.githubusercontent.com/78950913/109711137-d267cf80-7b9e-11eb-8316-0151892eaea0.png)

**Comment by DHowett** [comment]
This is a bug in how the windows console host determines what fonts are available. We are not intending on changing that algorithm. We are investing our effort in _Windows Terminal_, which definitely does support Cascadia. :)

**Comment by l3afblow3r** [comment]
Out of frustration of Googling possible workarounds, I made my own registry hack to make this possible.
Maybe add it to the repo for those considering to do the same?

# Code
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console]
"InsertMode"=dword:00000001
"QuickEdit"=dword:00000001
"ScreenBufferSize"=dword:23280050
"WindowSize"=dword:00180050
"FontSize"=dword:00110000
"FontFamily"=dword:00000036
"FontWeight"=dword:00000190
"FaceName"="Cascadia Mono"
"CursorSize"=dword:00000064
"HistoryBufferSize"=dword:00000019
"NumberOfHistoryBuffers"=dword:00000004
"HistoryNoDup"=dword:00000000
"LineWrap"=dword:00000001
"FilterOnPaste"=dword:00000001
"CtrlKeyShortcutsDisabled"=dword:00000000
"LineSelection"=dword:00000001
"WindowAlpha"=dword:000000ff
"ForceV2"=dword:00000001
"ExtendedEditKey"=dword:00000001
"CursorType"=dword:00000000
"CursorColor"=dword:ffffffff
"InterceptCopyPaste"=dword:00000000
"TerminalScrolling"=dword:00000000

; Font Face: Cascadia Mono
; Font Size: 17
```

# Screenshot
![image](https://user-images.githubusercontent.com/78950913/109714477-c1b95880-7ba2-11eb-883c-401aa64f59c8.png)

**Comment by yg8ijvjvjv** [comment]
Cascadia Mono is not a monospaced font, it's proportional. That's why it's impossible.

**Comment by yg8ijvjvjv** [comment]
I recommend using only bitmap fonts in terminal/commandprompt environments.
