### ISSUE TITLE
Bug Report - Close square bracket misformed

### ISSUE THREAD

**Issue by Slugsie** [microsoft/cascadia-code#433]
# Environment

Cascadia Code version number:2102.025
Application (with version) used to display text:SQL Server Management Studio v15.0.18369.0
OS platform and version: Windows 10 v1909 (18363.1198)
Screen resolution (i.e. 220dpi): 96dpi

# Steps to reproduce

Set Environment Fonts and Colors, Font to Cascadia Mono, size 9.
A close square bracket ']' is misformed 

# Expected behavior

The close square brakcet should appear correctly.

# Actual behavior

The close square bracket is misformed on the upper corner.
![FontIssue](https://user-images.githubusercontent.com/3976650/110929420-d672ba80-831f-11eb-934e-68be1e432e8b.png)

The bracket display correctly at both 8 and 10 point settings.

**Comment by aaronbell** [comment]
Looks like it may be a hinting issue. Will take a look. Thanks!
