### ISSUE TITLE
Windows Terminal "loses" the Cascadia font

### ISSUE THREAD

**Issue by clayms** [microsoft/cascadia-code#434]
# Environment

```none
Cascadia Code version number:
Application (with version) used to display text:
OS platform and version:
Screen resolution (i.e. 220dpi): 

Any other software?
Windows Terminal Preview
Version: 1.7.572.0
```

# Steps to reproduce

Install Cascadia font 
Open Windows Terminal 

where settings.json has
```
"fontFace": "Cascadia Code PL"
```

# Expected behavior

Terminal opens with Cascadia font loaded.

# Actual behavior

```
Warning 

Unable to find the selected font "Cascadia Code PL".
"Consolas" has been selected instead.
Please either install the missing font or choose another one.
```

![image](https://user-images.githubusercontent.com/12793783/111831048-355aa580-88c5-11eb-9fc1-c9eda05817fa.png)

The first few times it works as expected.  Then, randomly, after weeks and many system restarts, it suddenly "loses" the font.  I have reinstalled the font multiple times.  Each time it works for some weeks, then suddenly "loses" the font again.  

How do I stop Windows Terminal from "losing" the Cascadia font?

Also, each time I reinstall the font, I get the following message:

![image](https://user-images.githubusercontent.com/12793783/111832012-99ca3480-88c6-11eb-8ad6-b1a90ae013be.png)

Yet, this solves the problem temporarily, until Windows Terminal "loses" the font again in a few weeks.

**Comment by DHowett** [comment]
You must “install for all users.” There is a bug in the windows font system.

**Comment by clayms** [comment]
@DHowett 
 I believe, I have done that before.

In any case, I just did that now.  We'll see.

**Comment by aaronbell** [comment]
As this is not specifically an issue with the font I'm going to go ahead and close this bug. But please feel free to follow up if you continue to have problems!
