### ISSUE TITLE
== Ligature not working

### ISSUE THREAD

**Issue by aaron-warren** [microsoft/cascadia-code#436]
# Environment

```none
Cascadia Code version number: 2102.25
Application (with version) used to display text: VSCode 1.54.3 and Windows Font Settings
OS platform and version: Windows 10 Pro 20H2
Screen resolution (i.e. 220dpi): 163 dpi

Any other software?
```

# Steps to reproduce

1. Install Cascadia Code
2. Type == in either vscode or the windows font preview

I tried this on a much older version of Cascadia code, version 1911.20 and it worked as expected. Does not work on the later versions.

# Expected behavior

1. Expect ligature for == to show

Version 2102.25
![](https://i.imgur.com/60Q93On.png)

Version 1911.20
![](https://i.imgur.com/IEiWBQH.png)

# Actual behavior

1. No ligature shows as seen in first image

Only happens for the == ligature as far as I know as ===, !=, etc all work fine.

**Comment by DHowett** [comment]
It was decided that the ligature for `==` was "too confusing" and it was given a special treatment where it is still divided but the equals signs are closer together.

**Comment by aaron-warren** [comment]
Ah that makes a lot of sense, thanks!
