### ISSUE TITLE
U+0045 LATIN CAPITAL LETTER E has uneven left side

### ISSUE THREAD

**Issue by schuelermine** [microsoft/cascadia-code#439]
# Environment

```none
Cascadia Code version number: 2102.003
Application (with version) used to display text: konsole 20.08.2
Font size: any
Font variant: Cascadia Code Roman
OS: Pop!_OS 20.10
    with Linux 5.8.0-7642-generic and GNOME 3.38.3
Screen resolution (i.e. 220dpi): 1920px×1080px
    344mm×194mm (96x96dpi) according to xrandr and xdpyinfo
UI Scaling: 100%
Hinting setting: Slight
Antialiasing: Standard
Further settings: Large fonts accessibility option is enabled
```

# Steps to reproduce

Type “E”

# Expected behavior

Completely straight left edge

# Actual behavior

Areas that meet "forks" of the E extend slightly further left

# Screenshots

![Screenshot from 2021-03-26 14-54-16](https://user-images.githubusercontent.com/48802534/112642440-9b09dd00-8e43-11eb-96ea-8ae1a9b90cc5.png)
![Screenshot from 2021-03-26 14-53-28](https://user-images.githubusercontent.com/48802534/112642447-9ba27380-8e43-11eb-8807-81431af1bf01.png)
![Screenshot from 2021-03-26 14-52-57](https://user-images.githubusercontent.com/48802534/112642449-9ba27380-8e43-11eb-9143-2e9ca80226e3.png)

**Comment by DHowett** [comment]
Three questions-

Does this still happen with 2102.025?

Which variant are you using? (Variable TTF, Static TTF, Static OTF)

What does “slight” hinting mean; does the rasterizer simply ignore half of the hinting instructions? 😉

**Comment by schuelermine** [comment]
> Does this still happen with 2102.025?

Will test.

> Which variant are you using? (Variable TTF, Static TTF, Static OTF)

Probably variable TTF, there's only one file.
![Screenshot from 2021-03-26 15-04-48](https://user-images.githubusercontent.com/48802534/112643408-a3164c80-8e44-11eb-953c-df299d99d6bd.png)


> What does “slight” hinting mean; does the rasterizer simply ignore half of the hinting instructions? :wink:

It's a setting in the GNOME Tweaks app, I don't know if it affects how Konsole renders text, so I included it.
![Screenshot from 2021-03-26 15-03-25](https://user-images.githubusercontent.com/48802534/112643287-7f530680-8e44-11eb-8296-94ce213ad13e.png)

**Comment by schuelermine** [comment]
Update: Yes, still occurs with .025

**Comment by aaronbell** [comment]
What version of FreeType are you running?

**Comment by aaronbell** [comment]
Just adding a bit more context here. FreeType (and MacOS IIRC) have problems with rendering overlapping paths wherein if two separate paths are colinear, the rendering is 'doubled'. So in your case, the light edge of the /E suddenly becomes full dark. 

We [ran into this bug previously](https://github.com/microsoft/cascadia-code/issues/350) and implemented something of a [hacky fix](https://github.com/microsoft/cascadia-code/commit/f9145d53e888f2c428784126b1745f50ffd741f6) to apply OVERLAP_SIMPLE and OVERLAP_COMPOUND in the variable font to change FreeType's rendering mode and avoid this problem. However, it requires a newer version of FreeType (>=2.10.3) to work, I believe.

**Comment by schuelermine** [comment]
I don't know, and I'm currently not on the machine where this big occured,
I'll get back to you as soon as I can.

**Comment by schuelermine** [comment]
> What version of FreeType are you running?

2.10.2.

Output of `aptitude show libfreetype6`:
```
Package: libfreetype6
Version: 2.10.2+dfsg-3ubuntu1
```

**Comment by aaronbell** [comment]
Ah well there you go. You will need to update to a newer version of FreeType.

**Comment by aaronbell** [comment]
Anyway going to close this as it isn’t an issue with cascadia :)

**Comment by apodtele** [comment]
> 
> 
> > What version of FreeType are you running?
> 
> 2.10.2.
> 
> Output of `aptitude show libfreetype6`:
> 
> ```
> Package: libfreetype6
> Version: 2.10.2+dfsg-3ubuntu1
> ```

Next Ubuntu 21.04 will come with a good FreeType version on April 22.
