### ISSUE TITLE
Extrange glyphs on my terminal

### ISSUE THREAD

**Issue by JAndre761** [microsoft/cascadia-code#440]
Hello guys,

I found this article https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup and followed it (didn't install anything else than what the article says) to set up Powerline, Posh-Git and Oh-My-Posh. But I I'm not sure if what my terminal is printing is an error with the glyphs. 

![image](https://user-images.githubusercontent.com/32041983/112726386-1e323e00-8eeb-11eb-8ea9-74d4adef3569.png)

Does it happen to anyone else? I'm using windows 10 and my PS: 5.1.19041.868

**Comment by aaronbell** [comment]
Unfortunately oh my posh requires glyphs present in the full nerd fonts set, which is unfortunately not supported at this time.

See #194
