### ISSUE TITLE
Double quote doesn't work on vscode

### ISSUE THREAD

**Issue by shoaibsharif** [microsoft/cascadia-code#441]
# Environment

```none
Cascadia Code version number: 2102.25
Application (with version) used to display text: VSCode(1.54.3)
OS platform and version: MacOS Big Sur (11.2.3)
Screen resolution (i.e. 220dpi): 1440p

Any other software?
```

# Steps to reproduce

I just followed installation instruction, but the double quote doesn't work on my VSCode or JetBrain. 
It works on Microsoft Word. 

# Expected behavior

According to new release, I should see the new curly quotes.

# Actual behavior

I can't see the double quote. When I change my font face, I see this:
![double_quote_issue](https://user-images.githubusercontent.com/29075110/112791682-e88a7380-9016-11eb-8f23-d853599a435b.png).

**Comment by DHowett** [comment]
You should only see the curly quotes in a document that contains “smart quotes”. It is not a replacement for the standard ASCII quote character, which is the sort you find in JSON documents and source code.
