### ISSUE TITLE
[Documentation Issue] What is "static"??

### ISSUE THREAD

**Issue by WrongBit** [microsoft/cascadia-code#446]
I downloaded 'release' ZIP, opened `TTF` folder and see 4 fonts (I know what they mean), but along with 'em I see folder `static` w/o any explanation what is it. And inside I see many variations of fonts. What I should install?? Documentation lacks any explanation.

BTW after installing ttf\CascadiaMonoPL.ttf I found that font is too heavy (bold).

**Comment by aaronbell** [comment]
You might have missed this wiki page which discusses that term "static" is in relation to "variable": https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code

- `ttf variable:` we recommend this version for all users, particularly those on Windows or any other OS that employs TrueType hinting. It offers the greatest diversity of weight options (anything from 200-700).
- `ttf static:` in the rare situation where the above variable font version is not supported, or a singular weight is preferred to the entire range, static formats are supplied. However, please note they do not have the same degree of hinting quality as the variable font versions.

If you find the base form too heavy, I suggest changing the font weight / style to one of the lighter instances.

**Comment by WrongBit** [comment]
@aaronbell : thank you for explanation! But it's still issue with docs.
1. When I open "home page" of the font, I see just README page. Nobody will WASTE time in wikis just to realize "what is static?".
2. Since README already has explanation for "code" and "mono" variations, IT IS VERY PLACE to say additionally what is "static" version. Not so hard to do, right?

Related heavy letters: I tried font in Visual Studio and it has no option "light" or "lighter" - just single font name. I guess I must remove "variable" font and install all those "static" versions, right?

**Comment by aaronbell** [comment]
> Nobody will WASTE time in wikis just to realize "what is static?"

This hasn't been a problem in 1.5 years of this font being available on Github :). What is provided in the README is quick overview and common issues (which Code vs Mono has been), and there's a link that says "for more details check the wiki".

> I tried font in Visual Studio and it has no option "light" or "lighter" - just single font name. I guess I must remove "variable" font and install all those "static" versions, right?

My understanding is that the variable font is usable in Visual Studio as is, but if you are not able to figure out how to adjust the font weight, then yes, the static instances might be your best bet.
