### ISSUE TITLE
Box-drawing glyphs leave gaps between lines

### ISSUE THREAD

**Issue by cerebrate** [microsoft/cascadia-code#45]
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: Windows Terminal 0.4.2382.0
OS platform and version: Windows 10, Insider build 18980
```

# Steps to reproduce

1. Open Windows Terminal.
2. Switch the font in use to Cascadia Code in the Settings.
3. Run a program which displays lines drawn with box-drawing glyphs (for example, `pstree`).

# Expected behavior

Drawn lines should be continuous.

# Actual behavior

This shows the result of switching Windows Terminal to Cascadia Code 10, having previously been using Consolas 10, with which font the lines in the directory tree and at the right of the prompt _do_ appear continuous. As can be seen, this is not the case with Cascadia.

![linedrawing-cascadia](https://user-images.githubusercontent.com/371623/65227707-bf3a7000-da8e-11e9-8c8f-275da0844b43.jpg)

**Comment by ExE-Boss** [comment]
This is probably related to/caused by #11.

**Comment by cerebrate** [comment]
Hm, yeah. You're right; in clients that don't do font substitution, the glyphs don't show up at all.

Closing, then, as dupe of #11.
