### ISSUE TITLE
Bug Report : Glyphs for Windows Terminal and Oh-My-Posh Integration

### ISSUE THREAD

**Issue by mahyarmirrashed** [microsoft/cascadia-code#452]
# Environment

```none
Cascadia Code version number: 2102.025
Application (with version) used to display text: Windows Terminal 1.7.1033.0, PowerShell 5.1.19041.906
OS platform and version: Windows 10 Home, Build No. 19042.928
Screen resolution (i.e. 220dpi): 1920 x 1080 on HP Pavillion x360 15-dqxxxxx

Any other software?
```

# Steps to reproduce

1. Download Git.
2. Clone a Git Repo.
3. `touch` a file.
4. Follow https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup.
a. Install `Cascadia Code PL` for all users.
b. Enter into text editor and make necessary changes to settings.json file as outlined.
5. Restart the shell and navigate back.

# Expected behavior

Honestly, not entirely sure what glyphs to expect but they are certainly not supposed to be empty squares.

# Actual behavior

![image](https://user-images.githubusercontent.com/59240843/116951145-c22aaa00-ac4c-11eb-8a69-cc7698db7918.png)
Two, possibly distinct, square glyphs appear. I have tried searching online and in the issues but either they were hidden or non-existent because no one else has the same issue.

**Comment by 73VW** [comment]
Same problem with `powerline` theme and `Cascadia Code PL` font.

![image](https://user-images.githubusercontent.com/24651698/117013818-80533f80-acf0-11eb-8842-5b73436fccb8.png)

**Comment by aaronbell** [comment]
Thanks for the report, and a known issue. This is covered by #194 (and others, like #440).
