### ISSUE TITLE
Bug Report (Cascadia Code PL) `-|` is render wierd

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/cascadia-code#457]
`-|`

![image](https://user-images.githubusercontent.com/49113249/118353328-58899480-b598-11eb-9cf3-e0013d8de5be.png)

# Environment

```none
Cascadia Code version number:
Application (with version) used to display text:
OS platform and version:
Screen resolution (i.e. 220dpi): 

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by aaronbell** [comment]
That is expected behavior as `-|` is part of the 'infinite line' ligature set. What is the context of your use?

**Comment by HomyeeKing** [comment]
it's ok if it's intended,  I set it as my IDE font-family, just a little wierd during the code review such as  RegExp
not a big deal, I'll close this
