### ISSUE TITLE
Better alignment of ligatures and non-ligatures

### ISSUE THREAD

**Issue by erikdarlingdata** [microsoft/cascadia-code#458]
# Description of the new feature/enhancement (with images if possible)
With Cascadia Code, ligatures cause some odd misalignment in SQL Server Management Studio

![image](https://user-images.githubusercontent.com/2136037/118871427-8f6feb00-b8b5-11eb-9025-d4573bf6d633.png)

It also appears that not equal to is larger than other inequality ligatures:

![image](https://user-images.githubusercontent.com/2136037/118871619-ba5a3f00-b8b5-11eb-9c23-00877e2d857d.png)

# Proposed technical implementation details (optional)
These should all be the same size, and/or have better alignment

**Comment by aaronbell** [comment]
Well, `>=` *is* bigger because it takes up two widths, whereas `<` only uses one width. 

I'd suggest trying out Cascadia Mono, which has the ligatures disabled, as you're always going to have this kind of misalignment.
