### ISSUE TITLE
Bug Report: Greater than and less than ( <> ) looks bad

### ISSUE THREAD

**Issue by drakeaan** [microsoft/cascadia-code#459]
# Environment

```none
Cascadia Code version number: 2102.25
Application (with version) used to display text: 
- Visual Studio 2019 (16.9.6)
- Visual Studio Code (1.56.2)
OS platform and version: Windows 10 (version 19043.985)
Screen resolution: 1920x1080 with DPI=100%
```

# Steps to reproduce

Install `CascadiaCode.ttf (variable)` for all users. Then, in Visual Studio or Visual Studio Code simply type "<>" like this:

![Git-GtLtTest](https://user-images.githubusercontent.com/14839256/119002437-2a87c400-b98d-11eb-85cb-41d49c4091b0.png)

# Expected behavior

Greater than or Less than, and especially when typing as a placeholder before filling in the details of the Type, should display better and have a more distinct space between them.

# Actual behavior

Greater than and Less than next to each other displays badly. Instead of any spacing, it looks like a diamond.

**Comment by DHowett** [comment]
This is because it is a ligature. If you would rather not have ligatures, you may want to switch to Cascadia Mono. :smile:

**Comment by aaronbell** [comment]
Yup! Give a try to Cascadia Mono. The behavior you described is by design for Cascadia Code
