### ISSUE TITLE
== ligature

### ISSUE THREAD

**Issue by alanbirtles** [microsoft/cascadia-code#46]
The distinction between "=" and "==" is quite subtle which could be dangerous for c++ code, maybe a 3 line equals for the "==" ligature could be more appropriate?

**Comment by vianchen** [comment]
Just to illustrate this, here's what `=` and `==` look like with Cascadia and Fira Code:

![Snipaste_2019-09-19_18-28-33](https://user-images.githubusercontent.com/23373137/65236585-81c7f800-db0b-11e9-810b-52b1c5110d0b.png)

![Snipaste_2019-09-19_18-28-50](https://user-images.githubusercontent.com/23373137/65236671-aae88880-db0b-11e9-9cd3-f9252a3a9e22.png)

**Comment by hernancmartinez** [comment]
+1

**Comment by DHowett-MSFT** [comment]
@hernancmartinez Please use the voting buttons; commenting `+1` e-mails the whole team.

![image](https://user-images.githubusercontent.com/14316954/65263147-c8443500-dac0-11e9-8e10-15c59b5afd2a.png)

**Comment by hernancmartinez** [comment]
Done !

**Comment by fmeyertoens** [comment]
Three line equals already represents triple equals (===) for languages like Javascript.

**Comment by Itsey** [comment]
Maybe thicker bars or something, this just threw me while altering my code I turned an equality check into an assignment and was puzzled by the red squiggle, upon full compile it became obvious what was up but there are circumstances where this particular ligature causes confusion.

**Comment by ZiyiLikeIt** [comment]
It's really hard for me to distinguish the = and == using this font. So I just turn the ligature off. Please do something to fix it.
