### ISSUE TITLE
VIM NerdTree icons break with CascadiaCodePL.ttf

### ISSUE THREAD

**Issue by codeasashu** [microsoft/cascadia-code#460]
# Environment

```none
Cascadia Code version number: 2102.25
Application (with version) used to display text: iTerm2 (Build 3.4.6)
OS platform and version: MacOS BigSur v11.3.1 (20E241)
Screen resolution (i.e. 220dpi): 2560 × 1600

Any other software? 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  1 2021 08:37:51)
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
```

# Steps to reproduce

After installing the font:

1. Open iTerm2, Goto preferences > Profiles > Text and select CascadiaCodePL font
2. Create a folder somewhere
3. open vim in the folder with nerdtree plugin installed. See the folder icon

# Expected behavior

The folder icon should be displayed as a powerline font. See image below (Hack Nerd Mono font):
![image](https://user-images.githubusercontent.com/1492350/119193651-8cd0e980-ba9f-11eb-8be7-6b43e91287d5.png)
The folder icon is being displayed

# Actual behavior

The folder icon is not being displayed
![image](https://user-images.githubusercontent.com/1492350/119194033-1f718880-baa0-11eb-92c8-24ba889c600d.png)

**Comment by DHowett** [comment]
Cascadia Code PL is not a "nerd font."
