### ISSUE TITLE
2105.24 - Italic Style Groups and Font File Names Incorrect

### ISSUE THREAD

**Issue by kenmcd** [microsoft/cascadia-code#465]
The style groups are incorrect in the new Italic fonts.
This causes the all the Italic fonts to be in their own style group rather than linked with the related Regular.
Also causes the font file names to be confused.

And the Italic typographic family is also different.

**Comment by DHowett** [comment]
Sorry, what platform is this on? Windows seems to tolerate it... and link the fonts just fine!

**Comment by kenmcd** [comment]
Windows 10.
I am seeing the Italic style groups like this:
Cascadia Code Italic - which should be Cascadia Code
Cascadia Mono Italic - which should be Cascadia Mono

Same with the typographic family
Cascadia Code Italic
Cascadia Mono Italic

**Comment by madig** [comment]
There is something going on indeed. The Italic fonts have "Italic" in the family name when they shouldn't. See e.g. CascadiaCodeItalic-ExtraLightItalic.otf, `name` table ID 16: "Cascadia Code Italic" -- ID 16, when present, should just be "Cascadia Code" in all statics. This means that fontconfig on Linux does not pick the Italic font up as the italic of the regular.

**Comment by kenmcd** [comment]
> This means that fontconfig on Linux does not pick the Italic font up as the italic of the regular.

These will not work properly in LibreOffice on Linux or Windows.

**Comment by aaronbell** [comment]
Interesting. It appears that the static instances are not propagating properly. While I investigate that, I suggest using the variable font version which works as expected.
