### ISSUE TITLE
2105.24 /fi interpolation issue

### ISSUE THREAD

**Issue by moyogo** [microsoft/cascadia-code#469]
# Environment

Any other software?

# Steps to reproduce

Interpolate the /fi ligature glyph.

# Expected behavior

The i part of the fi ligature glyph should interpolate properly.

# Actual behavior

The i part of the fi ligature glyph doesn't interpolate properly.
<img width="348" alt="image" src="https://user-images.githubusercontent.com/1923747/119666710-86d76180-be2d-11eb-974e-68e07d0532c1.png">

**Comment by aaronbell** [comment]
Ah, thanks. That ligature shouldn't ever actually show up (assuming OT is working), but I'll fix that.
