### ISSUE TITLE
Some cursive lowercase glyphs appear to have a different slant than the others

### ISSUE THREAD

**Issue by JobLeonard** [microsoft/cascadia-code#470]
# Environment

```none
Cascadia Code version number: 2105.24
Application (with version) used to display text: not relevant
OS platform and version: not relevant
Screen resolution (i.e. 220dpi): not relevant
```

# Steps to reproduce

1. Use Cascadia Code v2105.24
2. Write something that involves a lowercase L, lowercase Y, and possibly some others

# Expected behavior

A consistent slant for every glyph (except for block glyphs and similar "graphic" ones)

# Actual behavior

I will use this screenshot of a doc comment to illustrate:

![image](https://user-images.githubusercontent.com/259840/119688596-67016700-be48-11eb-9650-0be8e66ea198.png)

In an attempt to highlight the differences in perceived slants I added vertical pipes between the lines, while forcing my editor to use a small line height.

So first of all, I want to acknowledge that this is somewhat subjective, and that I might be alone in "reading" these glyphs this way. Having said that, to me the cursive lowercase L feels almost straight. The other glyphs appear to "align" with the slanted vertical pipe characters above and below their lines (although the lowercase Y also appears a bit less slanted than the rest of the glyphs, but it's not as jarring). 

I know this is very nitpicky, and I don't want to criticize the designers of the cursive set - I think their design is cute overall, and I'm aware that font design is an art as much as a science, and more importantly that it's an incredible hassle to get it to "feel" just right. However, when quickly skimming text any cursive L's in the text really stand out a lot to me, kind of like how a single bold glyph among non-bold glyphs would stand out. They don't "disappear" into the whole word but break into individual characters, if that makes sense. And I think it's largely because of this difference in (perceived) slant.

(on a similar note the lowercase R breaks with the x-height in a way that makes `dendrogram` read a bit "wobbly", but that's probably overdoing the nitpicking)

**Comment by aaronbell** [comment]
Thanks for the response! I honestly haven't found that the /l to feel really 'out of slope' with the other letters, but I'll take another look at it. 

The /r in particular is really challenging because without that little bit sticking up on the top left, it can be mistaken for an /n at a glance. But then it makes the letter feel taller, especially if the top right part of the /r is at the x-height. So there's a degree of balance there. These cursive forms can be surprisingly tough!

**Comment by genesi5** [comment]
![image](https://user-images.githubusercontent.com/25093320/120176667-3b97c700-c210-11eb-911d-899bcb1becd4.png)
Check whether if it is set like this/. That helped me.

**Comment by JobLeonard** [comment]
@genesi5: was your reply meant to go below #468, where people explicitly ask for a non-cursive font version?

If not: I'm seeing the cursive variant glyphs just fine, I'm just nitpicking a bit on the style of an individual one (but the attempt to help is still appreciated!)
