### ISSUE TITLE
2105.24 - Italic numbersign_question.liga interpolation issue

### ISSUE THREAD

**Issue by kenmcd** [microsoft/cascadia-code#471]
Appears the element order is different in the Italic ExtraLight master. 

![2021-05-26_9-32-04](https://user-images.githubusercontent.com/844920/119698162-d43fd880-be05-11eb-82d6-b1732c1b8c10.gif)

**Comment by aaronbell** [comment]
Huh! Not sure how that snuck through. Thanks.
