### ISSUE TITLE
2105.24 - Italic dollar.BRACKET.600 interpolation issue

### ISSUE THREAD

**Issue by kenmcd** [microsoft/cascadia-code#473]
![2021-05-26_9-44-31](https://user-images.githubusercontent.com/844920/119699951-8a57f200-be07-11eb-8984-8011b22fae9e.gif)

**Comment by DHowett** [comment]
HA! I love it!

**Comment by DHowett** [comment]
I believe in this specific case, however, the version of $ with the divided line is only used in weights >=535. Still, it is funny.

**Comment by aaronbell** [comment]
Man. Usually hinting catches all of this sort of thing if I've missed it in the source file. Growl!

**Comment by kenmcd** [comment]
It is truly amazing that something this complex gets built with just a few easily fixable minor bugs.
