### ISSUE TITLE
2105.24 - Regular - less_less_hyphen_middle.seq interpolation issue

### ISSUE THREAD

**Issue by kenmcd** [microsoft/cascadia-code#479]
![Regular - 2021-05-26_10-57-52](https://user-images.githubusercontent.com/844920/119710639-6ef2e400-be13-11eb-9da5-df25487dff28.gif)

**Comment by aaronbell** [comment]
Huh. It looks fine in the source. Not sure why you're seeing it as problematic.

**Comment by aaronbell** [comment]
Ah, this is the Regular. These will be updated in mid-June when we do the next release.
