### ISSUE TITLE
Increase the slope of the first stroke for "1"

### ISSUE THREAD

**Issue by Shinerising** [microsoft/cascadia-code#48]
# Description of the new feature/enhancement (with images if possible)

The number "1" is hard to distinguish due to its first stroke is almost horizontal. It looks really like "l" rendered by other font.

![Screen Shot 2019-09-19 at 5 05 53 PM](https://user-images.githubusercontent.com/2839883/65230515-93f06900-db00-11e9-9bb7-3c28c8e94118.png)

This issue could be more obvious when using low-density screens.

![Screen Shot 2019-09-19 at 5 17 51 PM](https://user-images.githubusercontent.com/2839883/65230988-7243b180-db01-11e9-891a-eb7436da5a2c.png)

# Proposed technical implementation details (optional)

Please increase the slope of the first stroke, like so many other fonts did:(below is Menlo)

![Screen Shot 2019-09-19 at 5 06 45 PM](https://user-images.githubusercontent.com/2839883/65230679-dca82200-db00-11e9-816f-20bfeec31531.png)

**Comment by mdtauk** [comment]
I agree with this, I think it will make the number more distinct from the lowercase **l**

![image](https://user-images.githubusercontent.com/7389110/65379375-d6f83b00-dcbe-11e9-855e-f31d744bbe9f.png)

**Comment by Shinerising** [comment]
The latest release ( d3b1ada ) has fixed this issue.
