### ISSUE TITLE
No weigths in JetBrains 2021 typography settings panel

### ISSUE THREAD

**Issue by J3Rik0** [microsoft/cascadia-code#481]
# Environment

```none
Cascadia Code version number: 2105.024
Application (with version) used to display text: Webstorm 2021.1.1
OS platform and version: Windows 10
Screen resolution (i.e. 220dpi): 4k/163dpi

Any other software?
```

# Expected behavior

Main weight and Bold weight dropdowns under the Typography Settings section should display all of the weigths

# Actual behavior

The panel shows only Roman weight
![image](https://user-images.githubusercontent.com/1242984/119738108-d7c87380-be88-11eb-88ef-3721c4cd50e8.png)

This is happening with the latest italics realease, so I'm guessing it's losing some info during the build step as it was working just fine prior to the update.

**Comment by DHowett** [comment]
Are you using the static fonts or the variable ones? OTF or TTF?

**Comment by J3Rik0** [comment]
variable, TTF

**Comment by J3Rik0** [comment]
If I use the statics I lose the ligatures (expected) and the italics (unexpected), as expected they are all separate, including the italics though

**Comment by DHowett** [comment]
Huh. It's not actually expected that you lose the ligatures with the static version.

**Comment by J3Rik0** [comment]
Oh, my bad, I cycled through them and set it to mono without realizing it, but the italics shouldn't be separate, should they?
![image](https://user-images.githubusercontent.com/1242984/119739565-18c18780-be8b-11eb-9e64-ece89d85f9e5.png)

**Comment by J3Rik0** [comment]
Yeah, the italics shouldn't be separate, looked at recursive mono statics and they don't show up separately
![image](https://user-images.githubusercontent.com/1242984/119739857-8b326780-be8b-11eb-9260-217a59c074a7.png)

**Comment by DHowett** [comment]
The static italics being separate is was being tracked in #465 and has been fixed pending release :smile:

**Comment by DHowett** [comment]
@aaronbell sorry I decided to ship the non-italic variant from this build against your advice. Software engineer's ego 😓

**Comment by J3Rik0** [comment]
I'm guessing there's a naming issue that's causing the weights, I remember I've ran into the weights not being properly read in Windows when converting them in FontForge, had to ensure the naming pattern is consistent in order to get them properly organized. The workflow here is a bit over my hobbyist font know-how though, so I'm just drawing on my experiences 😁

**Comment by aaronbell** [comment]
@DHowett TBH, it seems like I need to remove the in-progress Hebrew and Arabic from the source so we can build and ship the Roman as is (with all the relevant updates / code). Otherwise we're chasing bugs that will get resolved in mid-June because everything has been updated for the new version. 

I'm actually surprised the build even worked for you since the feature code has changes and, I think, requires some new ligature glyphs.

**Comment by DHowett** [comment]
😬 I can just prepare a build with the 2105.26 fixes for Italic's static instance naming and include the 2102 files for Regular.

**Comment by aaronbell** [comment]
Well...it strikes me that the STAT table needs to be updated in the Roman for things to connect properly. :/

**Comment by DHowett** [comment]
... crap.

**Comment by aaronbell** [comment]
On the plus side, we get to push out a bunch of *other* fixes that needed doing. :P
