### ISSUE TITLE
Some letter ligatures might wrong

### ISSUE THREAD

**Issue by otomad** [microsoft/cascadia-code#488]
# Environment
> Cascadia Code version number: 2102.025
# Some wrong ligatures
* Didn't support ligatures `|=` `==` but used to support. (Or for some reason I don't know.)
* `=>>` `=<<` ligatures didn't support in italic, but support in normal font-style.
* `www` ligatures in itatic seems has **7** letter "v"??? (Likes *vvvvvvv* .)

**Comment by aaronbell** [comment]
- `|=` is disabled in the 'arrow' ligature set following Fira Code
- `==` is still enabled, but now has a small gap between the two equals to better differentiate it from `=`. There is an open issue on this: #347 
- `=>>` / `<<=` will be updated in Regular to follow Italic. See #435 
- Whoops! I must have gotten a little over-zealous with that. Thanks. Will reduce.

**Comment by otomad** [comment]
Thanks!

And I found another wrong ligatures in light italic, semilight italic, semibold italic (other italics no problem) `#_(`

![image](https://user-images.githubusercontent.com/56647156/120470067-b3631e80-c3d5-11eb-9351-e26156213ed2.png)

The unline looks like a parallelogram. But `#_` is no problem.

**Comment by aaronbell** [comment]
Thanks, that has already been fixed in source (#475).

**Comment by otomad** [comment]
I’ve just seen your pull request ([#476](https://github.com/microsoft/cascadia-code/pull/476)) , there are many interesting interpolation issues in Italic, lol.

Then I’ll just report something that hasn't been mentioned there.
* `=||` find in light and semilight (not italic).
* `>>>==` in all font-style, what’s that?

![image](https://user-images.githubusercontent.com/56647156/120504793-026d7b80-c3f7-11eb-9b3e-0a23f020808d.png)
![image](https://user-images.githubusercontent.com/56647156/120504823-0a2d2000-c3f7-11eb-9610-0b01b455f4f7.png)
![image](https://user-images.githubusercontent.com/56647156/120505263-65f7a900-c3f7-11eb-9961-1b8a6aa65e14.png)

**Comment by otomad** [comment]
And I'm curious to know why don't show ligatures `~=` as `≃` now? I remember it used to be shown like this.

**Comment by aaronbell** [comment]
Both of those ligatures are fixed in source.

As for `~=`, blame Lua #394.
