### ISSUE TITLE
Powerline font missing glyph U+E235 (Python)

### ISSUE THREAD

**Issue by Antyos** [microsoft/cascadia-code#492]
### Cascadia family version

2105.25

### Cascadia family variant(s)

Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 10, 20H2, build 19042.985

### Other Software

Visual Studio Code 1.56.2; Windows Terminal

### What happened?

I followed the instructions on Microsoft's website to add Powerline to Windows Terminal: <https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup>, however the symbol relating to the Python version does not show up:
![image](https://user-images.githubusercontent.com/17516195/120503347-d74c4300-c388-11eb-92bc-f499579706ba.png)

I mostly found this odd because a glyph from the official guide is missing.

**Comment by aaronbell** [comment]
Hi, this is a known issue as the full Nerd Font set is not supported at this time (#194)
