### ISSUE TITLE
Artifact on some letterforms with variable WOFF2s

### ISSUE THREAD

**Issue by idan** [microsoft/cascadia-code#493]
### Cascadia family version

2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.woff2 (variable)

### Platform

MacOS 10.15.7

### Other Software

Firefox 89.0b15
Chrome 91.0.4472.77

### What happened?

Some characters, notably lowercase `t` exhibit an artifact on the edges of the stems that looks like a "dot" at smaller sizes, but is actually some kind of discontinuity in the edge of the glyph:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/22723/120563439-73903d00-c3bd-11eb-8d0b-a23da1f621ff.png">

At smaller sizes, it's perceptible as well:

<img width="101" alt="image" src="https://user-images.githubusercontent.com/22723/120563525-a5090880-c3bd-11eb-9ec8-dd0f7e848f98.png">

<img width="137" alt="image" src="https://user-images.githubusercontent.com/22723/120563590-d08bf300-c3bd-11eb-9204-29448bdb89fc.png">

<img width="162" alt="image" src="https://user-images.githubusercontent.com/22723/120563612-e4cff000-c3bd-11eb-9a7a-bdbc80b2907c.png">

The effect is most pronounced on non-retina displays. It's not limited to the `t`, but now that I'm looking for other examples, I'm not seeing them.

I see similar artifacts in both Firefox and Chrome, at the same location on the stems.

Thanks!

/cc @wattenberger

**Comment by aaronbell** [comment]
Thanks for the feedback! Unfortunately, that is due to an issue with MacOS and how it renders variable fonts built like Cascadia Code is built. Ultimately it isn’t a bug with the font that I plan to resolve.

However, the static instances should work fine. If the rendering irritates you, I suggest using the statics.

**Comment by idan** [comment]
@aaronbell Oh interesting! Do you know what others are calling this problem with the MacOS rasterizer, so that I can google and hopefully track it?

It's sad to not be able to use the variable builds, `font-weight: 350` was my Goldilocks for a thing 😢

**Comment by aaronbell** [comment]
Check out #350 for some related info on the problem. 

With MacOS, the issue is caused by co-linear paths that cause overlapping semitransparent pixels, which become darker.
