### ISSUE TITLE
Latest Release - Standard Fonts Hidden

### ISSUE THREAD

**Issue by PeteSL** [microsoft/cascadia-code#495]
Cascadia Mono & Code say they are installed but do not show in Fonts nor does Terminal see them.  I also installed the PL versions and those do show and Terminal sees them.  When I tried to reinstall the non-PL fonts, Windows says they are already installed.

Running Win 10 21H1 Enterprise and all was good until latest Terminal update complaining the fonts aren't installed.

**Comment by DHowett** [comment]
This is an issue in the app deployment platform. If you restart your machine or "repair" terminal, it will be resolved.
