### ISSUE TITLE
Some below-base anchor points are too high

### ISSUE THREAD

**Issue by dscorbett** [microsoft/cascadia-code#499]
### Cascadia family version

2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable), .ttf (static), .otf (static)

### Platform

macOS 10.14.6

### What happened?

Some glyphs with descenders (including ones precomposed with below-base marks) have anchor points for below-base marks too high, such that the mark overlaps the descender.

Here is <U+0024, U+0051, U+0070, U+0071, U+0079, U+00A2, U+00FD, U+00FE, U+00FF, U+012F, U+0133, U+0173, U+0177, U+0233, U+0272, U+03B2, U+03BE, U+03C1, U+03CF, U+040F, U+0414, U+0426, U+0428, U+0434, U+0443, U+0446, U+0448, U+045E, U+045F, U+0496, U+0497, U+049A, U+049B, U+04A2, U+04A3, U+04AF, U+04B1, U+04B2, U+04B3, U+04B6, U+04B7, U+04EF, U+0E3F, U+1E8F, U+1E99, U+1EF3, U+1EF7, U+1EF9, U+20A1, U+20AB, U+20B2, U+20B5> with U+0331 COMBINING MACRON BELOW after each character. I may have missed some.
![$̱Q̱p̱q̱y̱¢̱ý̱þ̱ÿ̱į̱ĳ̱ų̱ŷ̱ȳ̱ɲ̱β̱ξ̱ρ̱Ϗ̱Џ̱Д̱Ц̱Ш̱д̱у̱ц̱ш̱ў̱џ̱Җ̱җ̱Қ̱қ̱Ң̱ң̱ү̱ұ̱Ҳ̱ҳ̱Ҷ̱ҷ̱ӯ̱฿̱ẏ̱ẙ̱ỳ̱ỷ̱ỹ̱₡̱₫̱₲̱₵̱](https://user-images.githubusercontent.com/1124347/120941325-faac2080-c6ef-11eb-8846-7a42b3f3da1a.png)

**Comment by aaronbell** [comment]
I’ll take a look, but I’m not sure most of those even have base anchors because AFAIK no script uses them thus. Why are you putting diacritics on them?

**Comment by dscorbett** [comment]
All of them have base anchors. I found them by checking all the base glyphs using that anchor. If they had not used an anchor, I would not have reported this, but Cascadia is currently going out of its way to position marks incorrectly.

**Comment by aaronbell** [comment]
Ah. This is probably a case of the propagateAnchors script being overzealous. Thanks.

TBH, I don’t expect folks to be putting combining macron below on these glyphs, so I’m not super concerned (if they didn’t have anchors the positioning would still be wrong) but I’ll see what can be done to correct it.
