### ISSUE TITLE
Issue in rendering <, >, <= and >= glyphs

### ISSUE THREAD

**Issue by anand-dot** [microsoft/cascadia-code#502]
### Cascadia family version

Newest

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

Windows Terminal included version (TTF (variable)), .ttf (variable), .ttf (static), .otf (static), .woff2 (variable), .woff2 (static)

### Platform

Windows

### What happened?

There is an issue in rendering <, >, <= and >= glyphs:

![](https://user-images.githubusercontent.com/85477755/120970220-c5074600-c788-11eb-848e-d38bbeb973f6.png)

I think it should look like this (got this from Fira Code):

![](https://user-images.githubusercontent.com/85477755/120970358-f54ee480-c788-11eb-9994-768c39fb72fe.png)

**Comment by aaronbell** [comment]
I disagree :). I dislike how Fira Code renders the `=>` ligature and find it looks weird in code (far too narrow for double width). So I changed to the version you see.

**Comment by anand-dot** [comment]
But I am talking about <= and >= ligatures. Don't you think they look sort of compressed and blurry in cascadia code?
