### ISSUE TITLE
I can't read the font clearly

### ISSUE THREAD

**Issue by lizy0329** [microsoft/cascadia-code#505]
### Cascadia family version

Cascadia Code 2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

windows 10

### Other Software

Visual Studio Code version: 1.56.2

## font setting
![font setting](https://i.loli.net/2021/06/09/s68mF4bGxljQVvt.png)

## I can't read the font clearly
![I can't read the font clearly](https://i.loli.net/2021/06/09/GUg6SiMYJaeoHyA.png)

**Comment by aaronbell** [comment]
Dupe of #468. Thanks.

**Comment by lizy0329** [comment]
This practice is like ant-design forced to add Christmas eggs

**Comment by DHowett** [comment]
@lizy0329 stop spamming this repository.
