### ISSUE TITLE
[Question] 'x' ligatures before numbers

### ISSUE THREAD

**Issue by io-qar** [microsoft/cascadia-code#508]
What about 'x' ligatures before numbers?
Fira code:
![Fira Code](https://user-images.githubusercontent.com/40149230/121900048-a88d7f80-cd2d-11eb-8f6f-355b09f03af8.png)

Cascadia Code:
![image](https://user-images.githubusercontent.com/40149230/121900573-3a958800-cd2e-11eb-9675-108a821d00c0.png)

**Comment by aaronbell** [comment]
This feature was intentionally removed. See #285.

**Comment by io-qar** [comment]
Is there any chance for enabling this feature with Stylistic Set or something else?

**Comment by aaronbell** [comment]
I not at current.
