### ISSUE TITLE
Bug (?) while using Cascadia Code PL Italic with Russian letters

### ISSUE THREAD

**Issue by io-qar** [microsoft/cascadia-code#509]
### Cascadia family version

2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

Windows Terminal included version (TTF (variable))

### Platform

Windows 10 21H1

### Other Software

Visual Studio Code 1.57.0

### What happened?

In your `README` file there's 2  Russian letter `П` and `Т` wich looks like this in Italic:
![RUSSIAN P](https://user-images.githubusercontent.com/40149230/121902137-b6dc9b00-cd2f-11eb-8847-de1e3c1fd43c.png)
![RUSSIAN T](https://user-images.githubusercontent.com/40149230/121902545-176bd800-cd30-11eb-8106-7e2c34091484.png)

It also looks great in Windows settings:
![Windows Settings](https://user-images.githubusercontent.com/40149230/121903046-94974d00-cd30-11eb-98fb-55a5c2d58daa.png)

But in VS Code I see this (the first and the last letters) while typing Russian letters:
![VSC example](https://user-images.githubusercontent.com/40149230/121902803-56019280-cd30-11eb-9822-c7261fe7dbe8.png)

Just like another 2 letters:
![image](https://user-images.githubusercontent.com/40149230/121903448-fc4d9800-cd30-11eb-8a64-7b8d5ef84c04.png) and something like `ш` with dash above.

Or maybe I get something wrong?

**Comment by aaronbell** [comment]
Hi! The `п` and `т` that you're seeing with the line above are alternate forms used in Serbian. 

The normal way of accessing these forms is via localized forms, but Cascadia Code Italic also includes them under Stylistic Set 3, a common method for providing those forms when the `locl` feature is not supported. I anticipate that you have that stylistic set activated in VS Code (probably for functionality in another font), so disabling it will return you to standard Russian.

**Comment by io-qar** [comment]
Thank you! i found out this problem was because of enabled `ss03` option in `editor.fontLigatures` in `settings.json` (I don't know why but anyway). I edited settings when I use Fira Code, so now it looks like this:
![image](https://user-images.githubusercontent.com/40149230/121915369-d1b50c80-cd3b-11eb-9dd3-283ed844f501.png)
 
Thank you once again!
