### ISSUE TITLE
Italic ‘f’ is too close to the '('

### ISSUE THREAD

**Issue by Rean1030** [microsoft/cascadia-code#51]
Like this 
![image](https://user-images.githubusercontent.com/15373807/65240124-1eda5f00-db13-11e9-96cf-c268aeb14566.png)
and this in my QtCreator
![image](https://user-images.githubusercontent.com/15373807/65240182-42050e80-db13-11e9-856c-4aab65dd9083.png)
Its not easy to see when the font is small
![image](https://user-images.githubusercontent.com/15373807/65240503-00c12e80-db14-11e9-8e50-0833dd19ff72.png)

 Can you please improve it?

**Comment by ExE-Boss** [comment]
This will probably be fixed by #63
