### ISSUE TITLE
Consolas powerline

### ISSUE THREAD

**Issue by fornous** [microsoft/cascadia-code#510]
# Description of the new feature/enhancement (with images if possible)
Could you add powerline version of consoles too? Consolas is standard clean font - much cleaner than Cascadia Font.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment]
Sorry, this isn't the appropriate place to request changes to Consolas. It's an okay font, but my team and our excellent typographer will not be making any changes to it.
