### ISSUE TITLE
[Feature Request] Add ligatures for bitwise-shift-assignment operators (<<= and >>=)

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [microsoft/cascadia-code#512]
# Description

Cascadia Code already has ligatures for bitwise-shift left and right operators (<< and >>, see image), and I feel that the font could be improved by adding the assignment operators for the bitwise-shift operations (i.e. <<= and >>=). This would benefit developers who are working with low- or mid- level languages (e.g. C, C++) who have the opportunity to work with bitwise operations. 
![image](https://user-images.githubusercontent.com/79387351/122627683-b4899080-d0e3-11eb-8a58-6b7e25747406.png)

**Comment by aaronbell** [comment]
Ligatures for these characters have been created (see #435 ) and should be available worth the next release.
