### ISSUE TITLE
Greek lowercase italic pi in the front page looks broken?

### ISSUE THREAD

**Issue by NoxUltima** [microsoft/cascadia-code#513]
### Cascadia family version

2105.25

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

I don't know

### Platform

Windows

### What happened?

This image was taken from Cascadia Code's home page (cascadia_code_italic_characters.png) - the top bar and left stem of the Greek &pi; is too thick. I believe this is the Semi-Light weight.

![2021-06-19 12_19_39-cascadia-code_cascadia-code-italic-characters png at main · microsoft_cascadia-c](https://user-images.githubusercontent.com/16898444/122630786-f8d35b80-d0f8-11eb-955e-7800c5108495.png)

**Comment by aaronbell** [comment]
Well that's interesting. It isn't broken in the glyphs source nor the hinting source (which makes me think it isn't actually broken). I wonder why it ended up behaving odd in the image. I'll have to investigate.

**Comment by aaronbell** [comment]
Looks like I'd used an older version of the font by accident. Ah well. Updated :)
