### ISSUE TITLE
GitHub Dark theme causes font sample to be illegible

### ISSUE THREAD

**Issue by janreggie** [microsoft/cascadia-code#514]
The following is a screenshot of the Readme while using the GitHub dark theme:

![Screenshot of the Readme while using the Dark theme](https://user-images.githubusercontent.com/33337903/122672764-d7a96280-d1ff-11eb-8310-38a3b8328c8d.png)

A fix could be [inverting the image by using custom HTML+CSS](https://dev.to/colinmcdermott/darkmode-hacks-1-inverted-images-jga).

**Comment by mdtauk** [comment]
The image could be updated to not use a transparent background, or using a colour which will work on a dark or light background
