### ISSUE TITLE
Problem in fontLigatures with forwardslash ('/') and equality symbol ('=')

### ISSUE THREAD

**Issue by Parvat-web-dev** [microsoft/cascadia-code#517]
### Cascadia family version

2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 10 32-bit

### Other Software

Visual Studio Code Insider

### What happened?

The use of `/` and `=` together makes the first-quarter part of the equal go up and shrink by the way when using like this: `/=`
![image](https://user-images.githubusercontent.com/73871020/122871965-64156b80-d34d-11eb-9dcc-2b18ed5a8b9d.png)
but works well when its `=/=`. 
![image](https://user-images.githubusercontent.com/73871020/122872045-83ac9400-d34d-11eb-9b77-2ed3bb6a06cb.png)

**Comment by aaronbell** [comment]
Interesting. Can you give more information regarding the exact resolution / point size that you're looking at? 

The outlines are perfectly aligned, so this appears to be hinting related, but the hinting instructions are also the same.... I wonder if you've just happened to fall into a crack where it doesn't align for some reason.

**Comment by Parvat-web-dev** [comment]
Okay, let me explain. The bottom left side of the equal symbol just moved 1 or 2 pixels up when used with the `/`. Here a more zoomed image.
![image](https://user-images.githubusercontent.com/73871020/123073914-7cac8100-d434-11eb-88ca-1abbf02cadae.png)
Why does that do up? Is is my VS code's problem or some minor bug?

**Comment by aaronbell** [comment]
Yes I understand the problem and believe it to be hinting related where the horizontal bar has been shifted slightly to align with the pixel grid. As I said before, can you provide the resolution of your device and the point size of the text?

**Comment by Parvat-web-dev** [comment]
I have dual screen. One of 1920x1080 and another of 1366x768

**Comment by Parvat-web-dev** [comment]
I think that is the problem of my VS code or the theme probably. Because it works well in `liber office`. See this image 
![image](https://user-images.githubusercontent.com/73871020/123444156-3736b200-d5f4-11eb-8214-00cf39154ebd.png)
And thanks for immediate response.
