### ISSUE TITLE
Feature Request: Clearer curly braces

### ISSUE THREAD

**Issue by jsit** [microsoft/cascadia-code#525]
# Description of the new feature/enhancement (with images if possible)

The shape of curly braces is not well-defined at small sizes and can resemble a parenthesis. Here it is in SemiLight 12 in iTerm 2:

<img width="86" alt="braces-cascadia" src="https://user-images.githubusercontent.com/643417/124151800-f100a900-da60-11eb-84f7-25c7b51411b3.png">

For comparison, here's Menlo:

<img width="74" alt="braces-menlo" src="https://user-images.githubusercontent.com/643417/124151828-f78f2080-da60-11eb-8c6c-47d273ebced3.png">

And IBM Plex Mono:

<img width="84" alt="braces-ibm-plex-mono" src="https://user-images.githubusercontent.com/643417/124151854-fc53d480-da60-11eb-9bbc-8a4dbba4af78.png">

# Proposed technical implementation details (optional)

Make the shape of the curly brace more pronounced so that it's more legible at small sizes.

**Comment by TehFynlNyt** [comment]
Some more designs from Operator Mono, the braces can be a lot more wider and more angular as they looked too thin.

![image](https://user-images.githubusercontent.com/90877277/137589543-bcd6edc3-e735-4bf3-9ac6-e86bd26b5f2f.png)

**Comment by SharakPL** [comment]
Honestly I like it the way it is now. The difference between { ( [ is very clear:

![obraz](https://user-images.githubusercontent.com/5007456/137633339-db9976a0-45cf-4b9a-83b4-5df7cee4afc4.png)
