### ISSUE TITLE
Italic variant non rendering is visual-studio-code-bin (Linux)

### ISSUE THREAD

**Issue by iRealistiX** [microsoft/cascadia-code#526]
### Cascadia family version

2105.4

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Linux; Kernel 5.10.46-1-lts

### Other Software

Visual Studio Code 1.57.1 (Installed through yay AUR)

### What happened?

Problem rendering Italic variant, since I configured my vscode install to render certain keywords with the italic cursive variant since it is gorgeous, worked right on windows 10, but with linux it  uses the generic italic version (non cursive one)

Any help?

**Comment by bradms** [comment]
I think you may need version 2105.24 of the font, based on the releases this is the one where cursive italics are introduced.

**Comment by iRealistiX** [comment]
> 
> 
> I think you may need version 2105.24 of the font, based on the releases this is the one where cursive italics are introduced.

Sorry but I missclicked the old 2102 version, yes I use the latest
