### ISSUE TITLE
Font Validation failed on MacOS

### ISSUE THREAD

**Issue by kmf** [microsoft/cascadia-code#53]
Getting an Error when installing the Font on a Mac

![image](https://user-images.githubusercontent.com/78700/65241883-05bab980-dae5-11e9-8192-1c8cceb981e2.png)

**Comment by DHowett-MSFT** [comment]
The VTT file is source code and contains extra data for compiling the hinting instructions. Can you try with the actual TTF from the releases page?

**Comment by davemyb** [comment]
The TTF from the releases page works correctly. Thanks!

**Comment by kmf** [comment]
@davemyb thanks!
