### ISSUE TITLE
Missing Arabic positional glyphs

### ISSUE THREAD

**Issue by dscorbett** [microsoft/cascadia-code#532]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable), .ttf (static), .otf (static)

### Platform

macOS 10.14.6

### What happened?

Some Arabic letters are missing some positional glyphs:

* U+0649 ARABIC LETTER ALEF MAKSURA: missing 'init' and 'medi'
* U+066F ARABIC LETTER DOTLESS QAF: missing 'init' and 'medi'
* U+06A2 ARABIC LETTER FEH WITH DOT MOVED BELOW: missing 'init', 'medi', and 'fina'
* U+08AA ARABIC LETTER REH WITH LOOP: missing 'fina'
* U+08B2 ARABIC LETTER ZAIN WITH INVERTED V ABOVE: missing 'fina'

![ىىـ␤ٯٯـ␤ڢڢڢ␤ـࢪ␤ـࢲ](https://user-images.githubusercontent.com/1124347/125517855-ddbc368a-e1aa-4971-88e2-fb13043dc63a.png)

**Comment by aaronbell** [comment]
Thanks for the feedback! It is my understanding that those positional characters are not used for Arabic. Under what conditions are you encountering the need for these forms?

**Comment by dscorbett** [comment]
This is a Unicode compliance issue, specifically with [ArabicShaping.txt](https://unicode.org/Public/UNIDATA/ArabicShaping.txt). It shouldn’t matter which languages use which forms.

**Comment by aaronbell** [comment]
Well, just because Unicode says it does not mean that it is necessary or useful for actual language use. If you want to argue with that I have 9000 Hangul forms to show you.

Can you provide any examples of where these would be necessary?

**Comment by aaronbell** [comment]
Thank you! The additional context is very useful for us to better understand the request.
