### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by W3Dojo** [microsoft/cascadia-code#533]
So its not an issue with a specific document, but rather an issue with the _version number_. I never really seen anything that uses a versioning system quite like the one that ___Cascadia Code___ implements. To be completely honest,I don't really understand it, but that isn't what bothers me. 

### What I don't get is this: 

I downloaded Version __`2106.17`__, in the documentation, the link I clicked on (as I am certain you know already) read  ___"2106.17"___, although, my GNU font manager, shows the ___Cascadia Code Version___ as being __`2106.02`__. I don't really care, if the versions don't match, because the font works, but I do care about any differences that exist between the two versions, and if there exist a 2106.01, 2106.03, 2106.04,  2106.18, or maybe there's a 2106.12345. So whats the difference, and why is it showing as 2106.02 on my machine?

**Comment by DHowett** [comment]
2106.02 is unexpected! I wonder where it's getting that.

The Cascadia family is versioned by the year, month and day. 2106.17 was completed on 2021-06-17.

**Comment by aaronbell** [comment]
The version string in the font is `2106.017` so it is likely just rounding to `2106.02` in your tool. @Dhowett, we might want to keep that in mind 😒

**Comment by W3Dojo** [comment]
__Tool's Name:__ "GTK+ Font Manager 0.8.6"
__Tool's Version__: "0.8.6"
__Platform__: "Ubuntu 21.04"

<br> 

### Here's a Screenshot:

---

![Cascadia-Code__Version-Issue](https://user-images.githubusercontent.com/82741003/125548841-cac1b6e2-5c77-4fc1-90b9-5a0f6dc4bb49.jpg)

**Comment by W3Dojo** [comment]
Oh ya, good thinking Mr. Bell, it probably is rounding off.
