### ISSUE TITLE
Freezing Cascadia Code Stylistic Sets into the font

### ISSUE THREAD

**Issue by krish-r** [microsoft/cascadia-code#534]
Firstly, both Cursive & Italics look awesome! 

With the latest update to the font, I was looking for options to enable the `ss01` stylistic set in my JetBrains IDEs. 
(This isn't possible right now, there's an open issue for this in JetBrains issue tracker - [IDEA-221886](https://youtrack.jetbrains.com/issue/IDEA-221886).)

And, I came across [OpenType Feature Freezer](https://github.com/twardoch/fonttools-opentype-feature-freezer/) tool - this freezes the OpenType features into the fonts. 
(Also, the tool gives an option to provide a suffix to the font name, so that it can be installed in parallel without uninstalling the original font.)

Gave this tool (CLI) a try with Cascadia Code PL - Static & Variable TTFs with `ss01` stylistic set and it works as described. 

Thought this might help those (like me), who are looking for options to use Cascadia Code's stylistic set(s) in Apps/IDEs/Text Editors which currently do not support these features.

Thanks

**Comment by aaronbell** [comment]
Oh thanks! I’ll add something to the readme about it. Looks like it is one of Adam Twardoch’s projects, so it’ll be pretty solid :).
