### ISSUE TITLE
Documentation Issue - Inaccurate stylistic set setup example

### ISSUE THREAD

**Issue by 0x4ab** [microsoft/cascadia-code#536]
In the README.md in [this section](https://github.com/microsoft/cascadia-code#to-enable-the-cursive-form-of-the-italic-heres-the-code-you-should-use) there is an example on how to set-up stylistic variants in VS Code - i.e.

```
"editor.fontLigatures": true,
"editor.fontLigatures": "'ss01'",
```

This is a bit confusing as you cannot have both lines in the VS Code configuration. There can be only a single line with one of these values:
* `true` to turn on defaults (_liga_ and _calt_ it seems)
* `false` for nothing
*  `comma-separated array of strings` where you specify details (seems like you will also get ligatures on top as well)

Could you make it clearer?

Thank you!

**Comment by aaronbell** [comment]
Oh! For some reason I thought it had worked for me like that. I’ll change it. Thanks.
