### ISSUE TITLE
U+0615 ARABIC SMALL HIGH TAH is too low

### ISSUE THREAD

**Issue by dscorbett** [microsoft/cascadia-code#543]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable), .ttf (static), .otf (static)

### Platform

macOS 10.14.6

### What happened?

The glyph assigned to U+0615 ARABIC SMALL HIGH TAH was not designed for U+0615. It was clearly designed to be a component of glyphs for characters like U+0768 ARABIC LETTER NOON WITH SMALL TAH, but when it is used as its own character, it is positioned too low.

It overlaps other above-base marks. For example, here it is with U+064B ARABIC FATHATAN:
![بًؕ](https://user-images.githubusercontent.com/1124347/126332666-cc4546f7-4d5a-4fbe-8381-2f740aae3939.png)

It also overlaps tall letters like kaf and lam.
![كؕلؕ](https://user-images.githubusercontent.com/1124347/126339807-848d7b87-8446-4e13-8e81-1de36dda4462.png)

U+0615 is a Quranic annotation sign, and as such should be placed at a constant high height, even if the base is short. For example, it should be at the same height above alef and beh.
![اؕبؕ](https://user-images.githubusercontent.com/1124347/126341346-a300bd90-7fd6-4db3-b683-04fb0822fc61.png)
For comparison, here is the same string in Amiri:
![اؕبؕ](https://user-images.githubusercontent.com/1124347/126341675-b96a6608-ffb6-4077-b1db-868b5a52b0c0.png)
For another comparison, here a similar string in Noto Sans Arabic (it shows U+06D6 instead of U+0615 but the idea is the same):
![اۖبۖ](https://user-images.githubusercontent.com/1124347/126342920-4cd198fd-94f6-4f8d-a7ec-84e13322f21d.png)

**Comment by aaronbell** [comment]
These particular use cases appear to be specific to Qur'anic typesetting, and as Cascadia Code is not intended for that purpose, it will not be supported at this time.

**Comment by dscorbett** [comment]
Why does Cascadia Code support U+0615 ARABIC SMALL HIGH TAH? Its only use is for Quranic typesetting.
