### ISSUE TITLE
ij_acute is a mark glyph

### ISSUE THREAD

**Issue by dscorbett** [microsoft/cascadia-code#546]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable), .ttf (static), .otf (static)

### Platform

macOS 10.14.6

### What happened?

<U+0133 LATIN SMALL LIGATURE IJ, U+0301 COMBINING ACUTE ACCENT> overlaps the following glyph when the language system is Dutch.
![ĳ́?](https://user-images.githubusercontent.com/1124347/126487434-ec724668-f907-4ea5-8181-5761a2cf71c5.png)
Intended rendering:
![ĳ́?](https://user-images.githubusercontent.com/1124347/126487469-175ef191-6499-4e0d-87e5-c67524f9f406.png)

**Comment by aaronbell** [comment]
Interesting. Appears to have been caused by the over-aggressive propogateAnchors command. Excluding that glyph from the command solves the problem.
