### ISSUE TITLE
Cascadia Code does not show infinite ligatures

### ISSUE THREAD

**Issue by jopefd** [microsoft/cascadia-code#547]
### Cascadia family version

2106.17, 2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

I don't know

### Platform

Linux

### Other Software

Konsole 19.12.3
Vim 8.1
Visual Studio Code 1.57.1

### What happened?

Below a comparison with Fira Code:

At Vim (Konsole)
Fira Code:
![Screenshot from 2021-07-21 09-32-31](https://user-images.githubusercontent.com/67479090/126491374-ab910e3f-9794-47b8-9f5e-ae903da5d3de.png)
Cascadia Code:
![Screenshot from 2021-07-21 09-32-58](https://user-images.githubusercontent.com/67479090/126491378-e4bb510d-e943-4f6d-86c3-609a8da0efc2.png)

At Visual Studio Code
Fira Code:
![Screenshot from 2021-07-21 09-46-20](https://user-images.githubusercontent.com/67479090/126491701-48e32056-9140-4ddc-940a-2a744842d192.png)
Cascadia Code:
![Screenshot from 2021-07-21 09-46-42](https://user-images.githubusercontent.com/67479090/126491713-130e3657-2450-42f1-801b-1325db9f4390.png)

I don't really know the exact version of my Cascadia, but I installed it at July, 8.

**Comment by aaronbell** [comment]
I can't repro the issue with the latest version. Please try uninstalling, [clearing the font cache](https://github.com/microsoft/cascadia-code/wiki/Double-installation-issue), restarting, and [re-installing the latest](https://github.com/microsoft/cascadia-code/releases/tag/v2106.17).

**Comment by aaronbell** [comment]
Hi, not sure but I'm guessing this issue got sorted? I'll close it for now :)
