### ISSUE TITLE
Wrong glyph for U+05C7 HEBREW POINT QAMATS QATAN

### ISSUE THREAD

**Issue by dscorbett** [microsoft/cascadia-code#548]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable), .ttf (static), .otf (static)

### Platform

macOS 10.14.6

### What happened?

U+05C7 HEBREW POINT QAMATS QATAN looks identical to U+05B8 HEBREW POINT QAMATS, but they should look different. According to [L2/04-150](https://www.unicode.org/L2/L2004/04150-n2755-qamats-qatan.pdf), U+05C7 “is usually presented with a longer vertical; it can also be represented simply with a larger glyph, and in one case we have found the horizontal lengthened and bent.”

**Comment by aaronbell** [comment]
We consulted with the Hebrew Language Academy and the standard design for the Qamatz is that it should have the same shape for both uni05B8 and uni05C7. 

> There are some unofficial practices among religious printing houses to alter the shape a bit, but it is meant to help with vocalizing the words. However, they recommended not to alter the shape for a typeface that is not meant for religious texts and even can cause harm in the case of the typesetter's ability to choose the right form for the text.

As such we will keep the design as is.

**Comment by dscorbett** [comment]
That’s a misunderstanding of the purpose of U+05C7. It does not simply represent any qamats qatan: it specifically represents a qamats qatan that has been modified to help distinguish it from qamats gadol. Almost all documents use U+05B8 for both qamats qatan and qamats gadol. Making U+05C7 and U+05B8 look identical defeats the purpose of using U+05C7. If you don’t want to support this unofficial practice, which is reasonable, you should remove U+05C7 from the font.

**Comment by aaronbell** [comment]
I trust the recommendations of the designer and Hebrew Language Academy as language experts to include both and keep them aligned for Cascadia Code.
