### ISSUE TITLE
BROKE

### ISSUE THREAD

**Issue by Looskie** [microsoft/cascadia-code#550]
### Cascadia family version

WTF

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

WTF

### Other Software

PELASE GOLAND BROK

### What happened?

../.....

**Comment by Looskie** [comment]
misclick sorry

**Comment by pxseu** [comment]
f-ont
![20210725_045243.jpg](https://user-images.githubusercontent.com/57842793/126886198-c90f75fd-368a-46df-9074-23b94b41753a.jpg)

**Comment by cnrad** [comment]
hey micorsof 💀
