### ISSUE TITLE
I don't like the new italic version and want to go back to previous. How to do that?

### ISSUE THREAD

**Issue by lakshits11** [microsoft/cascadia-code#556]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (static)

### Platform

Windows 10

### Other Software

Visual Studio Code

### What happened?

I don't like the new italic version and want to go back to previous. How to do that? The previous italic { or we can say cursive :) } version was great for me. But now I don't have any option to go back to previous settings.

I also tried to download the previous release 2105.24 but it has entirely different name { like `Cascadia Code Italic` } for italic fonts hence not implementable in VSCode with normal font since when I set font to `Cascadia Code Italic`, everything becomes italic, everything! . Please tell me solution.

Thank You.

### Images for Reference:

**The new version _(which I dont like)_**
![1](https://user-images.githubusercontent.com/54276661/127779560-c54d9ef3-0306-413e-8706-4d8ed04d1739.PNG)

**When using 2105.25 `Cascadia Code italic` _(which I like but only want italic font for textmate scopes I define in settings, not for everything )_**
![2](https://user-images.githubusercontent.com/54276661/127779562-232ce3a7-9353-4095-918c-c2424ce36af6.PNG)

**Comment by aaronbell** [comment]
We will not be going back to the previous version of the italic. However, you can activate the cursive variants in VSCode with the following code in the `settings.json` file:

"editor.fontLigatures": "'calt', 'ss01'",

**Comment by lakshits11** [comment]
So you are saying that this will replace the new italic version with cursive version that I want? And also will it turn on or off the font ligatures? Thanks

**Comment by aaronbell** [comment]
It will substitute the non-cursive variants with the cursive variants (see ss01 in the Stylistic Sets image in the README). And will also turn on font ligatures. If you don't want font ligatures, either remove `calt` from the line I provided or switch to Cascadia Mono.

**Comment by lakshits11** [comment]
Ok but what about the lowercase `i` in ss01. Its previous design was good by the way. I didn't find it in ss01 that's why asking 😅

**Comment by aaronbell** [comment]
Ah.. you might check #545. I don't have any plans to bring it back at this time, but will consider for the future.

**Comment by lakshits11** [comment]
Hello, Thanks for sharing. By the way, Where can I find documentation about the terms like `calt`, `salt`,`dlig`, `ss01` etc. I want to know more about what these terms mean and what do they do?

**Comment by aaronbell** [comment]
Here you go!
https://docs.microsoft.com/en-us/typography/opentype/spec/featurelist
