### ISSUE TITLE
Windows 10 - Jetbrains no way to select Cascadia Code PL weight (typography)

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/cascadia-code#557]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 10  [Version 10.0.18363.1379]  (managed system)

### Other Software

Jetbrains IntelliJ 2021.2 (<-- very recent release)

### What happened?

While I am able to pick Cascadia Code PL as my font in the Jetbrains IntelliJ 2021.2 IDE, I cannot make reasonable use of the typography settings to address lightness (or boldness); the weights simply don't fit.

Jetbrains IntelliJ only allows me to pick "Italics" (where as previously it allowed me to pick Roman); screenshot below. I am afraid (and sad) to say so, but with these settings the font is unusable in IntelliJ.

I understand that with 2106.17 a changed was issued, directly targetted at Jetbrains products, to make the font work. Alas, this does not work for me in the environment mentioned above.

It might be worthwhile adding that I have Windows Terminal Preview installed, too. I do not know whether this contributes to a rather strange scenario where some fonts I can uninstall, and some I can. "Cascadia Code PL -> ExtraLight Italic" appears twice, for instance, in my fonts list, one I could uninstall, the other not. Both are version 2106.17

![image](https://user-images.githubusercontent.com/3868036/127907970-45e41ec4-cf88-4cd8-9592-2ea2f2eee60e.png)

**Comment by shoffmeister** [comment]
On a slightly related note, perhaps: The font deployment story on the Windows OS does not seem to be fully fleshed out. Windows Terminal seems to _bundle_ a _subset_ of these fonts. It could be so much nicer, if Windows Terminal either bundled all the font, or the fonts were debundled and shipped / updated separately through an auto-updating scheme (aka Microsoft Store).

My preference would be to have Cascadia Code PL auto-updating, always, on Windows.

**Comment by shoffmeister** [comment]
On a every so slightly more positive note, I do love the font - inside Visual Studio Code on Windows, and as a mono font throughout my Linux system (where it works perfectly inside IntelliJ, and vscode, and the KDE konsole terminal with starship for powerline symbols)

And because I love your font - thank you very much for offering it - I am quite keen on using it in IntelliJ on that (managed) Windows box, too.

**Comment by aaronbell** [comment]
Hm. I suspect that this is due to the same issue as #500, which will be solved by PR #538. Sorry for the trouble! Once that gets merged in and rebuilt, things should be OK!

> It could be so much nicer, if Windows Terminal either bundled all the fonts, or the fonts were debundled and shipped / updated separately through an auto-updating scheme (aka Microsoft Store).
Yup! We have #39 tracking this. I think distributing via the MS Store would be great. 

> On an every so slightly more positive note, I do love the font - inside Visual Studio Code on Windows, and as a mono font throughout my Linux system (where it works perfectly inside IntelliJ, and vscode, and the KDE konsole terminal with starship for powerline symbols)
Thank you! Glad you like it :).

**Comment by aaronbell** [comment]
BTW, after conducting some more research, I came across an [old bug](https://youtrack.jetbrains.com/issue/JBR-3134) that I'd filed (ha!) with Jetbrains. 

Aside from the naming issue (which I discovered that I had re-introduced at some point), it seems that Jetbrains doesn't properly support variable fonts. As such, I'd suggest using the static instances instead for your needs so that you can use your preferred font weight.

**Comment by shoffmeister** [comment]
Many thanks!

I can confirm that the following steps render a working solution:
* uninstall existing (variable) fonts - possibly Windows Terminal (too, prior)
* install the "static" set of ttf fonts as released here
* configure IntelliJ
// profit !!!
(also works in Windows Terminal - CMD, PowerShell, VS Code)

![image](https://user-images.githubusercontent.com/3868036/128749897-c8e73f27-0572-437a-a4bb-330d7e750ef7.png)

**Comment by aaronbell** [comment]
Excellent! Glad to hear they're working for you :). It looks like variable font support is getting some traction over there, though, so hopefully you won't have to use the statics forever.
