### ISSUE TITLE
Incorrect syntax highlighting in ligatures

### ISSUE THREAD

**Issue by BonnyAD9** [microsoft/cascadia-code#558]
With ligatures there may by issues with sintax highlighting when the two characters in a ligature should have different color.

Here is an example where in the `*)` ligature `*` should be red and `)` should be white. But they are both red.
![image](https://user-images.githubusercontent.com/46282097/128014317-9abf990d-2bd2-4108-8a0f-8be64fef152a.png)

**Comment by aaronbell** [comment]
Unfortunately I don’t think that there is anything I can do to resolve this in the font, except to say turn off ligatures!

Sorry for the trouble.

**Comment by CodeCrazy-ywt** [comment]
@BonnyAD9 it's your editor/IDE's issue, not the font's. What editor/IDE are you using?

**Comment by BonnyAD9** [comment]
> @BonnyAD9 it's your editor/IDE's issue, not the font's. What editor/IDE are you using?

I'm using VS Code (latest version)
