### ISSUE TITLE
alternate version with slashed zero and regular number four. please do not deliver the current 4 number as default to eastern europe.

### ISSUE THREAD

**Issue by mailinglists35** [microsoft/cascadia-code#559]
# Description of the new feature/enhancement (with images if possible)
https://en.wikipedia.org/wiki/Slashed_zero
and the current number four reminds me of soviet occupation of eastern europe as it resembles with their capital letter [ц](https://en.wikipedia.org/wiki/Tse_(Cyrillic)) and only seeing that makes me sick. no matter how I like this new font, I will never be able to use it because of that character 4

# Proposed technical implementation details (optional)

**Comment by aaronbell** [comment]
A slashed zero is accessible via stylistic set 19 (Please see the README).
 
Sorry you don't like the 4, but I don't think it looks anything like the ц and have no intention to change the design at this time.
<img width="453" alt="Screen Shot 2021-08-12 at 2 46 10 PM" src="https://user-images.githubusercontent.com/8460297/129274277-09698734-4975-4b03-8c38-ecdb7e4c22d9.png">
See? :)

**Comment by mailinglists35** [comment]
> I don't think it looks anything like the ц

does not look to _you_. it definitely looks to me strong enough to make effort to file this issue and describe the feeling. but I guess you cannot imagine the feeling when you've grown out in a free country that never has been under soviet occupation

**Comment by mailinglists35** [comment]
basically every variant of 4 that has the two upper lines approximately equal and not closed resembles the russian letter. 

these are tolerable versions:
![2021-08-17_18-23-40](https://user-images.githubusercontent.com/2054302/129754945-d2671f45-40a5-4194-81a6-ca3e2486a711.png)

these along with Cascadia version are unacceptable versions:
https://www.designyourway.net/drb/ths/diverse/russianfonts/Soviet.jpg
https://ct.mob0.com/Fonts/CharacterMap/soviet.png
https://i.pinimg.com/originals/16/42/13/16421312e6fef18a8cb29f3b2337b5a5.jpg
https://allyourfonts.com/wp-content/uploads/2020/05/Soviet-Font-Free-Download1.jpg
https://www.fontriver.com/font/soviet/
https://www.designyourway.net/free/back-in-the-ussr/
https://www.designyourway.net/free/kremlin-grand-duke/
https://www.designyourway.net/free/wp-content/uploads/2019/05/Kremlin.jpg


At least please provide an alternate version.

**Comment by aaronbell** [comment]
Honestly, Cascadia Code has been out and available for 2+ years now, with people from around the world using it without any issue, including folks from Eastern Europe. 

Thus far yours is the only complaint that we have received regarding a perceived similarity to soviet letterforms. While I respect your opinion and the fact that the shape of the 4 bothers you, I don't plan to change the font based on a single person's opinion.

I'm sorry that the font doesn't work for you and hope you find another that works better.
