### ISSUE TITLE
The Cascadia Code on Emacs is shown in italics

### ISSUE THREAD

**Issue by Someone-Of-Liu** [microsoft/cascadia-code#560]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Linux (freetype 2.10.4)

### Other Software

Emacs 27.2

### What happened?

When I set the font to Cascadia code in Emacs, italics is displayed by default. However, no matter the width of the font is changed to regular, light or bold, only italics with the corresponding width will be displayed. Changing the font to Cascadia mono will display normally, but the font will look strange.

![image](https://user-images.githubusercontent.com/69884931/129218532-62bebcd3-33f6-45ac-beb0-e9ba74cecc73.png)
![image](https://user-images.githubusercontent.com/69884931/129219624-11f09262-ed64-4496-b5dc-3759a9d865cc.png)

**Comment by aaronbell** [comment]
This is probably the same problem as #500 and will be solved by #538.

I'd suggest using the static instances for the time being rather than the variable font. Sorry for the trouble!
