### ISSUE TITLE
Infinite arrows doesn't work in MacOS 12.0 Beta(21A5304g)

### ISSUE THREAD

**Issue by Jyunta** [microsoft/cascadia-code#561]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

MacOS 12.0 Beta(21A5304g)

### Other Software

VS Code (Version: 1.59.0)
Terminal.app
CotEditor

### What happened?

OS: MacOS 12.0 Beta(21A5304g)
VS Code Version: 1.59.0

As the screen shot showed, the infinite arrows doesn't work. Not only in VS Code, but also other text editors and terminals, e.g. terminal.app, CotEditor.
![image](https://user-images.githubusercontent.com/49888607/130043527-8081970f-31f8-47be-951e-38329ae506bb.png)

What's weird is that in 'Italic' version infinite arrows work.
![image](https://user-images.githubusercontent.com/49888607/130043428-5005512a-bdc2-4be7-9eb8-8054525f4e1c.png)

Maybe it's because of MacOS of beta version? If someone using MacOS 11 could tell me if it works in your mac, thanks a lot.

**Comment by aaronbell** [comment]
Sorry you’re having trouble! Did you have a version of Cascadia Code installed before? I suspect this may be a font cache related issue. And that removing the font, restarting, and reinstalling may help.

it would also be worth checking if the static instances also have problems is if it is just the variable font.

**Comment by Jyunta** [comment]
> Sorry you’re having trouble! Did you have a version of Cascadia Code installed before? I suspect this may be a font cache related issue. And that removing the font, restarting, and reinstalling may help.
> 
> it would also be worth checking if the static instances also have problems is if it is just the variable font.

Thank you so much!!! Removing and reinstalling did work!!! But sorry that I didn't try static instances before removing and reinstalling. After that, static instances also worked.

Thank you again!
