### ISSUE TITLE
Wrong italic localised Serbian glyph U+0434

### ISSUE THREAD

**Issue by VeskoRadic** [microsoft/cascadia-code#563]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (static), .otf (static)

### Platform

Linux (freetype 2.10.4)

### What happened?

Localised Serbian glyph U+0434 CYRILLIC SMALL LETTER DE should look like Bulgarian variation.

The image below shows Russian, Bulgarian and Serbian variants.
![image](https://user-images.githubusercontent.com/63882439/130368159-9d11361f-d939-4f79-b21c-058ea6871c6e.png)

**Comment by aaronbell** [comment]
Thanks! Looks like I missed the substitution in the `locl` feature. Will update it.

**Comment by VeskoRadic** [comment]
Then I guess we can close this?

**Comment by aaronbell** [comment]
I’ll keep it open until the fix is PR’d. Easier for tracking 🙂
