### ISSUE TITLE
\ue20f was displayed as a box symbol

### ISSUE THREAD

**Issue by zemelLeong** [microsoft/cascadia-code#564]
### Cascadia family version

CascadiaCode-2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (static)

### Platform

Win10 Windows Terminal

### What happened?

\ue20f was displayed as a box symbol. When I change `windows terminal fontFace` as `MesloLGM NF` it will be ok.
![image](https://user-images.githubusercontent.com/26835087/130552709-4f09f262-2c3c-43cd-b941-ccf3206961c9.png)
![image](https://user-images.githubusercontent.com/26835087/130552783-f16dbb85-e7a7-4525-b48e-e11804fba7e8.png)

**Comment by DHowett** [comment]
E20F is part of the private use area that has been occupied by glyphs from the "nerd font" collection. Cascadia does not contain these "nerd font" glyphs.

**Comment by aaronbell** [comment]
Please support #194 which will solve this issue :)
