### ISSUE TITLE
Missing/Unsupported Glyphs? 🤔

### ISSUE THREAD

**Issue by aress31** [microsoft/cascadia-code#565]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 10 19043.1165

### Other Software

Windows Terminal
Version: 1.9.1942.0

### What happened?

I followed the instructions available at https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup to configure my WT with Powerline and all the goodies, however it seems that there is an issue with the Cascadia Code PL font that I am using as some glyphs appear to be missing for the default theme, please see:

![image](https://user-images.githubusercontent.com/11601622/131843113-e5d3f2f3-e330-4250-b21d-d23088b6b944.png)

**Comment by aaronbell** [comment]
Hi. The PL font does not support the full Nerd Font character set, which is the reason why you're seeing missing glyphs. This issue is currently tracked by #194.
