### ISSUE TITLE
Variable font is not recognized by JetBrains Rider

### ISSUE THREAD

**Issue by FUJonathan** [microsoft/cascadia-code#566]
### Cascadia family version

2106.17

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 10 Pro 21H1 19043.1202

### Other Software

JetBrains Rider 2021.2.1 Build RD-212.5080.71

### What happened?

After installing the variable font in the TTF directory, Cascadia Code is not listed in Rider's editor font selection dropdown. I don't know if this is a problem with Cascadia Code or Rider itself, but other variable fonts such as [Inconsolata](https://fonts.google.com/specimen/Inconsolata) seem to be recognized (admittedly, only some of its weights are available).

![image](https://user-images.githubusercontent.com/7123060/131968028-50492cb7-686e-4a5c-a861-0a91a92cbaa3.png)

On the other hand, if I install the italic version of the variable font (`CascadiaCodeItalic.ttf`), Rider does recognize it, but **only** the italic version is available. The regular version of the font (`CascadiaCode.ttf`) just seems to be completely ignored.

![image](https://user-images.githubusercontent.com/7123060/131969103-fd8ee48d-4d9d-412f-be8c-dc5d29f1bcba.png)

**Comment by FUJonathan** [comment]
I just discovered this issue reported for IntelliJ IDEA, also from JetBrains, so I suspect both IDE's enumerate fonts in much the same way:
[Documentation: Update IntelliJ IDEA Setup Instructions](https://github.com/microsoft/cascadia-code/issues/416)
[Cascadia Code no longer recognized by IntelliJ IDEA](https://youtrack.jetbrains.com/issue/JBR-3134)

I haven't yet checked if the workaround for IntelliJ IDEA in the link above will also work for Rider. For now I may just stick with the static fonts instead.

**Comment by aaronbell** [comment]
Yes, I suspect that this is the same issue as previously described. This should be partially fixed by PR #538.

Unfortunately, at this time JetBrains doesn't really properly support variable fonts. So you'll have to use the static instances.
