### ISSUE TITLE
■■ Ligature

### ISSUE THREAD

**Issue by AdrianoAE** [microsoft/cascadia-code#569]
### Cascadia family version

2102.025

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

I don't know

### Platform

Windows 10

### Other Software

Visual Studio 2022 Enterprise

### What happened?

Without Cascadia
![image](https://user-images.githubusercontent.com/20192335/132915987-4959b4a0-7ccd-4311-b0ce-e07e39d4ca46.png)

With Cascadia
![image](https://user-images.githubusercontent.com/20192335/132916060-39b5c819-2fb6-474e-9bed-a940b67f8d0d.png)

```
███████████████████████
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼
■■■■■■■■■■■■■■■■■■■■■■■
```

Shouldn't the last character have ligature with one another?

**Comment by aaronbell** [comment]
The codepoints that you have provided are:
`fullBlock`
`lowerHalfBlock`
`upperHalfBlock`
`blackLargeSquare`
`mediumBlackSquare`
`blackSquare`

The top three are box drawing characters and are supposed to connect to one another. However, the bottom three are graphical "squares" and should not connect. Not sure which font you are comparing Cascadia to, but it is doing things wrong :)
