### ISSUE TITLE
Capital K throws off the spacing of words

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/cascadia-code#573]
In my code I have the text value `builder.HasKey`. I'm using Cascadia-Code, 11 point. For this particular text the font removes a little over a letter of spacing on the left causing the text to no longer line up with the rest of the lines.

![image](https://user-images.githubusercontent.com/3778674/133108286-38b40d80-52ff-44ac-9ec1-1fb4a42dcc14.png)

Removing the capital `K` fixes the issue.

![image](https://user-images.githubusercontent.com/3778674/133108396-6fb345a5-64fd-40a6-8f5a-048193fe118c.png)

Of course this isn't valid so that won't work. Some other letters have the same issue. For example `Z` causes the problem but `M` and `P` do not. Using Cascadia Code Light or Cascadia Code Semilight resolves the issue.

**Comment by DHowett** [comment]
In your screenshot, `HasKey` isn't even in Cascadia! The `K` has a very distinctive shape, which isn't present in your highlighted section of code.

This looks like it could be an editor configuration problem... what IDE is that?

**Comment by CoolDadTx** [comment]
It is Visual Studio 2019. The text editor is configured for Cascadia Code.

I agree the font wasn't right but it doesn't make sense why as the rest of the code around it was fine. Once I switched to Cascadia Code Light the problem has gone away. Switching back to Cascadia Code doesn't replicate the problem anymore.

**Comment by aaronbell** [comment]
Strange. Are you using the latest version of Cascadia Code? Or the previous version? And have you installed the variable version? Or the static instances?

**Comment by CoolDadTx** [comment]
Version is 2102.025

I just downloaded from Github and told Windows to install. I don't know what instance it installed from there.

**Comment by aaronbell** [comment]
Hi! Sorry for taking so long to follow up. In looking again at this, I wonder if there's something in your editor color theme that is causing a different font to be used. I thought initially there might be an issue with the Regular not being loaded, but I note that `base` is rendering correctly, but `HasColumn` is not. Maybe worth checking that out?

**Comment by aaronbell** [comment]
Thanks for the update. Hopefully this is just a one-off issue. Cheers!
