### ISSUE TITLE
not able to select italic font in vscode

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/cascadia-code#578]
### Cascadia family version

CascadiaCode-2108.26

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

windows

### Other Software

Visual Studio code (latest Insiders release)
Windows Terminal Preview.

### What happened?

i want to use the Italics version of Cascadia code in VSCode. However there is no way to select that font in VSCode.
if I only install the italics version of font I get what I expect in vscode. if I install Windows Terminal Preview then it installs the regular version of font and the italics are not available in VSCode from there on.
there is no italics selection property in vscode. 
i like Cascadia Code Italics more for my development activity over the regular.

expected result:
there should be a separate, selectable italic font family that can be used in VSCode and other development environments.

**Comment by aaronbell** [comment]
VSCode provides mechanisms to apply a font style (like italic) to given text runs: https://github.com/wesbos/cobalt2-vscode/issues/116

I have done similar to use italics for comments. In your case you need to apply the italic style to all text.
