### ISSUE TITLE
now,I add support for macOS package manager homebrew

### ISSUE THREAD

**Issue by KarlZeo** [microsoft/cascadia-code#58]
I add support for homebrew cask.

[This is commit link](https://github.com/Homebrew/homebrew-cask-fonts/blob/6bd69e99f94a3095238cabaea9da3c34a76f02de/Casks/font-cascadia.rb)

install command:

```
brew tap homebrew/cask-fonts 
brew cask install font-cascadia
```

**Comment by zl939144892** [comment]
![image](https://user-images.githubusercontent.com/18364560/65251322-b6e34300-db29-11e9-99a1-dede89951c8d.png)

**Comment by KarlZeo** [comment]
@zl939144892 
before you install ,you must install the fonts cask .

Install Command 
```
brew tap homebrew/cask-fonts  
```

**Comment by zl939144892** [comment]
> @zl939144892
> before you install ,you must install the fonts cask .
> 
> Install Command
> 
> ```
> brew tap homebrew/cask-fonts  
> ```

Oh, very thanks! Learn it!

**Comment by shmidt** [comment]
Does it install Cascadia-PL as well?

**Comment by jyzhao** [comment]
> Does it install Cascadia-PL as well?

you will execute:
`brew cask install font-cascadia-code-pl`

**Comment by squatto** [comment]
For anybody that ends up here looking for the brew command for this font, it isn't named `font-cascadia` anymore. These are the available fonts:

```bash
brew cask install font-cascadia-code
brew cask install font-cascadia-code-pl
brew cask install font-cascadia-mono
brew cask install font-cascadia-mono-pl
```

Make sure to do this first or the fonts won't be found:

```bash
brew tap homebrew/cask-fonts
```

**Comment by sebagomez** [comment]
As of 2021, you must still run `brew tap homebrew/cask-fonts`, but then use `brew install --cask <font>` instead of `brew cask install <font>`

**Comment by hugows** [comment]
In my system today:

`brew install --cask font-cascadia-code font-cascadia-code-pl  font-cascadia-mono font-cascadia-mono-pl`

**Comment by noname-03** [comment]
> brew install --cask font-cascadia-code

thanks it's work for me
