### ISSUE TITLE
Linux Emacs Cannot Render Italic Style Cascadia Code

### ISSUE THREAD

**Issue by drcxd** [microsoft/cascadia-code#582]
### Cascadia family version

2108.26

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows Subsystem for Linux 2, kali-linux

### Other Software

GNU Emacs 27,2 (x86_64-pc-linux-gnu, GTK+ Version 3.24.24)

### What happened?

To summarize, I am using Cascadia Code in Emacs in Kali Linux in WSL2, and I found Emacs in Kali cannot render Italic style Cascadia Code.

![image](https://user-images.githubusercontent.com/24535087/137416166-e3581998-4916-47bc-98b6-668081f05f80.png)

As you can see in the screen shot, I opened the same document in Emacs in Windows and Emacs in Kali in WSL2. The Windows version displayed the Italic style font correctly while the Linux version just underlined the characters. Both Emacs are standalone GUI applications, the only difference is that the Linux version is viewed through a VNC application while the Windows version lives in the native OS.

I am not sure if this is an issue of Cascadia Code font itself, but I decide to come to here to look for help first. Could you help with this issue or point me to somewhere else?

**Comment by drcxd** [comment]
Hmm... You are right. I should have thought about it. I tried some other fonts and Emacs failed to render all their Italics variations... Really weird.

I am sorry if this issue causes any unnecessary trouble for you.

**Comment by drcxd** [comment]
It turns out that the difference is caused by some Emacs internal configuration which defines how "italic" looks like. On the Windows version Emacs, it changes the slant, while on the Linux version Emacs, it just adds the underline.

**Comment by aaronbell** [comment]
Glad you figured it out! I'll keep this in mind if someone posts a similar issue in the future. Thanks!
