### ISSUE TITLE
Ligatures variants need more explanation

### ISSUE THREAD

**Issue by SharakPL** [microsoft/cascadia-code#583]
Docs could use more valid examples for available ligatures variants. So far [I see](https://github.com/microsoft/cascadia-code#font-features) **'ss01'** (this alone enables cursive alternative so [what does **'calt'** actually do](https://github.com/microsoft/cascadia-code#to-enable-the-cursive-form-of-the-italic-heres-the-code-you-should-use)?), **'ss02'**, **'ss03'**, **'ss19'** (seems like it has the same effect as **'zero'**) and **'ss20'**. Next part of the Readme looks like a copy-paste from FiraCode respository: it links there and has their example:

> "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'"

What does **'ss04'**, **'ss05'**, **'ss06'** and **'onum'** do in Cascadia font? 'onum' in FiraCode changes digits' vertical alignment, but it doesn't look like it works here. I don't see other mentioned stylistic sets in Cascadia Code or Cascadia Mono details:

![obraz](https://user-images.githubusercontent.com/5007456/137630567-4e21374b-c173-45fb-8e7d-bd05063ea098.png)

A lot of confusion here. It should be explained precisely like [for FiraCode](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets)

**Comment by Ionaru** [comment]
`calt` seems to enable ligatures like `=>` and `ss01` seems to enable cursive italics.

**Comment by SharakPL** [comment]
Cascadia Code has ligatures by default and doesn't need any switch. Cascadia Mono is for terminals and doesn't use ligatures. Besides according to the docs `'ss01', 'calt'` is required to enable cursive and it's not true, because `ss01` alone does the job. `calt` alone does nothing, not even enabling **c**ursive **alt**ernative.

**Comment by Ionaru** [comment]
That's not the behaviour I'm seeing in VSCode.

Ligatures: `true`: Symbols enabled.
![image](https://user-images.githubusercontent.com/3472373/141634210-5519ae8f-58e5-4493-9f8b-3533a81478a1.png)

Ligatures: `ss01`: Cursive enabled.
![image](https://user-images.githubusercontent.com/3472373/141634699-89167905-6ceb-4387-8fc8-6c9d83689fd1.png)

Ligatures: `calt`: Symbols enabled.
![image](https://user-images.githubusercontent.com/3472373/141635224-2b5f0324-40ed-4dd3-86df-563797f1502b.png)

Ligatures: `calt, ss01`: Both cursive and symbols enabled.
![image](https://user-images.githubusercontent.com/3472373/141635443-5ce84052-a97f-4a2b-bb29-4ab01a6566a2.png)

**Comment by SharakPL** [comment]
Check again ;) Do you even have [latest version 2110.31](https://github.com/microsoft/cascadia-code/releases) or just the default that comes bundled with Windows Terminal or VSCode? I'm using _Cascadia Code PL_ in VSCode so all ligatures are enabled by default. `"editor.fontLigatures": "'ss01'"` keeps ligatures and enables cursive. `"editor.fontLigatures": "'calt'"` changes nothing compared to `"editor.fontLigatures": true`. You would need `"editor.fontLigatures": false` to disable ligatures. Also no visible effect when `calt` is combined with other values. _Cascadia Code_ has exactly the same behaviour (only powerline symbols are missing). The same with _Cascadia Mono_ - missing ligatures obviously, but `ss01` alone enables cursive version of the font and `calt` does nothing.

**Comment by kenmcd** [comment]
>  `calt` alone does nothing, not even enabling **c**ursive **alt**ernative.

`calt` stands for Contextual Alternates, not "cursive alternative."
It is `calt` which creates the ligatures in Cascadia Code.
The is no `liga` Standard Ligatures feature in  Cascadia Code.
You have two ways to turn-on `calt` in VS Code - `true` or `calt`
`ss01` only controls cursive italics in the Italic fonts.
The example which is described as for cursive italics which shows both `calt` and `ss01` is just a poor example.
It actually shows two things - enabling ligatures (`calt`) and enabling cursive italics (`ss01`).
@Ionaru 's example above is working as expected.

**Comment by SharakPL** [comment]
> > `calt` alone does nothing, not even enabling **c**ursive **alt**ernative.
> 
> `calt` stands for Contextual Alternates, not "cursive alternative."

I know. Already fixed my answer couple minutes before your comment 😛
Nevertheless the behaviour is still just as I explained earlier

![cascadiacode](https://user-images.githubusercontent.com/5007456/141659663-b41a6a73-08e2-4fff-a138-f99405c71435.gif)

**Comment by kenmcd** [comment]
> As you can see all ligatures are still there even without `calt` which changes nothing.

I am not seeing this.
With a new install of VS Code 1.62.2 I see no ligatures or cursive italics.
So something is different.

**Comment by SharakPL** [comment]
> > As you can see all ligatures are still there even without `calt` which changes nothing.
> 
> I am not seeing this.

Of course you are 😅 Both ligatures and cursive enabled **without** `calt`

![obraz](https://user-images.githubusercontent.com/5007456/141660783-cce1256f-fde2-464b-bedf-e83ec617a5ca.png)

**Comment by kenmcd** [comment]
If you have an issue with how the font configuration works in VS Code,
it would be appropriate to post that issue in that repository.

Regarding your original question, the stylistic sets which do exist in these fonts are documented on the page you linked to.
The other stylistic sets in the Fira Code example do not exist in this font.
And `onum` does do not exist in this font either.
Those were just an example of how to configure OpenType features (for that font).

**Comment by SharakPL** [comment]
It's not an issue with VSCode and it's not even an issue with the font itselft, because it all works as expected. It's an issue with documentation which provides unclear/invalid examples of font configuration. Wasn't I clear on that in opening comment?

**Comment by aaronbell** [comment]
I see there has been some 'lively' discussion on this thread. And I'm glad you all figured out that `calt` means Contextual Alternatives 😉 .

My apologies that the documentation is not quite clear enough—given that the primarily user-defined features are all stylistic sets, I thought that providing guidance about those features (as seen in the image in the README) would be sufficient. And it seems that the sample I pulled from the VSCode repro was confusing. I'll get around to updating the documentation at some point, but if any of y'all would like to help out, please feel free to submit a PR!

Regarding use of `calt` in the code example:

When I wrote the documentation, writing `editor.fontLigatures` and providing a list of OT features _would only turn on those features_. This is shown by @Ionaru's example where not including `calt` in the list actually causes the coding ligatures to turned off However, it appears that behavior may have changed (?). At least in my version of VSCode, whenever `editor.fontLigatures` is present, unless set to `false` or `calt` is specifically set to `off`, the coding ligatures will automatically be applied if present.

VSCode version:
Version: 1.62.2 (Universal)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316

If that is indeed a change in behavior, then use of `calt` is no longer necessary and the documentation should be updated. I tried to see if there is any mention of this on the VSCode repro but was unable to locate any.

**Comment by SharakPL** [comment]
I would gladly make a PR, but that's the whole problem it's not clear which of the values used in description are actually related to and still valid to Cascadia Code, not FiraCode. Can you check again opening comment and confirm which of these are valid?

**Comment by aaronbell** [comment]
The full set of features described in the font is shown in the source folder under features: https://github.com/microsoft/cascadia-code/tree/main/sources/features

However, most of these are functionality either required for aspects of the font to work seamlessly, or are not items that I would expect users want to turn on at all times.

As I said, the only items that I expect users to want to enable globally are the stylistic sets which are already listed in the README. 

> How do you set calt or any other set to off? 

See https://github.com/microsoft/vscode/issues/124718
The format is listed as `"editor.fontLigatures": "'calt' off,"`

> Is Cascadia Code even included in VSCode updates?

No idea. I don’t believe so.

> so I'm guessing that's why @kenmcd and @Ionaru have older font versions and older behaviour.

The behavior has nothing to do with the font. It is entirely how VSCode has implemented things.

**Comment by SharakPL** [comment]
Stylistic sets are embedded into font itself so how is that not relevant?

**Comment by aaronbell** [comment]
I don’t understand your question.

**Comment by SharakPL** [comment]
> 
> > so I'm guessing that's why @kenmcd and @Ionaru have older font versions and older behaviour.
> 
> The behavior has nothing to do with the font. It is entirely how VSCode has implemented things.

It's the font that provides stylistic sets, VSCode can only enable them. I'd say it's all about the font. You say it has nothing to do with the font. Care to explain why is that?

#402 Looks like `calt` actually does something... when it's turned off, so it must be enabled by defualt:
![obraz](https://user-images.githubusercontent.com/5007456/141688247-20715f28-aa09-44a7-b05e-e921d80d4a46.png)
![obraz](https://user-images.githubusercontent.com/5007456/141688262-14c01407-bf6a-48a6-89de-c5456854cab0.png)
![obraz](https://user-images.githubusercontent.com/5007456/141688313-f42040c1-9571-458b-8659-d52008c91199.png)

but it still doesn't seem to impact cursive in any way

**Comment by aaronbell** [comment]
> It's the font that provides stylistic sets, VSCode can only enable them. I'd say it's all about the font. You say it has nothing to do with the font. Care to explain why is that?

Your inherent misunderstanding is that the coding ligatures are present in `ss01`. They are not. All coding ligatures are in the `calt` feature which [should be enabled at all times](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-calt) and `ss01` only handles the italic cursive variant. However, it is up to a particular environment to actually do the work to enable it, be it via the inbuilt OS text rendering engine, or a custom one. 

The actual impact of each stylistic set is documented in this image, from the README
![stylistic_set](https://user-images.githubusercontent.com/8460297/141689671-9e811b9a-cb45-4c39-93ba-893aa317e260.png)

> Looks like calt actually does something... when it's turned off, so it must be enabled by defualt

It appears to me as well that it is enabled by default (it wasn't previously). But that may also be OS-related. I'll need to check VSCode on other systems to confirm the behavior. The fact that @kenmcd and @Ionaru need `calt` to be included to get the ligatures to function gives me pause.

**Comment by SharakPL** [comment]
> > It's the font that provides stylistic sets, VSCode can only enable them. I'd say it's all about the font. You say it has nothing to do with the font. Care to explain why is that?
> 
> Your inherent misunderstanding is that the coding ligatures are present in `ss01`.

Not at all. It was my understaning [from the start](https://github.com/microsoft/cascadia-code/issues/583#issuecomment-967804361) that `ss01` handles only cursive alternate style. It's requirement for `calt` that was unclear in this part, especially with current descrition for the example which says nothing about ligatures. Only that `calt` [is required for cursive](https://github.com/microsoft/cascadia-code#to-enable-the-cursive-form-of-the-italic-heres-the-code-you-should-use):

> #### To enable the Cursive form of the italic, here's the code you should use:
> ```
> "editor.fontLigatures": "'calt', 'ss01'",
> ```

I understand now that `calt` may be enabled by default on Windows (or maybe it's Windows Terminal that enables it...), but it's still better to include it in the settings.

> The actual impact of each stylistic set is documented in this image, from the README ![stylistic_set](https://user-images.githubusercontent.com/8460297/141689671-9e811b9a-cb45-4c39-93ba-893aa317e260.png)

That's also clear from the begining. What's unclear is the use of FiraCode example with sets that clearly are not available in Cascadia Code so imho using such example is pointless. Unless of course CC does have `'ss04','ss05',ss06','onum'` hidden somewhere, but for now I can't see it:

![obraz](https://user-images.githubusercontent.com/5007456/141691553-7244a2b5-5570-4aba-8c0d-909a082f4491.png)


Fira Code on the other hand is quite clear with their examples. Everything mentioned [in the docs](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets) is there on the font:

![obraz](https://user-images.githubusercontent.com/5007456/141691623-f4b0c848-9006-48ae-b5ad-298314986d2a.png)

**Comment by aaronbell** [comment]
> `'ss04','ss05',ss06','onum' `

That code was provided as an example of how to request font features. That's it.

**Comment by SharakPL** [comment]
I think examples **valid** for Cascadia Code would be much more appreciated.
I assure you, if I ever decide to go back to FiraCode i'll definitely not look for settings examples on Cascadia Code repo 😉

**Comment by Krysl** [comment]
> "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'"

Setting this didn't work until I deleted all items from the registry(`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`) that were related to ` Windows Terminal`'s old fonts.

**Comment by SharakPL** [comment]
@Krysl that's probably because Windows Terminal uses font embeded within the installation as you can see in the paths. It's not Cascadia font installed on your system in _C:\Windows\Fonts_ and most likely not even the same version.

Besides this issue is all about this settings being **invalid for Cascadia Code** as it was simply copy/pasted from Fira Code repository. I can see readme has been updated already with valid description, but it still contains this invalid example. Why? 🤦‍♂️ It's pretty obvious most users will simply take this invalid example and then wonder why is it not working or what these seetings not mentioned in the description even mean.

**Comment by mitsukuri** [comment]
> > `'ss04','ss05',ss06','onum' `
> 
> That code was provided as an example of how to request font features. That's it.

But what does that example, relevant only to Fira Code, have to do with Cascadia documentation, where it is irrelevant, other than puzzling and baffling people?

**Comment by mitsukuri** [comment]
For me, `"editor.fontLigatures": "'ss01'"` enables _both_ cursive and ligatures.

I came here to find out what does that mysterious `calt` mean but alas, no solid understanding even after reading through the issue, let alone the official documentation aka readme.md

**Comment by Kunal25Das** [comment]
Is it possible to only enable cursive without the symbol ?

**Comment by warhodes-dev** [comment]
To summarize this thread, the README contains the following:

> For example, in VS Code, you can enable stylistic sets (and other OpenType features) via settings.json:
> `"editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'"`

However many of these stylistic sets do not exist for Cascadia Code, making the example invalid. A user (me) may try to enable/disable some of these options which will have no effect, and will erroneously assume something is wrong. We should only provide examples of valid configurations for this font in the documentation.
