### ISSUE TITLE
Normal Weight Cascadia Code Does Not Work in Linux Emacs

### ISSUE THREAD

**Issue by drcxd** [microsoft/cascadia-code#589]
### Cascadia family version

2108.03

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows Subsystem for Linux 2, kali-linux

### Other Software

GNU Emacs 27.2(x86_64-pc-linux-gnu, GTK+ Version 3.24.24)

### What happened?

It looks like Emacs in Linux cannot use normal weight Cascadia Code.

My Emacs configuration about fonts:
```
(add-to-list 'default-frame-alist '(font . "Cascadia Code-18"))
```

After I launch Emacs, I found that the font actually takes effect is 

```
xfthb:-SAJA-Cascadia Code-light-normal-normal-*-24-*-*-*-m-0-iso10646-1 (#xE1)
```

![image](https://user-images.githubusercontent.com/24535087/138867133-8ac5fe62-6b7c-47b8-b578-d85d9abb76ff.png)

The `light` indicates the weight of the font. I tried to manually set the weight as normal, but it does not work:

```
(add-to-list 'default-frame-alist '(font . "Cascadia Code-18:weight=Normal"))
;; an alternative, it does not work as well
;; (add-to-list 'default-frame-alist '(font . "Cascadia Code-18:weight=normal"))
```

Using the font manager, I can see that the normal weight Cascadia Code is installed and could be displayed correctly.

![image](https://user-images.githubusercontent.com/24535087/138866962-d03e5076-f9ec-49f4-8633-22ea1ebe26f1.png)

Another thing worth mentioning is that by executing the Emacs command/function `set-frame-font`, Emacs will prompt candidates fonts. I can see that there is a font named `...Cascadia-Mono-normal-normal-normal...` but there is no Cascadia Code correspondence, and if I set the normal weight Cascadia Mono font, I can tell the weight is correct (normal rather than light).

![image](https://user-images.githubusercontent.com/24535087/138867851-982e93fa-0ba4-4939-8e5e-7484116ed0e1.png)

Now the font taking effect is
```
xfthb:-SAJA-Cascadia Mono-normal-normal-normal-*-24-*-*-*-m-0-iso10646-1 (#x120)
```

**Comment by efermi** [comment]
I tried to reproduce the bug and can confirm an issue, although in my case it's the Mono font that's missing the normal-normal-normal variant and Emacs picks normal-italic-normal instead. I can also see a similar issue with the variable version of the Roboto Mono font. As I understand it Emacs has its own font handling parts so the issue could lie with the program itself.
![Screenshot_20211031_212138](https://user-images.githubusercontent.com/3966555/139596966-3c22de70-9e9f-4a71-847f-eb9e350dd069.png)

**Comment by drcxd** [comment]
> I tried to reproduce the bug and can confirm an issue, although in my case it's the Mono font that's missing the normal-normal-normal variant and Emacs picks normal-italic-normal instead. I can also see a similar issue with the variable version of the Roboto Mono font. As I understand it Emacs has its own font handling parts so the issue could lie with the program itself. ![Screenshot_20211031_212138](https://user-images.githubusercontent.com/3966555/139596966-3c22de70-9e9f-4a71-847f-eb9e350dd069.png)

Thanks for youre help, I'll investigate further.

**Comment by ndegruchy** [comment]
I was having this problem on Debian 11, with Emacs 27.1.

It turns out that I had installed the variable fonts, instead of the static ones. KDE seemed find with the variable ones, but Emacs did not. Installing the static ones worked out for me.

Still not sure where the root cause lies, but this got me working.

**Comment by drcxd** [comment]
Recently I found that Emacs 29 could recognize the variable fonts correctly. With Emacs 28, I still need to use the static ones.
