### ISSUE TITLE
Installation warning on MacOS Mojave

### ISSUE THREAD

**Issue by thetuxracer** [microsoft/cascadia-code#59]
# Environment

```none
Cascadia Code version number:
Application: Fontbook
OS platform and version: MacOS Mojave 10.14.6
Screen resolution (i.e. 220dpi): 2880 x 1800

Any other software?
```

# Steps to reproduce

Download the ttf from current master. Try to install using fontbook. 

# Expected behavior

Installation should proceed without warning

# Actual behavior

User is presented with minor warning found during validation

![image](https://user-images.githubusercontent.com/141946/65251096-5bf32100-db14-11e9-8695-5202a68585f4.png)

**Comment by thetuxracer** [comment]
This is a duplicate of #53

**Comment by DHowett-MSFT** [comment]
The filer in #53 confirmed that _when they used the actual correct font file, it worked file_.
Don't use the VTT file, it is source code. Use the TTF from the releases page.
