### ISSUE TITLE
No font files in current release?

### ISSUE THREAD

**Issue by watson13j** [microsoft/cascadia-code#591]
### Cascadia family version

Cascadia Code 2108.26

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

I don't know

### Platform

any

### What happened?

The installation instructions say the font files should be in the latest release, but there aren't any ttf, woff2 or otf files in the unarchived file. Had to download the previous release to find them.

**Comment by adrian5** [comment]
@watson13j Looks fine here too. Reconfirm you downloaded the right archive and close this issue if resolved.
