### ISSUE TITLE
Braces & their ligature variants not rendering properly in VS Code `#{` `}#` `{|` `|}` `{` `}`

### ISSUE THREAD

**Issue by NoxVentura** [microsoft/cascadia-code#595]
### Cascadia family version

2110.31

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 10 Home

### Other Software

Visual Studio Code (portable edition)

### What happened?

Just freshly installed the new Cascadia variants, however the ligatures with the curly braces are not rendering properly in VS Code.  I'm using the variable TTF variants here. Regular TTF files work however. 

12px, medium:

![2021-11-01 21_33_30-Visual Studio Code _ Notebook _ Trinity Language (new) md](https://user-images.githubusercontent.com/90877277/139680066-3bae5e2d-2172-45cf-995c-9986d6193f44.png)

21px, medium:

![2021-11-01 21_34_16-Visual Studio Code _ Notebook _ Trinity Language (new) md](https://user-images.githubusercontent.com/90877277/139680074-fbe2290c-b232-4bb1-991e-aae08ca54eae.png)

**Comment by aaronbell** [comment]
Ugg. I checked all of these. Guess time to check again!

**Comment by NoxVentura** [comment]
Thanks:)

**Comment by itsFelipeGg** [comment]
hola soy principiante en la personalizacion de las font pero las ligaduras no me las deja activar me ouenden ayudar

**Comment by jhologic12** [comment]
hello everyone, i m traying the theme of my terminal but  the color combination menu not save.
