### ISSUE TITLE
Font point size appears to be 1 point larger than should be.

### ISSUE THREAD

**Issue by TerawattX** [microsoft/cascadia-code#60]
# Environment

Cascadia Code version number: 1909.16
Application (with version) used to display text: Visual Studio 2017, Word 2013
OS platform and version: Windows 10, 16299.1387
Screen resolution (i.e. 220dpi): 1920x1080

Any other software?
```

# Steps to reproduce

Simple comparison of fonts side by side in Word will show.

I typed a few copies of the same character out on 1 line in Word, then repeated it with another character on the next line, like this:
  TTT
  AAA
  ZZZ
I then set the first character per line to 10pt Calibri, the 2nd to 10pt Consolas, and the 3rd to 10pt Cascadia Code.  Cascadia was noticeably taller:
![FontSizes](https://user-images.githubusercontent.com/36713063/65252188-874f1f00-dac6-11e9-867b-53e5ebc975ea.png)

I then set the first 2 characters to 11pt and they appeared as the same height as the Cascadia character:
![FontSizes2](https://user-images.githubusercontent.com/36713063/65252346-ce3d1480-dac6-11e9-9afa-aa1f18d2358a.png)

# Expected behavior

Characters should be the same size as other fonts.

# Actual behavior

Cascadia Code appears to be 1pt larger than other fonts of the same size (Calibri and Consolas at least).

**Comment by Amoystyle** [comment]
too Bold in Visual Studio 2019/2017/2015/2013

**Comment by adrientetar** [comment]
If anything, Calibri is [smaller than usual](https://www.scotxblog.com/writing/how-big-is-14-point-font-that-nerdy-question-is-now-before-the-michigan-supreme-court/).

**Comment by thisdarktao** [comment]
I've noticed this too, and it's why I'm not using the font. It's either slightly too small at 12 or too big at 13.

**Comment by aaronbell** [comment]
The display height of fonts is determined by the [metrics](http://westonthayer.com/writing/intro-to-font-metrics/) baked into an individual font file. This is to say that, in Cascadia Code, the letters are drawn bigger at a given point size than in either Calibri or Consolas. In your example, the /A in Cascadia Code is 1420 funits tall, whereas Calibri is 1306 funits tall. As such, when the letter falls _just so_ on the pixel grid, it will appear to be 1 pixel taller. Or it might be the same size. Cascadia Code is what we call "large on the body"—the letters are larger given the size of the glyph boundary (distance from descender to ascender). This kind of feature helps it render larger at smaller point sizes and makes it more clear. 

This is not a bug or anything that needs (or should) to be fixed. If letters are too large for your taste, simply tweak the font size (you can try decimal sizes too if you want depending on the application) until it is the size that you want it to be.
