### ISSUE TITLE
Am I installing the code correctly?

### ISSUE THREAD

**Issue by kamal-choudhary** [microsoft/cascadia-code#602]
### Cascadia family version

2110.31

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

macOS 11.1

### Other Software

Visual Studio Code

### What happened?

Hi, this is not actually a bug.

I am just not sure whether I installed the font correctly or not.

Here is what I did:

I opened the ZIP file and there were 3 folders i.e. otf, ttf & woff2.

As recommended, I wanted to install the "ttf" font. But I wasn't sure that should I drag my complete folder "ttf" to the "Font Book" app OR just install one font file.

So, I just dragged the complete "ttf" folder to the Font Book (MacOS app) and it installed all the fonts inside this folder.

Now, I feel that probably only one font file needed to be installed. but I am just not sure.

Can anyone please help me eliminate my confusion?

Note: there was a "static" folder inside the "ttf" folder.

**Comment by kamal-choudhary** [comment]
Well, everything is working fine on my side. Just wanted to confirm that whether I needed to only install one font file from the `TTF` folder OR the complete `TTF` folder?

**Comment by aaronbell** [comment]
You don’t need to install the full folder, no. Just the font variants that you want. At a minimum, I’d suggest Cascadia Code and Cascadia Code Italic.

**Comment by kamal-choudhary** [comment]
I got it. I'll uninstall the unnecessary fonts. Thanks for your time @aaronbell.
