### ISSUE TITLE
Ligature Character is duplicated on wrapped line

### ISSUE THREAD

**Issue by SauceMan8** [microsoft/cascadia-code#604]
### Cascadia family version

2102.025

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

I don't know

### Platform

Windows 10 10H2

### Other Software

Visual Studio 2022: V 17.0.1
Cascadia code light, size 9, 12, 22. (I only tried those 3)

### What happened?

![image](https://user-images.githubusercontent.com/28791284/143172148-c0da6c6e-3d0c-4fbd-837f-dc329920717b.png)
When a line wraps on a ligature, specifically "/>", the second character is duplicated on the next line. 

The image shows the issue. The actual text is: ...'name ="fileName"/>' 

I tested this with '++' and got the same issue, but'=>' worked correctly.

**Comment by aaronbell** [comment]
Fascinating. Unfortunately, I don't know if there is a way to fix this issue in font as it appears to be editor related. Essentially, what I would guess is happening, is that VS is duplicating the code that is wrapping onto the new line. So the font thinks that the text string continues, but it is being clipped. 

I'd suggest inquiring with the Visual Studio folks on this.

**Comment by SauceMan8** [comment]
Moving issue to Visual Studio
