### ISSUE TITLE
the ligature does not work in Visual Studio 2017 on the symbol '->'

### ISSUE THREAD

**Issue by ETEMORY** [microsoft/cascadia-code#608]
### Cascadia family version

2110.31

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (static)

### Platform

Windows10 Educational 20H2 (OS Build 19042.1348)

### Other Software

Visual Studio Community 2017
version 15.9.41

### What happened?

the ligature did not work on the symbol '->' when I was Coding C++ in Visual Studio ,but it worked in VScode.

![企业微信截图_20211210183849](https://user-images.githubusercontent.com/59430309/145561009-66d22a9b-6385-4dbe-8fd5-8ca7f88224b2.png)
Visual Studio

![企业微信截图_20211210183919](https://user-images.githubusercontent.com/59430309/145561014-b36934c1-2d0c-4eef-a17e-8d72417271f9.png)
VScode

**Comment by aaronbell** [comment]
Unfortunately this is a known issue in Visual Studio: https://github.com/dotnet/wpf/issues/109
