### ISSUE TITLE
Accessibility: Dyslexic and Neurodiverse friendly fonts

### ISSUE THREAD

**Issue by MobileRez** [microsoft/cascadia-code#61]
Love this new font but I am unable to find any info on this for in relation to dyslexia and neurodiversity. I think it was the One Note team that created the Fluent Calibri and Fluent Sitka fonts to help with readability for those with dyslexia, when used in presentations, it also increases readability for code for more members of the audience and allows a larger room to read code without having to zoom in with the editor. this is especially important when it comes to terminal windows where word crowding is an issue, but the windows system, terminal and editors, were not designed for that type of font so it is either not possible to set, or changes readability in other ways.

sample images of code editor using these fonts are not attaching on this issue post for some reason so I can provide samples from some other form. The accessibility arm of the Core C&E team also is aware of this and potential uses issues. Ideally id like to get this as a font to change for windows system default but if there is an option to change this, I seem to be missing where its located in windows 10.

**Comment by aaronbell** [comment]
Hello! I'm not exactly sure what you are hoping for with this bug. Many of the features that you're describing would be at the application level rather than built into the font itself. Can you help us understand what you're looking for?

**Comment by MobileRez** [comment]
@aaronbell I do not claim to be an expert in the terminal or console windows, but I was told to post this issue for this font. unless there is an option to effect Letter, word, and row spacing in these environments, it must in fact come from the font. I can set up a call to explain how this would differentiate and it looks in other scenarios and how this might relate to this environment. Possibly even make an offshoot of this font that would work with those needs. 

However the system or application level options do not currently address these needs. Have you looked at the fonts I described in the original post?

**Comment by aaronbell** [comment]
Yes, I am quite familiar with the fonts you mentioned, and know the folks that produced them. This is something that we can consider for the future.

In my opinion, though, this sort of functionality should be built into the applications rather than in the font. I suggest filing a bug on [Windows Terminal](https://github.com/microsoft/terminal) and suggest that they implement customization of line and letter spacing (word spacing is difficult within a monospaced environment).

**Comment by aaronbell** [comment]
As it appears there is no further discussion on the thread, I'm going to close it. Thanks!
