### ISSUE TITLE
"- - - - -" becomes "----------------" in terminal

### ISSUE THREAD

**Issue by nowshed-imran** [microsoft/cascadia-code#611]
### Cascadia family version

2111.01

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (static)

### Platform

Archlinux

### Other Software

I am using Linux with KDE Plasma as DE.

I can provide other information if necessary.

### What happened?

After `git pull` here is the problem:

![image](https://user-images.githubusercontent.com/22009014/148083581-c4230980-4141-48f4-858f-80c449dae00b.png)

As you can see, upto three "- - -" spacing is correct, but after that it becomes "----". 

![image](https://user-images.githubusercontent.com/22009014/148083830-9659208a-2bcd-429a-ae87-e7f6a14e6e84.png)

**Comment by aaronbell** [comment]
Hi, yes, this is intentional to enable creation of lines using hyphens. At this time there is no way to disable this behavior in the coding ligature version (Cascadia Code).

**Comment by nowshed-imran** [comment]
Ok, thanks for the reply.
