### ISSUE TITLE
does cascadia code support nerd fonts icons?

### ISSUE THREAD

**Issue by bryant-the-coder** [microsoft/cascadia-code#612]
hi there. the title says it all... does it supports nerd fonts icons? cause windows terminal tends to not render italics properly in neovim. how can i solve that?

**Comment by mfocko** [comment]
I patch the latest Cascadia Code with Nerd Font patcher and it seems to work fine

**Comment by bryant-the-coder** [comment]
will try thx

**Comment by bryant-the-coder** [comment]
it does not work
![image](https://user-images.githubusercontent.com/92417638/148625887-b5d41c40-f949-41bd-87cf-cc83ef721ff9.png)
![image](https://user-images.githubusercontent.com/92417638/148625892-cbb10066-7e7e-4d42-a629-df235ab29b69.png)

**Comment by mfocko** [comment]
are you sure that you're using the patched font? cause I don't have any problems with that…

btw the name of the font changes

    „Cascadia Code“ → „CaskaydiaCove Nerd Font“

and the basename is without spaces, e.g. PL version of Cascadia becomes: `CaskaydiaCovePL`

(Cascadia Mono without ligatures, doesn't change to caskaydia, not sure why)

**Comment by bryant-the-coder** [comment]
send me the download link

**Comment by gusbemacbe** [comment]
> send me the download link please

Go to https://github.com/ryanoasis/nerd-fonts, go to the folder `patched-fonts` and go to `CascadiaCode`.

**Comment by bryant-the-coder** [comment]
btw how to enable font ligatures in windows terminal? italics too

**Comment by gusbemacbe** [comment]
You need to take the non-mono and non-Windows-compatible fonts:

Take:

- [Caskaydia Cove Regular Nerd Font Complete.otf](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/CascadiaCode/Regular/complete/Caskaydia%20Cove%20Regular%20Nerd%20Font%20Complete.otf)
- [Caskaydia Cove Bold Nerd Font Complete.otf](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/CascadiaCode/Bold/complete/Caskaydia%20Cove%20Bold%20Nerd%20Font%20Complete.otf)

@ryanoasis of Nerd Fonts do not patch the italic fonts, but I can patch for you. Please wait that I am going to patch.

**Comment by bryant-the-coder** [comment]
y otf instead of ttf?

**Comment by gusbemacbe** [comment]
Yes, I am patching the OTF Code (not Mono) and Code PL fonts.

**Comment by bryant-the-coder** [comment]
ok... so should i download the zip from @ryanoasis ?

**Comment by gusbemacbe** [comment]
Yes, but it does not come with italic fonts you want. I finished the patcher. I'll send the compressed file to you here.

**Comment by gusbemacbe** [comment]
Ready. Get [patched-fonts.zip](https://github.com/microsoft/cascadia-code/files/7834721/patched-fonts.zip).

**Comment by bryant-the-coder** [comment]
how do u patch it?

**Comment by bryant-the-coder** [comment]
i dun think it really work with some stuff. 
![image](https://user-images.githubusercontent.com/92417638/148675823-c96155a8-1682-481d-873b-a09a436a3bee.png)

**Comment by bryant-the-coder** [comment]
only caskaydiacove nerd font renders everything properly... but the words to shiny lol

**Comment by gusbemacbe** [comment]
You need to have Docker installed. 

1. Pull @ryanoasis' original image from [](https://hub.docker.com/r/nerdfonts/patcher):

    ```sh
    docker pull nerdfonts/patcher
    ```
2. Create a folder where you want to save the original fonts and a subfolder where you'll save the patched fonts. See like (observe that I am a Linux user, if you are a Windows user, you may use WSL or PowerShell):

   ```sh
   docker run --rm -v '$HOME/.local/share/fonts/Cascadia Code':/in -v '$HOME/.local/share/fonts/Cascadia Code/patched':/out nerdfonts/patcher -c --careful
    ```

**Comment by bryant-the-coder** [comment]
y need docker?

**Comment by gusbemacbe** [comment]
> only caskaydiacove nerd font renders everything properly... but the words to shiny lol

If you find too shiny, you need to change the ANSI codes and colours. I never tried to modify it in Noevim at PowerShell. Maybe you should ask Noevim forum



> y need docker?

Yes, you can get Docker from https://docs.docker.com/get-docker/. It is totally free and easy.

**Comment by bryant-the-coder** [comment]
i know y i need to use docker?

**Comment by gusbemacbe** [comment]
> i know y i need to use docker?

Yes, because these commands, I gave you, depend on Docker. If you have WSL installed, you can install quick Docker and run the commands normally.

If you do not want to install Docker for Windows or on WSL, you need to download @ryanoasis' repository and run the `font-patcher` file. But it needs to run on WSL because it is a Shell script. You also need to install FontForge.

If you do not want to install a lot of stuff, you can use just Docker. It is lightweight, and you are not forced to download his repository and FontForge. Docker already has and does it. 

After, you can uninstall Docker if you want.

**Comment by bryant-the-coder** [comment]
can u show me how? newbie lol

**Comment by gusbemacbe** [comment]
Do you have WSL installed? If no, you can get the small and quick command. Open PowerShell as administrator and run the only command:

```
wsl --install
```

It will enable WSL and its features, then it will install automatically Ubuntu. Restart your PC. Ubuntu will open itself and will ask you to create your Unix user and password. Your Windows Terminal will add automatically Ubuntu to the list. 

After that, run the commands at WSL at Windows Terminal:

```sh
# It will update and upgrade Ubuntu system
sudo apt update && sudo apt upgrade

# Install some tools for Docker
sudo apt install apt-transport-https ca-certificates curl gnupg software-properties-common

# Add Docker's GPG to be authorised by Ubuntu
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# As the Ubuntu version is 20.04 as WSL chose automatically
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

# It will update to detect new packages as Docker
sudo apt update

# Set Docker's repo as default instead of Ubuntu's repo
apt-cache policy docker-ce

# Finally, you can install Docker
sudo apt install docker-ce

# But you need to start Docker before running those commands I gave you. Verify if the dot is green. 
sudo systemctl status docker
 
# To run Docker without sudo to run the commands normally
sudo usermod -aG docker ${USER}
```

Ready, you can run those Nerd Fonts' `font-patcher` commands I gave below.

**Comment by bryant-the-coder** [comment]
i dun have wsl :(

**Comment by bryant-the-coder** [comment]
can u teach me how u patch those fonts?

**Comment by gusbemacbe** [comment]
If you do not have WSL, you can download and install a Windows version of Docker: https://docs.docker.com/desktop/windows/install/

1. Install Docker. 
2. Restart your PC.
3. Start Docker. 

Choose any original monospaced fonts, including Cascadia Code. 

Now open Windows Terminal and select PowerShell:

1. Create a folder and a subfolder:

```sh
mkdir ~/fonts/patched
```

2. Move the original fonts you picked to the `~/fonts`. If you do not know where the folder `fonts` is in Explorer, then run the command:

```
explorer.exe .
```

3. Now run the commands:

```
docker run --rm -v ~/fonts/:/in -v ~/fonts/patched:/out nerdfonts/patcher -c --careful
```

It will begin to patch the fonts. It may take a lot of time. Once concluded patch, run the command:

```
cd ~/fonts/pacthed && explorer.exe .
```

Voilà!

**Comment by bryant-the-coder** [comment]
it will install all font? but i want fonts that supports italics and icons. sorry if i m kinda annoying :((

**Comment by gusbemacbe** [comment]
> it will install all font? but i want fonts that supports italics and icons. sorry if i m kinda annoying :((

It will not install automatically the fonts into Windows fonts. You who will install manually the fonts. It only will create the fonts, patching all Nerd Fonts icons. It also will create the italic version of those fonts, with all Nerd Fonts icon. 

But do not waste time. I have already patched for you. Get that zipped file I sent below. It came with the italic fonts, you can see: 

![image](https://user-images.githubusercontent.com/2257024/148677911-b1cf2982-bac4-4ec4-b4c8-f28dc1874c4b.png)

It is an italic font. It also came with Nerd Fonts icons:

![image](https://user-images.githubusercontent.com/2257024/148678103-3da6a311-421b-4535-a9ea-e9169c9280c5.png)

**Comment by bryant-the-coder** [comment]
wait how u edit those fonts? curious

**Comment by gusbemacbe** [comment]
> wait how u edit those fonts? curious

I patched all the fonts with Nerd Fonts' `font-patcher`. I have already taught you those commands. Remember that last command patches ALL the fonts, including the italic fonts, with ALL Nerd Fonts icons. It was exactly what you asked.

If you mean this second image to view the font, I use the extension [Font Preview](https://marketplace.visualstudio.com/items?itemName=ctcuff.font-preview) on VSCode.

**Comment by bryant-the-coder** [comment]
> If you do not have WSL, you can download and install a Windows version of Docker: https://docs.docker.com/desktop/windows/install/
> 
> 1. Install Docker. 
> 2. Restart your PC.
> 3. Start Docker. 
> 
> Choose any original monospaced fonts, including Cascadia Code. 
> 
> Now open Windows Terminal and select PowerShell:
> 
> 1. Create a folder and a subfolder:
> 
> ```sh
> mkdir -p ~/fonts/patched
> ```
> 
> 2. Move the original fonts you picked to the `~/fonts`. If you do not know where the folder `fonts` is in Explorer, then run the command:
> 
> ```sh
> explorer.exe .
> ```
> 
> 4. Pull the image:
> 
> ```sh
> docker pull nerdfonts/patcher
> ```
> 
> 4. Now run the commands:
> 
> ```sh
> docker run --rm -v ~/fonts/:/in -v ~/fonts/patched:/out nerdfonts/patcher -c --careful
> ```
> 
> It will begin to patch the fonts. It may take a lot of time. Once concluded patch, run the command:
> 
> ```sh
> cd ~/fonts/pacthed && explorer.exe .
> ```
> 
> Voilà!

i wanna ask. this will patch including italics? i wanna patch agave as i found it working just fine for me

**Comment by bryant-the-coder** [comment]
what is the original fonts u picked?
the folder and subfolder can be created at anywhere?

kinda hard to understand lol. mayb a recording might help as i m a visual learner

**Comment by gusbemacbe** [comment]
> i wanna ask. this will patch including italics? i wanna patch agave as i found it working just fine for me

Yes, this will. It always will patch everything IN A FOLDER. 

> what is the original fonts u picked?

I picked from this repo. You can check the releases list at this repo: https://github.com/microsoft/cascadia-code/releases/. In the zipped file, you find the sub folder `otf` you may want. Unzip only Code and Code PL, but do not unzip the Mono versions as you want the ligatures that are available only in the Code and Code PL versions. 

> the folder and subfolder can be created at anywhere?

Yes, and remember to change the path in those commands that I gave you. 

> kinda hard to understand lol. mayb a recording might help as i m a visual learner

Well, I am a Linux user. I do not use Windows. But I can boot into Windows to record how I do if you want.

**Comment by bryant-the-coder** [comment]
can u boot to windows. i m not really an intermediate or an expert

**Comment by bryant-the-coder** [comment]
(◡ ω ◡)

**Comment by gusbemacbe** [comment]
Hello.

Sorry, I had to update Windows because the terminal did not work. I did not update it for months. But I recorded. I posted the GIF images here. If you prefer watching and pausing the videos, I'll send you the compressed files at the end. 

1. I download and install Docker. I must restart:

![1 - Downloading and installing Docker](https://user-images.githubusercontent.com/2257024/148694503-caf904a8-bc3a-49fa-bfa0-51ce6af86651.gif)

2. After restarting the computer, Docker will start itself and I may set a bit:

![2 - Setting Docker](https://user-images.githubusercontent.com/2257024/148694527-d94effa2-919b-47c7-a9bb-f1652a1b7b9c.gif)

3. After closing Docker, I open the Windows Explorer and go to the `Downloads` folder, where I'll create a new `Fonts`. After I am going to GitHub page and Microsoft repository, in which I click the releases list. I download it and place on the folder `Fonts`. I chose only 4 fonts because the font patcher will take a bit of time. I created the subfolder `patched`: 

![3 - Downloading fonts and creating folders](https://user-images.githubusercontent.com/2257024/148694609-bb72e847-a31e-44c2-9384-e047d7a6bed8.gif)

4. Open Windows Terminal, with the mouse right click to select PowerShell. On PowerShell, I am going to pull the image from Docker, and after I copy and paste the command, and change the paths that appoints to the folder `Fonts that I created at the folder `Downloads`. Then I begin to patch. It may take a lot of time:

![4 - Pulling the images from Docker and patching the fonts](https://user-images.githubusercontent.com/2257024/148694730-f0d7ab92-81e8-433d-8107-670e40abccbe.gif)

Finally, voilà. 

If you prefer watching and pausing the videos, here is the compressed file of videos: [Videos.zip](https://github.com/microsoft/cascadia-code/files/7835628/Videos.zip)

**Comment by bryant-the-coder** [comment]
i will try. if i got any problem i will get back to u. is there any easier way to contact u?

**Comment by gusbemacbe** [comment]
You can just leave the problems here.

**Comment by bryant-the-coder** [comment]
noted eith thanks

**Comment by bryant-the-coder** [comment]
wait i need wsl or is it optional?

**Comment by bryant-the-coder** [comment]
i dont really see .otf all the fonts like fira code and jetbrains

**Comment by bryant-the-coder** [comment]
$ docker run --rm -v D:\Fira_Code_v6.2\ttf:/in -v D:\fonts\patched\firacode patched:/out nerdfonts/patcher -c --careful
docker: invalid reference format.
See 'docker run --help'.

**Comment by bryant-the-coder** [comment]
any other good fonts with ligatures and italics besides jetbrains?

**Comment by gusbemacbe** [comment]
> wait i need wsl or is it optional?

It is optional. Only if you want. But WSL is a very good tool for developers. It is a native embed Linux system for Windows. 



> any other good fonts with ligatures and italics besides jetbrains?

Free fonts:

- https://github.com/tonsky/FiraCod
- https://be5invis.github.io/Iosevka/
- https://rubjo.github.io/victor-mono/

Paid fonts:

- http://www.fsd.it/fonts/pragmatapro.htm

> $ docker run -rm -v D:\Fira_Code_v6 2\tff:/in -v D:\fonts\patched\firacode patched:/out nerdfonts/patcher -c --careful
> docker: invalid reference format
> See 'docker run --help'

There was a space in the folders names. It should be like:

```
# Incorrect
# \Fira_Code_v6 2\
# \firacode patched

# Correct
# \'Fira_Code_v6 2'\
# "\'firacode patched'

# The presence of space requires quotes "" or ''. 
# Now
docker run -rm -v D:\'Fira_Code_v6 2'\tff:/in -v D:\fonts\patched\'firacode patched':/out nerdfonts/patcher -c --careful
# Or
docker run -rm -v "D:\Fira_Code_v6 2\tff":/in -v "D:\fonts\patched\firacode patched":/out nerdfonts/patcher -c --careful
```

**Comment by aaronbell** [comment]
Alright gents. This discussion has gone a bit far off topic :).

Please take any further discussion regarding patching Cascadia code elsewhere, such as the nerdfonts repro.

There is already an open issue for Cascadia to support so this issue is tracked.

**Comment by bryant-the-coder** [comment]
ok
