### ISSUE TITLE
Something strange with font rendering

### ISSUE THREAD

**Issue by marshallovski** [microsoft/cascadia-code#618]
### Cascadia family version

2111.001

### Cascadia family variant(s)

Cascadia Mono (the version without ligatures)

### Font file format(s)

I don't know

### Platform

Windows 8.1 Pro 64-Bit

### Other Software

Mozilla Firefox Developer Edition 95.0b4 (64 bit version)

### What happened?

180-200% page zoom:
![изображение](https://user-images.githubusercontent.com/68496774/156924374-f3aa3c9d-9301-4b25-ba8d-d3a8f9c518b0.png)

normal page zoom:
![изображение](https://user-images.githubusercontent.com/68496774/156924425-a6412b48-9cab-452d-ac24-271912907068.png)

I'm found this bug on https://stackoverflow.com/questions/10036977/best-way-to-include-css-why-use-import

**Comment by mfocko** [comment]
Fedora 35, Firefox 97, can't reproduce, must be Windows related

**Comment by aaronbell** [comment]
Strange. I haven't been able to repro it. Sorry!
