### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JAYD3V** [microsoft/cascadia-code#619]
## Documentation that Thoroughly Documents the Stylistic Sets Currently Supported by Cascadia Codes Latest Version

I couldn't find any documentation that documents the stylistic sets. I know that many of them have to do with languages that I don't speak, but I know some of them change ligatures and characters, but I can't find where I got that information from originally.

If there is documentation on them, then my request is that a link be added to the `./README.md` document in the section that covers Stylistic sets.

**Comment by kenmcd** [comment]
Image from the front page of this repo:

![image](https://user-images.githubusercontent.com/844920/157334116-beff716d-f213-4287-91b6-9e4019d43ca2.png)

Black text is original (disabled); blue text is enabled.
Is there anything else that is needed?

**Comment by aaronbell** [comment]
Looks like this has been solved. Thanks!
