### ISSUE TITLE
the "=" sign is too much close to the attribute in html 

### ISSUE THREAD

**Issue by Sdmmjl759** [microsoft/cascadia-code#623]
### Cascadia family version

2111.01

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

macOS monterey , vsCode 1.65.2

### What happened?

the "=" sign is too much close to the attribute in html.
Actually in every pages "=" has no letter spacing with the word before it, but in html tags we shouldn't use 'spaceKey' between attribute and "=" and when we don't do that it just doesn't look nice

html:
<img width="187" alt="Screen Shot 2022-03-13 at 12 26 33 AM" src="https://user-images.githubusercontent.com/97896143/158034712-f95332ee-1beb-4343-a42a-f1b17216e00f.png">
.

jsx:

<img width="308" alt="Screen Shot 2022-03-13 at 12 27 22 AM" src="https://user-images.githubusercontent.com/97896143/158034734-c5ade084-9a4e-41f5-bf9f-6da4d1b166d8.png">

**Comment by CodeCrazy-ywt** [comment]
It seems that the italic texts are mechanically rendered, which means that there is no italic file. Try installing the italic font file?

**Comment by aaronbell** [comment]
Looks like this has been resolved. Thanks! :)
