### ISSUE TITLE
[Feature Request] Support for new icons

### ISSUE THREAD

**Issue by solairen** [microsoft/cascadia-code#625]
# Description of the new feature/enhancement (with images if possible)
I've been using Cascadia Code PL for a long time and I've started to use `oh-my-posh`.  Cascadia Code does not support some icons.
Can you add support for those icons:
- uf817
- uf07b
- uf044
- uf046
- uf692
- ue23a
- uf00d
- uf42e
- uf489
- ue22f
- uf583
- uf582
- uF179
- uE62A
- uF31b
- uF17C
- ufd31
- ufd03
- uE7AD

Now, I have to use `MesloLGM NF` font to be able to see those icons.

**Comment by Finii** [comment]
Just a side note.

Some of the codepoints you mention will be dropped from Nerd Fonts, the glyphs move to other codepoints.
Affected are `F500` - `FD46`.

Iirc there is a new tool for oh-my-posh to automagically change the codepoints
* https://github.com/JanDeDobbeleer/oh-my-posh/pull/3411
* https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404846809

**Comment by solairen** [comment]
Ok, thanks for the info.
