### ISSUE TITLE
Feature Request: stylistic for single character

### ISSUE THREAD

**Issue by Avimitin** [microsoft/cascadia-code#626]
# Description of the new feature/enhancement (with images if possible)

I really like the `f`, `l` cursive style, but `s` and `r` is so hard to read. Is it possible to enable cursive style for single character? Like the Iosevka implementation: https://github.com/be5invis/Iosevka/blob/master/doc/character-variants.md.

# Proposed technical implementation details (optional)

**Comment by aaronbell** [comment]
Unfortunately, this is not possible at this time on a large scale. If you want a specific letter to be implemented, you'd need to fork the repro, update the UFO, and build it yourself. 

Hopefully in the future we will be able to offer a customizer tool, but that is not on the roadmap...yet.
