### ISSUE TITLE
Feature Request: High lowercase letters to have a lower or same height than the uppercase letters

### ISSUE THREAD

**Issue by rafael-c-pires** [microsoft/cascadia-code#627]
# Description of the new feature/enhancement (with images if possible)

Some of the lowercase letters have a higher height than all uppercase letters. For example, the letters 'f', 'd', 'b', 'l', 'k', are higher than the height of the uppercase letters, and some lowercase letters are not, which is the case of 't' for instance. 

This makes the font have a lot of different heights for the different characters (at least 4, if we count the lowest lowercase letters, the highest lowercase letters, the ones in the middle (like 't' for example), and the uppercase letters (which have the same height, from what I could see).

![image](https://user-images.githubusercontent.com/56032484/163097928-266a7d9c-6c6c-4b9c-83e4-b8db61a227f1.png)

The image above is a screenshot of Visual Studio 2022, using the Cascadia Code Semilight font.

# Proposed technical implementation details (optional)

In my opinion, it would be a great improvement in readability if the highest lowercase letters had a lower or same height than the uppercase ones, and also if they have a standard height, which is not the case with the 't', for example, that's also a high letter.

I'm not a designer, and if by any means it's like this by design choice, I'm sorry, I don't want to criticize. I love Cascadia Code and use it everywhere, but something has always bothered me, and didn't know what it was, and now I finally found it. Please consider the possibility of making this improvement or something based on it that could improve the readability with all the height variants.

**Comment by kazuoteramoto** [comment]
Ascenders being higher than caps is true of many fonts, also is usual to make ascender higher when writing also! 

Refs:
https://material.io/design/typography/understanding-typography.html#type-properties
https://archive.org/details/librodimgiovamba00pala

**Comment by aaronbell** [comment]
Hi! Yes, this was a design intention and I'm not planning to change it at this point. Glad you've enjoyed using the font!
