### ISSUE TITLE
Feature Request: Provide italics version

### ISSUE THREAD

**Issue by cool-RR** [microsoft/cascadia-code#63]
I love the italics version of Consolas, and I use it for comments. I wish Cascadia had an italics version too.

**Comment by rschr** [comment]
Italic, Bold, and Bold+Italic typeface definitions would indeed be needed, many IDEs make use of them, and algorithmically produced italic/bold typefaces never look really good.

**Comment by vsalvino** [comment]
I would recommend looking to IMB Plex Mono, Courier Prime, or Operator Mono for inspiration which provide a more script-like italic versus just a slanted/oblique version.

**Comment by rschr** [comment]
Thanks, I'll have a look into those. Actually there's no shortage of code fonts these days; Consolas is good, so is Noto Sans Mono. I really like Cascadia Code's typeface, though...

**Comment by vsalvino** [comment]
Agreed, we are living in a golden era of monospace typography! Consolas is also quite a good font, albeit more neutral in design. But if you want to use cascadia as an all around programming font then having weights and styles would be nice to please us vain developers :)

**Comment by up-to-you** [comment]
The world's most popular Jetbrains IDE family use Regular, Heavy, Italic types for different cases in Font's rendering, thus `Cascadia` is not applicable there. Hope Heavy and Italic derivatives will coming soon.

**Comment by tomByrer** [comment]
I like ]Victor Mono's italics](https://github.com/rubjo/victor-mono/#a-programming-font-with-semi-connected-cursive-italics-and-symbol-ligatures), & I hope similar script-italics are added here.  Helps make italics stand out better.

**Comment by mdtauk** [comment]
I would definitely as my voice to calls for a true italic, and not just an oblique

**Comment by mcendu** [comment]
Please rename this issue as bold is not covered by the title but is covered by the contents.

**Comment by DHowett-MSFT** [comment]
The request for more weights is actually in #128.

**Comment by WTFox** [comment]
Is this in the pipeline for a future release?

**Comment by MiguelMachado-dev** [comment]
Is this going to happen?
I wish Cascadia had an italics version too.

**Comment by FrostyJet** [comment]
This is one of my dreams :)))) Hope it will come true

**Comment by TheSETJ** [comment]
I'll be cool, especially if there is a cursive version of italic.

**Comment by AnsonH** [comment]
It would be very awesome if the italic is not simply a slanted version of regular font. I think [IBM Plex Mono](https://fonts.google.com/specimen/IBM+Plex+Mono) is a great example of italic font done right

**Comment by adrianslupu** [comment]
Monospace font geek here, please don't use Dank Mono for any reference, the originator font for mainstream script italics is Operator Mono, I find Dank Mono a poorly designed font, and I've seen literally every programming font you can find on the web, even really obscure ones that you'll never see.

Victor Mono is a good example of script italics, Cartograph CF is again nice, Operator Mono also fits the bill, but I think script italics is a bit much, I think something along the lines of what Consolas has, subtle stylistic touches on the italics will fit the bill, Iosevka also does this and there's a really nice new comer, the font which has now become my daily driver for the past couple of months, Recursive Mono (i use the Semicasual style), they all have similar approaches to their italics, really subtle touches on various letters, to give it that distrinct look.

I think italics done on the subtle side are much better than script, that's my personal opinion and should be the most balanced approach to please everyone. Don't get me wrong, if the Cascadia team has the bandwidth, do both, or go full script, but I think there are enough devs that hate the script italics and they are really easy to mess up and become something else.

**Comment by TheSETJ** [comment]
I found another font that has good italic: [Recursive](https://www.recursive.design/). I wish it had ligatures built-in.

**Comment by adrianslupu** [comment]
@TheSETJ 
> I found another font that has good italic: [Recursive](https://www.recursive.design/). I wish it had ligatures built-in.

I'm not sure if you activated ligatures in VSCode (if that's what you're using) and I did mention this font in my comment above

>does this and there's a really nice new comer, the font which has now become my daily driver for the past couple of months, **Recursive Mono** (i use the Semicasual style), they all have similar approaches to their italics, really subtle touches on various letters, to give it that distinct look.

![image](https://user-images.githubusercontent.com/63045348/95907456-3fbbc500-0da4-11eb-835e-b6ca2fa1b97a.png)

**Comment by TheSETJ** [comment]
> @TheSETJ
> 
> > I found another font that has good italic: [Recursive](https://www.recursive.design/). I wish it had ligatures built-in.
> 
> I'm not sure if you activated ligatures in VSCode (if that's what you're using) and I did mention this font in my comment above
> 
> > does this and there's a really nice new comer, the font which has now become my daily driver for the past couple of months, **Recursive Mono** (i use the Semicasual style), they all have similar approaches to their italics, really subtle touches on various letters, to give it that distinct look.
> 
> ![image](https://user-images.githubusercontent.com/63045348/95907456-3fbbc500-0da4-11eb-835e-b6ca2fa1b97a.png)

I had it enabled from before. Odd that it's not working for me!

**Comment by patrickfatrick** [comment]
With Recursive you need to download the zip from the github repo and use the "Recursive_Code" fonts.

**Comment by shubhamkumarpanday** [comment]
Requesting to add Italics to cascadia code. 
Hope will consider my suggestion

**Comment by coxackie** [comment]
Any updates here? There is so much interest...

**Comment by rashil2000** [comment]
@DHowett-MSFT are there any plans for this? I don't see anything in the roadmap or elsewhere. 

The [latest](https://github.com/microsoft/terminal/releases/tag/v1.6.10272.0) release of Windows Terminal  supports inline italics, and Cascadia Code's programmatically generated italic variant looks, well, pretty ugly.

Would love to see an italics version of this, like Consolas itself. It's the only thing that's keeping me from using Cascadia :(

**Comment by colopatiron** [comment]
I love the font, but I went back to Iosevka and JetBrains Mono because of the lack of italics.
As soon as italics are added, I will switch back.

**Comment by Uxorious** [comment]
What happened to Italics ... it looks handwritten now!

**Comment by donn** [comment]
What is this. What am I looking at.

![image](https://user-images.githubusercontent.com/12652988/119917505-fbfa8200-bf66-11eb-8031-cdb00f81ebd0.png)

**Comment by donn** [comment]
𝒜𝓅𝑜𝓁𝑜𝑔𝒾𝑒𝓈

**Comment by mdtauk** [comment]
> Don't be mean guys. Someone put a lot of work into this and there are many other fonts to choose from.

It's easy to criticise, but font design is an art form, and there is obviously an intent to add a specific cursive flare to Cascadia.

If you don't like the cursive style, than please request an oblique version, and be constructive and kind in how you respond.

If you have issues reading particular glyphs, then mention it in a constructive and kind manner.

**Comment by donn** [comment]
Fair enough. I deleted my messages and I sincerely apologize. There is feedback from a lot of users in #468 as to why we'd simply prefer an oblique version.

**Comment by dmstern** [comment]
Great work, I like it! 💯👍

**Comment by rschr** [comment]
Excellent! This really has become a well made and very usable font. Right now I'm trying it in both my development environments and my Linux terminal, and I really can see myself staying with it.
