### ISSUE TITLE
Can we have an edition with slashed zero as default?

### ISSUE THREAD

**Issue by gengzhao2020** [microsoft/cascadia-code#631]
# Description of the new feature/enhancement (with images if possible)
It's fine to enable feature `ss19` of Cascadia Mono in VS Code and Windows Terminal, but in Microsoft Edge and other text editors, you just cannot do that. I have tried `opentype-feature-freezer`, but it's not working with feature `ss19`. I hope an edition with slashed zero as default can be released.

**Comment by JAYD3V** [comment]
Unless you have a good reason, I don't see the justification for putting in the work. It takes proffessional developers time and money to maintain opensource projects, only so much work can be done by those who do the work. Its critically important that the work that opensource projects (like this one) take on is useful to a good amount of people in the communities that use the software being developed. 

You need to give far more justification for the request than what you have offered.

**Comment by gengzhao2020** [comment]
You've made a fair point, I will find other ways to solve this.

**Comment by leana8959** [comment]
Hello,

@DHowett 
Were there any progress done to the customizer? I'm very interested!

Thanks :)

**Comment by DHowett** [comment]
I wish!
