### ISSUE TITLE
[Feature Request] Adding Bulgarian Cyrillic Script

### ISSUE THREAD

**Issue by XenBG** [microsoft/cascadia-code#634]
The Bulgarian Minister of e-Government Bozhidar Bojanov has launched an initiative for Bulgarian institutions to use fonts that support Bulgarian Cyrillic. Source: https://www.facebook.com/bozhidar.bozhanov/posts/pfbid036YFX1SuEjFv4Mzg4WGfdnmCSG6yKT5f4wBokqjZigxCER6tkFdmrxzsD6xeedLBzl

I suggest you add support for the Bulgarian Cyrillic Script so that everyone can take advantage of it. You can read more about the loclBGR glyphs with examples and info on this article - https://www.lettersoup.de/what-shall-be-done-for-bulgarian-cyrillic-loclbgr/. More detailed information can be found here - https://www.fontfabric.com/blog/rounded-bulgarian-cyrillic-narrative-and-comparison/.

I will be more than grateful if you consider my proposal!

![bg-ru-cyrillic](https://user-images.githubusercontent.com/4932709/171821605-723566cf-c9a8-49c2-8362-7b0683fcadc1.png)

**Comment by XenBG** [comment]
@aaronbell It seems that I downloaded an old version from another source and maybe that's why I didn't find the Bulgarian Cyrillic Script. Now I've downloaded the [latest release](https://github.com/microsoft/cascadia-code/releases/tag/v2111.01) from here and everything seems to be fine. Sorry for the inconvenience.

**Comment by vatnid** [comment]
@aaronbell Is it possible to turn on this `locl` option in VSCode?

**Comment by aaronbell** [comment]
@vatnid I'm not exactly sure, but I think that if you set the language for VsCode, it would affect the locl option:
https://code.visualstudio.com/docs/getstarted/locales

**Comment by SamuelLoSG** [comment]
@aaronbell Would this be possible as stylistic sets instead of `locl`? A lot of text editors allow stylistic sets but it's much harder to set the `locl`.
