### ISSUE TITLE
Alternate Braille glyphs optimized for pseudographics use

### ISSUE THREAD

**Issue by PhMajerus** [microsoft/cascadia-code#647]
# Introduction and concepts

Some characters are designed especially for pseudographics, such as the old ▄ ▀ █ (as well as ▌ ▐ ░ ▒ ▓), already found in IBM PC / MS-DOS. These are often referred to as half blocks as they can be used to treat each character cell as 2 pseudo-pixels (or a 1×2 grid).

Others have been inherited from the PET / Commodore 64 and other 8-bit era computers, splitting each cell in 4 pseudo-pixels (or a 2×2 grid): ▖ ▘ ▌ ▗ ▄ ▚ ▙ ▝ ▞ ▀ ▛ ▐ ▟ ▜ █.

A higher grid density has been inherited from TRS-80 and Teletext, and now added to the Unicode Symbols for Legacy Computing, supporting 6 pseudo-pixels (or a 2×3 grid): 
![image](https://user-images.githubusercontent.com/25664275/185758814-530142aa-a176-48d9-a864-a94c612a3e27.png)
These are not yet supported, but are in other feature requests: https://github.com/microsoft/cascadia-code/issues/597 and https://github.com/microsoft/cascadia-code/issues/607

The next grid density of pseudo-pixels would be a 2×4 grid, and it sort of exists, as the Braille characters are basically that, but with discrete dots instead of a no-gap pixels-like grid: ⠀⠁⠂⠃⠄⠅⠆⠇⠈⠉⠊⠋⠌⠍⠎⠏⠐⠑⠒⠓⠔⠕⠖⠗⠘⠙⠚⠛⠜⠝⠞⠟⠠⠡⠢⠣⠤⠥⠦⠧⠨⠩⠪⠫⠬⠭⠮⠯⠰⠱⠲⠳⠴⠵⠶⠷⠸⠹⠺⠻⠼⠽⠾⠿⡀⡁⡂⡃⡄⡅⡆⡇⡈⡉⡊⡋⡌⡍⡎⡏⡐⡑⡒⡓⡔⡕⡖⡗⡘⡙⡚⡛⡜⡝⡞⡟⡠⡡⡢⡣⡤⡥⡦⡧⡨⡩⡪⡫⡬⡭⡮⡯⡰⡱⡲⡳⡴⡵⡶⡷⡸⡹⡺⡻⡼⡽⡾⡿⢀⢁⢂⢃⢄⢅⢆⢇⢈⢉⢊⢋⢌⢍⢎⢏⢐⢑⢒⢓⢔⢕⢖⢗⢘⢙⢚⢛⢜⢝⢞⢟⢠⢡⢢⢣⢤⢥⢦⢧⢨⢩⢪⢫⢬⢭⢮⢯⢰⢱⢲⢳⢴⢵⢶⢷⢸⢹⢺⢻⢼⢽⢾⢿⣀⣁⣂⣃⣄⣅⣆⣇⣈⣉⣊⣋⣌⣍⣎⣏⣐⣑⣒⣓⣔⣕⣖⣗⣘⣙⣚⣛⣜⣝⣞⣟⣠⣡⣢⣣⣤⣥⣦⣧⣨⣩⣪⣫⣬⣭⣮⣯⣰⣱⣲⣳⣴⣵⣶⣷⣸⣹⣺⣻⣼⣽⣾⣿

And that is exactly how these characters are already being used by terminal apps, as can be seen in the screenshots of https://github.com/microsoft/cascadia-code/issues/130, showing that the reason Braille has been added to Cascadia was precisely for their use as pseudo-graphic characters.

# Another Braille design would improve the terminal
Now that we know Braille are often used as 2×4 pseudo-pixels grids in terminal apps, we could improve their display by optimizing their look for that scenario.

Here are their common discrete dots design currently found in Cascadia (reordered in a more natural pixels bits values order):
![image](https://user-images.githubusercontent.com/25664275/185759098-40ff48e2-e232-4a61-8019-7f6dc5681d75.png)

They could instead, or as a stylistic set, follow the design of the pseudo-pixels grids mentioned earlier:
![image](https://user-images.githubusercontent.com/25664275/185759175-0e202bf8-029c-4d87-9f2b-f807cae01807.png)

This would greatly improve the look of text-mode apps using Braille as a high-density pseudo-graphics mode.
Note this is already the style used by the UNSCII font: http://viznut.fi/unscii/, which has been used for the example above.

I would even go as far as to say their pixels look should be the default and their classic discrete dots look should be the alternate stylistic set, as I believe they'll be used as pseudo-pixels much more regularly when used in the context of terminal apps than to provide visual representation of Braille to people who cannot take advantage of Braille displayed on a screen anyway.

# Example
Here's a Braille pseudo-pixels example.

As displayed in Windows Terminal with the current Cascadia Mono:
![image](https://user-images.githubusercontent.com/25664275/187339843-9c9c3875-3565-4fd5-86d6-f877ed543467.png)

As displayed in Windows Terminal with UNSCII:
![image](https://user-images.githubusercontent.com/25664275/187339875-22a60d1b-dc07-4773-938b-06dc57c5081d.png)

**Comment by PhMajerus** [comment]
I just found out that Unicode plans to have those 2×4 grids separately from Braille, as U+1CD00...U+1CDE5 in “Symbols
for Legacy Computing Supplement".
This probably means we'll see two competing set of characters, on one hand the Braille characters will be supported in more terminal apps but be less even when used as pseudo-pixels, and on the other hand the block octant characters that will look better as pseudo-pixels, but will take a while to be supported everywhere, if ever...

Having the possibility to render Braille as octants could still be a nice stylistic set, and could use the same glyphs as the new Symbols for Legacy Computing Supplement. (https://www.unicode.org/L2/L2021/21235-terminals-supplement.pdf)

**Comment by aaronbell** [comment]
Interesting. As the thread from Finii at the end there mentions, Braille does serve a purpose and I'm hesitant to vary from the established forms for the sake of graphics. The Legacy symbols range seems a better place for it.

**Comment by PhMajerus** [comment]
All the pseudographics 2×2, 2×3, and 2×4, have been accepted for Unicode 16, including separated versions of 2×2 and 2×3.
So to finalize this feature request, here is a cheat sheet of all those blocks.
This can be useful to pick characters, or as a test to verify font support for them.

![image](https://github.com/microsoft/cascadia-code/assets/25664275/a42b8dae-e403-4242-88af-4ab4b0908c33)

`curl https://raw.githubusercontent.com/PhMajerus/ANSI-art/main/Unicode/Blocks%20tables.txt`

**Comment by PhMajerus** [comment]
Unicode 16.0 will include octants especially for the purpose presented in this feature request.
So I'm closing this one and replacing it with a new one for the octants: #711 

We could still provide a stylistic set to switch Braille to octants for apps that use Braille as pseudo-pixels and cannot be updated to use octants.
