### ISSUE TITLE
Feature Request: Add Hebrew glyphs

### ISSUE THREAD

**Issue by schorrm** [microsoft/cascadia-code#65]
# Description of the new feature/enhancement (with images if possible)
Basically, glyphs for Hebrew. Even if fairly basic ones and mostly cribbed from somewhere else, not needing to use fallback would be nice.
Also, Hebrew is a very small charset.

**Comment by ezity** [comment]
What is needed to move this forward?

**Comment by mdtauk** [comment]
> What is needed to move this forward?

@aaronbell would know for sure, as the typeface designer.  I imagine he has experience of Hebrew glyphs, but if he requires any research or resources I'm sure he will ask the community or consult others.

**Comment by aaronbell** [comment]
I've provided a proposal to @cinnamon-msft for the work. Is up to them when they want to get it done :).

**Comment by schorrm** [comment]
Will this be happening anytime soon?

**Comment by schorrm** [comment]
Is this in the works at all?

**Comment by cinnamon-msft** [comment]
This is still on our backlog, but it's high up on our list. :)

**Comment by sinapis** [comment]
Any chance of recommending a workaround until we have Hebrew glyphs in Cascadia Code? Mono space font that has Hebrew glyphs that already exists?

**Comment by aaronbell** [comment]
Oh, looks like I didn't close this, but Hebrew has been added now via PR #511
