### ISSUE TITLE
Cascadia Code font looks very thick in vscode

### ISSUE THREAD

**Issue by ZeroXiphYT** [microsoft/cascadia-code#654]
### Cascadia family version

2111.01

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

macOS monterey 12.5.1

### Other Software

Visual Studio Code and any other code editor

### What happened?

Cascadia Code looks very thick for some reason when I use it. I looked at tutorials to see how it looks and its very different

<img width="1210" alt="Screen Shot 2022-09-04 at 8 07 47 AM" src="https://user-images.githubusercontent.com/94765932/188320620-890af2a3-d831-49a9-b2f9-827b18c9873f.png">

![code](https://user-images.githubusercontent.com/94765932/188320633-b3875d2b-b68c-4d04-bdbc-e3f8512d40e0.png)

**Comment by oshytiko** [comment]
It might be just antialiasing on Mac. They do this quite heavily, but in most recent MacOS version global setting to control font aliasing was removed. 

I ended up using `SemiLight` instead of `Regular`.

**Comment by ZeroXiphYT** [comment]
How do you use SemiLight instead of regular? Do you do something like Cascadia Code SemiLight because I don't think it works like that

**Comment by oshytiko** [comment]
Just name it in FontFamily field:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/107051036/188396810-792e312f-2cfa-458e-915b-af797aaae8ba.png">


On MacOS it's also possible to disable individual fonts, so if this trick won't work, you can always just disable `Cascadia Code Regular` globally. But it will be disabled for apps then...

**Comment by ZeroXiphYT** [comment]
Thanks so much! I works now
