### ISSUE TITLE
Ligature rendering issue in kitty terminal

### ISSUE THREAD

**Issue by nimr0d** [microsoft/cascadia-code#661]
### Cascadia family version

2111.01

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

I don't know

### Platform

Linux (Fedora Linux 37.20221117.0 (Silverblue))

### Other Software

Kitty 0.26.5

### What happened?

"<<=" renders as:
![Screenshot from 2022-11-19 18-50-53](https://user-images.githubusercontent.com/13407339/202876085-a89239b9-3a59-4cf0-bc1e-6e553921d00a.png)

It does not seem to have an issue with VSCode:
![Screenshot from 2022-11-19 18-56-48](https://user-images.githubusercontent.com/13407339/202876202-5c5461c1-dc40-4d18-bd23-79b32805cbf5.png)

This seems likely to be a kitty issue, but since I haven't been able to reproduce this issue with other fonts, I am posting here.

**Comment by DHowett** [comment]
I wonder if you'd see the same issue with Fira Code! Cascadia and Fira use the same _type_ of ligature glyphs... which might be more prone to exposing poor rendering in the Kitty terminal.

**Comment by aaronbell** [comment]
Actually, while Cascadia does have ligatures like Fira Code, they work in a different way. 

Still, it is an issue on the kitty side.

**Comment by DHowett** [comment]
Ah, thanks for keeping me honest! 😄

**Comment by aaronbell** [comment]
Just doing some clean up. Hopefully your issue is solved! :)
