### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by claudiospizzi** [microsoft/cascadia-code#67]
To use Cascadia Code in a advanced PowerShell prompt , we need some additional characters. I would suggest adding the following characters. By the way, most of them are also missing in the Consolas font, so I had to switch to MesloLGS NF, even if I like the Consolas font more.

This is how the prompt looks like in the font "MesloLGS NF":
![image](https://user-images.githubusercontent.com/1934246/65273294-18eb7a80-db21-11e9-886c-455fd0a65187.png)

This is how it looks at the moment:
![image](https://user-images.githubusercontent.com/1934246/65273407-61a33380-db21-11e9-9a86-c9ec1404b21b.png)

The following characters are missing in my case, here the example again with MesloLGS NF:
![image](https://user-images.githubusercontent.com/1934246/65273884-703e1a80-db22-11e9-8e38-723b13d14a0e.png)

Would be great, if these symbols can be added.

**Comment by DHowett-MSFT** [comment]
So this is a request for #10?

**Comment by claudiospizzi** [comment]
Yeah some of them are covered, but not all like 57354. Should I add my requirements to the other feature request?

**Comment by DHowett-MSFT** [comment]
Perhaps. Are these just the "powerline extended" glyphs?

**Comment by claudiospizzi** [comment]
Yeah I guess this would cover all my used glyphs. Would be great if they can be included into Cascadia Code. Locking forward to test them out.
