### ISSUE TITLE
[Feature Request] slanted `|` in italics

### ISSUE THREAD

**Issue by leana8959** [microsoft/cascadia-code#678]
# Description of the new feature/enhancement (with images if possible)
The `|` character is straight in italics, which makes it look slightly slanted to the left in a line completely in italics.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/87855546/219940770-0c9662f7-48fb-4165-8c64-1d903dcbc962.png">
It'd be nice to have a feature set which includes a slanted `|` character in italics that's slanted to the same extent with `[` and `]` for example.

# Proposed technical implementation details (optional)

**Comment by aaronbell** [comment]
I'd actually tried a slanted one initially, but found that it started to become confusing with the slash `/`. So ended up leaving it straight to make it extra obvious which glyph it was. I haven't seen a lot of complaints over this thus far, but will keep an eye out.

**Comment by aaronbell** [comment]
I should add, though, that at this time I'm not planning to make a change. :)
Thanks!
