### ISSUE TITLE
Abnormal behavior if installed while VSCode is running

### ISSUE THREAD

**Issue by dsolodow** [microsoft/cascadia-code#68]
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: VSCode 1.38.1
OS platform and version: Windows 10 Enterprise x64 18362.356
Screen resolution (i.e. 220dpi): 1920x1080, scale 100%

Any other software? nope
```

# Steps to reproduce

Launch VSCode
Open terminal in VSCode
Install Cascadia Code font
Change editor.fontFamily to "Cascadia Code"

# Expected behavior
VSCode editor & terminal use Cascadia Code without warning or Error

# Actual behavior
Font size in editor is several sizes smaller than configured
Terminal throws warning "The terminal only supports monospace fonts"
![image](https://user-images.githubusercontent.com/7574074/65275275-4d484200-daf3-11e9-8204-77e4f23b1e45.png)

# Other observations
Restarting VSCode after installing & setting the font results in normal behavior
Installing the font while VSCode is closed behaves normally as well.

**Comment by DHowett-MSFT** [comment]
> IF I DO NOT CHANGE THIS THE ISSUE WILL BE CLOSED

**Comment by DHowett-MSFT** [comment]
We're a font. It's a binary font file. It doesn't run code. There's _nothing we can do about applications acting stupid and not updating the global font table._

**Comment by DHowett-MSFT** [comment]
Feel free to file a bug over at https://github.com/microsoft/vscode, though :smile:
