### ISSUE TITLE
Allow Fairy Sword to be mapped to B

### ISSUE THREAD

**Issue by mitchellwplunkett** [microsoft/cascadia-code#686]
woops. Sorry, too many tabs up at once

**Comment by DHowett** [comment]
This is a really good idea! We should do it.

**Comment by zadjii-msft** [comment]
🧚‍♀️⚔️→🅱️

Were you perhaps looking for https://github.com/HarbourMasters/Shipwright?

**Comment by aaronbell** [comment]
Maybe a stylistic set custom mapping?

**Comment by mitchellwplunkett** [comment]
> 🧚‍♀️⚔️→🅱️
> 
> Were you perhaps looking for https://github.com/HarbourMasters/Shipwright?

was definitely trying to add this to https://github.com/leoetlino/project-restoration/issues while simultaneously looking into why certain full-height unicode characters are coming up half-height in wt two tabs over lol

**Comment by mitchellwplunkett** [comment]
aaaand there's no delete button. If someone could delete this issue to hide my shame that would be cool
