### ISSUE TITLE
1 (one) and l (L) are hard to distringuish

### ISSUE THREAD

**Issue by mahoekst** [microsoft/cascadia-code#69]
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: Visual Studio 2019
OS platform and version: Windows 10 (1909)
Screen resolution (i.e. 220dpi): 150% (2256x1504) Surface Laptop

Any other software?
```

# Steps to reproduce

Change font to Cascadia Code, type 1111lllllll en see it's almost similar (I am an old person ;)

# Expected behavior

With Courier or something like that it's very easy to distinguish between the letter and the number

# Actual behavior

**Comment by mdtauk** [comment]
![image](https://user-images.githubusercontent.com/7389110/65379396-22124e00-dcbf-11e9-9ee4-28cdbfc6cd97.png)

The 1 could have a more slanted top stroke, which would help make it more distinguishable, but in my discussion thread #97 I also suggest changing the lowercase **l** to help it not look too much like the **one** glyph.

![image](https://user-images.githubusercontent.com/7389110/65378891-fbe8b000-dcb6-11e9-856e-47f6db6417ae.png)

**Comment by ExE-Boss** [comment]
I don’t like the new lowercase **<b>l</b>** design. Something about the curved top serif just looks wrong to me.

**Comment by mdtauk** [comment]
> I don’t like the new lowercase **l** design. Something about the curved top serif just looks wrong to me.

I wasn't proposing that exact change, only trying to make it look less like a serif, but this issue is about the **one** glyph. :)

**Comment by aaronbell** [comment]
Thanks for the comments! I'm not sure that, at current, there's sufficient need to modify the letterforms to differentiate the letters more than they already are. That said, I'll leave this open for now if other folks want to make the same feelings known!

**Comment by aaronbell** [comment]
So turns out I did actually increase the angle of the top bar of the 1 and forgot to close this bug. Doing so now :)
