### ISSUE TITLE
[Feature Request] Support for nvim-tree

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/cascadia-code#694]
# Description of the new feature/enhancement (with images if possible)

- Cascadia Mono
![image](https://github.com/microsoft/cascadia-code/assets/96709586/b0f25bfb-76fb-4be5-973c-d99a651a1305)

- Other Font
![image](https://github.com/microsoft/cascadia-code/assets/96709586/d42f86fb-f883-4dc1-9f9b-413f2acfa56b)

**Comment by DHowett** [comment]
Thanks for the request! At the end of the day, this is another ask for #194. Those icons are part of an extended glyph set that has fallen into common use but is not actually specified anywhere.
