### ISSUE TITLE
VS Code Configuration Issue

### ISSUE THREAD

**Issue by Chibudomcode4114** [microsoft/cascadia-code#697]
I saw the font on a Youtuber's Video and I tried implementing it on my vs code font using 'cascadia code' but it doesn't work. Is there something I'm getting wrong? 
![image](https://github.com/microsoft/cascadia-code/assets/108850889/4d58acbf-58f9-4dc4-80f7-8e6d628282b4)

**Comment by edwin-egalite** [comment]
![image](https://github.com/microsoft/cascadia-code/assets/10771300/98b2e4fb-aed1-41c4-a320-466c6772a0a0)

Enter Cascadia Code without the quote.

**Comment by aaronbell** [comment]
Looks like this has been solved :)
