### ISSUE TITLE
"Center dot" used for whitespace does not render properly.

### ISSUE THREAD

**Issue by Dinjoralo** [microsoft/cascadia-code#70]
# Environment

```none
Cascadia Code version number: 1909.16
Application (with version) used to display text: VS Code 1.38.1, Sublime Text 3.2.1
OS platform and version: Windows 10 1903
Screen resolution (i.e. 220dpi): 1440p

Any other software?
```

# Steps to reproduce

In VS Code, enable whitespace rendering and create a file with whitespace in it.

# Expected behavior

The whitespace dots appear in all programs that use them and display with proper spacing.
![Annotation 2019-09-19 164306](https://user-images.githubusercontent.com/2925248/65283373-951f9700-dafc-11e9-9e4f-aa9cb86ae782.png)

# Actual behavior

In VS Code, the dots do not conform properly to the monospacing of the rest of the font. In other editors like Sublime Text, they show up as an invalid character block.

![Annotation 2019-09-19 163530](https://user-images.githubusercontent.com/2925248/65282845-85ec1980-dafb-11e9-8ae2-f69ff1e3b9b7.png)

![Annotation 2019-09-19 164011](https://user-images.githubusercontent.com/2925248/65283175-2e01e280-dafc-11e9-89e5-82fb61031c82.png)

**Comment by gnuvince** [comment]
CENTER DOT (U+00B7) is not supported by Cascadia Code, so you're likely seeing the glyph of another font.

**Comment by abubakarm** [comment]
> # Environment
> ```
> Cascadia Code version number: 1909.16
> Application (with version) used to display text: VS Code 1.38.1, Sublime Text 3.2.1
> OS platform and version: Windows 10 1903
> Screen resolution (i.e. 220dpi): 1440p
> 
> Any other software?
> ```
> 
> # Steps to reproduce
> In VS Code, enable whitespace rendering and create a file with whitespace in it.
> 
> # Expected behavior
> The whitespace dots appear in all programs that use them and display with proper spacing.
> ![Annotation 2019-09-19 164306](https://user-images.githubusercontent.com/2925248/65283373-951f9700-dafc-11e9-9e4f-aa9cb86ae782.png)
> 
> # Actual behavior
> In VS Code, the dots do not conform properly to the monospacing of the rest of the font. In other editors like Sublime Text, they show up as an invalid character block.
> 
> ![Annotation 2019-09-19 163530](https://user-images.githubusercontent.com/2925248/65282845-85ec1980-dafb-11e9-8ae2-f69ff1e3b9b7.png)
> 
> ![Annotation 2019-09-19 164011](https://user-images.githubusercontent.com/2925248/65283175-2e01e280-dafc-11e9-89e5-82fb61031c82.png)

hey what font are you using in your "Expected Behavior" image?

**Comment by Dinjoralo** [comment]
> hey what font are you using in your "Expected Behavior" image?

Iosevka.
