### ISSUE TITLE
Letters with diacritical marks in Latin Extended-B block

### ISSUE THREAD

**Issue by Buqian-LI** [microsoft/cascadia-code#707]
I like this font a lot, this is why I propose the following improvement instead of switching to another one 😝 

I wish the Latin Extended-B block to be completed, especially for the letters with diacritical marks (there are some of them, but not all), which shouldn't be hard, I guess. (I mean, one can easily complete it using fontforge, but it would nice to have it by default.)

The missing letters with diacritical marks also cause inputs weirdly fallback to plain letters without diacritical marks in my terminal (kitty).

What's happening :
<img width="129" alt="截屏2024-01-14 18 19 52" src="https://github.com/microsoft/cascadia-code/assets/85029752/92fcb6cc-5344-4825-9e27-1d98391ecc92">

Expected :
<img width="131" alt="截屏2024-01-14 18 20 57" src="https://github.com/microsoft/cascadia-code/assets/85029752/b0ff3817-835f-4966-bb9d-2be0be01a917">

I have tried every possible solutions, but it seems only modifying the font itself can resolve it.

**Comment by PhMajerus** [comment]
It seems that most of Extended-B is available in decomposed forms, with the diacritics properly anchored over the characters, and they just need to be stitched together to have proper precomposed forms.

![image](https://github.com/microsoft/cascadia-code/assets/25664275/dd09e895-2694-4d6d-a955-9e286c24ecd1)

I don't know if this is something that is automated with the current build system, but it seems like something that could be handled by a clever script that grabs the base characters and diacritics and builds the equivalent precomposed glif files.
