### ISSUE TITLE
~= ligature

### ISSUE THREAD

**Issue by seanmars** [microsoft/cascadia-code#71]
Same as [== ligature] #46 
The distinction between "=" and "~=" is quite subtle too.

**Comment by seanmars** [comment]
Cascadia Code:
![20190920_114620](https://user-images.githubusercontent.com/4590764/65298225-483fcd00-db9d-11e9-980c-d99fe69f0288.png)

Fira Code:
![20190920_114634](https://user-images.githubusercontent.com/4590764/65298228-4bd35400-db9d-11e9-8280-4afc14124449.png)

**Comment by ExE-Boss** [comment]
They look distinct enough to me.

**Comment by weltkante** [comment]
hmm, what language does cascadia target? because some languages do ~= as a variant of == (as in the OP) but [other languages](https://stackoverflow.com/questions/34713203/what-does-lua-operator-mean/34713230) do ~= as a variant of != (not equals)

Most of the suggested symbols would making those languages harder to read because it looks like an equality test when its a not-equality test.

**Comment by laperraputs513** [comment]
Mm

**Comment by laperraputs513** [comment]
Mmm

**Comment by aaronbell** [comment]
@seanmars @weltkante Interesting. For Lua (and related languages), would swapping for a not equals ligature be workable? Like this:

<img width="106" alt="Screen Shot 2019-09-23 at 3 10 39 PM" src="https://user-images.githubusercontent.com/8460297/65466666-619e7e80-de14-11e9-81ff-2dc81fcfcb96.png">

I can certainly include a stylistic set variant that forces the not equals form. It'll require Terminal to build in intelligence to turn on the set when in Lua (and using Cascadia Code). @DHowett-MSFT, what do you think?

**Comment by DHowett-MSFT** [comment]
We can't exactly guess when Lua's in use in the terminal, so this would be another user-driven choice. :smile:

**Comment by seanmars** [comment]
I think that consistent behavior is less confusing to the user. 😄

**Comment by ExE-Boss** [comment]
Well, **VS Code** could support something like:

```jsonc
"[lua]": {
	"editor.fontStylisticSets": "luaNotEquals"
}
```

**Comment by weltkante** [comment]
I still think the defaults should be easily distinguishable from other operators and any language specific cases should be opt-in. When you are in a terminal you don't know which language you are showing (say, piping source code file content to stdout via command line tooling is a common operation) and you want to make sure that the user can easily read everything regardless of which language he uses for the job.
