### ISSUE TITLE
How to add Cascadia Code font in VS Code

### ISSUE THREAD

**Issue by gupta-ji6** [microsoft/cascadia-code#72]
The documentation is missing a 'How to use Cascadia Code in VS Code' guide.

Many developers would like to try Cascadia Code in their code editors so including it in documentation would be helpful.

**Comment by ShubhamBelwal** [comment]
The steps are mentioned in this page: https://devblogs.microsoft.com/commandline/cascadia-code/

**Comment by creeperyang** [comment]
1. download & install the font;

2. config VS Code's setting, search `editor.fontFamily` & edit it:

    `'Cascadia Code', Consolas, 'Courier New', monospace`

**Comment by gupta-ji6** [comment]
That works!

I made it work myself too but I had to visit a Microsoft Blog to see how to add this.

I submitted a PR #73 so that others don't have to go somewhere else.

**Comment by tavrez** [comment]
Also enable font ligatures in vscode:
`"editor.fontLigatures": true,`

**Comment by josexlito** [comment]
Hi to all! My VSCode does't want Cascadia :( 

This is my current settings.json:

"editor.fontFamily": "'Cascadia Code', 'Consolas', 'IBM Plex Mono', 'Ubuntu Mono', 'monospace', monospace",

I'm with Version 1.38.1 - Linux x64 5.2.16-200.fc30.x86_64

**Comment by kenmick** [comment]
@josexlito Did you restart VSCode after installing Cascadia Code font? Seems VSCode can't recognize newly installed font unless you restart it.

**Comment by josexlito** [comment]
> @josexlito Did you restart VSCode after installing Cascadia Code font? Seems VSCode can't recognize newly installed font unless you restart it.

Gotcha! I've restarted VSCode and the font is recognized! Thanks a lot!

**Comment by birdyhurricane** [comment]
Nice guide on how to install & setup both font anf font ligatures ;)
https://devblogs.microsoft.com/commandline/cascadia-code/

**Comment by PranavBhattarai** [comment]
> Also enable font ligatures in vscode:
> `"editor.fontLigatures": true,`
```
This is alll i see when I try to go to **Settings** > **Fonts** > **Fonts Ligature** > **Edit in settings.json**
{
   "editor.defaultFormatter": "vscode.json-language-features"
},
```

**Comment by gupta-ji6** [comment]
It will work if you add the line in your user settings.
I think they've removed the checkmark option to enable font ligatures in latest update.

**Comment by PranavBhattarai** [comment]
@gupta-ji6 Can I just randomly write `"editor.fontLigatures": true,` anywhere I want or is there certain place?!

**Comment by jcnils** [comment]
Yes, anywhere. Just add 'Cascadia Code'  to fontFamily and the new line.

On Ubuntu is something like this:

`
{
    "editor.fontFamily": "'Cascadia Code', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
    "editor.fontLigatures": true
}
`

**Comment by codejockie** [comment]
Two types of the Cascadia font exists

+ Cascadia Code
+ Cascadia Code PL

```json
{
    "editor.fontFamily": "'Cascadia Code [PL]', 'Droid Sans Mono', ...",
    "editor.fontLigatures": true
}
```

**Comment by MetroMediumM** [comment]
> Yes, anywhere within the {}. Just add 'Cascadia Code' to fontFamily and the new line.
> 
> On Ubuntu is something like this:
> 
> ```
> {
>     "editor.fontFamily": "'Cascadia Code', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
>     "editor.fontLigatures": true
> }
> ```
> 
> There is no problem if you have more lines from other parameters. just make sure that every line ends with `,` and the last line don't.

Tried this and it worked like a charm

**Comment by osamatsu** [comment]
> Also enable font ligatures in vscode:
> `"editor.fontLigatures": true,`

it works, i love you :)

**Comment by zeroxia** [comment]
Is there anything different when specifying the suffix " PL"?

**Comment by GypsyyCode** [comment]
> Is there anything different when specifying the suffix " PL"?

PL is for powerline symbols. Mostly used in terminal.

**Comment by zeroxia** [comment]
> > Is there anything different when specifying the suffix " PL"?
> 
> PL is for powerline symbols. Mostly used in terminal.

So could it benefit the "integrated terminal" inside VS Code?

**Comment by codejockie** [comment]
@zeroxia yes it will benefit the terminal

**Comment by xedera** [comment]
> 2\. 'Cascadia Code', Consolas, 'Courier New', monospace

Thanks for the solution, was looking for a while for this.

**Comment by invinciblesharma** [comment]
> 

still not working :(


- [ ]
