### ISSUE TITLE
Nerd fonts icons got smaller after most recent update

### ISSUE THREAD

**Issue by jasursadikov** [microsoft/cascadia-code#730]
### Cascadia family version

2404.23-1

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.otf (static)

### Platform

ArchLinux

### Other Software

GNOME Terminal

### What happened?

I am not sure where I should pull this out, here or in nerd-fonts repo, but icons got smaller on the most recent otf font update.
`otf-cascadia-code (2111.01-2 -> 2404.23-1)`
![image](https://github.com/microsoft/cascadia-code/assets/14846427/12f43e67-3fb5-4637-95d8-b8b29f648ee6)
That was overlapping before

**Comment by aaronbell** [comment]
They all fit within the mono width space, as intended. I don’t see the problem here.

**Comment by jasursadikov** [comment]
@aaronbell they do, but they got shrinked down, they were much larger before latest update.
Before:
![image](https://github.com/microsoft/cascadia-code/assets/14846427/a7e2832f-4b9d-4177-b929-578057a0cb1e)
After:
![image](https://github.com/microsoft/cascadia-code/assets/14846427/9ec49569-9df4-4f1d-9a18-aafcbf10c2fb)

**Comment by aaronbell** [comment]
I don’t think that glyph was previously natively supported by Cascadia Code. Are you thinking of one of the alternate versions? I am not using the method of adding the glyphs as provided by the NF repository so there may be some differences.

**Comment by jasursadikov** [comment]
@aaronbell I guess it is a custom one, I am not sure how does it work, if it fallbacks to original cascadia or other way around. But this has happened right after the update.
```
otf-cascadia-code 2404.23-1
ttf-cascadia-code-nerd 3.2.1-1
```

**Comment by justbispo** [comment]
I'm also using the same system as @jasursadikov but I've tried two other terminal emulators, Kitty and Alacritty.

Before the last Cascadia Code update I was using the [ttf-cascadia-code-nerd](https://archlinux.org/packages/extra/any/ttf-cascadia-code-nerd/) package, which includes the patched Cascadia Code font from Nerd Fonts. Kitty doesn't require a patched font, it only needs the symbols font ([ttf-nerd-fonts-symbols](https://archlinux.org/packages/extra/any/ttf-nerd-fonts-symbols/)).

After updating and removing the old Nerd Font font, both terminal emulators show the symbols small compared to before.

**Before update, using old Nerd Font font:**
![before](https://github.com/microsoft/cascadia-code/assets/38961424/e76ed411-9ed4-496f-9d05-dc3372681923)

**After update, removed old Nerd Font font:**
![after](https://github.com/microsoft/cascadia-code/assets/38961424/e8552f5f-9217-48c2-a41b-bbd9fce6424b)

I don't know much about how font patching works but [this comment](https://github.com/ryanoasis/nerd-fonts/discussions/1103#discussioncomment-4852120) should explain a little bit. The non-mono font from Nerd Font, which is the one I used, makes the symbols be 2 cells wide. It seems the non-mono version from the new update uses the symbols in a similar way as the mono version.

**Comment by aaronbell** [comment]
We don't currently support the three variant approach described in the linked comment. I'm aware of that desire, but this initial release is just mono width. Thus, the icons are within a single cell block.

**Comment by justbispo** [comment]
Alright, I'm glad to know it's not a bug. Do you know if another variant is planned for future releases?

**Comment by aaronbell** [comment]
It is on my list of things I want to implement. :)

**Comment by jasursadikov** [comment]
Offtopic, but @justbispo what kind of screenfetch/neofetch are you using? How did you made that custom view?

**Comment by justbispo** [comment]
> Offtopic, but @justbispo can you share your neofetch config? :D

Sure, [here](https://gist.github.com/justbispo/76da8652a5139c483aa302fef27f3513). I'm using [fastfetch](https://github.com/fastfetch-cli/fastfetch) instead tho, since neofetch just got archived and is slower.

> @justbispo also, let me know, if you found a solution

For the time being, I made pacman [ignore](https://wiki.archlinux.org/title/pacman#Skip_package_from_being_upgraded) any updates to [ttf-cascadia-code](https://archlinux.org/packages/extra/any/ttf-cascadia-code/) and kept [ttf-cascadia-code-nerd](https://archlinux.org/packages/extra/any/ttf-cascadia-code-nerd/) installed.
Not the ideal but works for me.

**Comment by jasursadikov** [comment]
I am still wondering if would be fixed in anytime in future

**Comment by aaronbell** [comment]
It is on my list of things I want to implement. :)

**Comment by smit-io** [comment]
Still have the same issue. Can't seem to patch them manually either.

**Comment by jasursadikov** [comment]
@smit-io You can only do that by downgrading it to 2111.01-2

**Comment by jasursadikov** [comment]
@aaronbell I wounder why this issue is closed, since people are still suffering from this...

**Comment by aaronbell** [comment]
The alternate icon sizes is on my list of things to implement in the future but the lack of them is not actually a bug with the font.
