### ISSUE TITLE
Cascadia Mono NF not recognized by VS Code

### ISSUE THREAD

**Issue by dmonder** [microsoft/cascadia-code#731]
### Cascadia family version

2404.23

### Cascadia family variant(s)

Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 11 Enterprise 21H2 22000.2899

### Other Software

Visual Studio Code 1.88.1
Microsoft Terminal 1.19.10821.0
PowerShell 7.4.2
Oh-My-Posh 19.25.0

### What happened?

I have Oh-My-Posh setup in PowerShell. In Terminal, I have Cascadia Mono NF selected as my font face and it works correctly.

![Screenshot 2024-05-01 132300](https://github.com/microsoft/cascadia-code/assets/2252189/1ddf09b4-4186-40ab-bf6f-d20bbacf0fb4)

However, in VS Code, when I set the terminal font to Cascadia Mono NF, I get the following error:

![Screenshot 2024-05-01 132337](https://github.com/microsoft/cascadia-code/assets/2252189/df3880b6-e394-49ad-bbfe-c43c4a82d80a)

If I change to Cascadia Mono PL, I don't get that error but the font is not correct (but I did not expect it to be since it is not a Nerd Font - it doesn't work right in Terminal either).

![Screenshot 2024-05-01 132312](https://github.com/microsoft/cascadia-code/assets/2252189/ca6886ff-765e-4803-b7c1-888663cb3e41)

Any idea how to get this font to work in VS Code? I can still use the old CaskaydiaCove Nerd Font Mono but I would like to switch to use the new Cascadia Code.

I am also tracking https://github.com/microsoft/vscode/issues/173079 which may be where this needs to be fixed.

Thanks.

**Comment by dmonder** [comment]
That does not work for me. I get the same error as before.

**Comment by mfocko** [comment]
Fine here too, both `Cascadia Code NF` and `Cascadia Mono NF`… have you tried restarting Windows after the installation of the fonts; also making sure that you have only the latest version installed?

**Comment by dmonder** [comment]
I did uninstall all prior versions and then reinstalled. I will reboot as soon as I can and post again.

**Comment by dmonder** [comment]
It is working now. I rebooted the machine and all is well! Thanks.
