### ISSUE TITLE
Nerd Font Glyph \uf119 missing

### ISSUE THREAD

**Issue by TheBlubb14** [microsoft/cascadia-code#738]
### Cascadia family version

2404.023

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

Windows Terminal included version (TTF (variable))

### Platform

Windows

### Other Software

Windows Terminal 1.19.11213.0

### What happened?

Nerd Font Glyph `\uf119` `nf-fa-face_frown` is missing.
![grafik](https://github.com/microsoft/cascadia-code/assets/12298942/1071cee0-90cc-4468-be11-a303be9b0451)

In my previously used font Caskaydia Cove Nerd Font its rendered correctly
![grafik](https://github.com/microsoft/cascadia-code/assets/12298942/0f4f03bd-2a9d-4502-9187-840506ceebf6)

**Comment by DHowett** [comment]
> Windows Terminal included version (TTF (variable))

The version of Cascadia Code that comes with Windows Terminal is not the Nerd Font version. You will need to install the Nerd Font version separately.

**Comment by TheBlubb14** [comment]
> > Windows Terminal included version (TTF (variable))
> 
> The version of Cascadia Code that comes with Windows Terminal is not the Nerd Font version. You will need to install the Nerd Font version separately.

I assumed from the release notes that it was included.
After installing `CascadiaCodeNF.ttf` it's working. Thanks for the hint!
