### ISSUE TITLE
Suggestions regarding Microsoft's new terminal/coding font

### ISSUE THREAD

**Issue by mdtauk** [microsoft/cascadia-code#74]
![image](https://user-images.githubusercontent.com/7389110/58172440-86c98780-7c90-11e9-8ce1-e8c62339ef22.png)

Until the font and its design makes its way to GitHub, I wanted to offer a couple of thoughts on where the font stands so far.

### a
I think the lowercase a feels heavy and awkward.

### f
I think the bar on the lowercase f feels too low (I know this is done to make the ascender of the f more visible, but it feels a tad too low.

### r
The lowercase r's serifs make it feel out of character to the other lettershapes.

### m
The m feels very crushed and narrow.  There is little that can be done to fix this, unless every other character is made wider to allow it to breathe.

### 1
The lack of character on the top stroke of the number 1 feels out of keeping with the shape on the lowercase c and the stylised 2.  Now the bottom stroke of the lowercase l is curved, it is distinct enough from the number 1 to allow for a diagonal top stroke.

#### Other ideas
There could also be **vertically centred punctuation** when used between Uppercase or Lowercase letters or numbers.

There could be oldstyle and tabular digits used contextually.

There could be special digits used for line numbers.

If the font was a variable font, the regular and bold thickness could adapt when the text is dark on light, or light on dark.

Error messages could also appear bolder than the standard regular and bold weights.

**Comment by madig** [comment]
The hinting of the "=" could be improved:

![image](https://user-images.githubusercontent.com/380829/65316981-d6628600-db92-11e9-8d75-ff313af90ede.png)

The bottom stroke is fuzzier than the top one.

**Comment by DHowett-MSFT** [comment]
Actually, this is somewhat of a "bucket" issue which we try to avoid. I already migrated out the salient points (#1, #2, #3, #4, #5), and the rest are really individual feature requests that deserve their own tracking.
