### ISSUE TITLE
Some of the Arabic letters look extremely corrupted

### ISSUE THREAD

**Issue by AptiviCEO** [microsoft/cascadia-code#743]
### Cascadia family version

2404.23

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

Windows Terminal included version (TTF (variable)), .ttf (variable)

### Platform

Windows 11 23H2

### What happened?

First, thank you for your hard work on Cascadia Code 2404.23!

It looks like that some of the following Arabic glyphs look corrupted on all the applications. I was exploring new typefaces using the character map program on Windows while trying to brainstorm an idea for Terminaux (a C# library) while I encountered some corrupted characters at least for the Arabic language. It only happens in the NF and the PL variants.

However, this corruption doesn't happen on large font sizes (43 px and up); only happens on 42 px and lower. When these Arabic characters connect, the corruption increases.

The following characters all suffer from visual graphical glitches (connected or not) that make such letters illegible: (Note that the terminal I-Beam cursor line is not part of the glyph and, hence, not part of the corruption)

| Letter | Once | Twice | Thrice
|:-------|:-----|:------|:-------
| U+063B: ARABIC LETTER KEHEH WITH TWO DOTS ABOVE (ػ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/898d5ca7-3466-4371-b419-c336b465061b) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/52955f24-b8f4-4afe-a3a7-a776e2c669c3) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/8b55c2bf-3358-4255-bb48-37cee0fa5ad9)
| U+0684: ARABIC LETTER DYEH (ڄ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/30c65f19-0aab-4ddd-a24e-32e901510185) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/ad41567c-daac-46b8-bd4f-c09cbfb3db74) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/b3bca6a6-a89c-4998-9f3f-b33b45350421)
| U+0687: ARABIC LETTER TCHEH (چ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/05ff260c-e065-423d-b212-98ba51418843) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/ea54e6c2-54c6-4518-a347-4f9b605c14a6) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/914753d2-9ace-4c69-a02d-0a895a645ad9)
| U+0688: ARABIC LETTER TCHEHEH (ڇ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/3e908ae9-4382-4e3e-a8cf-3189b18d2b36) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/afc113af-63b3-4a52-9e4d-b55ead0b6d17) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/61c4a54b-9eb1-46cf-80ed-ada5d35e5cde)
| U+06AD: ARABIC LETTER NG (ڭ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/e5132dc1-d99e-4021-908e-095ba885a75f) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/ec9a1c6c-42d1-4029-ad8b-99446b14a3b4) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/84d129ae-60c6-42fe-b5b9-17c0908fa216)
| U+06AF: ARABIC LETTER GAF (گ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/8eb2f153-e5cd-47ac-896b-237e4815a4f9) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/2a06d50a-05cc-487e-a19d-ec234f2f8bd4) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/2e0ea002-fa37-40c3-886e-59071ec8bb3b)
| U+06B0: ARABIC LETTER GAF WITH RING (ڰ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/e9241cad-17e6-4d23-82ed-fd66a5cd99f9) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/45d6ee6b-6aeb-4afe-b6e6-81d15aea7ce2) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/e591759a-cccd-4ac3-9545-26c8a395e282)
| U+06B1: ARABIC LETTER NGOEH (ڱ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/4874a23d-f5fc-4e64-9215-8e2fe14ef678) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/1152a9e6-4eb6-4a81-88f5-5ac8a0ae093f) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/3bc09918-3f68-4e50-8b99-6d55afda7c91)
| U+06B2: ARABIC LETTER GAF WITH TWO DOTS BELOW (ڲ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/e1b74f4d-7849-45d0-bb6b-2ae9dd7dccc4) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/90e0a8b3-93ec-4277-9ca1-dfe2efd32530) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/f4ab7603-37fb-4426-bc75-0d78430a209d)
| U+06B3: ARABIC LETTER GUEH (ڳ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/17fb6713-699c-47f3-bc3b-17a44f29cf86) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/49e0dff5-6ef1-4823-a4cf-f3891b988c2b) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/9b1620a4-856f-4e1a-8775-0f03872f996c)
| U+06B4: ARABIC LETTER GAF WITH THREE DOTS BELOW (ڴ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/aeb05d3b-c54f-4f53-bf71-47cfa4ec8521) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/ed82c465-5ba9-427b-a7c3-1ecd103c5708) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/c85c0ff4-d018-4fc5-9150-9c6a203ca520)
| U+06B7: ARABIC LETTER LAM WITH THREE DOTS ABOVE (ڷ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/5665fb3c-5a5c-4896-80b9-4137d58f9707) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/eebe9f19-a315-4d88-a3d4-e427f56e06a2) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/0447c6d2-a0b2-4bf6-a07a-852ccf86cd2d)
| U+06B8: ARABIC LETTER LAM WITH THREE DOTS BELOW (ڸ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/129bb759-8985-43f4-acf7-3b983a864688) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/7c9333de-f74a-4577-a1dd-882fe5575caf) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/21de9abb-47a2-4fd7-8dd0-b7465260088f)
| U+06BF: ARABIC LETTER TCHEH WITH DOT ABOVE (ڿ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/d3a28114-7f4f-4e7b-8f96-100ae2e04ef1) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/93c6edf2-5668-4fc7-9230-b0778fdfb575) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/eead729e-151a-4faf-8f34-141dce53d1e4)
| U+075E: ARABIC LETTER AIN WITH THREE DOTS POINTING DOWNWARDS ABOVE (ݞ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/5c32fd49-7931-4016-8820-518da4795a41) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/a595dc2f-d967-4add-8217-4fbad21955d9) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/759bc96e-6012-4e00-a0f2-8508e83a5f76)
| U+0763: ARABIC LETTER KEHEH WITH THREE DOTS ABOVE (ݣ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/501431a8-6e81-4651-8a3c-58434f123615) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/c863a199-1c7f-43a3-b38c-bc0983262760) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/e6f469da-c447-4a68-bb8b-1fb98418d483)
| U+076A: ARABIC LETTER LAM WITH BAR (ݪ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/1b4b37e3-1c3c-4b8e-b374-71f5ae4dba80) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/b2588a3b-a6ae-4ea7-89d7-59b1541b143a) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/5c2a5729-add1-4ae5-9a76-2eac5b073aeb)
| U+077F: ARABIC LETTER KAF WITH TWO DOTS ABOVE (ݿ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/14dab27a-5ed8-406f-a262-e2e09be2fb53) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/30e9d0df-4402-48e7-b48c-2fcc886b1203) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/6b40eb45-ca46-40e3-8b7e-5f3a59b56584)
| U+08B0: ARABIC LETTER GAF WITH INVERTED STROKE (ࢰ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/76dc1f65-ae97-4eb0-9654-8467ef5bd670) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/d4e4a910-9564-44e5-b434-a5636f18dc10) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/c840d20f-fb53-460e-a14e-a0aae260cd6d)
| U+08B3: ARABIC LETTER AIN WITH THREE DOTS BELOW (ࢳ) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/5bd296e8-e184-43bc-bf35-b6ab831ecc73) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/65e537c3-b596-4b20-8b36-34ce7a58d0f6) | ![image](https://github.com/microsoft/cascadia-code/assets/15963131/b6a4a6c4-1d5c-41a0-bb37-a83c3ccc6d22)

Out of all the glitches experienced by these characters, U+06AF, U+06B0, U+06B2, U+06B3, U+06B4, U+075E, U+077F, and U+08B0 characters are the most affected with their corruption at its worst. However, the normal Arabic characters look fine, such as this:

![image](https://github.com/microsoft/cascadia-code/assets/15963131/2cf73d3f-d5d9-4262-bf8a-35f4bc06bd35)

I suspect that the glyphs for the above characters may not have been generated properly in the final font files.

**Comment by lhecker** [comment]
> However, this corruption doesn't happen on large font sizes (43 px and up); only happens on 42 px and lower. When these Arabic characters connect, the corruption increases.

FYI the issue happens due to incorrect hinting instructions (= when "grid fit" is enabled). On Windows, at large font sizes hinting won't occur anymore and text will be drawn from the outlines instead. That's why it works at >42px. If for instance `DWRITE_RENDERING_MODE_OUTLINE` is used, then the issue will be fixed even at small font sizes.

**Comment by AptiviCEO** [comment]
Alright, thanks for this information. Can the grid fitting instructions for these characters be fixed? And how did such instructions go wrong in the first place?

By the way, I've also tested this issue on Android 14 (Termux [grid hinting] and QuickEdit [outline?]), with the U+077F: ARABIC LETTER KAF WITH TWO DOTS ABOVE (ݿ) letter, and Termux has exactly the same issue, so it isn't isolated to Windows.

  * QuickEdit:
    * ![Screenshot_20240518_221233_QuickEdit](https://github.com/microsoft/cascadia-code/assets/15963131/c6b1593b-8b6b-4322-877c-333994b4a2bd)
  * Termux (2111.01 (2021) version of Cascadia Code PL):
    * ![Screenshot_20240518_221622_Termux](https://github.com/microsoft/cascadia-code/assets/15963131/e45a07d5-a27e-439a-b70a-29e68897b416)
  * Termux (2404.23 (2024) version of Cascadia Code NF):
    * ![Screenshot_20240518_221515_Termux](https://github.com/microsoft/cascadia-code/assets/15963131/15d11a52-1cb5-402a-b9d5-d3946e5df9c9)

So, I think that this is a huge regression, because it used to work perfectly in the 2021 version as it had the correct grid fitting instructions.

**Comment by aaronbell** [comment]
What has likely happened is that the point order changed at some point unexpectedly. I will have to investigate.

**Comment by skycommand** [comment]
AptiviCEO, your investigation is more comprehensive than mine. Thanks a lot.

**Comment by aliajboy** [comment]
It isn't fixed: https://github.com/dotnet/wpf/issues/9381#issuecomment-2266681904

**Comment by skycommand** [comment]
@aliajboy Are you aware that Microsoft has not so far released any version of the font that includes this fix? This bug report applies to version 2404.23, which is also the latest release version.

Please either wait for the next release or compile the font on your end.
