### ISSUE TITLE
No visible ligature for ==

### ISSUE THREAD

**Issue by ShaiAvr** [microsoft/cascadia-code#748]
### Cascadia family version

2404.23

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows

### What happened?

I started using this font and I noticed that there is no visible ligature for the `==` symbol:

![Screenshot 2024-05-31 140428](https://github.com/microsoft/cascadia-code/assets/35605235/f81ada66-38fa-4b68-9ebf-2e37efe4ced1)

I tested it in VSCode and Visual Studio and it seems to be an issue with the font. How can I get a nice and smooth ligature for the `==` symbol like most other fonts with ligatures give?

**Comment by aaronbell** [comment]
By design, for now. 

see: https://github.com/microsoft/cascadia-code/issues/284
