### ISSUE TITLE
ö,ü,ä have no real bold versions

### ISSUE THREAD

**Issue by Frei78** [microsoft/cascadia-code#75]
# Environment

Cascadia Code version number: 19.09.16
Application (with version) used to display text: Visual Studio 2019
OS platform and version: Win10
Screen resolution:  1440* 2560 (109 dpi) 27"

In german language the characters ö,ü,ä (umlauts) are quit common and Cascadia-code supports them.

# Steps to reproduce
Just use  ä,ü,ö,Ö,Ä,Ü with bold text.

# Expected behavior
The use of umlauts should also be supported with bold text and the characters should look just like their counterparts without dots.

# Actual behavior
Umlauts can be used in bold text, but the letters are too thin and not really bold.

**Comment by jroessel** [comment]
Umlauts are not currently part of the font. See #33.

**Comment by Frei78** [comment]
Oh, okay. Thank you! So the umlauts are just fall back characters in a different font.
So this is not a bug just a missing feature. I gonna support feature request #33 then and I go back to "Consolas" for now.

**Comment by Frei78** [comment]
#54 is also the same thing.
