### ISSUE TITLE
Some Arabic glyphs broken in variable ttf

### ISSUE THREAD

**Issue by miloush** [microsoft/cascadia-code#757]
### Cascadia family version

2404.023

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

Windows Terminal included version (TTF (variable)), .ttf (variable)

### Platform

Windows

### What happened?

![image](https://github.com/microsoft/cascadia-code/assets/10546952/2a52d1e6-3e7e-4726-a0e9-0472b506f614)

![image](https://github.com/microsoft/cascadia-code/assets/10546952/b9da9626-bce1-4c23-b042-f4da2a558c80)

Note this only happens in the variable ttf file and only in sizes up to 40. The static rendered ones work correctly.

I have seen similar issues before in other fonts and I am starting to wonder whether this is a bug in the font software. Reproduces in Harfbuzz.

**Comment by aaronbell** [comment]
See #743
