### ISSUE TITLE
Arrow ligature do not works in visual studio

### ISSUE THREAD

**Issue by IcEarthlight** [microsoft/cascadia-code#760]
### Cascadia family version

2404.023

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 11 23H2 22631.3880

### Other Software

Visual Studio Community 2022 17.10.4

### What happened?

When I used the font Cascadia Code in visual studio, the ligature do not works with character '-'. (The same thing occurs in Cascadia Code NF and Cascadia Code PL with any weight) I have also tested in notepad, and the ligature works well.
![Cascadia Code in Visual Studio](https://github.com/user-attachments/assets/8f5040d9-c999-407a-a4fb-2ebc27d757aa)

**Comment by glebd** [comment]
It's a Visual Studio editor problem, see https://developercommunity.visualstudio.com/t/font-ligatures-not-working/591741 -- hyphen-based ligatures are not working in WPF. Fira Code issue: https://github.com/tonsky/FiraCode/issues/259

**Comment by DHowett** [comment]
Indeed, this is a VS issue! Thanks @glebd.
