### ISSUE TITLE
Diacritic support (ąńůň etc..)

### ISSUE THREAD

**Issue by Alwer87** [microsoft/cascadia-code#77]
# Please add diacritics to this font, e.g. ąźůň - now writing in many spoken languages look ugly, and yes  it is sometimes used when comments are added to code

# How many users? Lot of them, because in nearly all European languages diacretis are used.

**Comment by rschr** [comment]
Indeed. They're frequently used, not only in comments, but in strings, too. As it is now, using such characters can even break the fixed-width property of the typeface.

**Comment by Tomirad** [comment]
Some test, all diacritical marks look bad.
But I think the font will be useful not only for the console as it will be fully done.

![image](https://user-images.githubusercontent.com/12190843/65320076-63acd700-dba1-11e9-91c3-e55dcefd7142.png)

**Comment by Aokromes** [comment]
#33

**Comment by cinnamon-msft** [comment]
Duplicate of #33
