### ISSUE TITLE
Persian letter bad display (please translate)

### ISSUE THREAD

**Issue by Sage-He** [microsoft/cascadia-code#770]
### Cascadia family version

latest

### Cascadia family variant(s)

Cascadia Code (the version with ligatures), Cascadia Mono (the version without ligatures)

### Font file format(s)

.ttf (variable), .ttf (static)

### Platform

Windows

### Other Software

VSCode
Visual Studio 2022 & ...

### What happened?

سلام. برخی کلمات فارسی متاسفانه در هنگام نمایش دادن، بد پردازش میشن و اتفاقات بسیار عجیبی در هنگام کار با فونت شما میوفته
مثلا در مورد حرف « گ » این خیلی بارز هست. به تصویر زیر توجه کنید:

![اسکرین شات از نمایش بد حروف](https://github.com/user-attachments/assets/2f0b5f8e-3b15-446c-bb4b-52ec4f32e82e)

کلمه‌ای که در تصویر نوشته شده، کلمه « کانفیگ » هست، معادل فارسیِ Config. حرف آخر، یعنی « گ » اینجوری میشه

 یا مثلا این تصویر:
![حرف چ وحشتناک شده!](https://github.com/user-attachments/assets/60303433-750d-4105-b600-2b5a551c695a)
حرف   « چ  » و   « گ »

ممنون میشم به پشتیبانی هاتون از زبان فارسی بیشتر ادامه بدید. همچنین میتونید برای زیباتر شدن فونت از برخی فونت های بومی فارسی ایده بگیرید. مثل Vazirmatn و Yekanbakh یا IranSansX 🙏

**Comment by itskazemk** [comment]
i have the same issue and i'm aggre that if they merge Vazirmatn with this font for persian/farsi or even arabic it will be the best.

**Comment by aaronbell** [comment]
This issue has been reported (#743) and fixed.

We do not intend to replace the existing Arabic.

**Comment by Sage-He** [comment]
سلام. به هر حال بابت زحماتتون متشکرم 🙏
