### ISSUE TITLE
Font and ligatures no longer working in vscode after update to version 1.95.0

### ISSUE THREAD

**Issue by bertoloti** [microsoft/cascadia-code#782]
### Cascadia family version

2404.23

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Ubuntu 24.04

### Other Software

Visual Studio Code 1.95.0

### What happened?

Cascadia Code Font with ligatures and cursive was working up to last vscode update to 1.95.0

Config of vscode `setting.json`:
```
"editor.fontFamily": "Cascadia Code PL, Consolas, 'Courier New', monospace",
"editor.fontLigatures": "'calt', 'ss01'",
```

**Comment by DHowett** [comment]
This may not be the cause of your issue, but I’d thought that `Cascadia Code PL` needed to be in secondary quotes just like `'Courier New'` is.

Can you share a screenshot?

**Comment by bertoloti** [comment]
> This may not be the cause of your issue, but I’d thought that `Cascadia Code PL` needed to be in secondary quotes just like `'Courier New'` is.
> 
> Can you share a screenshot?

![Image](https://github.com/user-attachments/assets/fa6a5882-3d5e-40de-a2dd-26e1ba21f740)

I has always worked like this but i have tried adding quotes, removing, leaving only the `Cascadia Code PL` and removing the rest of the fonts but still not working. Obviously that the fonts are installed in my system as I was using this for months now without any problems, nothing has change apart from the new version of vscode.
FYI, before I was using vscode insiders with Cascadia Code PL and it was working ok until a new update came and then it stop working, that is why I switch back to vscode and it worked up to the last update.

**Comment by aaronbell** [comment]
Have you filed a bug with [vscode](https://github.com/microsoft/vscode/issues)? It sounds like this issue is on their side.

**Comment by bertoloti** [comment]
> Have you filed a bug with [vscode](https://github.com/microsoft/vscode/issues)? It sounds like this issue is on their side.

You are right
