### ISSUE TITLE
Wheel of Darma / Helm symbol (☸) Rendered differently in Windows Terminal and Conhost

### ISSUE THREAD

**Issue by Hazmi35** [microsoft/cascadia-code#784]
### Cascadia family version

2404.23

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 11 23H2; Arch Linux

### Other Software

Visual Studio Code
Windows Terminal 1.21
Konsole 24.08.3

### What happened?

I am using Cascadia Code NF with Starship prompt with Kubernetes module enabled.
![Image](https://github.com/user-attachments/assets/cad6790b-0b69-43b7-837e-d6ee25ea536c)
As you can see, vscode renders the symbol correctly, but Windows Terminal is using an emoji?

This is fine on Linux too
![Image](https://github.com/user-attachments/assets/4d49d673-2205-4348-b5b6-a18f01e1bbd5)

**Comment by Hazmi35** [comment]
Strangely enough, MesloLGS NF from powerlevel10k is fine.
![Image](https://github.com/user-attachments/assets/c4c14161-7b56-4151-a7e0-b533edb3ac7c)

But Hack NF is not
![Image](https://github.com/user-attachments/assets/1de4fadc-222e-40f1-b35f-2cd75f0aea67)

**Comment by Hazmi35** [comment]
Ah, interesting. Starship uses the emoji instead of `\udb83\udea4` icon from NF. 

While I can change the symbol from my starship config, shouldn't be there a toggle in Windows Terminal to behave the same like everyone else?

**Comment by aaronbell** [comment]
Sounds like this is an issue for Windows Terminal not for Cascadia Code: https://github.com/microsoft/terminal

**Comment by DHowett** [comment]
FWIW it also isn’t a terminal issue. If a glyph exists in emoji form but not in non-emoji form in your font, it will be rendered as an emoji. Period. :)
