### ISSUE TITLE
emoji ☺️ not rendered correctly

### ISSUE THREAD

**Issue by rockmandash** [microsoft/cascadia-code#786]
### Cascadia family version

2404.23

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (static)

### Platform

 macOS 15.1.1

### Other Software

Visual Studio Code 1.95.3

### What happened?

![Image](https://github.com/user-attachments/assets/9a09b949-8758-4d38-96a6-71f3738957d1)

```
    '😀',
    '😃',
    '😄',
    '😁',
    '😆',
    '🥹',
    '😅',
    '😂',
    '🤣',
    '🥲',
    '☺️',
```

everything rendered perfectly except ☺️

My vscode font family is `'Cascadia Code NF', Menlo, Monaco, 'Courier New', monospace`

**Comment by aaronbell** [comment]
The reason the final emoji shows up differently is because Cascadia contains it.  The others are being rendered via fallback with an emoji font. The only solution on the font side would be to remove the glyph, which I do not plan to do at this time. Maybe take it up with VSCode?

**Comment by DHowett** [comment]
Alternatively, you can (and should!) employ the FE0E and FE0F variation selectors.

The origin of this issue is that that glyph existed before emoji did. It had a well-known representation before _Unicode_ existed, even.
