### ISSUE TITLE
No .ttf or .otf files in releases

### ISSUE THREAD

**Issue by perigozin** [microsoft/cascadia-code#792]
The font files are not available in zipped releases, how am I supposed to install it?
The readme states I have to download the latest release but only the source is available, no `.ttf` or `.otf` files.

Am I missing something? If so, please correct the readme documentation.

**Comment by DHowett** [comment]
You need to download the artifact ZIP file from the release you are interested in, not the "source code zip".

![image](https://github.com/user-attachments/assets/d3f57d4c-658b-4371-978f-287996c81d18)

**Comment by perigozin** [comment]
Sorry, my mistake, for some reason I downloaded both the release zip and the source zip and when I clicked the last downloaded file in Chrome's download popup I accidentally opened the source zip. Thanks anyway!
