### ISSUE TITLE
Better Parentheses 

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/cascadia-code#82]
The Parentheses are not nice.

**Comment by DHowett-MSFT** [comment]
This bug report is as good as our parenthesis are.







I think we have another eight bugs tracking this, but they all have 100x more detail than this.

**Comment by fwd079** [comment]
Hi

Indeed, @khoshroomahdi  didn't do justice in reporting the bug, which is not actually a bug to be honest. I guess here the Issue/gripe is, that small parenthesis actually don't look _similar_ as Fira Code so the chang is kind of disturbing for some.

Fira Code:

![image](https://user-images.githubusercontent.com/7912632/65409223-0ef69f80-dddf-11e9-896f-70ce3979df6c.png)


Cascadia Code:

![image](https://user-images.githubusercontent.com/7912632/65409263-29c91400-dddf-11e9-9a13-f27d1753bba0.png)

I am _guessing_ here, but I think a _squary_ parenthesis is kind of not sitting well with OP. 

Regards.

**Comment by mdtauk** [comment]
I like the thicker and curvier parenthesis design.  It is so widely used in code, they are distinguished from the square and curly ones.

**Comment by fwd079** [comment]
> I like the thicker and curvier parenthesis design. It is so widely used in code, they are distinguished from the square and curly ones.

Yeah guessed already that it is personal preference, that's why posted screenshots of both after installing Cascadia Code font.

Regards.
