### ISSUE TITLE
support persian and arabic

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/cascadia-code#84]
I install Cascadia and i found unfortunately this font doesn't support Arabic and Persian.

**Comment by cinnamon-msft** [comment]
Duplicate of #33

**Comment by mohd-akram** [comment]
@cinnamon-msft Could this be reopened? The other issue was closed.

**Comment by cinnamon-msft** [comment]
Good catch, reopened!

**Comment by morezafard** [comment]
Why don't you merge this monospace font with cascadia? It supports both persian and arabic too!
https://github.com/rastikerdar/vazir-code-font
