### ISSUE TITLE
Feature Request => ligature

### ISSUE THREAD

**Issue by jhechtf** [microsoft/cascadia-code#85]
# Description of the new feature/enhancement (with images if possible)
It's not a very long request, simply just adding in a ligature for "=>", which is common in Javascript nowadays.

# Proposed technical implementation details (optional)
None

**Comment by DHowett-MSFT** [comment]
?

![image](https://user-images.githubusercontent.com/14316954/65358603-dc666000-dbae-11e9-854c-6dc2ebc485e4.png)

**Comment by jhechtf** [comment]
I just installed the font earlier today and I don't see that ligature in my code editor, only reason why I created the issue.

**Comment by jhechtf** [comment]
![image](https://user-images.githubusercontent.com/8152471/65359325-04ef5980-dbb1-11e9-87f6-c5373626683b.png)

**Comment by DHowett-MSFT** [comment]
That's a screenshot of Consolas.

**Comment by jhechtf** [comment]
Huh you're right I hadn't noticed that. That's really weird, why can my text editor find it, but VSCode can't... alright then yeah nvm. This is probably a dumb on my part.

**Comment by DHowett-MSFT** [comment]
VSCode doesn't seem like it reloads the font table when the system tells it to; perhaps relaunching it will help?

**Comment by jhechtf** [comment]
Yeah that did it. Weird, I don't remember this issue when I started using Fira Code? Thanks!
