### ISSUE TITLE
List of ligature combinations Documentation Issue

### ISSUE THREAD

**Issue by ArjangAssadi** [microsoft/cascadia-code#86]
Is there a list of characters combinations and their corresponding ligatures?

**Comment by DHowett-MSFT** [comment]
duplicate of #37 -- **please search before reporting a new issue**

**Comment by ArjangAssadi** [comment]
The list is not in documentation, this is still a documentation issue,

**Comment by DHowett-MSFT** [comment]
That documentation issue is already covered by #37.
