### ISSUE TITLE
SIL Open Font License is not an open source license

### ISSUE THREAD

**Issue by luke-jr** [microsoft/cascadia-code#88]
# Environment

In any jurisdiction of a copyright law where judges are free to observe violations trying to violate the license terms on a mere technicality.

# Steps to reproduce

Sell a modified version of the font by itself.

# Expected behavior

No legal problems.

# Actual behavior

The license prohibits sale of the font by itself in point (1).

**Comment by mdtauk** [comment]
I don't think anyone should be selling this font or any of its variations.  Allowing forks with different names is fine, if they remain free and link back to the original repo.

**Comment by luke-jr** [comment]
Forbidding selling makes it non-free. If you don't want the font to be open source, that's your choice, but you should probably make that clear, since people/media are falsely claiming Microsoft is releasing an open source font.

**Comment by JKingweb** [comment]
With respect, @luke-jr, OSI disagrees with you. FSF disagrees with you, too. So does Debian. Fonts being fonts (i.e. data rather than code) it's logical to expect Terms to be dissimilar from software. 

If you really want to sell the font, bundling a PDF document with the font embedded would seem to satisfy the condition. You could probably bundle it with an essay on why that condition of the license is something you disagree with, even.

**Comment by luke-jr** [comment]
Modern fonts (including this one) are code, not data. The licenses might arguably still have reason to differ, but this clause in particular is clearly at odds with it being free.

Bundling a dummy program (whether it be a PDF, hello world, or anything else) - as the OSI/FSF use as an excuse to approve the SIL OFL - is clearly an effort to ignore the terms on a technicality, and in the event a copyright holder sued for infringement, I highly doubt a court couldn't see through it as a violation.

**Comment by JKingweb** [comment]
The FAQ from SIL themselves makes it clear that trivial inclusions are all that's required. Indeed, neither the language of the license nor the FAQ suggest that you can't simply sell a package of exactly two OFL fonts with nothing else, as neither would then be by itself. 

https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&item_id=OFL-FAQ_web#98ed3755

**Comment by luke-jr** [comment]
SIL isn't the copyright holder in this case. Their opinion isn't binding and irrelevant.

**Comment by fitojb** [comment]
Can’t tell if trolling.

**Comment by cinnamon-msft** [comment]
Thanks for bringing this up. It looks like, according to the FSF, the SIL OFL is an open-source license. We're not planning to change to a different license.
