### ISSUE TITLE
Feature Request: Consider making it a Variable Font

### ISSUE THREAD

**Issue by mdtauk** [microsoft/cascadia-code#90]
# Make Cascadia Code a Variable Font

Additional weights, widths, should be generated by making the font family Variable.  This means all glyphs should have the same number of nodes defining the outline, between the light and bold weight axis, as well as between the narrow and wide width axis.

By making the typeface variable, it allows for users to adjust the base weight to aid in readability, whilst allowing for bold text for contextual styling and emphasis, whatever the chosen weight value.

**Comment by be5invis** [comment]
+1 for a narrow “half-width” variant -- Glyphs being exactly 1/2-em wide.

**Comment by bitcrazed** [comment]
We hear you and discussed with @aaronbell yesterday. @cinnamon-msft is writing up a plan & roadmap and will share in a week or two, so stay tuned :)

**Comment by mdtauk** [comment]
When defining a Weight axis, I think the current font would fall into a **Semibold**, rather than Bold or Normal/Regular/Medium weight.

This is when you actually generate instances.  But it would be good for Windows Terminal at least, to support a Weight (and a Width) slider when those axies are present in the chosen font.

**Comment by ahmed-alamer** [comment]
A Regular and Retina editions would be great, the font is a bit bold on mac -- both built in and external display (4k) --

**Comment by smlombardi** [comment]
I like the glyph shapes, but overall it's too "heavy".  As others have said, it seems more like "semibold".  If I could specify a font-weight of 300, or it it's weight was more like that of Fira Code Regular I would be happier with it.  This is on a Mac with a 5K display.

**Comment by aaronbell** [comment]
@smlombardi Yes, a lighter weight is definitely on the roadmap. This version was aimed to have enough weight to render well at smaller sizes on mid-to-low resolution screens, but it would definitely feel a bit heavy on high-end screens :)
