### ISSUE TITLE
Feature Request: Cascadia Code Display

### ISSUE THREAD

**Issue by mdtauk** [microsoft/cascadia-code#91]
# Cascadia Code Display variation

Microsoft presents a lot of code, on a lot of slides, at a lot of developer events.  Some of the characters will have slightly awkward works which aid in readability at the small sizes often used in code views, but may not look the most elegant at larger sizes.

Just as Segoe has a display variant, which removes ink traps and adjusts the shape of letter curves, there could be a version of Cascadia Code which is optimised for beauty at larger sizes, used in slide displays and in print.

**Comment by madig** [comment]
Best to couple this with https://github.com/microsoft/cascadia-code/issues/90. This will also test how well VTT can cope with more than one axis.

**Comment by mdtauk** [comment]
It's not quite the same suggestion, but I suppose with enough effort, things like ink traps, and changes to the delicacy of curves could be added as an Axis.  I would prefer to see any Display version be atuned for press and presentation uses, which may require an entire new set of outlines.

**Comment by mdtauk** [comment]
@aaronbell  Do you have any thoughts on there being a display version of Cascadia, for presentations, etc?

**Comment by aaronbell** [comment]
I think that display could certainly be something to develop! That said, there's other areas that I think are a much higher priority, so it might be a while before a Display would be developed :)

**Comment by mdtauk** [comment]
> I think that display could certainly be something to develop! That said, there's other areas that I think are a much higher priority, so it might be a while before a Display would be developed :)

I agree, I just wanted to hear your thoughts and interest in the idea,

**Comment by aaronbell** [comment]
I think that the new ExtraLight weight of Cascadia Code variable accomplishes what you are hoping for in this issue, yes? :) 
As such, I'm closing this for now!
