### ISSUE TITLE
Suggestion: Removing Serifs from glyphs to solidify Sans Serif character

### ISSUE THREAD

**Issue by mdtauk** [microsoft/cascadia-code#97]
**Not a specific request yet, but ideas to address an issue that has come up from a few people.  The mixture of a few distinctly Serifed letters among a general Sans Serif design.**

I hope this issue can become a collaborative discussion at how we may be able to alter some of the glyphs which preserve the use of space and the intention of filling the character width, whilst preserving some of the distinctive strokes and shapes.

~~I am currently away from my usual PC and software, so consider the following image as a crude mock up, rather than a finished submission.~~
**Edit:** Adding higher quality mock-ups

## lowercase _a_

![image](https://user-images.githubusercontent.com/7389110/65630807-087a4a80-dfce-11e9-9b6d-ca95bbb36a74.png)
[SVG Export from FontLab - Stylistic Alternative - lowercase A](https://github.com/microsoft/cascadia-code/files/3654305/a_salt.zip)

Have the spine of the letter take on a diagonal angle, to fill the space where the serif currently is, as well as reduce the very tight ink trap with the lower story of the **a**'s curve

**Comment by adrientetar** [comment]
> The mixture of a few distinctly Serifed letters among a general Sans Serif design.

How is that an issue? This font is an original design, and many monospace fonts have serifs on some of their glyphs.

**Comment by madig** [comment]
I agree with @adrientetar. Serifs are often used to fill a void in monospace designs. Play e.g. with the `PROP` axis on https://www.recursive.design/ to see why.

**Comment by mdtauk** [comment]
There is one issue asking for a Sans Serif version of the typeface, and characters like the **a** and the **r**  could be mistaken as belonging to different typefaces.  But it is subjective, and not everyone will share the same opinion,  which is why I consider it a discussion as opposed to a specific request.

My goal with these ideas are to keep the widths whilst not using such strong serifs.

**Comment by mdtauk** [comment]
## lowercase _l_

![image](https://user-images.githubusercontent.com/7389110/65378891-fbe8b000-dcb6-11e9-856e-47f6db6417ae.png)

Instead of a straight serif on the top of the **l** (which could be mistaken for a numeral **one**, we could have a characteristic flick, which still gives it a distinctive shape.

**Comment by mdtauk** [comment]
## lowercase _r_

![image](https://user-images.githubusercontent.com/7389110/65379250-23db1200-dcbd-11e9-88ff-0c61218caad3.png)


The lowercase **r** is probably the most Serif like of all the characters in the typeface.  Like the lowercase **i** it uses the full bottom and left serifs but stands out from the other letters.

Here I have removed the serifs, pulled the spine towards the left, and lengthened the arm on the letter.

**Comment by aaronbell** [comment]
Thanks again for the suggestions! For the sake of streamlining the bug list, I'm duping this against #83.
